### ISSUE TITLE
Memory leak caused during initialization

### ISSUE THREAD

**Issue by KocsisV** [opencv/opencv#16464] opened 2020-01-29 16:46 UTC
##### System information (version)
- OpenCV => 4.2.0
- Operating System / Platform => Windows 10 64 Bit
- Compiler => MSVC++ 14.24

##### Detailed description

The static variables named "__initialization_mutex" are never freed, causing (false) memory leak detections. 
For example one such variable is in modules/core/src/system.cpp .

IPP also produces a lot of false positives since it leaves a lot of TLS objects on the heap without cleaning them up upon unloading the DLL (exiting the application). But IPP can be disabled.

I have not yet checked if this issue is also present on linux or not.

##### Steps to reproduce

I used [link](https://docs.microsoft.com/en-us/visualstudio/debugger/finding-memory-leaks-using-the-crt-library?view=vs-2019) to check for memory leaks, linked OpenCV (compiled from source) as a DLL to my application.

There is a solution in [link](https://answers.opencv.org/question/121272/false-memory-leaks-in-mfc/) that gets rid of this issue in certain cases.

**Comment by alalek** [comment] 2020-01-29 16:51
On Linux we have [valgrind suppression files](https://github.com/opencv/opencv/tree/3.4.9/platforms/scripts).

duplicate of #5452

**Closed by alalek** 2020-01-29 16:51 UTC
Labels: duplicate
