### ISSUE TITLE
OpenCV 3.4.3.18 bug on Windows 7

### ISSUE THREAD

**Issue by josephernest** [opencv/opencv#13083] opened 2018-11-08 21:33 UTC
When installing on Windows 7 x64 with:

    pip install opencv-python     # py 2.7

or

    pip3 install opencv-python     # py 3.6

in both cases, it installs succesfully but at the end, when doing:

    import cv2

we have this bug:

> ImportError: DLL load failed: The specified module could not be found.

As noted [on many posts](https://github.com/skvark/opencv-python/issues/114), the reason is that this file is missing:

    MS-WIN-DOWNLEVEL-SHLWAPI-L1-1-0.DLL

Fix: install KB2670838 / [Platform Update for Windows 7](https://www.microsoft.com/en-us/download/details.aspx?id=36805), less than 15 MB

    Windows6.1-KB2670838-x64.msu

**Todo: Can we put this in the release notes of Open CV 3.4.3 or better: 
Can we do a `try: ... except: ...` and display `Please install Platform Update for Windows 7 / KB2670838` instead of just a non-explicit `DLL load failed` message ?**

It would save countless hours for Windows users trying to install OpenCV.

**Comment by alalek** [comment] 2018-11-09 05:54
We don't maintain `opencv-python` package ( https://github.com/skvark/opencv-python/issues ).

Binaries are built using Win10 machines.

duplicate of #12010

**Closed by alalek** 2018-11-09 05:54 UTC
Labels: duplicate, invalid, platform: win32
