### ISSUE TITLE
BUG: ‘Your platform doesn’t suppport hardware accelerated AV1 decoding.’ when i use ‘cv2.VideoCapture’

### ISSUE THREAD

**Issue by piwawa** [opencv/opencv#22304] opened 2022-07-26 03:56 UTC
##### System information (version)
- OpenCV => 4.6.0
- Operating System / Platform => Windows 64 Bit 21H2
- Compiler => Visual Studio Code 1.69.2
- opencv_videoio_ffmpeg460_64.dll
- Python => 3.10
- opencv-contrib-python 4.6.0.66
- opencv-python 4.5.5.64
##### Detailed description
I download a '.mkv' video from YOUTUBE. When i used **cv2.VideoCapture(path)** with python in VSCode, it throwed a warning as follow and can't decode it. I post it in [opencv forum](https://forum.opencv.org/t/error-your-platform-doesnt-suppport-hardware-accelerated-av1-decoding-when-i-use-cv2-videocapture/9605) and figure out that maybe an issue with 'opencv_videoio_ffmpegxxx_64.dll' which does not include AV1 support. Maybe update opencv_videoio_ffmpegxxx_64.dll will work.
##### Warning message:
[av1 @ 0000028a88053c40] Your platform doesn’t suppport hardware accelerated AV1 decoding.
[av1 @ 0000028a88053c40] Failed to get pixel format.
[av1 @ 0000028a88053c40] Missing Sequence Header.
[av1 @ 0000028a88053c40] video_get_buffer: image parameters invalid
[av1 @ 0000028a88053c40] get_buffer() failed
[av1 @ 0000028a88053c40] thread_get_buffer() failed
[av1 @ 0000028a88053c40] Failed to allocate space for current frame.
[av1 @ 0000028a88053c40] Get current frame error

**Comment by alalek** [comment] 2022-07-26 04:26
duplicate of #11389

**Closed by alalek** 2022-07-26 04:26 UTC
Labels: duplicate

**Comment by piwawa** [comment] 2022-07-27 05:31
> duplicate of #11389

Any solution?

**Comment by canghaiyunfan** [comment] 2022-09-16 14:10
How to solve this issue?

**Comment by ChuyaoZellFu** [comment] 2025-07-08 07:46
Still having this issue in 2025

**Comment by lucasjinreal** [comment] 2025-07-26 03:58
Why does AV1 have so many issues? Does it also have patent concerns?
