### ISSUE TITLE
cv::stereoRectify fails if given inliers mask of type vector<uchar> 

### ISSUE THREAD

**Issue by ejoebstl** [opencv/opencv#5769] opened 2015-12-08 20:00 UTC
The function `cv::recoverPose` fails when given an inliers mask of type `vector<uchar>`, which is a valid input/output array. If an equal `Mat`of type `CV_U8` is given instead, the function works fine. 

This is unfortunate since `cv::MatchesInfo`uses `vector<uchar>` to store the inliers mask.

I assume the error is due to a bogus assertion in the [corresponding method](https://github.com/Itseez/opencv/blob/master/modules/calib3d/src/five-point.cpp#L541):

`CV_Assert(mask.size() == mask1.size());`

`mask1` is always of type `Mat`, `mask` is the given input. In the case described here, `cv::Size` might be compared to a `size_t`, never returning `true`.

**Comment by DiebBlue** [comment] 2019-02-26 10:07
This bug can be simply fixed in five-point.cpp:

int cv::recoverPose( InputArray E, InputArray _points1, InputArray _points2, InputArray _cameraMatrix, OutputArray _R, OutputArray _t, double distanceThresh, InputOutputArray _mask, OutputArray triangulatedPoints)
{
...
   mask1 = mask1.t(); // here cols and rows will be swapped
    mask2 = mask2.t();
    mask3 = mask3.t();
    mask4 = mask4.t();

    // If _mask is given, then use it to filter outliers.
    if (!_mask.empty())
    {
        Mat mask = _mask.getMat();
       // size of mask is 1xnx1
       // but size of mask1 is 1x1xn because of transponation before
       // therefore the assertion failes
       mask = mask.t(); // <- add this line to fix this bug
        CV_Assert(mask.size() == mask1.size()); 
        ...
   }
...
}

**Comment by alalek** [comment] 2019-02-26 10:30
Perhaps `checkVector()` should be used instead of `.size()`.

Simple reproducer would help to land patch for this (and to add regression test).

**Closed** 2019-09-20 22:56 UTC
Labels: bug, category: calib3d, priority: normal
