### ISSUE TITLE
opencv v4.1 calling 'authorizationStatusForMediaType' on MacOS prior to Mojave

### ISSUE THREAD

**Issue by chris-praxis** [opencv/opencv#14476] opened 2019-05-03 23:10 UTC
Attempting to open a webcam (e.g. new VideoCapture(0)) throws the following exception:

+[AVCaptureDevice authorizationStatusForMediaType:]: unrecognized selector sent to class 0x7fff884586a0
[ERROR:0] VIDEOIO(AVFOUNDATION): raised unknown C++ exception!

I see in the documentation that 'authorizationStatusForMediaType' is only available on Mojave (macOS 10.14+).

##### System information (version)
- OpenCV => 4.1.0_1  (version 3.4.5_1 works)
- Operating System / Platform => macOS High Sierra (10.13.6)
- Compiler => Apple Clang with Xcode 10.1

##### Detailed description

Creating a VideoCapture object with integer zero to open the default camera results in the 'authorizationStatusForMediaType' exception above when run with camera plugged in.  I'm using a Mac Mini, so there's no built-in camera.  Code is C++.

##### Steps to reproduce

Run a simple camera sample on High Sierra with OpenCV version 4.1 (I got mine via "brew install opencv") and observe.  FYI I'm running a Debug Xcode scheme.  Note that OpenCV version 3.4.5_1 (via "brew install opencv@3") does not have this problem.

**Comment by alalek** [comment] 2019-05-04 00:03
> "brew install opencv"

You should report about this problem to homebrew maintainers.
Try to force installation from the sources (instead of bottle binaries).

see discussions here: #14267 #14278

**Comment by fxcoudert** [comment] 2019-05-09 14:25
> Try to force installation from the sources

Binaries are built on the same macOS version as the user is running, so I am not sure what this would achieve.

> You should report about this problem to homebrew maintainers

As far as I can see, the problem is simply that the fix (https://github.com/opencv/opencv/commit/5cb0eded642861d0f845f9c32140b00afd15826a) is not in the latest version, which is what Homebrew ships. It will be fixed in the next release.

**Closed** 2019-07-14 21:14 UTC
Labels: category: videoio(camera), platform: ios/osx
