### ISSUE TITLE
Issues in Compiling Opencv with Custom FFMPEG

### ISSUE THREAD

**Issue by jayantySrikrishna** [opencv/opencv#16972] opened 2020-04-03 17:23 UTC
System Information:
- OpenCV => 4.2
- Operating System / Platform => Windows 7/ 32 Bit
- Compiler => Visual Studio 2015

##### Detailed description
I am currently editing cap_ffmpeg_impl.hpp in modules/videoio/src and compiling the binaries. As FFMPEG is a 3rd party library it doesn't register changes in the cap_ffmpeg_impl.hpp and downloads the external binary(opencv_videoio_ffmpeg420.dll ) instead of compiling with the local files.   

What is the procedure for compiling with the source files?

**Comment by alalek** [comment] 2020-04-03 17:43
duplicate of #13826

**Closed by alalek** 2020-04-03 17:43 UTC
Labels: duplicate
