### ISSUE TITLE
Build from Source Raspberry pi

### ISSUE THREAD

**Issue by arushgupta2007** [opencv/opencv#15300] opened 2019-08-14 12:18 UTC
##### System information (version)

- OpenCV => 4.1.1
- Operating System / Platform => Raspberry Pi, Raspbian
- Compiler => CMake?

##### Detailed description

I am working on Raspberry Pi 4 which has python 3.7 installed. As Pi wheels has not added opencv to their list in python3.7, I am forced to build from source. I have followed a couple of tutorials like: [https://www.pyimagesearch.com/2017/09/04/raspbian-stretch-install-opencv-3-python-on-your-raspberry-pi/](https://www.pyimagesearch.com/2017/09/04/raspbian-stretch-install-opencv-3-python-on-your-raspberry-pi/) or [https://www.deciphertechnic.com/install-opencv-python-on-raspberry-pi/](https://www.deciphertechnic.com/install-opencv-python-on-raspberry-pi/) but no matter what I do, I get this error:

`
/usr/bin/ld: ../../lib/libopencv_core.so.4.1.1: undefined reference to '__atomic_fetch_add_8'
/usr/bin/ld: ../../lib/libopencv_core.so.4.1.1: undefined reference to '__atomic_fetch_sub_8'
/usr/bin/ld: ../../lib/libopencv_core.so.4.1.1: undefined reference to '__atomic_store_8'
/usr/bin/ld: ../../lib/libopencv_core.so.4.1.1: undefined reference to '__atomic_load_8'
/usr/bin/ld: ../../lib/libopencv_core.so.4.1.1: undefined reference to '__atomic_compare_exchange_8'
collect2: error: ld returned 1 exit status
make[2]: *** [modules/core/CMakeFiles/opencv_test_core.dir/build.make:571 : bin/opencv_test_core] Error 1
make[1]: *** [CMakeFiles/Makefile2:2678: modules/core/CMakeFiles/opencv_test_core.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
`

##### Steps to reproduce

(Error while compiling the module)

**Comment by dkurt** [comment] 2019-08-14 14:25
duplicate of https://github.com/opencv/opencv/issues/15278

**Closed by dkurt** 2019-08-14 14:25 UTC
