### ISSUE TITLE
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/surbhi/.local/lib/python3.8/site-packages/cv2/qt/plugins" even though it was found. #

### ISSUE THREAD

**Issue by surbhi1986** [opencv/opencv#19507] opened 2021-02-11 17:36 UTC
Hi I was using mmdetection for custom data, after training i saved the model.
But during testing on single image i am getting error during show which is given please. Please help guys.

QObject::moveToThread: Current thread (0x3d9b720) is not the object's thread (0x5af24f0).
Cannot move to target thread (0x3d9b720)

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/surbhi/.local/lib/python3.8/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl.

Aborted (core dumped)

**Comment by alalek** [comment] 2021-02-11 18:49
Looks like there is conflicts between different Qt versions on your system (the first is from opencv-python, the second is from the system). This is nothing to fix in OpenCV itself.

No need to open issues in multiple repositories.
duplicate of https://github.com/opencv/opencv-python/issues/447

**Closed by alalek** 2021-02-11 18:49 UTC
Labels: category: 3rdparty, duplicate, invalid
