### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by Jiewen2017** [opencv/opencv#10538] opened 2018-01-07 11:13 UTC
- OpenCV => 3.4
- Operating System / Platform => Windows 7 64 Bit
- Compiler => Visual Studio 2017
- CUDA => 9.1

Can opencv build with cuda 9? There are many errors! however, when I build opencv without cuda, it runs perfectly.

**Comment by alalek** [comment] 2018-01-07 12:07
Duplicate of #9908
Related PR #10497

**Closed by alalek** 2018-01-07 12:07 UTC
Labels: category: build/install, duplicate, incomplete
