### ISSUE TITLE
Opencv failed to call ONNX model: shape_utils.hpp:171 in function 'cv::dnn::dnn4_v20211220::total'

### ISSUE THREAD

**Issue by geoexploring** [opencv/opencv#21967] opened 2022-05-11 03:29 UTC
##### System information (version)
```
- OpenCV-python          4.5.5.64
- Windows 64 Bit
```

When I call the ONNX model with ONNXRuntime it works fine, but when I call it with OpenCV I get an error: `opencv-python\opencv\modules\dnn\include\opencv2/dnn/shape_utils.hpp:171: error: (-215:Assertion failed) start <= (int)shape.size() && end <= 
(int)shape.size() && start <= end in function 'cv::dnn::dnn4_v20211220::total'`

The complete code is as follows:
```python

import cv2
import numpy as np

def load_model(onnx_model):
    net = cv2.dnn.readNetFromONNX(onnx_model)
    net.setPreferableBackend(cv2.dnn.DNN_BACKEND_CUDA)
    net.setPreferableTarget(cv2.dnn.DNN_TARGET_CUDA)
    return net

def onnx_test():
    input_shape = [512, 512, 3]
    img= np.random.random(input_shape).astype('float32')
    onnx_model = "./bisenetv2.onnx"
    net = load_model(onnx_model)

    blob = cv2.dnn.blobFromImage(img, 1, (512, 512))
    net.setInput(blob)
    out = net.forward()

if __name__ == '__main__':
    onnx_test()

```

The ONNX model is available for download：[bisenetv2.zip](https://github.com/opencv/opencv/files/8666504/bisenetv2.zip) 

Could you give me some advice? Thank you

**Comment by fengyuentau** [comment] 2022-05-11 11:58
I also ran into this issue with another model. It may be related to some shape mismatched problems of some layers. Some brief discussions can be found at https://github.com/opencv/opencv/issues/20072. I will investigate into this problem.

**Comment by fengyuentau** [comment] 2022-05-19 11:30
I did some debugging on your model simplified by [onnx-simplifier](https://github.com/daquexian/onnx-simplifier), and it turns out the problem is about broadcasting. Tensor shape is 1x128x1x1 after node GlobalAveragePool, and it is added with output `relu_27.tmp_0` which has shape 1x128x16x16. So the previous tensor needs to be broadcasted to 1x12816x16 for the add operation, which opencv does not support for now.

![image](https://user-images.githubusercontent.com/17219438/169283068-55d9f907-0d37-4635-86f9-04891d8f518a.png)


There is a PR https://github.com/opencv/opencv/pull/21865 working on supporting broadcasting for element-wise layers.

**Comment by fengyuentau** [comment] 2022-07-19 03:22
Close as fixed in https://github.com/opencv/opencv/pull/21865

**Closed by fengyuentau** 2022-07-19 03:22 UTC
Labels: bug, category: dnn (onnx)

**Comment by LaoWangJF** [comment] 2024-09-05 07:52
#include <opencv2/opencv.hpp>  
#include <opencv2/dnn.hpp>  
#include <iostream>  
  
int main() {  
    cv::dnn::Net net = cv::dnn::readNet("best.onnx");  
  
    // 加载图像并创建blob  
    cv::Mat img = cv::imread("pose.bmp");  
    cv::Mat blob = cv::dnn::blobFromImage(img, 1.0 / 255.0, cv::Size(224, 224), cv::Scalar(0, 0, 0), true, false);  

    // 设置输入并运行网络  
    net.setInput(blob);  
    cv::Mat outs; 
    //std::vector<cv::Mat> outs;  
    //在 OpenCV 的 DNN 模块中，net.forward() 函数的调用方式有一点需要注意：当你想要收集多个输出层的输出时，你应该传递一个 std::vector<cv::Mat> 来接收输出，
    
    //net.forward(outs, "output0"); // 确保这里的"output0"与ONNX模型中的输出层名相匹配 
    std::vector<std::string> layersNames = net.getLayerNames();  
    std::string outputLayerName = layersNames[layersNames.size() - 1]; // 假设输出层是最后一个层  
    std::cout << outputLayerName  << std::endl; 
    net.forward(outs, outputLayerName); // 使用索引获取输出
  
    // 检查输出并处理  
    if (!outs.empty()) {  
        const cv::Mat& out = outs; //[0];  
        // 根据out的维度进行适当处理  
        std::cout << "Output shape: " << out.size << std::endl;  
        // ... 其他处理逻辑  
    } else {  
        std::cerr << "No outputs were produced by the network." << std::endl;  
    }  
  
    return 0;  
}

net.forward(outs, outputLayerName); OpenCV: terminate handler is called! The last OpenCV error is:
OpenCV(4.5.2) Error: Assertion failed (start <= (int)shape.size() && end <= (int)shape.size() && start <= end) in total, file I:/ProgramProjects/files/opencv/opencv-4.5.2/modules/dnn/include/opencv2/dnn/shape_utils.hpp, line 171
