### ISSUE TITLE
Windows+Qt5 unable to build opencv_highgui

### ISSUE THREAD

**Issue by magres** [opencv/opencv#20005] opened 2021-04-29 04:35 UTC
##### System information (version)

- OpenCV => 4.5.2
- Operating System / Platform => Windows 10 64bit
- Compiler => MSVC 2019
- Options: Qt5

##### Detailed description

While highgui compilation it issues
```
window.obj : error LNK2019: unresolved external symbol "double __cdecl cvGetPropVsync_W32(char const *)" (?cvGetPropVsync_W32@@YANPEBD@Z) referenced in function "double __cdecl cv::getWindowProperty(class std::
basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,int)" (?getWindowProperty@cv@@YANAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H@Z) [D:\CPPLIBS\sources\op
encv\build\modules\highgui\opencv_highgui.vcxproj]
window.obj : error LNK2019: unresolved external symbol "void __cdecl cvSetPropVsync_W32(char const *,bool)" (?cvSetPropVsync_W32@@YAXPEBD_N@Z) referenced in function "void __cdecl cv::setWindowProperty(class st
d::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,int,double)" (?setWindowProperty@cv@@YAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HN@Z) [D:\CPPLIBS
\sources\opencv\build\modules\highgui\opencv_highgui.vcxproj]
D:\CPPLIBS\sources\opencv\build\bin\Release\opencv_highgui452.dll : fatal error LNK1120: 2 unresolved externals [D:\CPPLIBS\sources\opencv\build\modules\highgui\opencv_highgui.vcxproj]
```
Two symbols cvSetPropVsync_W32 and cvGetPropVsync_W32 are missing. those are defined in window_w32.cpp but not included to the build.

**Comment by alalek** [comment] 2021-04-29 07:42
duplicate of #19870

**Closed by alalek** 2021-04-29 07:42 UTC
Labels: duplicate
