### ISSUE TITLE
The headers cannot be included using a C-compiler

### ISSUE THREAD

**Issue by HJarausch** [opencv/opencv#16108] opened 2019-12-09 19:12 UTC
opencv-4.1.2 breaks vlc, e.g., since it compiles some files with gcc instead of g++
Some parts of /usr/include/x86_64-pc-linux-gnu/opencv4/opencv2/core/cvdef.h
can only be compiled by a C++ compiler, e.g.,
  #ifndef CV_CXX11
  #  if __cplusplus >= 201103L || (defined(_MSC_VER) && _MSC_VER >= 1800)
  #    define CV_CXX11 1
  #  endif
  #else
  #  if CV_CXX11 == 0
  #    undef CV_CXX11
  #  endif
  #endif
  #ifndef CV_CXX11
  #  error "OpenCV 4.x+ requires enabled C++11 support"
  #endif

or

#include <array>

Is it really intended to break packages which compile (some) files with a C-compiler?

**Comment by alalek** [comment] 2019-12-09 19:43
C compiler is not supported anymore (and not tested >7 years).
duplicate of #10963

**Closed by alalek** 2019-12-09 19:43 UTC
Labels: category: build/install, duplicate
