### ISSUE TITLE
Code snippet alignment

### ISSUE THREAD

**Issue by dkurt** [opencv/opencv#24391] opened 2023-10-12 12:32 UTC
### Describe the doc issue

https://docs.opencv.org/5.x/d8/d19/tutorial_stitcher.html
Original code https://github.com/opencv/opencv/blob/5.x/samples/cpp/stitching.cpp:
```cpp
int main(int argc, char* argv[])
{
    int retval = parseCmdArgs(argc, argv);
    if (retval) return EXIT_FAILURE;

    //![stitching]
    Mat pano;
    Ptr<Stitcher> stitcher = Stitcher::create(mode);
    Stitcher::Status status = stitcher->stitch(imgs, pano);

    if (status != Stitcher::OK)
    {
        cout << "Can't stitch images, error code = " << int(status) << endl;
        return EXIT_FAILURE;
    }
    //![stitching]

    imwrite(result_name, pano);
    cout << "stitching completed successfully\n" << result_name << " saved!";
    return EXIT_SUCCESS;
}
```
from the docs:
```cpp
int main(int argc, char* argv[])
{
 int retval = parseCmdArgs(argc, argv);
 if (retval) return EXIT_FAILURE;
 Mat pano;
 Ptr<Stitcher> stitcher = Stitcher::create(mode);
 Stitcher::Status status = stitcher->stitch(imgs, pano);
 if (status != Stitcher::OK)
 {
 cout << "Can't stitch images, error code = " << int(status) << endl;
 return EXIT_FAILURE;
 }
 imwrite(result_name, pano);
 cout << "stitching completed successfully\n" << result_name << " saved!";
 return EXIT_SUCCESS;
}
```

### Fix suggestion

Probably, need to check for tabs and consider them in doxygen

**Comment by krishkhimasia** [comment] 2023-10-12 17:45
Can you please assign this issue to me?

**Comment by R0gue-one** [comment] 2023-10-13 05:52
Hey I want to work on this can you tell me the from where is the source file of that doc. Sorry if I ask any stupid question I'm new to all this

**Comment by opencv-alalek** [comment] 2023-10-13 06:17
I don't see formatting issue with Chrome on Linux.
What is used browser version?

**Comment by dkurt** [comment] 2023-10-13 06:33
I use Firefox 118.0.2. Unfortunately, with Chrome 118.0.5993.71 issue is the same. Both on Windows.
![image](https://github.com/opencv/opencv/assets/25801568/734a5d89-c8e6-4be7-91f7-897468193147)

**Comment by opencv-alalek** [comment] 2023-10-14 04:19
Confirmed on Windows: Google Chrome 117.0.5938.92

There is no problem with source code anyway.
Perhaps we need to take a look on documentation styles.

**Comment by opencv-alalek** [comment] 2023-10-14 05:00
Not related to Windows/Linux or browsers.

Caused by Cloudflare CDN "optimizations".

[issue_24391.zip](https://github.com/opencv/opencv/files/12902411/issue_24391.zip)

**Comment by mshabunin** [comment] 2023-10-28 17:08
HTML minification has been disabled on CDN site, issue should be fixed now (might need to clear the cache).

**Closed by mshabunin** 2023-10-28 17:08 UTC
Labels: bug, category: documentation, category: infrastructure
