### ISSUE TITLE
Assert Failed in cv::transpose

### ISSUE THREAD

**Issue by wstcegg** [opencv/opencv#10365] opened 2017-12-20 13:24 UTC
##### System information (version)

- OpenCV => 3.3
- Operating System / Platform => Windows 64 Bit & Ubuntu 16.04 64 Bit
- Compiler => Visual Studio 2015,  g++ 5.4.0

##### Detailed description

OpenCV raised an exception when running to the third line of code:
"OpenCV Error: Assertion failed (dst.cols == dst.rows) in cv::transpose"

##### Steps to reproduce

```
#include <opencv2/core/core.hpp>

using namespace cv;

int main() {
	Mat m = (Mat_<int>(3, 2) << 1, 2, 3, 4, 5, 6);
	Mat t = m.reshape(1, 2);
	t = m.t();	//OpenCV Error: Assertion failed (dst.cols == dst.rows) in cv::transpose
        return 0;
}
```

**Comment by alalek** [comment] 2017-12-20 13:32
What is expected result here?
OpenCV's assignment operator try reusing destination cv::Mat (by design). In this sample it is the same cv::Mat for src and dst => "inplace transpose" which can't work for non-squared matrix.

**Comment by arf1372** [comment] 2019-10-09 23:35
Hi @alalek
I thought you added the invalid label to this issue without closing it. Is this intentional?

**Closed** 2022-03-23 16:19 UTC
Labels: invalid
