### ISSUE TITLE
Fails to build with ffmpeg 5.0

### ISSUE THREAD

**Issue by berolinux** [opencv/opencv#21455] opened 2022-01-16 01:13 UTC
OpenCV uses some ffmpeg APIs that have been removed in the just released ffmpeg 5.0 and makes some assumptions about ffmpeg structs that are no longer true (primarily trying to access the "codec" member in an AVStream).
This causes the build to fail.

**Comment by berolinux** [comment] 2022-01-17 04:07
duplicate of what? I see some relation to https://github.com/opencv/opencv/issues/20147, but ffmpeg 5.0 introduces additional problems not relevant for ffmpeg 4.x (4.4.1 works).
Among others, AVLockOp and AVPicture have been removed.

**Comment by berolinux** [comment] 2022-01-17 17:15
Something like this patch
[opencv-4.5.5-ffmpeg-5.0.patch.txt](https://github.com/opencv/opencv/files/7883693/opencv-4.5.5-ffmpeg-5.0.patch.txt)
is needed, but I'm not sure I got it 100% right (in fact I know I didn't because I omitted a couple of `ifdef`s for compatibility with old versions).

**Comment by rgaufman** [comment] 2022-03-09 00:48
Any update on this one?

**Comment by alalek** [comment] 2022-03-16 12:36
closing as duplicate of #20147

**Closed by alalek** 2022-03-16 12:36 UTC
Labels: duplicate

**Comment by tolysz** [comment] 2023-05-21 00:08
Are the changes from: 
https://github.com/opencv/opencv/issues/21455#issuecomment-1014750968
being worked on i.e. some patch that removes `avcodec_get_context_defaults3`?
