### ISSUE TITLE
DepthWise convolution

### ISSUE THREAD

**Issue by yanchao12122** [opencv/opencv#12315] opened 2018-08-27 01:54 UTC
Is there any plan to add DepthwiseConvolution layer of caffeImporter into opencv?

**Comment by dkurt** [comment] 2018-08-27 04:49
Looks like a duplicate of http://answers.opencv.org/question/195257/shufflenet-has-two-new-network-layers-namely-shufflechannel-and-convolutiondepthwise/

@yanchao12122, depthwise convolution is just a name. Actually this is a regular Caffe's convolution with number of groups equals to number of output channels. Please add a reference to origin implementation of layer (is it a DepthwiseConvolution or ConvolutionDepthwise) or modify your `.prototxt`.

**Comment by dkurt** [comment] 2018-09-20 08:57
There are two possible ways to enable it in OpenCV:

### Custom layers
If there is no layer in OpenCV but you know how to implement it, you may use custom layers feature (details: https://docs.opencv.org/master/dc/db1/tutorial_dnn_custom_layers.html). The main advantage - you do not need to recompile a library but implement a layer in your application.

First of all, let's try to run the model from https://github.com/msnqqer/ShuffleNet ([source](http://answers.opencv.org/question/195257/shufflenet-has-two-new-network-layers-namely-shufflechannel-and-convolutiondepthwise/)) using OpenCV's deep learning image classification sample:

  <img src="https://user-images.githubusercontent.com/25801568/45807201-9e98d800-bccb-11e8-90cb-2cd6a9fa130c.png" width="128">

```
./bin/example_dnn_classification --config=shufflenet_1x_g3_deploy.prototxt --model=shufflenet_1x_g3.caffemodel --mean="103.94 116.78 123.68" --scale=0.017 --width=224 --height=224 --input=toucan.png --rgb=0 --classes=/path/to/opencv/samples/data/dnn/classification_classes_ILSVRC2012.txt
```

error:
```
Can't create layer "resx1_conv2" of type "ConvolutionDepthwise" in function 'getLayerInstance'
```

Let's modify a sample by adding an alias from `ConvolutionDepthwise` to `Convolution` (add it before `cv::dnn::readNet`):

```cpp
#include <opencv2/dnn/all_layers.hpp>  // ConvolutionLayer
#include <opencv2/dnn/layer.details.hpp>  // CV_DNN_REGISTER_LAYER_CLASS

// ...
    CV_DNN_REGISTER_LAYER_CLASS(ConvolutionDepthwise, ConvolutionLayer);
    Net net = readNet(model, config, framework);
// ...
```

Output (is printed on the image):
```
toucan: 19.2081
```

### OpenCV modification
Open [opencv/modules/dnn/src/init.cpp
](https://github.com/opencv/opencv/blob/master/modules/dnn/src/init.cpp)

and add the following line to the rest of layers:
```cpp
CV_DNN_REGISTER_LAYER_CLASS(ConvolutionDepthwise,    ConvolutionLayer);
```

recompile the library and enjoy!


### Call to action
Feel free to propose a PR which adds a line mentioned above into init.cpp.

**Closed** 2018-10-24 09:21 UTC
Labels: category: dnn, good first issue

**Comment by dkurt** [comment] 2018-10-24 13:05
@yanchao12122, necessary changes have been merged.
