### ISSUE TITLE
Mat::release() resets channels info for Mat_

### ISSUE THREAD

**Issue by cdcseacave** [opencv/opencv#8680] opened 2017-05-01 09:00 UTC
In debug Mat::release() resets fixed info for Mat_ (pls see https://github.com/opencv/opencv/blob/master/modules/core/include/opencv2/core/mat.inl.hpp#L780).
For instance if Mat_ is compiled with 3 channels, release() sets it to 1.

**Comment by cdcseacave** [comment] 2017-05-01 09:25
Fix: overwrite Mat_::release()
```
template<typename _Tp> inline
void Mat_<_Tp>::release()
{
    Mat::release();
#ifdef _DEBUG
    flags = (flags & ~CV_MAT_TYPE_MASK) | DataType<_Tp>::type;
#endif
}
```

**Comment by sovrasov** [comment] 2017-05-05 13:15
Could you provide a PR with the proposed fix and a regression test?

**Comment by alalek** [comment] 2017-05-05 14:36
Mat has design of smart pointer with some cached fields (like cols, rows, type/flags) - so instead of `"m->obj.field_name"` we just write `m.field_name`.
Why do you need to access to information fields of released Mat?
This "Mat" is not attached to any "object/data" anymore, so there are no valid fields "to cache". I believe, we should raise error in these cases (like smart ptr, working with fields of `m->obj` is invalid, because `obj` is nullptr), but there is no way (in the current C++ design) to catch these cases, so these fields always return/contain something ("garbage" in the case of released Mat).

Using of released fields is not a good practice and will lead to real errors (some problems are already fixed in OpenCV).

BTW, `release()` is not a virtual method, so there are still some ways "to break" proposed patch (just to cast to regular `Mat*` and release it).

**Comment by cdcseacave** [comment] 2017-05-05 15:10
I'll give you an example bellow that breaks OpenCV without this patch. But before that, pls explain following our logic above, why the channels returned by `m.channels();` is different from immediately after constructing the matrix `cv::Mat_<cv::Point2i> m;` and after `m.release();` (more exactly `2 !=1`).

Example:
```
	cv::Mat_<cv::Point2i> m;
	mat.release();
	m.channels(); // this line rises an assert at mat.inl.hpp line 1597
```

**Comment by kinchungwong** [comment] 2017-05-05 22:33
You can use `Mat.empty()` or `Mat_<T>.empty()` to check whether the matrix is empty before use.

The quirk that `Mat_<T>.channels()` returns one (1) (as opposed to the more widely accepted practice of returning zero (0)) is due to the way OpenCV encodes the numeric type and channel count into a 32-bit integer type code.

https://github.com/opencv/opencv/blob/fe2416575babc52888ce7e162be43c90c3675ce4/modules/core/include/opencv2/core/mat.inl.hpp#L861

The `CN` macro simply don't have a way to encode a channel count of zero. (When the masked bits give a value of zero, that is interpreted as a channel count of 1; when the masked bits give 1, that's interpreted as 2, and so on.) Likewise, the `DEPTH` macro simply don't have a way to encode a matrix pixel format that is not one of the 8 predefined types.

**Comment by cdcseacave** [comment] 2017-05-06 16:45
@kinchungwong nothing from your answer addresses the 2 points I made earlier

@alalek pls review

**Comment by kinchungwong** [comment] 2017-05-06 22:40
@cdcseacave Sorry, I stand corrected.

I would suggest the following "criteria" (or, line of reasoning) that tries to explain why your suggested fix is better than the existing code.

Suppose a new `Mat_<T>` variable is created locally without allocating its data (i.e. it doesn't have a size). Suppose we have a different variable, that is allocated, and then released. After release, it is reasonable to expect that its properties (all getters), those that don't depend on the matrix being allocated, should compare equal between a default-constructed variable and a released variable.

```
Mat_<cv::Vec2i> matOne;
Mat_<cv::Vec2i> matTwo(cv::Size(1, 1));
matTwo.release();
assert(matOne.channels() == matTwo.channels()); 
// Assert not just channels(), but also every property that don't depend on whether the matrix is allocated.
```

Don't get me wrong; I think your fix is good; I'm just searching for a rationale in support of the new code (as opposed to being seen as an unnecessary code change).

The OpenCV API does require that, given a `Mat_<cv::Vec2i>` that doesn't have allocated data, that its `type()` method should still return `CV_32SC2`.

**Closed** 2017-05-23 10:46 UTC
Labels: bug, category: core
