### ISSUE TITLE
When the number of input's dimension is 1, the resize function's results has a dimensionality reduction

### ISSUE THREAD

**Issue by jyliu-dn** [opencv/opencv#16126] opened 2019-12-11 02:41 UTC
import numpy as np
import cv2

# If the third dimension is 1, the result's  dimension is reduced.
input = np.zeros((10,20,1))
print(input.shape)  ----------------> (10, 20, 1)
masks = cv2.resize(input, (40, 20), interpolation = cv2.INTER_LINEAR)
print(masks.shape)    ----------------> (20, 40)

# But if the third dimension is large than 1, the result's  dimension is same to the input.
input = np.zeros((10,20,3))
print(input.shape)  ----------------> (10, 20, 3)
masks = cv2.resize(input, (40, 20), interpolation = cv2.INTER_LINEAR)
print(masks.shape)    ----------------> (20, 40, 3)

This problem occurs in my project in doing the mask of image, and I think there is maybe something error in here,  the number of input's feature should not be reduced if the third dimension is 1.
Please give me some suggestion, and I am wishing your help

**Comment by dkurt** [comment] 2019-12-11 05:37
This is OpenCV's interpretation of grayscale and color images. There is no separate dimension in general. There are two spatial dimensions: width and height. Number of channels is different from them.

So this is not a bug but OpenCV's way to represent grayscale images. In fact, it has a single channel and no channels at the same time. Anyway we won't change this behavior because of compatibility.

BTW, I believe that in your algorithm you need to know which images are processed

**Comment by jyliu-dn** [comment] 2019-12-11 05:49
Thanks a lot, I have got it, and it's easy to process it with the reshape function.

**Comment by dkurt** [comment] 2019-12-11 07:38
Let me close it. Thanks!

**Closed by dkurt** 2019-12-11 07:38 UTC
Labels: wontfix
