### ISSUE TITLE
imshow throws error with any images other than dtype=np.uint8

### ISSUE THREAD

**Issue by daniel-s-ingram** [opencv/opencv#13318] opened 2018-11-28 13:46 UTC
##### System information (version)
- OpenCV => 4.0.0-dev
- Operating System / Platform => Ubuntu 16.04.05
- Compiler => gnu

##### Detailed description
When attempting to run the `dft.py` sample, I got the following error:

```
daniel@FX705GM:~/opencv/samples/python$ python dft.py 
usage : python dft.py <image_file>
[ WARN:0] cv::samples::findFile('baboon.jpg') => '/home/daniel/opencv/samples/python/../../samples/data/baboon.jpg'
Traceback (most recent call last):
  File "dft.py", line 111, in <module>
    cv.imshow("magnitude", log_spectrum)
cv2.error: OpenCV(4.0.0-dev) /home/daniel/opencv/modules/imgproc/src/color.hpp:261: error: (-2:Unspecified error) in function 'cv::CvtHelper<VScn, VDcn, VDepth, sizePolicy>::CvtHelper(cv::InputArray, cv::OutputArray, int) [with VScn = cv::Set<1>; VDcn = cv::Set<3, 4>; VDepth = cv::Set<0, 2, 5>; cv::SizePolicy sizePolicy = (cv::SizePolicy)2u; cv::InputArray = const cv::_InputArray&; cv::OutputArray = const cv::_OutputArray&]'
> Unsupported depth of input image:
>     'VDepth::contains(depth)'
> where
>     'depth' is 6 (CV_64F)
```

log_spectrum is float64 image, and after some digging, I found that my build is unable to display _any_ images other than ones with a dtype of np.uint8. These are the error messages I get for each dtype:

int8
```
cv2.error: OpenCV(4.0.0-dev) /home/daniel/opencv/modules/imgproc/src/color.hpp:261: error: (-2:Unspecified error) in function 'cv::CvtHelper<VScn, VDcn, VDepth, sizePolicy>::CvtHelper(cv::InputArray, cv::OutputArray, int) [with VScn = cv::Set<1>; VDcn = cv::Set<3, 4>; VDepth = cv::Set<0, 2, 5>; cv::SizePolicy sizePolicy = (cv::SizePolicy)2u; cv::InputArray = const cv::_InputArray&; cv::OutputArray = const cv::_OutputArray&]'
> Unsupported depth of input image:
>     'VDepth::contains(depth)'
> where
>     'depth' is 1 (CV_8S)
```

int16
```
cv2.error: OpenCV(4.0.0-dev) /home/daniel/opencv/modules/imgproc/src/color.hpp:261: error: (-2:Unspecified error) in function 'cv::CvtHelper<VScn, VDcn, VDepth, sizePolicy>::CvtHelper(cv::InputArray, cv::OutputArray, int) [with VScn = cv::Set<1>; VDcn = cv::Set<3, 4>; VDepth = cv::Set<0, 2, 5>; cv::SizePolicy sizePolicy = (cv::SizePolicy)2u; cv::InputArray = const cv::_InputArray&; cv::OutputArray = const cv::_OutputArray&]'
> Unsupported depth of input image:
>     'VDepth::contains(depth)'
> where
>     'depth' is 3 (CV_16S)
```

uint16
```
cv2.error: OpenCV(4.0.0-dev) /home/daniel/opencv/modules/highgui/src/window_gtk.cpp:146: error: (-215:Assertion failed) dst.data == widget->original_image->data.ptr in function 'cvImageWidgetSetImage'
```

int32
```
cv2.error: OpenCV(4.0.0-dev) /home/daniel/opencv/modules/imgproc/src/color.hpp:261: error: (-2:Unspecified error) in function 'cv::CvtHelper<VScn, VDcn, VDepth, sizePolicy>::CvtHelper(cv::InputArray, cv::OutputArray, int) [with VScn = cv::Set<1>; VDcn = cv::Set<3, 4>; VDepth = cv::Set<0, 2, 5>; cv::SizePolicy sizePolicy = (cv::SizePolicy)2u; cv::InputArray = const cv::_InputArray&; cv::OutputArray = const cv::_OutputArray&]'
> Unsupported depth of input image:
>     'VDepth::contains(depth)'
> where
>     'depth' is 4 (CV_32S)
```

float32
```
cv2.error: OpenCV(4.0.0-dev) /home/daniel/opencv/modules/highgui/src/window_gtk.cpp:146: error: (-215:Assertion failed) dst.data == widget->original_image->data.ptr in function 'cvImageWidgetSetImage'
```

float64
```
cv2.error: OpenCV(4.0.0-dev) /home/daniel/opencv/modules/imgproc/src/color.hpp:261: error: (-2:Unspecified error) in function 'cv::CvtHelper<VScn, VDcn, VDepth, sizePolicy>::CvtHelper(cv::InputArray, cv::OutputArray, int) [with VScn = cv::Set<1>; VDcn = cv::Set<3, 4>; VDepth = cv::Set<0, 2, 5>; cv::SizePolicy sizePolicy = (cv::SizePolicy)2u; cv::InputArray = const cv::_InputArray&; cv::OutputArray = const cv::_OutputArray&]'
> Unsupported depth of input image:
>     'VDepth::contains(depth)'
> where
>     'depth' is 6 (CV_64F)
```

Is this happening for anyone else?

**Comment by alalek** [comment] 2018-11-28 15:16
Support of non-`CV_8U` images are not straightforward. Some scale are applied implicitly.
To receive accurate results consider using of manual conversion with proper scaling.

Try this patch: #13264

duplicate of #13216

**Closed by alalek** 2018-11-28 15:16 UTC
Labels: duplicate

**Comment by dhaya-849-Elon** [comment] 2021-02-18 12:45
cv2.error: OpenCV(4.0.0-dev) /home/daniel/opencv/modules/imgproc/src/color.hpp:261: error: (-2:Unspecified error) in function 'cv::CvtHelper<VScn, VDcn, VDepth, sizePolicy>::CvtHelper(cv::InputArray, cv::OutputArray, int) [with VScn = cv::Set<1>; VDcn = cv::Set<3, 4>; VDepth = cv::Set<0, 2, 5>; cv::SizePolicy sizePolicy = (cv::SizePolicy)2u; cv::InputArray = const cv::_InputArray&; cv::OutputArray = const cv::_OutputArray&]'
> Unsupported depth of input image:
>     'VDepth::contains(depth)'
> where
>     'depth' is 6 (CV_64F) 

this happens to me when I tried saving my file.. Can you help me out in this...???
