### ISSUE TITLE
cv2.dnn performance comparison between 2060 and 3070

### ISSUE THREAD

**Issue by QBarbeAusy** [opencv/opencv#19323] opened 2021-01-14 14:58 UTC
System information (version):

    OpenCV => 4.4.0
    Operating System / Platform => Windows 64 Bit
    Compiler => Visual Studio 2019
    Cuda => 11.1
    Cudnn => 8.0.5
    Python => 3.8.2

Detailed description:

Hi there,

I think I maybe have a problem that I'm not sure to understand. I'm trying to use Cuda Dnn to perform objects detection using yolov4 using this [script ](https://gist.github.com/YashasSamaga/e2b19a6807a13046e399f4bc3cca3a49) with python.

Everything is ok with a 2060 and Cuda 10.1 with Cudnn 7.6.5 and I hit around 60 fps .

I bought a 3070 to improve this analysis and ,due to compute capability which insreases, I need to use Cuda 11.1 with Cudnn 8.0.5 now. The problem is, when I'm trying to run this code using my brand new 3070 I hit 'only' 85 fps which is less than exepected for a 2080 for example.

I already try this code on a 2070 GPU and I hit around 75 fps.

Did I missed something? I know that 3070 GPU get less FP16 cores than 2080/2080TI is that the reason why I have this misimprovment?

Is there a way to correct this? To use FP32 instead of FP16?

**Comment by YashasSamaga** [comment] 2021-01-14 17:44
I am not sure but I think this has something to do with old cuDNN API being used in OpenCV. cuDNN 8 introduced a new API but provided the v7 API for backwards compatibility (which OpenCV is currently using). The v7 API in cuDNN 8 has performance regressions on many devices. YOLOv4 appears to be slower (even 2x slower sometimes) on many devices.

There have been some discussion on NVIDIA developer forums and elsewhere. It could be due to suboptimal selection of convolution algorithms. Autotuning or moving to v8 API might solve the issue but that's quite some work.

**Comment by QBarbeAusy** [comment] 2021-01-14 18:10
Thanks for you answer @YashasSamaga . So you mean that, for the moment and due to the 8.X.X version of Cudnn it's normal to have this 'low' performances?
To conclude ,for Opencv's Dnn use it's better to use a 2080 TI than a 3090 ?

**Comment by YashasSamaga** [comment] 2021-01-15 02:40
> So you mean that, for the moment and due to the 8.X.X version of Cudnn it's normal to have this 'low' performances?

I think so. This performance regression affects Darknet too.

> To conclude ,for Opencv's Dnn use it's better to use a 2080 TI than a 3090 ?

Yes, YOLOv4 with 608 x 608 gives 110+ FPS on FP16 on RTX 2080 Ti with cuDNN 7.6.5. You can find more stats in Darknet's ReadMe.

**Comment by QBarbeAusy** [comment] 2021-01-18 07:52
Perfect, Thanks @YashasSamaga !
Good luck with it, I'm already satisfied that the 3070 is a bit better than a 2060! Time to be patient now.

**Closed** 2021-01-18 07:52 UTC
Labels: category: dnn, category: gpu/cuda (contrib)

**Comment by YashasSamaga** [comment] 2021-04-29 12:45
> There was a performance regression in certain use cases comparing RTX 3090 using cuDNN version 8.x to RTX 2080 Ti using cuDNN version 7.x. This regression has been fixed in this release. 
> Source: [cuDNN 8.2 release notes](https://docs.nvidia.com/deeplearning/cudnn/release-notes/rel_8.html)

**Comment by QBarbeAusy** [comment] 2021-04-29 20:50
I did a little experiment which can be usefull for 30XX users.

As mentionned before,with cuda 11.1 and Cudnn 8.0.5, using my RTX3070 I hit around 85 fps before with yolov4.

With Cuda 11.3 and Cudnn 8.2.0 I now hit (same video, same input_size, with yolov4, same computer'setup...) I hit around 91 fps which means +5% of efficiency.

BUT

using yolov3 before I hit around 90-95 fps and now I'm up to 115 which means +20-25% of efficiency.

So, it looks that Cudnn 8.2.0 changed some things but it gives some better results with yolov3 than yolov4!

| | Cuda 11.1 + Cudnn 8.0.5 | Cuda 11.3 + Cudnn 8.2.0 | + Efficiency | 
| ------------- | ------------- | ------------- | ------------- | 
|yolov3| 90-95 fps  | 115 fps | + 20% |
|yolov4| 85 fps | 91 fps | + 5 % |
