### ISSUE TITLE
cv2 VideoCapture doesn't work correctly when fps and tbr are different

### ISSUE THREAD

**Issue by ramya1782** [opencv/opencv#12810] opened 2018-10-12 12:07 UTC
I have a video with 25 fps and 50 tbr, when i capture video the output is not as expected,
Observations:
 1.set CV_CAP_PROP_POS_FRAMES to some position and start to capture, the captured frame won't match the actual frame (at that time) pos/time when i watch the video using vlc player
2.The number of frames captured is less than the frames captured directly using ffmpeg. Many frames at the start are missing
You can download the video from the specified link,
https://drive.google.com/open?id=1RPvNcaiMTNWTA8Pi5MOMT1i07FmPiFXR

How to simulate:
1.Dump all the frames using video capture from the beginning without using set position.

handler = cv2.VideoCapture()
fd = handler.open(filename)
 ret,frame=handler.read()
index = 0
while frame is not None:
	cv2.imwrite(str(index)+".jpg",frame)
	ret,frame=handler.read()
	index+=1

2.Set frame position to 5840 and try to match the frame dumped now and the previous one without set.

handler = cv2.VideoCapture()
fd = handler.open(filename)
ret,frame=handler.read()
handler.set(cv2.CAP_PROP_POS_FRAMES, 5340)
ret,frame=handler.read()
cv2.imwrite("using_set_"+str(5340)+".jpg",frame)

Output  [5340.jpg] is not same as [using_set_5340.jpg]

**Comment by alalek** [comment] 2019-09-26 13:38
duplicate of #9053

**Closed by alalek** 2019-09-26 13:38 UTC
Labels: category: videoio, duplicate, feature, priority: low
