### ISSUE TITLE
bindings generatator does not respect opencv_modules.hpp

### ISSUE THREAD

**Issue by paroj** [opencv/opencv#12672] opened 2018-09-27 13:56 UTC
##### System information (version)
- OpenCV => 3.4.3

##### Detailed description

the bindings generator seems not to respect the `HAVE_OPENCV_*` defines.

##### Steps to reproduce

in cmake set:
```
BUILD_LIST=features2d,python3
```

you will get a compile error like
```
opencv/build/modules/python_bindings_generator/pyopencv_generated_types.h:710:46: error: ‘FlannBasedMatcher’ is not a member of ‘cv’
 template<> PyObject* pyopencv_from(const Ptr<cv::FlannBasedMatcher>& r)
```

as the generator still picks up code guarded by
```
#if defined(HAVE_OPENCV_FLANN)
```

**Comment by dkurt** [comment] 2018-09-27 14:11
duplicate of https://github.com/opencv/opencv/issues/10175

**Closed** 2018-09-27 14:28 UTC
Labels: duplicate
