### ISSUE TITLE
Python bindings generation fails if path to source code contains a "+" character

### ISSUE THREAD

**Issue by SwooshyCueb** [opencv/opencv#11894] opened 2018-07-04 14:24 UTC
If the path to the OpenCV source code contains a "+" character (common scenario: code is extracted into folder named like `opencv-3.4.1+0dfsg1`), generation of the `headers.txt` used in python bindings generation fails silently during configuration. Building off this configuration fails spectacularly, but without any indication that this is the culprit. This seems to be caused by the call to `ocv_list_filter` on [line 23 of `modules/python/bindings/CMakeLists.txt`](https://github.com/opencv/opencv/blob/3.4.1/modules/python/bindings/CMakeLists.txt#L23), as the output of the command is empty in this situation.

While an easy solution might be "don't put opencv in a folder with a plus in it", I suspect this will interfere with some debian package building software.

**Comment by hrnr** [comment] 2018-07-04 15:13
duplicate of #6046

However, I think this is a valid issue and fixing should be considered. Interacting with existing packaging software is a real concern.

I believe there should be a better way in CMake than using paths as regexes.

**Comment by hrnr** [comment] 2018-07-04 15:17
BTW all the people had problems with just `+` sign. This could be easily tested in CI, by putting OpenCV under and evil crafted folder.

**Closed** 2018-08-01 11:05 UTC
Labels: bug, category: build/install, priority: low
