### ISSUE TITLE
opencv4 load onnx model 

### ISSUE THREAD

**Issue by amandazw** [opencv/opencv#17652] opened 2020-06-24 09:16 UTC
net = cv2.dnn.readNetFromONNX(model_path)
cv2.error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\dnn\src\dnn.cpp:562: error: (-2:Unspecified error) Can't create layer "conv2d_9.tmp_2" of type "HardSigmoid" in function 'cv::dnn::dnn4_v20191202::LayerData::getLayerInstance'

How can i fix this error？

**Comment by dkurt** [comment] 2020-06-24 11:06
Closing until we have a reproducer

**Closed** 2020-06-24 11:06 UTC
Labels: category: dnn, incomplete

**Comment by sky-fly97** [comment] 2020-07-01 02:52
> net = cv2.dnn.readNetFromONNX(model_path)
> cv2.error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\dnn\src\dnn.cpp:562: error: (-2:Unspecified error) Can't create layer "conv2d_9.tmp_2" of type "HardSigmoid" in function 'cv::dnn::dnn4_v20191202::LayerData::getLayerInstance'
> 
> How can i fix this error？

Can you read the onnx model now?I can't read in any onnx model！

**Comment by amandazw** [comment] 2020-07-01 02:54
> > net = cv2.dnn.readNetFromONNX(model_path)
> > cv2.error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\dnn\src\dnn.cpp:562: error: (-2:Unspecified error) Can't create layer "conv2d_9.tmp_2" of type "HardSigmoid" in function 'cv::dnn::dnn4_v20191202::LayerData::getLayerInstance'
> > How can i fix this error？
> 
> Can you read the onnx model now?I can't read in any onnx model！

I can't read any onnx using opencv dnn, I think there must be some operators that opencv dnn does not support.......

**Comment by sky-fly97** [comment] 2020-07-01 02:59
> > > net = cv2.dnn.readNetFromONNX(model_path)
> > > cv2.error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\dnn\src\dnn.cpp:562: error: (-2:Unspecified error) Can't create layer "conv2d_9.tmp_2" of type "HardSigmoid" in function 'cv::dnn::dnn4_v20191202::LayerData::getLayerInstance'
> > > How can i fix this error？
> > 
> > 
> > Can you read the onnx model now?I can't read in any onnx model！
> 
> I can't read any onnx using opencv dnn, I think there must be some operators that opencv dnn does not support.......

Me too! ! ! My opencv reads **Darknet's yolov3.weights** without any problems, but when I want to use opencv dnn to read **yolov3-spp.weights** I get an **error**. Then I converted it to **yolov3-spp.onnx** and still reported an **error**. Finally, I downloaded a lot of models from the **ONNX model library**, and **none** of them can be read in! ! !

**Comment by amandazw** [comment] 2020-07-01 03:05
> > > > net = cv2.dnn.readNetFromONNX(model_path)
> > > > cv2.error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\dnn\src\dnn.cpp:562: error: (-2:Unspecified error) Can't create layer "conv2d_9.tmp_2" of type "HardSigmoid" in function 'cv::dnn::dnn4_v20191202::LayerData::getLayerInstance'
> > > > How can i fix this error？
> > > 
> > > 
> > > Can you read the onnx model now?I can't read in any onnx model！
> > 
> > 
> > I can't read any onnx using opencv dnn, I think there must be some operators that opencv dnn does not support.......
> 
> Me too! ! ! My opencv reads **Darknet's yolov3.weights** without any problems, but when I want to use opencv dnn to read **yolov3-spp.weights** I get an **error**. Then I converted it to **yolov3-spp.onnx** and still reported an **error**. Finally, I downloaded a lot of models from the **ONNX model library**, and **none** of them can be read in! ! !

Maybe you can find the layer that opencv dnn does not support,  and rewrite by yourself.I know what's wrong with my onnx model(maybe is the lstm layer???), but I don't know how to rewrite :-( ,

**Comment by sky-fly97** [comment] 2020-07-01 04:33
> > > > > net = cv2.dnn.readNetFromONNX(model_path)
> > > > > cv2.error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\dnn\src\dnn.cpp:562: error: (-2:Unspecified error) Can't create layer "conv2d_9.tmp_2" of type "HardSigmoid" in function 'cv::dnn::dnn4_v20191202::LayerData::getLayerInstance'
> > > > > How can i fix this error？
> > > > 
> > > > 
> > > > Can you read the onnx model now?I can't read in any onnx model！
> > > 
> > > 
> > > I can't read any onnx using opencv dnn, I think there must be some operators that opencv dnn does not support.......
> > 
> > 
> > Me too! ! ! My opencv reads **Darknet's yolov3.weights** without any problems, but when I want to use opencv dnn to read **yolov3-spp.weights** I get an **error**. Then I converted it to **yolov3-spp.onnx** and still reported an **error**. Finally, I downloaded a lot of models from the **ONNX model library**, and **none** of them can be read in! ! !
> 
> Maybe you can find the layer that opencv dnn does not support, and rewrite by yourself.I know what's wrong with my onnx model(maybe is the lstm layer???), but I don't know how to rewrite :-( ,

It can’t even read Frcnn’s onnx model, let alone some of the current models. I think it’s missing a lot...but no one seems to notice this problem.

**Comment by sky-fly97** [comment] 2020-07-01 04:34
> Closing until we have a reproducer

Is there no problem when you read the **onnx** model? I want to know whether it is our own problem or the inherent problem of opencv.

**Comment by zbigos** [comment] 2021-06-16 19:32
> net = cv2.dnn.readNetFromONNX(model_path)
> cv2.error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\dnn\src\dnn.cpp:562: error: (-2:Unspecified error) Can't create layer "conv2d_9.tmp_2" of type "HardSigmoid" in function 'cv::dnn::dnn4_v20191202::LayerData::getLayerInstance'
> 
> How can i fix this error？

I've run into this problem today when running mobilenet v3 in onnx format (it's not quite OPs yolov3, and I'm not sure if it's 100% related). This specifically (message pasted) is opencv screaming that it can't do HardSigmoid. Now, I managed to patch my local opencv instalation to run this function, and it seems to work. 

@dkurt I'm tagging you to ask if implementing HardSigmoid into `opencv/dnn` would be a welcome PR. If so, would you have any docs/guidelines that would guide me into writing this properly (i.e. not missing any files, and writing good cuda code would be my main concerns)

**Comment by berak** [comment] 2021-06-17 08:12
@zbigos, you could start experimenting with a  [custom dnn layer](https://docs.opencv.org/master/dc/db1/tutorial_dnn_custom_layers.html)
(that's supposed to happen in *your program*, not inside  the *library*, much easier to work with)

**Comment by zbigos** [comment] 2021-06-17 09:04
> could start experimenting with a custom dnn layer  

That was an interesting read, thanks. I definitely should look at the manual before jumping into editing sources.

> that's supposed to happen in your program, not inside the library

Yeah, with the possibility of adding a custom layer from program I see that my changes don't align with what an end user is supposed to do with opencv. However, my main question was about writing a PR for it. Since I've done basically 80% of the work already, I may as well finish it so everyone can have the proper library implementation. I'm just not so sure about rules about merging PRs with network operators, that's why I asked if I should even bother with it.

And on the side (I know that's derailing the conversation a bit). I definitely think that the link you posted should be printed alongside the `Can't create layer of type "HardSigmoid"` error message. I know that sounds like me trying to excuse myself from not reading the docs, but I honestly didn't even assume that adding a custom layer is a possibility.
