### ISSUE TITLE
cv::aruco::refineDetectedMarkers change detectedCorners[i] shape in some cases

### ISSUE THREAD

**Issue by LaurentBerger** [opencv/opencv#14014] opened 2019-03-09 18:04 UTC
Opencv 4.0.1-dev python version with cmake
visual studio 2017 win 64

I don't understand why cv.aruco.refineDetectedMarkers changes ndarray shape : 

My code : 

```
import cv2 as cv
import numpy as np

dico = cv.aruco.Dictionary_get(cv.aruco.DICT_7X7_250)
board=	cv.aruco.CharucoBoard_create(8, 5,  0.03455, 0.02164, dico)
detectorParams=cv.aruco.DetectorParameters_create()
detectorParams.cornerRefinementMethod = cv.aruco.CORNER_REFINE_SUBPIX
detectorParams.cornerRefinementMinAccuracy = 0.01
x = cv.imread("c:/tmp/nonerecover.png")
if x is None:
    print("Oops")
    exit()
print ("Detect ")
refAruco,ids,refus = cv.aruco.detectMarkers(image=x, dictionary=dico,parameters=detectorParams)
print("type ", type(refAruco[0]), "shape ",refAruco[0].shape, "len ",len(refAruco))
refAruco,ids,refus,recover = cv.aruco.refineDetectedMarkers(x, board, refAruco,ids,rejectedCorners=refus)
print("Refine\nRecover ",recover)
print("type ", type(refAruco[0]), "shape ",refAruco[0].shape, "len ",len(refAruco))
x = cv.imread("c:/tmp/recover.png")
if x is None:
    print("Oops")
    exit()
print ("Detect ")
refAruco,ids,refus = cv.aruco.detectMarkers(image=x, dictionary=dico,parameters=detectorParams)
print("type ", type(refAruco[0]), "shape ",refAruco[0].shape, "len ",len(refAruco))
refAruco,ids,refus,recover = cv.aruco.refineDetectedMarkers(x, board, refAruco,ids,rejectedCorners=refus)
print("Refine\nRecover ",recover)
print("type ", type(refAruco[0]), "shape ",refAruco[0].shape, "len ",len(refAruco))

```
results : 
```
Detect
type  <class 'numpy.ndarray'> shape  (1, 4, 2) len  20
Refine
Recover  None
type  <class 'numpy.ndarray'> shape  (1, 4, 2) len  20
Detect
type  <class 'numpy.ndarray'> shape  (1, 4, 2) len  19
Refine
Recover  [[6]]
type  <class 'numpy.ndarray'> shape  (4, 1, 2) len  20
```
shape  (1, 4, 2)  means 1 array with 4 points in plane
 shape  (4, 1, 2) why does shape change?

nonrecover.png
![nonerecover](https://user-images.githubusercontent.com/3591626/54075389-128d6380-429f-11e9-8ed4-7386db971d84.png)

recover.png
![recover](https://user-images.githubusercontent.com/3591626/54075390-15885400-429f-11e9-96f5-e9e01174e31f.png)

There is no problem with c++ code (of course you cannot change size as in python )

```
   Ptr<aruco::Dictionary>  dico = aruco::getPredefinedDictionary(aruco::PREDEFINED_DICTIONARY_NAME(cv::aruco::DICT_7X7_250));
    Ptr<aruco::CharucoBoard> board = aruco::CharucoBoard::create(8, 5, 0.03455, 0.02164, dico);
    Ptr<aruco::DetectorParameters> detectorParams = aruco::DetectorParameters::create();
    detectorParams.get()->cornerRefinementMethod = aruco::CORNER_REFINE_SUBPIX;
    detectorParams.get()->cornerRefinementMinAccuracy = 0.01;

    vector< int > ids;
    vector< vector< Point2f > > refAruco, refus;
    vector<Point2f> echiquier;
    Mat x = imread("c:/tmp/nonerecover.png");
    cout << "\nDetect\n";
    aruco::detectMarkers(x, dico, refAruco, ids, detectorParams, refus);
    cout << "size refaruco : " << refAruco.size() << endl;
    cout << "size refus : " << refus.size() << endl;
    aruco::refineDetectedMarkers(x, board, refAruco, ids, refus);
    cout << "\nRefine\n";
    cout << "size refaruco : " << refAruco.size() << endl;
    cout << "size refus : " << refus.size() << endl;
    x = imread("c:/tmp/recover.png");
    refus.clear();
    ids.clear();
    refAruco.clear();

    cout << "\nDetect\n";
    aruco::detectMarkers(x, dico, refAruco, ids, detectorParams,refus);
    cout << "size refaruco : " << refAruco.size() << endl;
    cout << "size refus : " << refus.size() << endl;
    aruco::refineDetectedMarkers(x, board, refAruco, ids, refus);
    cout << "\nRefine\n";
    cout << "size refaruco : " << refAruco.size() << endl;
    cout << "size refus : " << refus.size() << endl;

```

Results : 

G:\LiDetect
size refaruco : 20
size refus : 41

Refine
size refaruco : 20
size refus : 41

Detect
size refaruco : 19
size refus : 42

Refine
size refaruco : 20
size refus : 41

 . . .

**Comment by LaurentBerger** [comment] 2019-03-09 18:18
sorry it sould be in opencv_contrib

**Comment by alalek** [comment] 2019-03-09 18:22
BTW, "admins" can transfer issue: https://help.github.com/en/articles/transferring-an-issue-to-another-repository (GitHub creates new one and adds redirect from the old link).

**Comment by AleksandrPanov** [comment] 2021-11-10 15:43
There is no python bindings problem.
cpp reproducer:
[repr_refineDetectedMarkers.cpp.txt](https://github.com/opencv/opencv/files/7514004/repr_refineDetectedMarkers.cpp.txt)

**Comment by AleksandrPanov** [comment] 2021-11-10 15:45
The problem is fixed [here](https://github.com/AleksandrPanov/opencv_contrib/commit/363a8634c9e8aba303259f1447714aff2c053afb). It remains to add a test and open PR.

**Comment by alalek** [comment] 2021-11-18 04:35
> shape (1, 4, 2) means 1 array with 4 points in plane

> means 1 array

This just means that `cv::Mat` can't work with 1D arrays. `1` here has no real meaning in the code - just extra dimension for 2D.
`Mat` contains 4 points of 2 components (x,y = `CV_32FC2`).

---

IMHO, `InputOutputArrayOfArrays` should not be used to pass array of pointers.
It should be just `OutputArray` with ndarray shape `[npoints, 4, 2]` or `cv::Mat` with `Size(4, npoints)` of `CV_32FC2`.

**Comment by AleksandrPanov** [comment] 2022-02-09 22:55
fixed by https://github.com/opencv/opencv_contrib/pull/3105

**Closed** 2022-02-09 22:54 UTC
Labels: bug, category: contrib
