### ISSUE TITLE
OpenCV 4.5.3 on VS2019 cannot find *.dll

### ISSUE THREAD

**Issue by Huihh** [opencv/opencv#20416] opened 2021-07-15 09:26 UTC
##### System information (version)
- OpenCV => 4.5.3
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2019

##### Detailed description
after I create OpenCV on VS2019 enviroment,   I write a simple OpenCV demo on VS2019, It can build and run ok, but terminal info failed load *dll.    error like this:

[ INFO:0] global c:\build\master_winpack-build-win64-vc15\opencv\modules\highgui\src\registry.impl.hpp (114) cv::highgui_backend::UIBackendRegistry::UIBackendRegistry UI: Enabled backends(4, sorted by priority): GTK(1000); GTK3(990); GTK2(980); WIN32(970) + BUILTIN(WIN32UI)
[ INFO:0] global c:\build\master_winpack-build-win64-vc15\opencv\modules\core\src\utils\plugin_loader.impl.hpp (67) cv::plugin::impl::DynamicLib::libraryLoad load D:\develop_tool\vs_studio\opencv\build\x64\vc15\bin\opencv_highgui_gtk453_64.dll => FAILED
[ INFO:0] global c:\build\master_winpack-build-win64-vc15\opencv\modules\core\src\utils\plugin_loader.impl.hpp (67) cv::plugin::impl::DynamicLib::libraryLoad load opencv_highgui_gtk453_64.dll => FAILED
[ INFO:0] global c:\build\master_winpack-build-win64-vc15\opencv\modules\core\src\utils\plugin_loader.impl.hpp (67) cv::plugin::impl::DynamicLib::libraryLoad load D:\develop_tool\vs_studio\opencv\build\x64\vc15\bin\opencv_highgui_gtk3453_64.dll => FAILED
[ INFO:0] global c:\build\master_winpack-build-win64-vc15\opencv\modules\core\src\utils\plugin_loader.impl.hpp (67) cv::plugin::impl::DynamicLib::libraryLoad load opencv_highgui_gtk3453_64.dll => FAILED
[ INFO:0] global c:\build\master_winpack-build-win64-vc15\opencv\modules\core\src\utils\plugin_loader.impl.hpp (67) cv::plugin::impl::DynamicLib::libraryLoad load D:\develop_tool\vs_studio\opencv\build\x64\vc15\bin\opencv_highgui_gtk2453_64.dll => FAILED
[ INFO:0] global c:\build\master_winpack-build-win64-vc15\opencv\modules\core\src\utils\plugin_loader.impl.hpp (67) cv::plugin::impl::DynamicLib::libraryLoad load opencv_highgui_gtk2453_64.dll => FAILED
[ INFO:0] global C:\build\master_winpack-build-win64-vc15\opencv\modules\highgui\src\backend.cpp (90) cv::highgui_backend::createUIBackend UI: using backend: WIN32 (priority=970)
[ INFO:0] global C:\build\master_winpack-build-win64-vc15\opencv\modules\highgui\src\window_w32.cpp (3009) cv::impl::Win32BackendUI::createWindow OpenCV/UI: Creating Win32UI window: input (1)
[ INFO:0] global c:\build\master_winpack-build-win64-vc15\opencv\modules\core\src\parallel\registry_parallel.impl.hpp (96) cv::parallel::ParallelBackendRegistry::ParallelBackendRegistry core(parallel): Enabled backends(3, sorted by priority): ONETBB(1000); TBB(990); OPENMP(980)
[ INFO:0] global c:\build\master_winpack-build-win64-vc15\opencv\modules\core\src\utils\plugin_loader.impl.hpp (67) cv::plugin::impl::DynamicLib::libraryLoad load D:\develop_tool\vs_studio\opencv\build\x64\vc15\bin\opencv_core_parallel_onetbb453_64d.dll => FAILED
[ INFO:0] global c:\build\master_winpack-build-win64-vc15\opencv\modules\core\src\utils\plugin_loader.impl.hpp (67) cv::plugin::impl::DynamicLib::libraryLoad load opencv_core_parallel_onetbb453_64d.dll => FAILED
[ INFO:0] global c:\build\master_winpack-build-win64-vc15\opencv\modules\core\src\utils\plugin_loader.impl.hpp (67) cv::plugin::impl::DynamicLib::libraryLoad load D:\develop_tool\vs_studio\opencv\build\x64\vc15\bin\opencv_core_parallel_tbb453_64d.dll => FAILED
[ INFO:0] global c:\build\master_winpack-build-win64-vc15\opencv\modules\core\src\utils\plugin_loader.impl.hpp (67) cv::plugin::impl::DynamicLib::libraryLoad load opencv_core_parallel_tbb453_64d.dll => FAILED
[ INFO:0] global c:\build\master_winpack-build-win64-vc15\opencv\modules\core\src\utils\plugin_loader.impl.hpp (67) cv::plugin::impl::DynamicLib::libraryLoad load D:\develop_tool\vs_studio\opencv\build\x64\vc15\bin\opencv_core_parallel_openmp453_64d.dll => FAILED
[ INFO:0] global c:\build\master_winpack-build-win64-vc15\opencv\modules\core\src\utils\plugin_loader.impl.hpp (67) cv::plugin::impl::DynamicLib::libraryLoad load opencv_core_parallel_openmp453_64d.dll => FAILED

I search online over, but I can't find ansower, please give me a favor, think you very much.

##### Steps to reproduce

#include <opencv2/opencv.hpp>
#include <iostream>

using namespace std;
using namespace cv;

int main()
{
	Mat src = imread("D:/windows_tool/dask_background/test.jpg");
	imshow("input", src);

	waitKey(0);

	destroyAllWindows();

	return 0;
}

##### Issue submission checklist

 - [ ] I checked the problem with documentation, FAQ, open issues,

**Comment by alalek** [comment] 2021-07-15 10:54
duplicate of #20113
These messages are visible in debug builds or with enabled INFO through OPENCV_LOG_LEVEL

**Closed by alalek** 2021-07-15 10:54 UTC
Labels: duplicate, question (invalid tracker)
