### ISSUE TITLE
Compile failed

### ISSUE THREAD

**Issue by codeloverr** [opencv/opencv#9916] opened 2017-10-23 09:49 UTC
I cloned the master branch of opencv and opencv_contrib. Trying to build using 
`     cmake -DCMAKE_INSTALL_PREFIX=/usr      \
      -DCMAKE_BUILD_TYPE=Release       \
      -DCMAKE_CXX_FLAGS=-std=c++11     \
      -DOPENCV_EXTRA_MODULES_PATH=~/opencv_contrib/modules \
      -DBUILD_WITH_DEBUG_INFO=OFF  ..                     && 
      make`
Also tried with `make -j4`. I'm using Ubuntu 16.04. But getting same error 

`      [ 35%] Building NVCC (Device) object modules/core/CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_gpu_mat.cu.o
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
/usr/lib/gcc/x86_64-linux-gnu/5/include/stddef.h(436): error: identifier "nullptr" is undefined

/usr/lib/gcc/x86_64-linux-gnu/5/include/stddef.h(436): error: expected a ";"

/usr/include/x86_64-linux-gnu/c++/5/bits/c++config.h(200): error: expected a ";"

/usr/include/c++/5/exception(63): error: expected a ";"

/usr/include/c++/5/exception(68): error: expected a ";"

/usr/include/c++/5/exception(76): error: expected a ";"

/usr/include/c++/5/exception(83): error: expected a ";"

/usr/include/c++/5/exception(93): error: expected a "{"

/usr/include/c++/5/bits/exception_ptr.h(64): error: function "std::current_exception" returns incomplete type "std::__exception_ptr::exception_ptr"

/usr/include/c++/5/bits/exception_ptr.h(64): error: expected a "{"

/usr/include/c++/5/bits/exception_ptr.h(79): error: expected a ";"

/usr/include/c++/5/bits/exception_ptr.h(81): error: expected a ";"

/usr/include/c++/5/bits/exception_ptr.h(82): error: expected a ";"

/usr/include/c++/5/bits/exception_ptr.h(84): error: expected a ";"

/usr/include/c++/5/bits/exception_ptr.h(86): error: declaration is incompatible with previous "std::current_exception"
(64): here

/usr/include/c++/5/bits/exception_ptr.h(86): error: use of a local type to declare a function

/usr/include/c++/5/bits/exception_ptr.h(86): error: expected a ";"

/usr/include/c++/5/bits/exception_ptr.h(87): error: use of a local type to declare a function

/usr/include/c++/5/bits/exception_ptr.h(90): error: expected a ";"

/usr/include/c++/5/bits/exception_ptr.h(92): error: expected a ";"

/usr/include/c++/5/bits/exception_ptr.h(95): error: incomplete type is not allowed

/usr/include/c++/5/bits/exception_ptr.h(95): error: expected a ";"

/usr/include/c++/5/bits/exception_ptr.h(116): error: expected a ";"

/usr/include/c++/5/bits/exception_ptr.h(126): error: expected a ";"

/usr/include/c++/5/bits/exception_ptr.h(143): error: use of a local type to declare a function

/usr/include/c++/5/bits/exception_ptr.h(144): error: expected a ";"

/usr/include/c++/5/bits/exception_ptr.h(147): error: expected a ";"

/usr/include/c++/5/bits/exception_ptr.h(152): error: use of a local type to declare a function

/usr/include/c++/5/bits/exception_ptr.h(153): error: expected a ";"

/usr/include/c++/5/bits/exception_ptr.h(156): error: use of a local type to declare a function

/usr/include/c++/5/bits/exception_ptr.h(157): error: expected a ";"

/usr/include/c++/5/bits/exception_ptr.h(160): error: use of a local type to declare a function

/usr/include/c++/5/bits/exception_ptr.h(161): error: expected a ";"

/usr/include/c++/5/bits/exception_ptr.h(169): error: expected a ";"

/usr/include/c++/5/bits/exception_ptr.h(195): error: expected a ";"

/usr/include/c++/5/bits/nested_exception.h(57): error: incomplete type is not allowed

/usr/include/c++/5/bits/nested_exception.h(60): error: expected a ";"

/usr/include/c++/5/bits/nested_exception.h(64): error: expected a ";"

/usr/include/c++/5/bits/nested_exception.h(66): error: expected a ";"

/usr/include/c++/5/bits/nested_exception.h(78): error: expected a ";"

/usr/include/c++/5/bits/nested_exception.h(73): error: identifier "rethrow_exception" is undefined

/usr/include/c++/5/bits/nested_exception.h(74): error: namespace "std" has no member "terminate"

/usr/include/c++/5/new(96): error: expected a "{"

/usr/include/c++/5/new(111): error: allocation operator may not be declared in a namespace

/usr/include/c++/5/new(113): error: allocation operator may not be declared in a namespace

/usr/include/c++/5/new(115): error: deallocation operator may not be declared in a namespace

/usr/include/c++/5/new(115): error: expected a "{"

/usr/include/c++/5/new(130): error: identifier "__p" is undefined

/usr/include/c++/5/new(131): error: allocation operator may not be declared in a namespace

/usr/include/c++/5/new(131): error: expected a "{"

/usr/include/c++/5/new(135): error: deallocation operator may not be declared in a namespace

/usr/include/c++/5/new(135): error: expected a "{"

/usr/include/c++/5/new(136): error: deallocation operator may not be declared in a namespace

/usr/include/c++/5/new(136): error: expected a "{"

/usr/include/c++/5/bits/cpp_type_traits.h(185): error: identifier "char16_t" is undefined

/usr/include/c++/5/bits/cpp_type_traits.h(192): error: identifier "char32_t" is undefined

/usr/include/c++/5/bits/cpp_type_traits.h(192): error: class "std::__is_integer<<error-type>>" has already been defined

/usr/include/c++/5/bits/cpp_type_traits.h(344): error: namespace "std::__gnu_cxx" has no member "__normal_iterator"

/usr/include/c++/5/bits/cpp_type_traits.h(344): error: expected a ">"

/usr/include/c++/5/ext/type_traits.h(159): error: inline specifier allowed on function declarations only

/usr/include/c++/5/ext/type_traits.h(160): error: declaration is incompatible with overloaded function "__gnu_cxx::__is_null_pointer"
(150): here

/usr/include/c++/5/ext/type_traits.h(160): error: namespace "std" has no member "nullptr_t"

/usr/include/c++/5/ext/type_traits.h(161): error: expected a ";"

/usr/include/c++/5/ext/type_traits.h(173): error: a template argument list is not allowed in a declaration of a primary template

/usr/include/c++/5/ext/type_traits.h(177): error: __promote is not a template

/usr/include/c++/5/ext/type_traits.h(181): error: __promote is not a template

/usr/include/c++/5/ext/type_traits.h(185): error: __promote is not a template

/usr/include/c++/5/ext/type_traits.h(189): error: __promote is not a template

/usr/include/c++/5/ext/type_traits.h(189): error: expected a ">"

/usr/include/c++/5/ext/type_traits.h(189): error: the global scope has no "__type"

/usr/include/c++/5/ext/type_traits.h(197): error: __promote is not a template

/usr/include/c++/5/ext/type_traits.h(197): error: expected a ">"

/usr/include/c++/5/ext/type_traits.h(197): error: the global scope has no "__type"

/usr/include/c++/5/ext/type_traits.h(206): error: __promote is not a template

/usr/include/c++/5/ext/type_traits.h(206): error: expected a ">"

/usr/include/c++/5/ext/type_traits.h(206): error: the global scope has no "__type"

/usr/include/c++/5/cmath(80): error: inline specifier allowed on function declarations only

/usr/include/c++/5/cmath(80): error: expected a ";"

/usr/include/c++/5/cmath(105): error: inline specifier allowed on function declarations only

/usr/include/c++/5/cmath(105): error: variable "std::constexpr" has already been defined

/usr/include/c++/5/cmath(105): error: expected a ";"

/usr/include/c++/5/cmath(124): error: inline specifier allowed on function declarations only

/usr/include/c++/5/cmath(124): error: variable "std::constexpr" has already been defined

/usr/include/c++/5/cmath(124): error: expected a ";"

/usr/include/c++/5/cmath(143): error: inline specifier allowed on function declarations only

/usr/include/c++/5/cmath(143): error: variable "std::constexpr" has already been defined

/usr/include/c++/5/cmath(143): error: expected a ";"

/usr/include/c++/5/cmath(162): error: inline specifier allowed on function declarations only

/usr/include/c++/5/cmath(162): error: variable "std::constexpr" has already been defined

/usr/include/c++/5/cmath(162): error: expected a ";"

/usr/include/c++/5/cmath(183): error: inline specifier allowed on function declarations only

/usr/include/c++/5/cmath(183): error: variable "std::constexpr" has already been defined

/usr/include/c++/5/cmath(183): error: expected a ";"

/usr/include/c++/5/cmath(202): error: inline specifier allowed on function declarations only

/usr/include/c++/5/cmath(202): error: variable "std::constexpr" has already been defined

/usr/include/c++/5/cmath(202): error: expected a ";"

/usr/include/c++/5/cmath(221): error: inline specifier allowed on function declarations only

/usr/include/c++/5/cmath(221): error: variable "std::constexpr" has already been defined

/usr/include/c++/5/cmath(221): error: expected a ";"

/usr/include/c++/5/cmath(240): error: inline specifier allowed on function declarations only

Error limit reached.
100 errors detected in the compilation of "/tmp/tmpxft_00002f2d_00000000-21_gpu_mat.compute_61.cpp1.ii".
Compilation terminated.
CMake Error at cuda_compile_generated_gpu_mat.cu.o.cmake:264 (message):
  Error generating file
  /home/hannan/opencv/build/modules/core/CMakeFiles/cuda_compile.dir/src/cuda/./cuda_compile_generated_gpu_mat.cu.o

modules/core/CMakeFiles/opencv_core.dir/build.make:63: recipe for target 'modules/core/CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_gpu_mat.cu.o' failed
make[2]: *** [modules/core/CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_gpu_mat.cu.o] Error 1
CMakeFiles/Makefile2:2531: recipe for target 'modules/core/CMakeFiles/opencv_core.dir/all' failed
make[1]: *** [modules/core/CMakeFiles/opencv_core.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by codeloverr** [comment] 2017-10-23 10:41
Tried again with the following command 
`cd opencv
git checkout 3.3.0
cd
cd opencv_contrib
git checktou 3.3.0
cd
cd opencv/build

cmake -D CMAKE_BUILD_TYPE=RELEASE \
      -D CMAKE_INSTALL_PREFIX=/usr/local \
      -D INSTALL_C_EXAMPLES=ON \
      -D INSTALL_PYTHON_EXAMPLES=ON \
      -D WITH_TBB=ON \
      -D WITH_V4L=ON \
      -D WITH_QT=ON \
      -D WITH_OPENGL=ON \
      -D OPENCV_EXTRA_MODULES_PATH=~/opencv_contrib/modules \
      -D BUILD_EXAMPLES=ON ..
make -j8`

got following error:
 `[ 42%] Building CXX object modules/cudacodec/CMakeFiles/opencv_cudacodec.dir/src/video_writer.cpp.o
//usr/lib/x86_64-linux-gnu/libsoxr.so.0: undefined reference to `GOMP_parallel@GOMP_4.0'
collect2: error: ld returned 1 exit status
apps/visualisation/CMakeFiles/opencv_visualisation.dir/build.make:103: recipe for target 'bin/opencv_visualisation' failed
make[2]: *** [bin/opencv_visualisation] Error 1
CMakeFiles/Makefile2:26239: recipe for target 'apps/visualisation/CMakeFiles/opencv_visualisation.dir/all' failed
make[1]: *** [apps/visualisation/CMakeFiles/opencv_visualisation.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 42%] Building CXX object modules/cudacodec/CMakeFiles/opencv_cudacodec.dir/src/frame_queue.cpp.o
[ 42%] Building CXX object modules/cudacodec/CMakeFiles/opencv_cudacodec.dir/src/video_decoder.cpp.o
[ 42%] Building CXX object modules/cudaarithm/CMakeFiles/opencv_cudaarithm.dir/src/core.cpp.o
[ 42%] Linking CXX executable ../../bin/example_dnn-squeezenet_halide
[ 42%] Building CXX object modules/cudaarithm/CMakeFiles/opencv_cudaarithm.dir/src/element_operations.cpp.o
[ 42%] Building CXX object modules/cudacodec/CMakeFiles/opencv_cudacodec.dir/src/cuvid_video_source.cpp.o
[ 42%] Linking CXX executable ../../bin/example_dnn-ssd_object_detection
[ 42%] Built target example_dnn_squeezenet_halide
[ 42%] Building CXX object modules/cudaarithm/CMakeFiles/opencv_cudaarithm.dir/src/arithm.cpp.o
[ 42%] Building CXX object modules/cudacodec/CMakeFiles/opencv_cudacodec.dir/src/video_parser.cpp.o
[ 42%] Building CXX object modules/cudacodec/CMakeFiles/opencv_cudacodec.dir/src/ffmpeg_video_source.cpp.o
[ 42%] Linking CXX shared library ../../lib/libopencv_cudacodec.so
[ 42%] Built target example_dnn_ssd_object_detection
[ 42%] Built target opencv_cudacodec
[ 42%] Building CXX object modules/cudaarithm/CMakeFiles/opencv_cudaarithm.dir/src/reductions.cpp.o
[ 42%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/matchers.cpp.o
[ 42%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/gftt.cpp.o
[ 42%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/agast.cpp.o
[ 42%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/akaze.cpp.o
[ 42%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/mser.cpp.o
[ 42%] Linking CXX shared library ../../lib/libopencv_cudaarithm.so
[ 42%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/agast_score.cpp.o
[ 42%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/bagofwords.cpp.o
[ 42%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/orb.cpp.o
[ 42%] Built target opencv_cudaarithm
[ 42%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/dynamic.cpp.o
[ 42%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/fast.cpp.o
[ 42%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/evaluation.cpp.o
[ 42%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/feature2d.cpp.o
[ 42%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/opencl_kernels_features2d.cpp.o
[ 43%] Linking CXX shared library ../../lib/libopencv_features2d.so
[ 43%] Built target opencv_features2d
Scanning dependencies of target opencv_cudawarping
[ 43%] Building CXX object modules/cudawarping/CMakeFiles/opencv_cudawarping.dir/src/resize.cpp.o
[ 44%] Building CXX object modules/cudawarping/CMakeFiles/opencv_cudawarping.dir/src/warp.cpp.o
[ 44%] Building CXX object modules/cudawarping/CMakeFiles/opencv_cudawarping.dir/src/remap.cpp.o
[ 44%] Building CXX object modules/cudawarping/CMakeFiles/opencv_cudawarping.dir/src/pyramids.cpp.o
[ 44%] Linking CXX shared library ../../lib/libopencv_cudawarping.so
[ 44%] Built target opencv_cudawarping
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by codeloverr** [comment] 2017-10-24 07:36
@alalek Any response?

**Comment by alalek** [comment] 2017-10-24 09:32
Don't expect any response here.
This tracker is for issues and bugs that needs fix in OpenCV. At least we should have clear reason of the problem or we should able to reproduce it (our CUDA build is green).

We don't have spare time to help with investigation of remote problems on custom configurations. Current messages blames on system headers / CUDA compiler / OpenMP runtime / and unusual library libsoxr.so - so try to build standalone CUDA samples and try to build OpenCV without CUDA at first. Also try to disable OpenMP / libsoxr.so somehow.

Questions/help requests should go to Users OpenCV Q/A forum: http://answers.opencv.org
Feel free to return back with fix suggestion or at least with clear reason of the problem - so we could provide some fix for this.

**Closed by alalek** 2017-10-24 09:32 UTC
Labels: category: build/install, category: gpu (cuda), question (invalid)

**Comment by trohit920** [comment] 2017-12-05 05:49
@codeloverr @alalek Did you solved your problem ? I am also getting same error like this.
I am also trying to install OpenCV 3.3 on Ubuntu 16.04 with CUDA 9 and Caffe framework. I am following this guide: https://github.com/BVLC/caffe/wiki/Op... I already changed the FindCUDA.cmake and OpenCVDetectCUDA.cmake file according to CUDA9 requirement and finished building environment successfully by running: cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D FORCE_VTK=ON -D WITH_TBB=ON -D WITH_V4L=ON -D WITH_QT=ON -D WITH_OPENGL=ON -D WITH_CUBLAS=ON -D CUDA_NVCC_FLAGS="-D_FORCE_INLINES --expt-relaxed-constexpr" -D WITH_GDAL=ON -D WITH_XINE=ON -D BUILD_EXAMPLES=ON .. However when i tried: make -j $(($(nproc) + 1)) it is giving me an error as follows: [ 44% ] Linking CXX shared library ../../lib/libopencv_cudawarping.so [ 44% ] Build target opencv_cudawarping Makefile:160: recipe for target 'all' failed make: * [all] Error 2.
Please help me with this.

**Comment by jmrichardson** [comment] 2018-03-04 03:31
@trohit920 I am getting the same error.  Were you able to solve it?

**Comment by nasica88** [comment] 2018-04-13 04:44
I had the same error, just after "Built target opencv_cudawarping", although my environment was ppc64le Redhat 7.4, CUDA 9.1.   I have no idea what the root cause was, but I solved the error by inserting "-DBUILD_LIBPROTOBUF_FROM_SOURCES=ON" in the cmake flags.  Hope this should help out you, too.

**Comment by cjhkeep** [comment] 2019-03-19 11:33
I solve this problem by using `make`, instead of `make -j8`
and I find there is a mistake by the gstream version
` sudo apt-get install libgstreamer1.0-dev  libgstreamer-plugins-base1.0-dev` 
after that `make -j8`

there seems no problem with cuda.
you can use `make` to find some problem that ignore by the 8 thread.

**Comment by moe123-cmd** [comment] 2021-02-07 18:56
hello everyone I am using raspberry pi 3 B and python 3.8
I am trying to install OpenCV on it
  after many steps...
I arrived to last steps
I putted this code:
 cmake -D CMAKE_BUILD_TYPE=RELEASE \
    -D CMAKE_INSTALL_PREFIX=/usr/local \
    -D OPENCV_EXTRA_MODULES_PATH=~/opencv_contrib-4.0.0/modules \
    -D ENABLE_NEON=ON \
    -D ENABLE_VFPV3=ON \
    -D BUILD_TESTS=OFF \
    -D WITH_TBB=OFF \
    -D INSTALL_PYTHON_EXAMPLES=OFF \
    -D BUILD_EXAMPLES=OFF ..

**after this step to build OpenCV I putted:**
**make -j4**
I waited for 2 hours and this error appeared:
[ 43%] Linking CXX shared library ../../lib/libopencv_core.so
CMakeFiles/opencv_core.dir/src/matmul.cpp.o: file not recognized: File truncated
collect2: error: ld returned 1 exit status
modules/core/CMakeFiles/opencv_core.dir/build.make:2178: recipe for target 'lib/libopencv_core.so.4.0.0' failed
make[2]: *** [lib/libopencv_core.so.4.0.0] Error 1
CMakeFiles/Makefile2:2396: recipe for target 'modules/core/CMakeFiles/opencv_core.dir/all' failed
make[1]: *** [modules/core/CMakeFiles/opencv_core.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

**any solution please??**
