### ISSUE TITLE
Fragmentation of heap

### ISSUE THREAD

**Issue by lishuaijielsj** [opencv/opencv#17443] opened 2020-06-01 03:03 UTC
https://github.com/opencv/opencv/blob/c3e8a82c9c0b18432627fe100db332b42d64b8d3/modules/core/include/opencv2/core/private.hpp#L119
there is a problem: if a small struct which is created by `new` is stored with cv::Mat, the memory increases a lot, if CV_MALLOC_ALIGN = 64, else it is normal when CV_MALLOC_ALIGN=8

```
#include <thread>
#include <boost/circular_buffer.hpp>
#include <Eigen/Eigen>
#include <opencv2/core/core.hpp>
#include <stdlib.h>
#include <iostream>

struct OdometryEigen
{
    Eigen::Matrix<double, 6, 6> p_cov;
    Eigen::Matrix<double, 6, 6> v_cov;
    Eigen::Matrix<double, 3, 3> R;
    Eigen::Matrix<double, 3, 1> t;
    Eigen::Matrix<double, 6, 1> v;
};

struct Impl
    uint32_t s;
    uint32_t ns;
};

struct TimestampOut
{
    TimestampOut()
        : impl_(new Impl)
    {
    }
    std::shared_ptr<Impl> impl_;
};


#define ALIGN_BYTE 8 

struct AlignedMat // opencv mat alloc
{
    AlignedMat()
        : data_(NULL)
    {
    }

    AlignedMat(int size)
        : size_(size)
        , data_(NULL)
    {
        init();
    }

    AlignedMat(const AlignedMat& in)
    {
        size_ = in.size_;
        init();
    }

    bool init()
    {
        int ret;
        std::cerr << "size ----" << size_ << std::endl;
        ret = posix_memalign((void**)&data_, ALIGN_BYTE, size_);

        if (ret)
        {
            std::cerr << "failde ------------" << std::endl;
            data_ = NULL;
            return false;
        }
        std::cerr << "sucess -------" << std::endl;
        for (int i = 0; i < size_; i++)
        {
            data_[i] = 0;
        }

        return true;
    }

    ~AlignedMat()
    {
        if (data_)
        {
            free(data_);
        }
    }

    void operator=(const AlignedMat& in)
    {
        if (data_)
        {
            free(data_);
        }

        size_ = in.size_;

        init();
    }

    int size_;
    char* data_;
};

#define USE_ALIGNED 1
#define USE_IMPL 0

struct ImageMat
{
#if USE_ALIGNED
    ImageMat(int size)
        : mat(size)
    {
    }

    AlignedMat mat;
#else
    cv::Mat mat;
#endif

    ImageMat()
    {
    }

#if USE_IMPL
    Impl timestamp;
#else
    TimestampOut timestamp;
#endif
};

void addImage();
void addOdometry();
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
int main(int argc, char** argv)
{
    (void) argc;
    (void) argv;
    std::shared_ptr<std::thread> add_thread = std::make_shared<std::thread>(&addImage);
    add_thread->detach();

    // add odo
    addOdometry();

    return 0;
}

void addImage()
{
    static uint64_t i = 0u;
    boost::circular_buffer<ImageMat> img_buffer(100);
    uint64_t num = 1e7;
    float delta_t = 1e-3;
    (void) delta_t;

    for(; i < num; i++)
    {
        // prepare data
        const uint16_t        width       = 1920u;
        const uint16_t        height      = 1080;
        const uint64_t        buffer_size = static_cast<uint64_t>(width) * height * 3u;
        uint8_t buffer_stack[buffer_size];
        (void)  buffer_stack;
        uint8_t*               buffer = new uint8_t[buffer_size];

        // set image data
#if USE_ALIGNED
        ImageMat image(buffer_size);
#else
        ImageMat image;
        image.mat.create(width, height, CV_8UC3);
        if (image.mat.isContinuous())
        {
            std::cerr << "true" << std::endl;
        }
        else
        {
            std::cerr << "flase" << std::endl;
        }

        for(int i = 0;i < (int)buffer_size; i++)
        {
            image.mat.data[i] = 0;
        }
        //memcpy(image.mat.data, buffer_stack, buffer_size);
        memcpy(image.mat.data, buffer, buffer_size);
#endif
        delete [] buffer;
        usleep(1e5);
        std::cerr << i << "th run \n";
        img_buffer.push_back(image);

        std::cerr << "image buffer size: " << img_buffer.size() << std::endl;
    }

    return;
}
void addOdometry()
{
    static uint64_t i = 0u;
    boost::circular_buffer<OdometryEigen> odo_buffer(1000);

    uint64_t num = 1e7;
    float delta_t = 1e-3;
    (void) delta_t;

    for(; i < num; i++)
    {

        OdometryEigen odo;
        usleep(1e5);
        std::cerr << i << "th odo run \n";
        odo_buffer.push_back(odo);
        std::cerr << "odo buffer size: " << odo_buffer.size() << std::endl;
    }

    return;
}
```
thanks.

**Comment by lishuaijielsj** [comment] 2020-06-01 12:00
for the test on Ubuntu 18.04, 64bit machine 
- ALIGN_BYTE=64  USE_IMPL = 0 the memory usage will be larger than the real size of image in the buffer.
- ALIGN_BYTE=16  USE_IMPL = 0 the memory usage will be similar to the real size of image in the buffer.

**Comment by alalek** [comment] 2020-06-04 00:31
Which OpenCV version?
Looks like as a duplicate of #15526

> CV_MALLOC_ALIGN = 64

won't fix due performance (CPU cache line, OpenCL buffers mapping, etc) and accuracy (some part of code assumes this alignment) reasons.

**Comment by lishuaijielsj** [comment] 2020-06-04 03:32
The version is 3.3.1. I am sorry to create a similar issue, thanks for your reply.

**Closed** 2020-06-10 11:16 UTC
Labels: category: 3rdparty
