### ISSUE TITLE
cv2.dnn.blobFromImage results in segmentation fault

### ISSUE THREAD

**Issue by changbaishan** [opencv/opencv#14976] opened 2019-07-04 02:42 UTC
The purpose of this issue is to present a case where Holistically-Nested Edge Detection fails.

Link to the code I used:
https://github.com/acarcher/hed-opencv-dl/blob/master/detect_edges_image.py

Link to the image being processed.
https://pbs.twimg.com/media/DKtuk25VwAYWFBu.jpg

I suspect that this is the limitation of the model used (https://github.com/acarcher/hed-opencv-dl/tree/master/hed_model)

I hope this image can be included in future test cases.

Thanks

**Comment by dkurt** [comment] 2019-07-04 03:17
Have you tried this sample https://github.com/opencv/opencv/blob/master/samples/dnn/edge_detection.py?

**Comment by dkurt** [comment] 2019-07-16 04:56
Cannot reproduce an issue. Sample works fine with the latest OpenCV version. Let me close it.

**Closed by dkurt** 2019-07-16 04:56 UTC
Labels: category: dnn, incomplete

**Comment by changbaishan** [comment] 2019-07-16 18:11
Thanks for your efforts!
