### ISSUE TITLE
 memory leak in multi threading  --  leak point TlsStorage's Thread data and  slotdata

### ISSUE THREAD

**Issue by xingxing-2019** [opencv/opencv#16151] opened 2019-12-13 07:32 UTC
we found if we create and finish  much thread  and use  Parallel_for in these thread ,  system will be 
out of memory and  i study the code and found for every thread  TlsStorage will cache the  Thread data and  slotdata but never release  util  my process exit

**Comment by xingxing-2019** [comment] 2019-12-13 07:40
TlsStorage's ThreadData and slotData  is in  global vector and will not release after  the child thread finish

**Comment by xingxing-2019** [comment] 2019-12-13 07:49
1. valgrind  report  in my Attack test （about 2000 circles for thread created and finished  ）
==8325== 1,436,840 bytes in 35,921 blocks are still reachable in loss record 12 of 13
==8325==    at 0x4844368: operator new(unsigned long) (vg_replace_malloc.c:334)
==8325==    by 0x5128997: cv::TLSData<cv::CoreTLSData>::createDataInstance() const (in /usr/local/lib/libopencv_core.so.4.1.0)
==8325==    by 0x512EAC7: cv::TLSDataContainer::getData() const (in /usr/local/lib/libopencv_core.so.4.1.0)
==8325==    by 0x511311B: cv::theRNG() (in /usr/local/lib/libopencv_core.so.4.1.0)
==8325==    by 0x50E39C3: cv::parallel_for_(cv::Range const&, cv::ParallelLoopBody const&, double) (in /usr/local/lib/libopencv_core.so.4.1.0)
==8325==    by 0x4DB463F: cv::hal::resize(int, unsigned char const*, unsigned long, int, int, unsigned char*, unsigned long, int, int, double, double, int) (in /usr/local/lib/libopencv_imgproc.so.4.1.0)
==8325==    by 0x4DB642F: cv::resize(cv::_InputArray const&, cv::_OutputArray const&, cv::Size_<int>, double, double, int) (in /usr/local/lib/libopencv_imgproc.so.4.1.0)
==8325== 
2. ==8325== 9,195,776 bytes in 35,921 blocks are still reachable in loss record 13 of 13
==8325==    at 0x4844368: operator new(unsigned long) (vg_replace_malloc.c:334)
==8325==    by 0x512ECE3: cv::TLSDataContainer::getData() const (in /usr/local/lib/libopencv_core.so.4.1.0)
==8325==    by 0x511311B: cv::theRNG() (in /usr/local/lib/libopencv_core.so.4.1.0)
==8325==    by 0x50E39C3: cv::parallel_for_(cv::Range const&, cv::ParallelLoopBody const&, double) (in /usr/local/lib/libopencv_core.so.4.1.0)
==8325==    by 0x4DB463F: cv::hal::resize(int, unsigned char const*, unsigned long, int, int, unsigned char*, unsigned long, int, int, double, double, int) (in /usr/local/lib/libopencv_imgproc.so.4.1.0)
==8325==    by 0x4DB642F: cv::resize(cv::_InputArray const&, cv::_OutputArray const&, cv::Size_<int>, double, double, int) (in /usr/local/lib/libopencv_imgproc.so.4.1.0)
==8325==

**Comment by alalek** [comment] 2019-12-16 09:42
duplicate of #9745

**Closed by alalek** 2019-12-16 09:42 UTC
Labels: duplicate

**Comment by xingxing-2019** [comment] 2019-12-16 10:41
thank you very much ,  https://github.com/opencv/opencv/commit/17e2bf5717559ccf4fe809dd9f83afa7582f8ef5   is not merge to 4.1.0 ?, why not
