### ISSUE TITLE
Assertion failed (inputs.size()) in cv::dnn::dnn4_v20190122::Layer::getMemoryShapes

### ISSUE THREAD

**Issue by Aeroxander** [opencv/opencv#14713] opened 2019-06-04 03:45 UTC
##### System information (version)

- OpenCV => 4.1.0 C++
- Operating System / Platform => Mac OS High Sierra (also had this issue on Windows 10)
- Compiler => XCode

##### Detailed description

So I have 3 PyTorch models where 2 of them give me trouble when loading in ONNX, the inference works fine in PyTorch and the conversion is all ok too.

So in the first model I get this error when reading the ONNX model in OpenCV:

> Assertion failed (inputs.size()) in cv::dnn::dnn4_v20190122::Layer::getMemoryShapese

With the other model I get this error:

> Blob 64 not found in const blobs

This has all something to do with the input where in the first error the inputs.size() is 0 and in the second model the blob isn't big enough somehow. 
I don't know which framework or action I did I can pinpoint the error to..

##### Steps to reproduce
Read the decoder ONNX model

##### Standalone project
https://github.com/Aeroxander/decodererror

**Comment by alalek** [comment] 2019-06-04 07:00
> keep them both as a global variable

Due static initialization order fiasco it is a bad practice in general.

Please provide:
- complete standalone reproducer (without extra dependencies outside of OpenCV)
- and stack trace of your crashes (to ensure that problem is the same)

**Comment by Aeroxander** [comment] 2019-06-05 01:38
@alalek My mistake, I actually get an error just for that 1 wrong ONNX model, it just can't parse it and gives an "Can't read ONNX model file" error.

As the first one works fine, I suppose the conversion to my ONNX model went fine, although something may have not converted properly. Here is some info of the model:

format: ONNX v4
producer: pytorch 1.1
imports: ai.onnx v9
name: torch-jit-export

Should I try out ONNX v5 that may be more compatible with converting from PyTorch to ONNX, or how can I discover what's wrong with my model (could still something be wrong with ONNX)?

Here is an visualized Netron picture of it if that helps:

![decoder4Kr31](https://user-images.githubusercontent.com/11189629/58924188-b5ffe000-86f7-11e9-8f9d-6cc52ab5970e.png)

**Comment by Aeroxander** [comment] 2019-06-05 04:37
Alright, so I'm just trying everything out right now, but the model that doesn't give any errors also doesn't give any models if I try to convert the ONNX model to a Tensorflow model, but the other one gives this error:

`ValueError: Tensor conversion requested dtype float32 for Tensor with dtype int64: 'Tensor("Mul_3:0", shape=(), dtype=int64)'`

So I'd think the same happens when OpenCV reads the file (and it basically also converts it in OpenCV format I suppose?)

**Comment by Aeroxander** [comment] 2019-06-07 02:36
So I get this error now: 
`OpenCV(4.1.0) Error: Assertion failed (inputs.size()) in cv::dnn::dnn4_v20190122::Layer::getMemoryShapes, file c:\build\master_winpack-build-win64-vc15\opencv\modules\dnn\src\dnn.cpp, line 3616`

@alalek as requested, here is the standalone project:

**Comment by Aeroxander** [comment] 2019-06-07 20:41
I suppose OpenCV is unable to generate a tensor to test the model out?
@dkurt Could you possibly remove the incomplete/needs reproducer labels? Thanks!

**Comment by Aeroxander** [comment] 2019-06-09 23:56
It looks like it's referencing to the Mul layer with ID 18;

>  %18 = Mul(%16, %17)

Have no idea why there isn't an input..

**Comment by Aeroxander** [comment] 2019-06-11 05:34
I also get this error in another model: 

> Blob 64 not found in const blobs
And this seems to be in the MatMul layer, so there must be something wrong with the PyTorch -> ONNX conversion right?

**Comment by ashishkrshrivastava** [comment] 2020-02-24 15:32
Hii @Aeroxander , are you still working with this model ?

**Comment by dkurt** [comment] 2020-03-03 20:52
@ashishkrshrivastava, Please check if we can close this issue because it's resolved by https://github.com/opencv/opencv/pull/16709 or not (if we can run a model).

**Comment by ashishkrshrivastava** [comment] 2020-03-05 05:40
@dkurt It is resolved. I am able to load it successfully.

**Closed** 2020-03-05 05:47 UTC
Labels: category: dnn
