### ISSUE TITLE
opencv/modules/core/include/opencv2/core/ptr.inl.hpp:301:26: error: invalid new-expression of abstract class type ‘cv::linemod::Modality’      

### ISSUE THREAD

**Issue by SmitSheth** [opencv/opencv#12225] opened 2018-08-16 08:34 UTC
##### System information (version)

- OpenCV => 3.4.1:
- Operating System / Platform => Ubuntu 16.04:
- Compiler => :cmake/gcc:

##### Detailed description

Tried to compile opencv_contrib3.4.1 with opencv repository .But got following error:

opencv/modules/core/include/opencv2/core/ptr.inl.hpp:301:26: error: invalid new-expression of abstract class type ‘cv::linemod::Modality’
     return Ptr<T>(new T());

**Comment by alalek** [comment] 2018-08-16 09:14
[Can't reproduce](http://pullrequest.opencv.org/buildbot/grid?tag=scheduled-3.4-contrib).

We don't help with remote investigation of problems which we are not able to reproduce on our side (because it is very time consuming and usually configuration problem without any following fix into OpenCV), but we can take a look on **the clear reason of the problem** and suggest some fix/workaround.

**Comment by alalek** [comment] 2018-08-16 09:18
Contrib issues should go into corresponding repository.

**Comment by berak** [comment] 2018-08-16 09:19
see also: https://github.com/opencv/opencv_contrib/issues/1638

**Comment by alalek** [comment] 2018-08-16 09:43
Duplicate of #10844

> 3.4.1

We don't fix already released code. If you want fixes then you should upgrade.

**Closed by alalek** 2018-08-16 09:43 UTC
Labels: category: build/install, category: contrib, incomplete

**Comment by gongyue666** [comment] 2018-11-21 02:56
get the same error, with opencv-4.0.0-rc.I close the error modules.
