### ISSUE TITLE
use efficientdet on opencv4.5.1-pre

### ISSUE THREAD

**Issue by RexNeal** [opencv/opencv#18942] opened 2020-11-27 05:54 UTC
- OpenCV => 4.5
- Operating System / Platform => Windows 64 Bit
- Compiler => anaconda jupyter notebook

error                                     Traceback (most recent call last)
<ipython-input-17-706e4a9ddab2> in <module>
      1 #Load YOLO
----> 2 net = cv2.dnn.readNet(r"C:\Users\ciphe\Downloads\efficientdet-d0.pb",r"C:\Users\ciphe\Downloads\efficientdet-d0.pbtxt")
      3 classes = []
      4 with open(r"C:\Users\ciphe\Desktop\yolo\coco.names","r",) as f:
      5     classes = [line.strip() for line in f.readlines()]

error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\dnn\src\tensorflow\tf_importer.cpp:1823: error: (-2:Unspecified error) in function 'void __cdecl cv::dnn::dnn4_v20191202::`anonymous-namespace'::TFImporter::populateNet(class cv::dnn::dnn4_v20191202::Net)'
>  (expected: 'factorHeight.type() == CV_32SC1'), where
>     'factorHeight.type()' is 5 (CV_32FC1)
> must be equal to
>     'CV_32SC1' is 4 (CV_32SC1)

use weight and config from:
https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API

**Comment by dkurt** [comment] 2020-11-27 06:59
Closing until bug report became reproducible

**Comment by dkurt** [comment] 2020-11-27 07:01
Please specify AutoML model version. We have EfficientDet-d0 in tests.

**Comment by RexNeal** [comment] 2020-11-27 08:00
https://github.com/opencv/opencv/pull/17384
I think it's this version

**Comment by dkurt** [comment] 2020-11-27 08:19
Cannot reproduce on master branch. Can you please check OpenCV version?
```bash
wget https://www.dropbox.com/s/9mqp99fd2tpuqn6/efficientdet-d0.pb
wget https://raw.githubusercontent.com/opencv/opencv_extra/master/testdata/dnn/efficientdet-d0.pbtxt
```
```python
import numpy as np
import cv2 as cv
print(cv.__file__)
print(cv.__version__)

net = cv.dnn.readNet('efficientdet-d0.pb', 'efficientdet-d0.pbtxt')
inp = np.random.standard_normal([1, 3, 512, 512]).astype(np.float32)
net.setInput(inp)
out = net.forward()
print(out.shape)
```

**Comment by RexNeal** [comment] 2020-11-27 13:21
#!/usr/bin/env python
# coding: utf-8
import cv2
import numpy as np
import time
#Load YOLO
net = cv2.dnn.readNet("efficientdet-d0.pb","efficientdet-d0.pbtxt") # Original yolov3
#net = cv2.dnn.readNet("yolov3-tiny.weights","yolov3-tiny.cfg") #Tiny Yolo
net.setPreferableBackend(cv2.dnn.DNN_BACKEND_CUDA)
net.setPreferableTarget(cv2.dnn.DNN_TARGET_CUDA)
classes = []
with open("coco.names","r",) as f:
    classes = [line.strip() for line in f.readlines()]

print(classes)

layer_names = net.getLayerNames()
outputlayers = [layer_names[i[0] - 1] for i in net.getUnconnectedOutLayers()]

colors= np.random.uniform(0,255,size=(len(classes),3))

#loading image
cap=cv2.VideoCapture(1) #0 for 1st webcam
cap.set(3,640)
cap.set(4,480)
font = cv2.FONT_HERSHEY_PLAIN
starting_time= time.time()
frame_id = 0

while True:
    _,frame= cap.read() # 
    frame_id+=1
    
    height,width,channels = frame.shape
    #detecting objects
    blob = cv2.dnn.blobFromImage(frame,0.00392,(512,512),(0,0,0),True,crop=False) #reduce 416 to 320    

        
    net.setInput(blob)
    outs = net.forward(outputlayers)
    #print(outs[1])


    #Showing info on screen/ get confidence score of algorithm in detecting an object in blob
    class_ids=[]
    confidences=[]
    boxes=[]
    for out in outs:
        for detection in out:
            scores = detection[5:]
            class_id = np.argmax(scores)
            confidence = scores[class_id]
            if confidence > 0.3:
                #onject detected
                center_x= int(detection[0]*width)
                center_y= int(detection[1]*height)
                w = int(detection[2]*width)
                h = int(detection[3]*height)

                #cv2.circle(img,(center_x,center_y),10,(0,255,0),2)
                #rectangle co-ordinaters
                x=int(center_x - w/2)
                y=int(center_y - h/2)
                #cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0),2)

                boxes.append([x,y,w,h]) #put all rectangle areas
                confidences.append(float(confidence)) #how confidence was that object detected and show that percentage
                class_ids.append(class_id) #name of the object tha was detected

    indexes = cv2.dnn.NMSBoxes(boxes,confidences,0.4,0.6)


    for i in range(len(boxes)):
        if i in indexes:
            x,y,w,h = boxes[i]
            label = str(classes[class_ids[i]])
            confidence= confidences[i]
            color = colors[class_ids[i]]
            cv2.rectangle(frame,(x,y),(x+w,y+h),color,2)
            cv2.putText(frame,label+" "+str(round(confidence,2)),(x,y+30),font,1,(255,255,255),2)
            

    elapsed_time = time.time() - starting_time
    fps=frame_id/elapsed_time
    cv2.putText(frame,"FPS:"+str(round(fps,2)),(10,50),font,2,(0,0,0),1)

    cv2.imshow("Image",frame)
    key = cv2.waitKey(1) #wait 1ms the loop will start again and we will process the next frame
    
    if key == 27: #esc key stops the process
        break;
    
cap.release()    
cv2.destroyAllWindows()   


new error  
Traceback (most recent call last):
  File "google.py", line 51, in <module>
    class_id = np.argmax(scores)
  File "/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 963, in argmax
    return _wrapfunc(a, 'argmax', axis=axis, out=out)
  File "/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: attempt to get argmax of an empty sequence

Sorry for using wrong version for opencv

**Comment by dkurt** [comment] 2020-11-27 13:42
Seems like a problem in your application. Please try https://github.com/opencv/opencv/blob/master/samples/dnn/object_detection.py

**Closed** 2020-11-29 16:14 UTC
Labels: incomplete
