### ISSUE TITLE
error: 'nullptr' was not declared in this scope

### ISSUE THREAD

**Issue by yongduek** [opencv/opencv#10086] opened 2017-11-14 05:30 UTC
#### Solution:
 
```ENABLE_PRECOMPILED_HEADERS=OFF```

##### System information (version)
- OpenCV => 3.1
- Operating System / Platform => Ubuntu 16.04
- Compiler => c++ (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609

#### Building Opencv 3.3.1 with QT 5.7, VTK-9.0 produced the following message
```
Generating perf_precomp.hpp.gch/opencv_perf_dnn_Release.gch
In file included from /usr/local/include/vtk-9.0/vtkObject.h:48:0,
                 from /usr/local/include/vtk-9.0/vtkAlgorithm.h:36,
                 from /usr/local/include/vtk-9.0/vtkPolyDataAlgorithm.h:35,
                 from /usr/local/include/vtk-9.0/vtkAppendPolyData.h:35,
                 from /disk1/packages/opencv-3.3.1/build/modules/viz/precomp.hpp:56:
/usr/local/include/vtk-9.0/vtkWeakPointerBase.h: In constructor ‘vtkWeakPointerBase::vtkWeakPointerBase()’:
/usr/local/include/vtk-9.0/vtkWeakPointerBase.h:39:33: error: ‘nullptr’ was not declared in this scope
   vtkWeakPointerBase() : Object(nullptr) {}
```

Unfortunately, `cmake` with
```
ENABLE_CXX11=YES
``` 
did not remove the errors.

- Without precompiled header option enabled, the build time was much longer.
- I think I saw a text about this problem of not applying C++11 to the case of precompiled headers, but cannot find the right link. 
- Anyway, OpenCV with VTK9.0, QT5.7 was built, without 'nullptr' error.

**Comment by alalek** [comment] 2017-11-14 06:40
Looks like VTK 9.0 requires C++11 support.

Please add failed command lines (via `make VERBOSE=1`) and attach CMakeCache.txt / CMakeVars.txt (at least parts about CXX_FLAGS)

**Comment by achalshah20** [comment] 2018-02-21 01:09
I am also getting the same error. How did you resolve this issue?

**Comment by arunabhcode** [comment] 2018-04-09 22:55
@achalshah20 add -std=c++11 to the cmake_cxx_flags and it'll build.

**Comment by csukuangfj** [comment] 2018-06-02 11:41
It cannot be reproduced anymore with the following settings:
 - OpenCV master branch
 - VTK master branch
 - QT 5.6.0

**Comment by arkceajin** [comment] 2018-06-13 03:07
Thanks `ENABLE_CXX11=YES` solves my problem in mingw32 + qt 5.10.1

**Comment by vpisarev** [comment] 2018-06-25 14:17
ok, let's close it then

**Closed by vpisarev** 2018-06-25 14:17 UTC
Labels: bug, category: build/install, category: viz
