### ISSUE TITLE
HTML docs, search box: `searchResults.Toggle` doesn't expand result

### ISSUE THREAD

**Issue by crackwitz** [opencv/opencv#15232] opened 2019-08-05 14:03 UTC
* visit https://docs.opencv.org/3.4/ or https://docs.opencv.org/master/, doesn't matter
* focus search box on the top right
* enter "split"
* second result is a single word that *used to* expand when clicked

it doesn't now. it should. hasn't for a few weeks, now that I think back.

particularly for this function, it prevented a newbie from finding the `cv::split` he needed.

**Comment by alalek** [comment] 2019-08-05 14:07
duplicate of #8057

**Closed by alalek** 2019-08-05 14:07 UTC
Labels: duplicate
