### ISSUE TITLE
c++ opencv4.01 called  tensorflow inception-v4 model ,readNetFromTensorflow ERROR!

### ISSUE THREAD

**Issue by JaosonMa** [opencv/opencv#14149] opened 2019-03-26 03:00 UTC
train a tf flowers model with inception-v4, 
after got the mode.ckpy , use the code to convert it:
echo "create model.pb over"
cd ..
CUDA_VISIBLE_DEVICES=1 python3 -u export_inference_graph.py \
    --model_name=inception_v4 \
    --output_file=./data/flowers_5/models/infer/flowers.pb \
    --dataset_name=flowers \
    --dataset_dir=./data/flowers_5

echo "start create frzee pb"

CUDA_VISIBLE_DEVICES=1 python3 -u /usr/local/lib/python3.5/dist-packages/tensorflow/python/tools/freeze_graph.py \
    --input_graph=./data/flowers_5/models/infer/flowers.pb \
    --input_checkpoint=./data/flowers_5/models/model.ckpt-10027 \
    --output_graph=./data/flowers_5/models/infer/my_freeze.pb \
    --input_binary=True \
    --output_node_name=InceptionV4/Logits/Predictions

i test the flowers.pb with  classify.sh (https://github.com/isiosia/models/tree/lession/slim)
it works well
 
id:[0] name:[daisy] (score = 0.80188)
id:[1] name:[dandelion] (score = 0.11308)
id:[3] name:[sunflowers] (score = 0.05036)
id:[4] name:[tulips] (score = 0.02128)
id:[2] name:[roses] (score = 0.01340)

then  i use it for vs2015+opencv4.01, with the code 
![image](https://user-images.githubusercontent.com/23551774/54968514-ef102b80-4fb5-11e9-8871-74955b2431ba.png)

then got the error
![image](https://user-images.githubusercontent.com/23551774/54968526-00f1ce80-4fb6-11e9-8fbb-be9cd56edac0.png)

load models
OpenCV: terminate handler is called! The last OpenCV error is:
**OpenCV(4.0.1) Error: Assertion failed (scaleMat.type() == CV_32FC1)** in cv::dnn::dnn4_v20181221::`anonymous-namespace'::TFImporter::populateNet, file E:\product\opencv-4.0.1\modules\dnn\src\tensorflow\tf_importer.cpp, line 1377

so  i dont know where was wrong? 
how can i make it work in c++ opoencv4.01?

@dkurt

**Comment by alalek** [comment] 2019-03-26 03:54
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by JaosonMa** [comment] 2019-03-26 04:05
> Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
> 
> If you think this is a bug which should be fixed - provide complete reproducer including models.

i have done this, but there don have the A,

**Comment by alalek** [comment] 2019-03-26 04:58
We really don't have spare time to download datasets and try to train models using outdated instructions (you point on commits which are modified 2+ years ago).

Reproducer should have:
- OpenCV C++ code
- data/images processed by OpenCV code
- no more external dependencies.

Ask for help on http://answers.opencv.org if you are not able to provide this.

---

Could you try add this before mentioned assertion?
```.diff
+std::cout << typeToString(scaleMat.type()) << std::endl;
+scaleMat.convertTo(scaleMat, CV_32FC1);
 CV_Assert(scaleMat.type() == CV_32FC1);
```

**Comment by JaosonMa** [comment] 2019-03-26 05:36
> ```diff
> std::cout << typeToString(scaleMat.type()) << std::endl;
> +scaleMat.convertTo(scaleMat, CV_32FC1);
> ```

i tried the code ,
![image](https://user-images.githubusercontent.com/23551774/54973516-33f28d00-4fcb-11e9-9e7d-1b5d2355b079.png)

here is the result before change and after change with debug

before change:
![image](https://user-images.githubusercontent.com/23551774/54973685-e0cd0a00-4fcb-11e9-91d7-97fff664a7d6.png)


after change:
![image](https://user-images.githubusercontent.com/23551774/54973571-72884780-4fcb-11e9-97fb-926b986f3eb6.png)

here is my pb.  baidu ，i don 't know can you download or not , 
链接：https://pan.baidu.com/s/1d9nWjKV_NCLFuzReOP4WKQ 
提取码：94sx 

c++ code 

#include "pch.h"
#include <opencv2/dnn.hpp>
#include <opencv2/imgproc.hpp>
#include <opencv2/highgui.hpp>
#include <Windows.h>
#include <fstream>
#include <iostream>
#include <cstdlib>
using namespace cv;
using namespace cv::dnn;
using namespace std;
//自己新建一个txt文件，写入分类的标签（一行写一个标签，例如二分类，第一行写good，第二行bad）
string labels_txt_file = R"(D:\downloads\googledownloads\labels.txt)";
string tf_pb_file = R"(D:\downloads\googledownloads\my_freeze.pb)";
vector <string> readClassNames();
void main()
{
	Mat src = imread(R"(D:\downloads\googledownloads\437859108_173fb33c98.jpg)");
	if (src.empty())	{
		cout << "error:no img" << endl;
	}
	vector <string> labels = readClassNames();
	Mat rgb;
	int w = 299;
	int h = 299;
	resize(src, src, Size(w, h));
	cvtColor(src, rgb, COLOR_BGR2RGB);
	cout << "load models" << endl;
	Net net = readNetFromTensorflow(tf_pb_file);
	cout << "load over" << endl;
	DWORD timestart = GetTickCount();
	if (net.empty())
	{
		cout << "error:no model" << endl;
	}
	Mat inputBlob = blobFromImage(src, 0.00390625f, Size(w, h), Scalar(), true, false);
	//inputBlob -= 117.0;
	//执行图像分类
	Mat prob;
	net.setInput(inputBlob, "input");
	prob = net.forward("output");
	cout << prob << endl;
	//prob=net.forward("softmax2");
	//得到最大分类概率
	Mat probMat = prob.reshape(1, 1);
	Point classNumber;
	double classProb;
	minMaxLoc(probMat, NULL, &classProb, NULL, &classNumber);
	DWORD timeend = GetTickCount();
	int classidx = classNumber.x;
	printf("\n current image classification : %s, possible : %.2f\n", labels.at(classidx).c_str(), classProb);
	cout << "用时(毫秒):" << timeend - timestart << endl;
	// 显示文本
	putText(src, labels.at(classidx), Point(20, 20), FONT_HERSHEY_SIMPLEX, 1.0, Scalar(0, 0, 255), 2, 8);
	imshow("Image Classfication", src);
	waitKey(0);

}
vector <string>readClassNames()
{
	vector <string>classNames;
	fstream fp(labels_txt_file);
	if (!fp.is_open())
	{
		cout << "does not open" << endl;
		exit(-1);
	}
	string name;
	while (!fp.eof())
	{
		getline(fp, name);
		if (name.length())
			classNames.push_back(name);
	}
	fp.close();
	return classNames;
}

**Comment by JaosonMa** [comment] 2019-03-26 06:45
@alalek  @dkurt

**Comment by JaosonMa** [comment] 2019-03-26 06:50
here is my train.sh with tensorflow's slim API:
cd ..
CUDA_VISIBLE_DEVICES=1 python3 train_image_classifier.py \
    --dataset_name=flowers \
    --dataset_dir=./data/flowers_5 \
    --model_name=inception_v4 \
    --train_dir=./data/flowers_5/models \
    --learning_rate=0.001 \
    --learning_rate_decay_factor=0.76 \
    --num_epochs_per_decay=50 \
    --moving_average_decay=0.9999 \
    --optimizer=adam \
    --ignore_missing_vars=True \
    --batch_size=32

**Comment by mshabunin** [comment] 2019-03-26 07:37
>i have done this, but there don have the A,

I can not find your question on answers.opencv.org? Please provide a link.

**Comment by JaosonMa** [comment] 2019-03-26 07:59
> > i have done this, but there don have the A,
> 
> I can not find your question on answers.opencv.org? Please provide a link.

sorry , i mean i don't find the A on answers.opencv.org? and  i can not sing in or create an username, 
so i have not ask this Q on answers.opecn.org , so sorry

**Comment by JaosonMa** [comment] 2019-03-26 13:43
OpenCV: terminate handler is called! The last OpenCV error is:
OpenCV(4.0.1) Error: Unspecified error (Input [eval_image/central_crop/stack] for node [eval_image/central_crop/Slice] not found) in cv::dnn::dnn4_v20181221::`anonymous-namespace'::TFImporter::getConstBlob, file E:\product\opencv-4.0.1\modules\dnn\src\tensorflow\tf_importer.cpp, line 535

**Comment by dkurt** [comment] 2019-03-27 09:23
@JaosonMa, Please follow issue's template and make it reproducible. Provide a reference to model so we can test it locally.

**Comment by JaosonMa** [comment] 2019-03-27 09:56
##### System information (version)

- OpenCV => :4.01:
- Operating System / Platform => win10 64bite
- Compiler => :vs2017 x86:

##### Detailed description


i train a model with a tensorflow slim, inception-v4 with code like this 
`CUDA_VISIBLE_DEVICES=1 python3 train_image_classifier.py \
    --dataset_name=flowers \
    --dataset_dir=./data/flowers_5 \
    --model_name=inception_v4 \
    --train_dir=./data/flowers_5/models \
    --learning_rate=0.001 \
    --learning_rate_decay_factor=0.76 \
    --num_epochs_per_decay=50 \
    --moving_average_decay=0.9999 \
    --optimizer=adam \
    --ignore_missing_vars=True \
    --batch_size=32`
1> i got a tf-model save as model.ckpt-xxx
2> freeze the model to .pb file with the code like this 
`echo "create model.pb start"
CUDA_VISIBLE_DEVICES=1 python3 -u export_inference_graph.py \
    --model_name=inception_v4 \
    --output_file=./data/flowers_5/models/infer_isiosia/flowers.pb \
    --dataset_name=flowers \
    --dataset_dir=./data/flowers_5


echo "start create frzee pb"

CUDA_VISIBLE_DEVICES=1 python3 -u /usr/local/lib/python3.5/dist-packages/tensorflow/python/tools/freeze_graph.py \
    --input_graph=./data/flowers_5/models/infer_isiosia/flowers.pb \
    --input_checkpoint=./data/flowers_5/models/model.ckpt-10027 \
    --output_graph=./data/flowers_5/models/infer_isiosia/my_freeze.pb \
    --input_binary=True \
    --output_node_name=InceptionV4/Logits/Predictions
`
3> use the my_freeze.pb to opencv4.01 + vs2017 with code like this 

first  i got the error , like this 
![image](https://user-images.githubusercontent.com/23551774/55066524-f2d8a680-50b8-11e9-9ac4-56ce48ceebc8.png)

then add some code  in openv-dnn module, as @alalek say
https://github.com/opencv/opencv/issues/14149#issuecomment-476475899
then got the error like this 
![image](https://user-images.githubusercontent.com/23551774/55066664-392e0580-50b9-11e9-8879-5259a8200311.png)
OpenCV: terminate handler is called! The last OpenCV error is:
OpenCV(4.0.1) Error: Unspecified error (Input [eval_image/central_crop/stack] for node [eval_image/central_crop/Slice] not found) in cv::dnn::dnn4_v20181221::`anonymous-namespace'::TFImporter::getConstBlob, file E:\product\opencv-4.0.1\modules\dnn\src\tensorflow\tf_importer.cpp, line 535

##### Steps to reproduce


@dkurt  
forgive me for my bad english !!

**Comment by dkurt** [comment] 2019-03-27 10:01
@JaosonMa, please do not use Baidu for sharing. We just cannot download anything from there because it downloads `.exe` files!

**Comment by JaosonMa** [comment] 2019-03-27 10:13
> @JaosonMa, please do not use Baidu for sharing. We just cannot download anything from there because it downloads `.exe` files! Please provide a direct link.

sorry, i can not google , and i  can not find some good ways ,that can just provide a direct link ,  can you give me a email or some other ways... so sorry for thie

**Comment by JaosonMa** [comment] 2019-03-27 10:24
> > @JaosonMa, please do not use Baidu for sharing. We just cannot download anything from there because it downloads `.exe` files! Please provide a direct link.
> 
> sorry, i can not google , and i can not find some good ways ,that can just provide a direct link , can you give me a email or some other ways... so sorry for thie

can you tell me , my steps was right or not, 
1> use tensorflow - slim train a model ( https://github.com/tensorflow/models/edit/master/research/slim/preprocessing/preprocessing_factory.py)saved as model.ckpt
2>, use export_inference_graph.py export the model.pb file 
3>. use freeze_graph.py ceate the freeze.pb 
does opencv 4.01 can load the the freeze.pb direct or not ?
did i miss some steps?

**Comment by dkurt** [comment] 2019-03-27 10:29
@JaosonMa, please try Dropbox at least.

**Comment by JaosonMa** [comment] 2019-03-27 10:34
> @JaosonMa, please try Dropbox at least.
ok  ,i will give a shoot. 
i also tried this [mobilenet_v2_1.0_224](https://storage.googleapis.com/mobilenet_v2/checkpoints/mobilenet_v2_1.0_224.tgz)

![image](https://user-images.githubusercontent.com/23551774/55069296-ab551900-50be-11e9-92c3-0fba550c13d0.png)

does the mobilenet_v2_1.4_224_frozen.pb can used by opencv4.01 direct?

**Comment by JaosonMa** [comment] 2019-03-27 10:35
> > @JaosonMa, please try Dropbox at least.
> > ok  ,i will give a shoot.
> > i also tried this [mobilenet_v2_1.0_224](https://storage.googleapis.com/mobilenet_v2/checkpoints/mobilenet_v2_1.0_224.tgz)
> 
> ![image](https://user-images.githubusercontent.com/23551774/55069296-ab551900-50be-11e9-92c3-0fba550c13d0.png)
> 
> does the mobilenet_v2_1.4_224_frozen.pb can used by opencv4.01 direct?

ok  ,i will give a shoot. 
i also tried this [mobilenet_v2_1.0_224](https://storage.googleapis.com/mobilenet_v2/checkpoints/mobilenet_v2_1.0_224.tgz)

![image](https://user-images.githubusercontent.com/23551774/55069296-ab551900-50be-11e9-92c3-0fba550c13d0.png)

does the mobilenet_v2_1.4_224_frozen.pb can used by opencv4.01 direct?

**Comment by JaosonMa** [comment] 2019-03-27 11:14
> @JaosonMa, please try Dropbox at least.

i faild , my internet can not use DropBox

**Comment by dkurt** [comment] 2019-03-27 12:16
@JaosonMa, Thanks for your issue! Please test the changes from PR https://github.com/opencv/opencv/pull/14166. It'll be merged into 3.4 and then ported to master branch.

**Comment by JaosonMa** [comment] 2019-03-27 13:42
> @JaosonMa, Thanks for your issue! Please test the changes from PR #14166. It'll be merged into 3.4 and then ported to master branch.

i change these codes in my opencv4.01 source code 
![image](https://user-images.githubusercontent.com/23551774/55078051-2f65cb80-50d4-11e9-9ed9-0ce8521cc8e9.png)
![image](https://user-images.githubusercontent.com/23551774/55078094-473d4f80-50d4-11e9-806d-2b232a50d1a7.png)
![image](https://user-images.githubusercontent.com/23551774/55078110-52907b00-50d4-11e9-96f7-4fe9e211095a.png)

then rebuild the opencvdnn modules . try two times with diffient codes:

![image](https://user-images.githubusercontent.com/23551774/55078452-288b8880-50d5-11e9-855f-f0f0b9b2ebb3.png)

and  mobilenet_v2 SUCC!

![image](https://user-images.githubusercontent.com/23551774/55079100-82408280-50d6-11e9-94c0-541dd0ad927b.png)

But  inceptionv-v4 Failed!
![image](https://user-images.githubusercontent.com/23551774/55080449-2297a680-50d9-11e9-82ab-3c8ee56ac1cf.png)


i closed this , i think i must do something wrong with the inception-v4, i will keep trying....

**Closed** 2019-03-27 13:42 UTC
Labels: bug, category: dnn

**Comment by JaosonMa** [comment] 2019-04-09 06:18
@dkurt  @alalek 
I tried many many times ,but always failed! ,so please help me again!
i ran the [mobilenet_v2_1.0_224](https://storage.googleapis.com/mobilenet_v2/checkpoints/mobilenet_v2_1.0_224.tgz) sucess! 
so i train the data again with mobilenet_v2_1.0_224 on my data,
after training, got the ckpt, 
`cd ..

# Where the pre-trained MobilenetV1 checkpoint is saved to.
PRETRAINED_CHECKPOINT_DIR=./data/flowers_2/models/all
# Where the training (fine-tuned) checkpoint and logs will be saved to.
TRAIN_DIR=/tmp/flowers-models/mobilenet_v1_1.0_224
# Where the dataset is saved to.
DATASET_DIR=./data/flowers_2
DATASET_NAME=flowers
INFER_DIR=./data/flowers_2/models/all/infer
MODEL_NAME=mobilenet_v2_140

echo "create model.pb start"
CUDA_VISIBLE_DEVICES=0 python3 -u export_inference_graph.py \
    --model_name=${MODEL_NAME} \
    --output_file=${INFER_DIR}/flowers.pb \
    --dataset_name=${DATASET_NAME} \
    --dataset_dir=${DATASET_DIR}


echo "start create frzee pb"

CUDA_VISIBLE_DEVICES=0 python3 -u /usr/local/lib/python3.5/dist-packages/tensorflow/python/tools/freeze_graph.py \
    --input_graph=${INFER_DIR}/flowers.pb \
    --input_checkpoint=${PRETRAINED_CHECKPOINT_DIR}/model.ckpt-44885 \
    --output_graph=${INFER_DIR}/my_freeze.pb \
    --input_binary=True \
    --output_node_name=MobilenetV2/Predictions/Reshape_1
`
[export_inference_graph.pu](https://github.com/tensorflow/models/blob/master/research/slim/export_inference_graph.py)

then i got the [flowers.pb](https://github.com/JaosonMa/for-models-download/blob/master/flowers.pb)
and the [my_freeze.pb](https://github.com/JaosonMa/for-models-download/blob/master/my_freeze.pb)

the use the  same code ,the got error :
![image](https://user-images.githubusercontent.com/23551774/55776601-e1879500-5acf-11e9-9f65-34c1bda09410.png)
it seems like that some layers was not found in opencv4.01,so i check the two pbfile(my_freeze.pb and mobilenet_v2_1.0_224_frozen.pb) with code like this:

`mobile_net = '../data/mobilenet_v2_1.4_224/mobilenet_v2_1.4_224_frozen.pb'
my_mobile_net = '../data/flowers_2/models/all/infer/my_freeze.pb'
def create_graph():
    with tf.gfile.FastGFile(my_mobile_net, 'rb') as f:
        graph_def = tf.GraphDef()
        graph_def.ParseFromString(f.read())
        tf.import_graph_def(graph_def, name='')
create_graph()
tensor_name_list_my = [tensor.name for tensor in tf.get_default_graph().as_graph_def().node]

print(len(tensor_name_list))
print(len(tensor_name_list_my))
for idx,tensor_name in enumerate(tensor_name_list_my):
    if(idx<len(tensor_name_list)):
        print(idx+1,"-->",tensor_name,idx+1,"-->",tensor_name_list[idx],'\n')
    else:
        print(idx+1,"-->",tensor_name,'\n')
`
the length is not same ,
![image](https://user-images.githubusercontent.com/23551774/55777285-14328d00-5ad2-11e9-8fd2-cc32c41eb3eb.png)
...
![image](https://user-images.githubusercontent.com/23551774/55777307-2280a900-5ad2-11e9-96a5-938c4a5abee2.png)
...
![image](https://user-images.githubusercontent.com/23551774/55777323-2b717a80-5ad2-11e9-8c9b-ae41b0fa2276.png)

so i think some thing was wrong with my export_inference_graph.py, can you tell me how can i got the pb just as same as the tf's mobilenet_v1_1.0_224_.pb,

**Comment by dkurt** [comment] 2019-04-09 07:18
@JaosonMa, before the neural network this graph has a lot of support nodes (jpeg decoding, cropping, resizing). It's might be done out of the network (i.e. by blobFromImage). So you can remove these nodes:

before:
![image](https://user-images.githubusercontent.com/25801568/55780245-30253700-5ab0-11e9-9170-9949135cdbc9.png)

```python
import tensorflow as tf
from tensorflow.tools.graph_transforms import TransformGraph

with tf.gfile.FastGFile('my_freeze.pb') as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())

graph_def = TransformGraph(graph_def, ["ExpandDims"], ["MobilenetV2/Predictions/Reshape_1"], ["strip_unused_nodes"])
with tf.gfile.FastGFile("graph.pb", 'wb') as f:
    f.write(graph_def.SerializeToString())
```

after:
![image](https://user-images.githubusercontent.com/25801568/55780465-a2961700-5ab0-11e9-9003-4c1878b3a866.png)

**Comment by JaosonMa** [comment] 2019-04-09 07:53
first  thank you a lot!!!
i try the code you give me,  error like this :
![image](https://user-images.githubusercontent.com/23551774/55782065-1f8bb580-5ade-11e9-9773-a3e569a17d2f.png)
![image](https://user-images.githubusercontent.com/23551774/55782077-231f3c80-5ade-11e9-831c-788381f7753e.png)
so i change from
`with tf.gfile.FastGFile(my_mobile_net) as f:` to `with tf.gfile.FastGFile(my_mobile_net,'rb') as f:`
then it run succ
got the [frozen_graph.pb](https://github.com/JaosonMa/for-models-download/blob/master/frozen_graph.pb)

use frozen_graph.pb in opencv4.01 ,got error:
![image](https://user-images.githubusercontent.com/23551774/55782538-16e7af00-5adf-11e9-8bd7-47d7926046eb.png)

so i print the nodes , like this:
![image](https://user-images.githubusercontent.com/23551774/55782610-44345d00-5adf-11e9-8ddc-acf61b3eb77d.png)

so which is the input? 
`       Net net = readNetFromTensorflow(tf_pb_file);
	Mat src = imread(R"(D:\downloads\googledownloads\dc165458a6955e67399f2186f90cccc9.jpg)");

	Mat rgb;
	int w = 224;
	int h = 224;
	resize(src, src, Size(w, h));
	Mat inputBlob = blobFromImage(src, 0.00390625f, Size(w, h), Scalar(), true, false);
	Mat prob;
	net.setInput(inputBlob, "input");  // what should i put in there?
	prob = net.forward("MobilenetV2/Predictions/Reshape_1");`

net.setInput(inputBlob, "input");   what should i put in there?

@dkurt

**Comment by JaosonMa** [comment] 2019-04-09 07:56
`Mat prob;
	net.setInput(inputBlob, "ExpandDims");
	prob = net.forward("MobilenetV2/Predictions/Reshape_1");`

i put ExpandDims in ，it run succ!
i think it is right!

**Comment by JaosonMa** [comment] 2019-04-11 13:17
@dkurt  So sorry to disturb you again.
I used the pb with input:ExpanDims run succ in opencv4.01, 
but the acc is lower than the my_freeze.pb in tensorflow code ,
the acc when before TransformGraph:
![image](https://user-images.githubusercontent.com/23551774/55959561-97540e80-5c9d-11e9-8525-7962e5c2e0a2.png)
my data only have two classes, They are somewhat similar. so acc=0.9 It's almost what I expected.
but used the pb after TranfromGraph , the acc is only 0.65, i don't know why, i check three  graphs in tensorboard ,1> tensorflow's slim mobilenet_v2_1.4_224.pb 2> my_freeze.pb 3>frozen_graph.pb
the mobilenetV2 part is all the same 
![image](https://user-images.githubusercontent.com/23551774/55959948-6c1def00-5c9e-11e9-910b-e62d21fb403a.png)
![image](https://user-images.githubusercontent.com/23551774/55959967-73dd9380-5c9e-11e9-8241-73656072d9fe.png)

but  there input layer was diffient ,
1> mobilenet_v2_1.4_224.pb 
![image](https://user-images.githubusercontent.com/23551774/55960169-d040b300-5c9e-11e9-8f76-793a8fb9a10c.png)

2>my_freeze.pb
![image](https://user-images.githubusercontent.com/23551774/55960304-0847f600-5c9f-11e9-9c7d-0f2af994b0c1.png)

3>froze_graph.pb
![image](https://user-images.githubusercontent.com/23551774/55960106-af785d80-5c9e-11e9-8d6f-0ca76f277ff2.png)

can i just got a pb , just like the mobilenet_v2_1.4_224.pb with the input "input",

**Comment by dkurt** [comment] 2019-04-11 13:36
@JaosonMa, Please provide two code snippets: how you run the model with TensorFlow and with OpenCV. Please make it as minimal as possible: remove dataset reading. Just a single image.

**Comment by JaosonMa** [comment] 2019-04-11 14:11
@dkurt 
tensorflow:
classify code: [classify.py](https://github.com/JaosonMa/for-models-download/blob/master/classify.py)
[my_freeze.pb:](https://github.com/JaosonMa/for-models-download/blob/master/my_freeze.pb)
[class.sh:](https://github.com/JaosonMa/for-models-download/blob/master/classify.sh)
[labels.txt:](https://github.com/JaosonMa/for-models-download/blob/master/labels.txt)

c++:
[classfi.cpp:](https://github.com/JaosonMa/for-models-download/edit/master/pch.cpp)
[frozen_graph.pb:](https://github.com/JaosonMa/for-models-download/blob/master/frozen_graph.pb)
labels.txt: same as tenflow labels.txt

[test_img:](https://github.com/JaosonMa/for-models-download/blob/master/2_1_25_3_1.jpg)

this image is one of the val data , its label is 'N'
 in my computer : 
tensorflow output is 
![image](https://user-images.githubusercontent.com/23551774/55964100-af7c5b80-5ca6-11e9-9ea5-d928c036c0c8.png)

C++ outPut is 
![image](https://user-images.githubusercontent.com/23551774/55964159-cae76680-5ca6-11e9-964f-f7e9635f9584.png)

it is diffient!

**Comment by JaosonMa** [comment] 2019-04-12 04:56
@dkurt  Is this enough for you to debug?What else do you need?I will certainly give it to you.

**Comment by JaosonMa** [comment] 2019-04-12 08:15
@dkurt please help me , My project has been delayed for 10 days.
![image](https://user-images.githubusercontent.com/23551774/56022390-2284e100-5d3e-11e9-9b16-6ffab7e52e2c.png)

**Comment by dkurt** [comment] 2019-04-12 08:20
@JaosonMa, please stop it. We already figured out that the problem might be fixed with current version of OpenCV. For now the question is to align TensorFlow and OpenCV usage. Actually, the problem in your code. So be patient please.

**Comment by JaosonMa** [comment] 2019-04-12 08:24
got you , so sorry for what i have done , i will just wait .

**Comment by dkurt** [comment] 2019-04-13 15:05
@JaosonMa, There are two nodes which impact on different predictions from OpenCV and TensorFlow: `DecodeJpeg` and `ResizeBilinear`. The thing is that precision of Jpeg decoding is not similar even between different versions of decoding libraries. ResizeBilinear's interpolation strategy differs from OpenCV's one.

So to achieve similar outputs you need to pass similar inputs to the node after these ones:

```python
import numpy as np
import cv2 as cv

import tensorflow as tf
from tensorflow.tools.graph_transforms import TransformGraph

image = cv.imread("2_1_25_3_1.jpg")
image = image[:,:,[2,1,0]]  # BGB 2 RGB
image = cv.resize(image, (224, 224))
paddedImage = cv.copyMakeBorder(image, 15, 15, 15, 15, cv.BORDER_CONSTANT)

#
# TensorFlow
#
with tf.gfile.FastGFile("my_freeze.pb", 'rb') as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())

with tf.Session() as sess:
    sess.graph.as_default()
    tf.import_graph_def(graph_def, name='')

    tfOut = sess.run(sess.graph.get_tensor_by_name('MobilenetV2/Predictions/Reshape_1:0'),
                     feed_dict={'eval_image/convert_image/Cast:0': paddedImage})
    print tfOut

#
# OpenCV
#
net = cv.dnn.readNet("graph.pb")
net.setPreferableBackend(cv.dnn.DNN_BACKEND_OPENCV)

blob = cv.dnn.blobFromImage(image, 1.0/127.5, (224, 224), [127.5, 127.5, 127.5])
net.setInput(blob)
cvOut = net.forward()

print cvOut
```

Central crop looks also a bit confusing (it crops by a 0.875 ratio). So I resized an image out of the graph and added zero paddings so both Central Crop and ResizeBilinear don't affect an accuracy:

```
TF
[[1.7407431e-01 8.2585084e-01 3.5822773e-05 3.9013106e-05]]
CV
[[1.7408027e-01 8.2584488e-01 3.5821628e-05 3.9013088e-05]]
```

To achieve better similarity, you man try to define `ExpandDims` layer as a custom one (read a tutorial https://docs.opencv.org/master/dc/db1/tutorial_dnn_custom_layers.html) so `ResizeBilinear` will be inside a graph.

Please use a forum for future usage questions: http://answers.opencv.org

**Comment by bnascimento** [comment] 2019-05-21 14:15
Hey dkurt, can you clarify the reason to the 15 pixel padding?

**Comment by dkurt** [comment] 2019-05-21 17:42
@bnascimento, I guess the same padding (which depends on image size) is done inside the TensorFlow graph (please visualize it with TensorBoard and show the nodes from the beginning up to `eval_image/convert_image/Cast:`.

**Comment by memeda2232** [comment] 2019-11-21 01:07
@JaosonMa  hi brother, i also met this problem,Have you already  solve it?
