### ISSUE TITLE
Improve `UMatUsageFlags` documentation

### ISSUE THREAD

**Issue by JoeHowse** [opencv/opencv#20765] opened 2021-09-28 18:45 UTC
The documentation of `UMatUsageFlags` does not shed much light on what each flag really does.  I suggest that the documentation should be revised to clarify at least the following points:

- `USAGE_DEFAULT` is equivalent to `USAGE_ALLOCATE_DEVICE_MEMORY`.
- `USAGE_ALLOCATE_SHARED_MEMORY` depends on Shared Virtual Memory (SVM). For it to work as intended, it needs OpenCV to be built using the `WITH_OPENCL_SVM` CMake option (which is off by default), it needs to be running on a compatible OpenCL 2 device, and it needs SVM to be enabled via `cv::ocl::Context::setUseSVM(true)`. If these conditions are not met, it falls back to an equivalent of `USAGE_ALLOCATE_DEVICE_MEMORY` (or possibly just fails with an exception in the case of an incompatible OpenCL device).

(The above is my understanding from reading the `ocl.cpp` source code, but if any of this is wrong, please correct me.)

**Comment by alalek** [comment] 2021-09-28 19:39
UMat usage flags are hints. Requested behavior may be applied if HW/SW stack supports that.
In general it should not fail, fallbacks should be available.

/cc @diablodale FYI

**Comment by diablodale** [comment] 2021-09-29 12:34
Hi, Joe. Here are the doc updates on this I already have in an opencl PR I've got pending. It looks nice in doxygen.

```c++
//! Usage flags for allocator; buffer allocation policy is platform and usage specific
enum UMatUsageFlags
{
    USAGE_DEFAULT = 0, ///< Generally best as most allocators choose intelligently

    // buffer allocation policy is platform and usage specific
    USAGE_ALLOCATE_HOST_MEMORY = 1 << 0,    ///< Prefer memory optimized for frequent host access
    USAGE_ALLOCATE_DEVICE_MEMORY = 1 << 1,  ///< Prefer memory optimized for frequent device access
    USAGE_ALLOCATE_SHARED_MEMORY = 1 << 2,  ///< Prefer shared address-space memory, e.g. OpenCL SVM memory
                                            // It is not equal to: USAGE_ALLOCATE_HOST_MEMORY | USAGE_ALLOCATE_DEVICE_MEMORY

    __UMAT_USAGE_FLAGS_32BIT = 0x7fffffff   // Binary compatibility hint
};
```

I could imagine more exposition, like `cv::Mat` has already. Here is some of what is involved.

UMat and the intention of OpenCV is to abstract the user-code interface `UMatUsageFlags::USAGE_DEFAULT` from the internal management done by OpenCV memory allocators. OpenCV has 3 (4ish) allocators: malloc, opencl, numpy, (kinda) cuda. The base allocator defines an interface and each of the 4 allocators implement it. So you can use `USAGE_DEFAULT`, `...HOST`, etc. on all of them. Each allocator will interpret it into needed internal implementation. It is the allocator's choice to accept, deny, or translate flags with already defined error code/throw behaviors. All the allocators do not always accept all flags and fallback. I can appreciate what @alalek wrote, but it is not realistic and possible to guarantee universal fallback. For example, `...SHARED` flag with the OpenCL allocator can not actually fallback to a non-shared flag since the address space would then be different. Today's OpenCV OpenCL code silently accepts it, falls back to DEFAULT when SVM isn't available, and therefore creates a scenario for later failure... harder to debug since the location of failure isn't in the allocator but sometime much later when an OpenCL kernel is run. The dev is left to try and understand why their pointer defererences are not working.

`DEFAULT` is the best for the super majority of OpenCV coders. As I refactored part of the underlying OpenCL support, I can see that...no one...wants to do that level of coding/analysis except for systems programmers like me. Looking at typical OpenCV coders (lots use python), a larger set yet still super minority have the resources/knowledge to make best/perfect choices of `HOST`, `DEVICE`, `DEFAULT` in a way that works across different compute devices, configurations, drivers, etc. Therefore, OpenCV provides `DEFAULT` and the allocators chose the generally good underlying implementation. OpenCV also provides the other options `HOST`, `SHARED`, etc. for the super minority that has the resources/knowledge to dig deep.

🤔 My view? I see value in more exposition. To have both technical details, and more... um... strategic/suggestions. I hestitate providing all details because too much detail/flexibility for the unprepared coder will often result in poor outcome. The super-majority should use `DEFAULT` and focus their thinking and testing on their app and using CV algorithms....not supertweaking the memory allocator internals.

**Comment by JoeHowse** [comment] 2021-09-29 15:34
Hi, Dale. Thanks for the explanation. I agree that `USAGE_DEFAULT` is generally the best choice for compatibility and performance. I also agree that more exposition could be of interest to readers of the docs.

I think that so far, your doc updates do help to clarify the intent of the API, but the user may still be tripped up by the implementation. I suggest adding something like the following advisory about the implementation:

```
The current implementation has the following behavior:

`USAGE_ALLOCATE_DEVICE_MEMORY` is equivalent to `USAGE_DEFAULT`. The
allocator's underlying implementation (e.g. the OpenCL driver) may choose to
use dedicated device memory.

`USAGE_ALLOCATE_SHARED_MEMORY` depends on OpenCV's optional integration with
OpenCL SVM. To enable this integration, build OpenCV using the
`WITH_OPENCL_SVM=ON` CMake option and, at runtime, call
`cv::ocl::Context::getDefault().setUseSVM(true);` or similar code. Note that
SVM is incompatible with OpenCL 1.x.
```

(Please correct me if any of the above is wrong. I did not see anything in the source code that differentiates between `USAGE_ALLOCATE_DEVICE_MEMORY` and `USAGE_DEFAULT`.)

**Comment by alalek** [comment] 2021-09-29 17:15
> USAGE_ALLOCATE_SHARED_MEMORY 
> OpenCL SVM

These two are different things actually.
`USAGE_ALLOCATE_SHARED_MEMORY` is about `CL_MEM_ALLOC_HOST_PTR` flag (a.k.a pinned memory).

**Comment by diablodale** [comment] 2021-09-29 17:18
I prefer not publically describing implementation. That is the distinction between SDK documentation -vs- a specification given to a development team to implement that SDK. We need former, not latter. OpenCV is an organic open-source project with 20 years history and in its current ecosystem does not broadly do the latter (from what I've seen). If we made the latter, it is a promise and then locks implementation for "legacy/compatibility". I don't want to add any more such challenges to OpenCV, I want to do somewhat the opposite.

In a pending PR I have, I am refactoring, optimizing, and fixing issues with the OpenCL allocator. The `DEFAULT` implementation for OpenCL allocator is subtly different than `DEVICE` in some combinations of usage, compute devices, and drivers. The nuances are complex. It would be exhaustive to write details in English clear enough to doc/describe those nuances. The text would be difficult for the majority to understand without first having solid knowledge of both OpenCV and OpenCL memory management. That combination of long technical text plus that text referring to OpenCL specifications... 🤖Does not compute🤖 😉 The human cost vs. human benefit doesn't justify that doc work.

And that's just the OpenCL allocator. There are 3+ allocators and each of them imlement `USAGE_ALLOCATE_DEVICE_MEMORY` differently. I do love a spreadsheet 🤓 so I can imagine a grid of allocators and flags but the text in the cells would be sooo looong and difficult to understand.

I have added *a lot* of comments/doc to the codebase. When/if my PR is merged, the OpenCL code and two of the allocators will take a step forward in readibility and code comments. As I was untangling OpenCV's approach and the codebase, I wrote code comments, doxygen comments, var/func names for readibility, etc. Zero performance cost, aids in validation of code, and helps the next OpenCV contributor take over after my work. I believe this approach has a better cost/benefit balance. More clarity for the majority of developers reading SDK doc (headers, doxygen). And the minority of developers that have the needed OpenCV and OpenCL memory allocation knowledge can read the OpenCV implementation code itself for these comments to follow the code and the nuances. It is an evolution and I am expecting several refactorings to continue improving both doc and the code.

In your suggestions above, I think the SVM text has some good stuff and I can imagine it being either in the `Context` or `UsageFlags` areas. I don't see any writeup/discussion about it, only a brief mention at https://github.com/opencv/opencv/wiki/OpenCL-optimizations.

* If you must have a single address space, then `SHARED` is your only option.
* If you can guarantee and ensure that you will never pull data down to the host CPU (this can be difficult), then `DEVICE` can be used. But if you accidently pull data down to the CPU, then this option performs *worse* than `DEFAULT`.
* In all other cases, I recommend using `DEFAULT`.
* Yes `HOST` exists... I don't recommend it at this time.

@alalek `SHARED` is about SVM.  It is `HOST` that is an attempt to use pinned memory. But the current OpenCL allocator is borked in this area.

**Comment by diablodale** [comment] 2021-09-29 17:20
https://github.com/opencv/opencv/blob/cf08eac15e28675c9dffd17fa7d337d0698254f0/modules/core/src/ocl.cpp#L5400-L5402

**Comment by JoeHowse** [comment] 2021-09-30 00:10
@diablodale, when you make your pull request, please c.c. me. I would be interested in reviewing your improvements to the documentation, comments, and implementation at that time.

Based on the discussion in this thread, as well as the current source code in OpenCV 4.5.3 and the master branch, it seems that only `USAGE_DEFAULT` is considered stable at this point.  Thus, the scope of the issues goes beyond documentation and I think it would be more fruitful to continue this discussion in connection with Dale's upcoming pull request.

**Comment by alalek** [comment] 2021-09-30 04:08
> SHARED is about SVM.

Not exactly. `UMatUsageFlags` is a high level abstraction (even over OpenCL).

OpenCL backend mapping:
- HOST should wrap `cv::Mat` (`CL_MEM_USE_HOST_PTR` or just store direct `cv::Mat` which is not supported for now)
- DEVICE represents normal device-based cl_buffer with best performance
- SHARED is a [pinned memory](https://stackoverflow.com/questions/24158909/how-to-use-pinned-memory-mapped-memory-in-opencl) (`CL_MEM_ALLOC_HOST_PTR`)

---

FYI, "Unified shared memory" USM (next gen SVM) has different allocation strategies:

> host allocations with wide visibility, devices allocations for best performance, and shared allocations that may migrate between devices and the host.

- https://github.com/intel/llvm/blame/b3977b5776477ee1fdb3bcc51b6c6e6e820c54b3/sycl/doc/extensions/USM/cl_intel_unified_shared_memory.asciidoc#L84
- API: https://github.com/intel/llvm/blame/b3977b5776477ee1fdb3bcc51b6c6e6e820c54b3/sycl/doc/extensions/USM/cl_intel_unified_shared_memory.asciidoc#L102-L123

---

@JoeHowse I believe mentioned PR is here: #20489

---

> If we made the latter, it is a promise and then locks implementation for "legacy/compatibility"

Agreed. We should not over expose implementation details.

**Comment by JoeHowse** [comment] 2021-09-30 05:20
> OpenCL backend mapping:
>
> * HOST should wrap `cv::Mat` (`CL_MEM_USE_HOST_PTR` or just store direct `cv::Mat` which is not supported for now)
> * DEVICE represents normal device-based cl_buffer with best performance
> * SHARED is a pinned memory (`CL_MEM_ALLOC_HOST_PTR`)

Perhaps this was the original intent of the API designers (I do not know and, more to the point, the documentation does not say) but the current implementation deviates from this.

The current implementation relates `USAGE_ALLOCATE_SHARED_MEMORY` to SVM...

https://github.com/opencv/opencv/blob/cf08eac15e28675c9dffd17fa7d337d0698254f0/modules/core/src/ocl.cpp#L3104-L3115

...and relates `USAGE_ALLOCATE_HOST_MEMORY` to pinned memory (`CL_MEM_ALLOC_HOST_PTR`)...

https://github.com/opencv/opencv/blob/cf08eac15e28675c9dffd17fa7d337d0698254f0/modules/core/src/ocl.cpp#L5400-L5401

Based on the discussion in this thread, it is clear that the `USAGE_*` names are not self-explanatory and are open to conflicting interpretations. I believe that for the sake of users and developers alike, the documentation needs to clarify the intent.

**Comment by diablodale** [comment] 2021-09-30 13:41
@alalek , you've made the mistake of confusing HOST/SHARED with OpenCL svm and pinned memory several times (outside this issue). I haven't corrected you before because it was not important then. In this issue, it is important. What you are writing is not what the OpenCV codebase does. I think in the ~10 years since committing some of the OpenCL code you have misunderstood or misremembered things.

The OpenCV codebase (for years) has the following intention and code implementation. I believe this is right approach. It has some bugs (I fix some, not all, in my PR).
OpenCL backend mapping:

* `HOST` prefers memory that is more often used on the cpu and is originally "from" the cpu memory address space. The allocator will use strategies like CL_MEM_USE_HOST_PTR, CL_MEM_ALLOC_HOST_PTR, CL_MEM_COPY_HOST_PTR along with alignment and specific OpenCL api calls for mapping. This is the "pinned" idea you keep mentioning. "Pinned" memory is about DMA transfer optimization. On discrete GPUs like Intel+AMD graphics, they have even better "Zero Copy Buffer" tech. https://software.intel.com/content/www/us/en/develop/articles/getting-the-most-from-opencl-12-how-to-increase-performance-by-minimizing-buffer-copies-on-intel-processor-graphics.html#inpage-nav-2. Please note, the stackoverflow link you used is slightly wrong. Use the Intel link and OpenCL spec instead. These OpenCL enums and the specific method to get "pinned" or "zero copy buffer" is internal to, and chosen by, the OpenCL allocator based on the specific scenario, device, and driver capabilities -- this is not SDK user choice and should not be. For example, on NVIDIA it will attempt to have pinned memory and on Intel will attempt zero copy buffer.
* `DEVICE` prefers memory that is more often only read and written by the OpenCL compute device. It is memory native to the device and intended to only be used by the device...not mapped/copied to the cpu. This is *not* best performance in many situations and OpenCV should never make that best promise. Using `DEVICE` and doing data transfers to/from the host might make this the slowest. I only recommend using `DEVICE` if the data will only be used on the device by the device. If it is only used one time on the device (cpu source data -> gpu for compute -> return results to cpu), there is little to no improvement over `DEFAULT`
* `SHARED` demands the memory has shared address space (cpu and computer device). OpenCL SVM isn't next generation. This is 8 year old technology supported for years by Intel and AMD. NVidia added support this year. SVM is required when the OpenCL kernel operates on the memory with pointers (e.g. linked-list). This enables performant improvements when the cpu-side code and the OpenCL kernel use this shared address space. There is no alternative if shared address space is needed.

@JoeHowse , alalek provided the PR and here is the corresponding issue https://github.com/opencv/opencv/issues/20486
At the end of the issue, I document what's blocking (waiting on the maintainers @alalek  😉) and that I have local updates beyond the pushed commits so that PR is not ready for use.

**Comment by diablodale** [comment] 2021-09-30 15:32
😝 This discussion surfaced another issues with OpenCL SVM memory. Good discussion!
https://github.com/opencv/opencv/issues/20781

**Comment by alalek** [comment] 2021-09-30 17:36
> What you are writing is not what the OpenCV codebase does.

Right, my bad.

> SHARED demands the memory has shared address space (cpu and computer device). 
> SVM is required when the OpenCL kernel operates on the memory with pointers (e.g. linked-list).

I would suggest to interpret usage flags as hints. Existed `useSVM()` performs as a hint for usageFlags.
Hints can't guarantee final type of allocated memory.

---

> There is no alternative if shared address space is needed.

Traditional OpenCL kernels use offsets / indexes to handle that.

>  OpenCL SVM isn't next generation

I mean, USM is next generation of SVM.

When SVM support was introduced it was disabled because we observed performance regressions for the most use case scenarios on available H/W (7 years ago). SVM is still in experimental disabled state.
There is no reason to write kernels with "pointers" if they perform slower and provide less compatibility.

**Comment by diablodale** [comment] 2021-09-30 18:36
I completely agree DEFAULT, HOST, DEVICE are hints. 👍
I disagree on `SHARED`. It is not a hint. It is a demand/requirement for a single address space. It is errant to return non-SVM memory. If OpenCV were to treat it as a hint and return the wrong memory type, it can lead to later failures as I discuss in the new bug I just opened above.

Agreed that indexes, relative memory offsets, etc. can be used in some use cases. It is more coding work and a slight performance hit. Most C++ pointers are absolute unless they take on the additional overhead to use relative. And since most pointers are absoute, coders can't often use their favorite libraries.

I am not aware of any OpenCL kernels in OpenCV written specifically for SVM. 🙂 @alalek, do you have the kernels from 7 years ago from the SVM testing? I will gladly use them when coding/testing my OpenCL PR work. 7 years is multiple generations of hardware and driver changes.

Naturally, the existing OpenCV kernels in the many OpenCV modules work when given SVM memory because none of them use absolute memory pointers. Probably little benefit unless it is the SVM fine-grained system (needs no mapping/copying) or...maybe...SVM fine grained buffer if the sync points are fast. Would need testing.

Performance improvements using SVM memory may be possible when OpenCL kernels are coded to use a single address space. Those kernels are SVM specific and won't work on non-SVM memory. I use linked-list as an example because traditional implementations with absolute pointers won't work without a single address space on both cpu+device.

Maybe trees/lists can be processed faster when managing 1,000,000 list nodes given a GPU has thousands of threads vs a CPU having maybe 8. And maybe that processing is faster when using absolute pointers vs. relative. Until specific SVM kernel code is written and tested, I doubt we can judge. It will depend on memory coherence/locality, atomic contingency, size of data, workgroup sizes, and more

Perhaps OpenCV's modules don't want SVM. That's ok. `dnn`, `imgproc` have, to date, chosen to write kernels that do not require SVM and they use `core` services to run them. I prefer to have the `core` module of OpenCV provide a reliable set of services. It needs to provide reliable memory allocation, kernel running, etc. There are many users of `core` outside of OpenCV.

Earlier this year, I wrote my own OpenCL kernel for processing pointclouds. I use the `core` functionality to run my own kernel. It is easy to write a kernel and they are widely available on the Internete. In the future, I might want to write a kernel that benefits from SVM single-address space. And there may also be another developer in the world that also wants to write an SVM kernel...or run on some exotic/embedded OpenCL compute device. https://www.phoronix.com/scan.php?page=news_item&px=Intel-SVM-Support-Published

OpenCV `core` module makes it easy to allocate memory, run kernels, etc. SVM support is a natural extension.

**Comment by JoeHowse** [comment] 2021-12-30 17:59
@alalek Since Dale has withdrawn his pull request, I believe it would make sense to document the experimental status of `UMatUsageFlags` as-is. I propose the following addition to the documentation:

```
All flags except `USAGE_DEFAULT` are experimental.

For the OpenCL allocator, `USAGE_ALLOCATE_SHARED_MEMORY` depends on OpenCV's
optional integration with OpenCL SVM. To enable this integration, build OpenCV
using the `WITH_OPENCL_SVM=ON` CMake option and, at runtime, call
`cv::ocl::Context::getDefault().setUseSVM(true);` or similar code. Note that
SVM is incompatible with OpenCL 1.x.
```

Please let me know whether you would like me to make a pull request similar to this.

**Comment by alalek** [comment] 2021-12-30 18:05
@JoeHowse Sounds good. Please open a PR with a patch. Thank you!

**Comment by JoeHowse** [comment] 2021-12-31 18:15
> @JoeHowse Sounds good. Please open a PR with a patch. Thank you!

PR issued: #21375

In my opinion, this specific issue (about documentation) can be closed if the PR is accepted.

**Closed** 2022-01-04 13:34 UTC
Labels: category: core, category: documentation, category: ocl, category: t-api
