### ISSUE TITLE
Can the custom layer set the output type？

### ISSUE THREAD

**Issue by zhoujinhai** [opencv/opencv#21215] opened 2021-12-08 07:34 UTC
### 1. Problem
I implenmented a layer with reference to the [tutorial_dnn_custom_layers](tutorial_dnn_custom_layers)， I want to get the type of output is `np.long`,  but the default type is `np.float32`, **Can I set the output type?**

### 2. some key code
```python
class ALayer(object):
    def __init__(self, params, blobs):
        ...

    # Our layer receives one inputs. We need to find the max
    def getMemoryShapes(self, inputs):
        ...

    def forward(self, inputs):
        data = inputs[0]
        # find max ids on axis
        res = np.argmax(data, axis=self.axis).astype(np.float32)
        print(res, res.shape, res.dtype)
        return [res]
```
This code is run  after registered the ALayer.

- type error
I  droped the `astype(np.float32)` in `forward` function,  I got the type error like below after registered the ALayer.
```
pyopencv_dnn.hpp:175: error: (-215:Assertion failed) pyOutputs[i].type() == outputs[i].type() in function 'pycvLayer::forward'
```

**Comment by alalek** [comment] 2021-12-08 09:19
Not supported.
Feature request is duplicate of #16633

---

Usage questions should go to Users OpenCV Q/A forum: https://forum.opencv.org/

**Comment by zhoujinhai** [comment] 2021-12-08 09:19
您的邮件已收到 谢谢

**Closed by alalek** 2021-12-08 09:19 UTC
Labels: duplicate, question (invalid tracker)
