### ISSUE TITLE
Failed to precompile header when Eigen imported as CMake target

### ISSUE THREAD

**Issue by avilleret** [opencv/opencv#15610] opened 2019-09-29 13:07 UTC
##### System information (version)

- OpenCV => 3.4.7 / 4.1.1
- Operating System / Platform => Ubuntu 18.04 x86_64
- Compiler => gcc 8.3 / gcc 9.1

##### Detailed description

OpenCV fails to build when Eigen is imported as a CMake target and precompiled header are ON.

When Eigen is imported as a CMake target (here https://github.com/opencv/opencv/blob/3.4.7/cmake/OpenCVFindLibsPerf.cmake#L47-L50) I got the following error when compiling : 

```
[321/1436] Building CXX object modules/core/CMakeFiles/opencv_core_pch_dephelp.dir/opencv_core_pch_dephelp.cxx.o
FAILED: modules/core/CMakeFiles/opencv_core_pch_dephelp.dir/opencv_core_pch_dephelp.cxx.o 
/usr/bin/c++  -DOPENCV_WITH_ITT=1 -D_USE_MATH_DEFINES -D__OPENCV_BUILD=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I. -I../modules/core/src -I../modules/core/include -Imodules/core -I../3rdparty/include/opencl/1.2 -I../3rdparty/ittnotify/include -fsigned-char -ffast-math -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-delete-non-virtual-dtor -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG  -DNDEBUG -fPIC   -std=c++11 -MD -MT modules/core/CMakeFiles/opencv_core_pch_dephelp.dir/opencv_core_pch_dephelp.cxx.o -MF modules/core/CMakeFiles/opencv_core_pch_dephelp.dir/opencv_core_pch_dephelp.cxx.o.d -o modules/core/CMakeFiles/opencv_core_pch_dephelp.dir/opencv_core_pch_dephelp.cxx.o -c modules/core/opencv_core_pch_dephelp.cxx
In file included from /tmp/Genie/External/source/opencv/modules/core/src/precomp.hpp:55,
                 from modules/core/opencv_core_pch_dephelp.cxx:1:
../modules/core/include/opencv2/core/private.hpp:66:12: fatal error: Eigen/Core: No such file or directory
 #  include <Eigen/Core>
            ^~~~~~~~~~~~
```

Disabling precompiled header with `ENABLE_PRECOMPILED_HEADER=OFF` when configuring is workaround.

**Comment by alalek** [comment] 2019-09-29 13:31
duplicate of #15157
`ENABLE_PRECOMPILED_HEADER=OFF` is new default values on Linux.

**Closed by alalek** 2019-09-29 13:31 UTC
Labels: duplicate
