### ISSUE TITLE
samples/dnn/text_detection.cpp example bug with image reading

### ISSUE THREAD

**Issue by ghost** [opencv/opencv#14138] opened 2019-03-24 21:43 UTC
##### System information (version)

- OpenCV => 4.0.1
- Operating System / Platform => Windows 10 64bit
- Compiler => Visual C++ 14.0

##### Detailed description

Hi, this is my first bug report,
I have tried to use this example code:
https://docs.opencv.org/3.4.3/db/da4/samples_2dnn_2text_detection_8cpp-example.html

It doesn't work well on my computer when trying to load images,
I tried replacing

        if (parser.has("input"))
		cap.open(parser.get<String>("input"));
	    else
		cap.open(0);
        ...
        ...
        ...
        cap >> frame;

with a simpler code:

       frame = imread(parser.get<String>("input"), cv::IMREAD_COLOR);

and it worked. Before that the command cap >> frame did not load the image.

##### Steps to reproduce

Change these lines : 

        cap >> frame;
        if (frame.empty())
        {
            waitKey();
            break;
        }

to this:

    frame = imread(parser.get<String>("input"), cv::IMREAD_COLOR);

**Comment by metallicat97** [comment] 2019-03-24 21:44
Sorry if this isn't written too well. This little issue took me like an hour to resolve so I thought I'd share my solution.

**Comment by mshabunin** [comment] 2019-03-25 07:24
Please provide example of file path which did not work with VideoCapture.

**Comment by berak** [comment] 2019-03-25 07:42
@metallicat97 , was that with [a `.png` image](https://github.com/opencv/opencv/issues/11625) file ?

**Comment by metallicat97** [comment] 2019-03-25 09:36
The problem wasn't just with png files. It also occurred on jpeg's and bmp's

The path was something like : C:\Users\username\Desktop\image.png

I tried with multiple paths. The VideoCap cap object still didn't stream
the image to the Mat frame object correctly.
For users who just need a single image, it's just easier to load the image
to the frame object right away.

**Comment by dkurt** [comment] 2019-11-20 14:52
Please provide more details about build configuration (print cv::getBuildInformation) and attach problematic images.

Closing the ticket for now u til we can reproduce it.

**Closed by dkurt** 2019-11-20 14:52 UTC
Labels: category: dnn
