### ISSUE TITLE
readNetFromTensorflow gives error 

### ISSUE THREAD

**Issue by hardiktechnoplanet** [opencv/opencv#14799] opened 2019-06-13 21:23 UTC
I have a custom tensorflow model (.pb) file and I have generated graph.pbtxt file. Now, when I use the readNetFromTensorflow function, I got the error below:
"cv2.error: OpenCV(4.1.0) /io/opencv/modules/dnn/src/tensorflow/tf_importer.cpp:616: error: (-215:Assertion failed) const_layers.insert(std::make_pair(name, li)).second in function 'addConstNodes'"

Below is the code to import tensorflow model in opencv:

```
#!/usr/bin/env python
import cv2

cvNet = cv2.dnn.readNetFromTensorflow('Frozen-Master.pb','graph.pbtxt')

# Input image
img = cv2.imread("image3.jpg")
rows = img.shape[0]
cols = img.shape[1]

# Use the given image as input, which needs to be blob(s).
cvNet.setInput(cv2.dnn.blobFromImage(img, size=(300, 300), swapRB=True, crop=False))

# Runs a forward pass to compute the net output
cvOut = cvNet.forward()

# Loop on the outputs
for detection in cvOut[0,0,:,:]:
    score = float(detection[2])
    if score > 0.3:
        left = detection[3] * cols
        top = detection[4] * rows
        right = detection[5] * cols
        bottom = detection[6] * rows
        cv2.rectangle(img, (int(left), int(top)), (int(right), int(bottom)), (23, 230, 210), thickness=2)

cv2.imshow('img', img)
#save the image
cv2.imwrite( "processedImg4.jpg", img );
cv2.waitKey()
cv2.destroyAllWindows()

Below is the code to create .pbtxt file from the .pb file:
def graphdef_to_pbtxt(filename): 
  with gfile.FastGFile(filename,'rb') as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())
    tf.import_graph_def(graph_def, name='')
    tf.train.write_graph(graph_def, 'pbtxt/', 'protobuf.pbtxt', as_text=True)
  return

graphdef_to_pbtxt('Frozen-Master.pb')
```
----------------------------------------------------------------
I have also tried the below code for optimizing the model and I got the error "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 52: invalid start byte
```
import tensorflow as tf
from tensorflow.tools.graph_transforms import TransformGraph

graph = 'frozen_inference_graph_opt.pb'
with tf.gfile.FastGFile(graph) as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())

    for i in reversed(range(len(graph_def.node))):
        op = graph_def.node[i].op
        name = graph_def.node[i].name

        if op == 'Switch' or op == 'Merge':
            inp = graph_def.node[i].input[0]
            for node in graph_def.node:
                for j in range(len(node.input)):
                    if name == node.input[j]:
                        node.input[j] = inp
            del graph_def.node[i]

    graph_def = TransformGraph(graph_def, ["img_inputs"], ["embeddings"], ["strip_unused_nodes"])
    with tf.gfile.FastGFile("graph.pb", 'wb') as f:
        f.write(graph_def.SerializeToString())
```
Please help me with this issue
The model works fine if I use it directly (without trying to import it in opencv)
Please find the attached .zip file that contains .pb file and the .pbtxt file:
[attachments.zip](https://github.com/opencv/opencv/files/3288369/attachments.zip)

**Comment by dkurt** [comment] 2019-06-21 06:46
`pbtxt` is optional argument. If you haven't modified it - it is not needed. Have you tried just `readNetFromTensorflow('Frozen-Master.pb')`? Have you tried to find issues with similar error message?

**Comment by dkurt** [comment] 2019-07-16 04:51
Cannot reproduce an issue:

```python
import cv2 as cv
import numpy as np
print(cv.__file__)

net = cv.dnn.readNet('Frozen-Master.pb')

inp = np.random.standard_normal([1, 3, 300, 300]).astype(np.float32)
net.setInput(inp)
net.setPreferableBackend(cv.dnn.DNN_BACKEND_OPENCV)
out = net.forward()
print(out.shape)
```

Let me close it

**Closed by dkurt** 2019-07-16 04:51 UTC
Labels: category: dnn, incomplete
