### ISSUE TITLE
'import cv2' fails because numpy.core.multiarray fails to import

### ISSUE THREAD

**Issue by yurivict** [opencv/opencv#8139] opened 2017-02-07 02:26 UTC
```
$ cat x.py 
import cv2

[yuri@yv ~/]$ python2 x.py 
ImportError: numpy.core.multiarray failed to import
Traceback (most recent call last):
  File "x.py", line 3, in <module>
    import cv2
ImportError: numpy.core.multiarray failed to import
```

Adding ```import numpy.core.multiarray``` before ```import cv2``` fixes the problem.

py27-opencv2-2.4.13.1_1 on FreeBSD.

**Comment by yurivict** [comment] 2017-02-12 07:43
Any chance to fix this? Why is it incomplete?

**Comment by mshabunin** [comment] 2017-02-21 13:45
@yurivict , we haven't met this problem on other platforms, for example: http://pullrequest.opencv.org/buildbot/builders/2_4_noOCL-lin64/builds/10020 - test_python passed (https://github.com/opencv/opencv/blob/2.4/modules/python/test/test.py). And FreeBSD is not officially supported, so it can be platform or package specific issue.

**Comment by J-A-M-E-5** [comment] 2017-04-01 20:28
This happens for me too on Windows 7 64-bit. Same solution (import numpy.core.multiarray before import cv2) fixes it.

numpy         1.12.1+mkl
opencv-python 3.2.0

Wheels available from here: http://www.lfd.uci.edu/~gohlke/pythonlibs/

**Comment by arrowd** [comment] 2017-09-23 07:22
Met this too on FreeBSD when trying out OpenFace.

**Comment by ManojGuha** [comment] 2017-09-27 10:06
The same error came for me. The problem is that you might have created a file called numpy.py. This file might coincide with numpy library. So, delete that numpy.py file and problem gets solved

**Comment by xagano** [comment] 2017-10-09 17:58
I don't really understand this error but I solved this error with below.
"pip install -U opencv-python"

**Comment by rwestlund** [comment] 2017-10-19 22:34
I just ran into this too with `py27-opencv-2.4.13.1_1` on FreeBSD.  Workaround by manually importing `numpy.core.multiarray` first.

There's a patch that fixes this in the FreeBSD bugtracker.  It's something to do with fortran and the build system.

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=211805

It looks like this isn't opencv's problem.

**Comment by oholimoli** [comment] 2019-10-07 07:56
Did anybody find a solution for this?

**Comment by alalek** [comment] 2019-10-07 08:06
@oholimoli see comments above:

> Adding import numpy.core.multiarray before import cv2 fixes the problem.
> Workaround by manually importing numpy.core.multiarray first.

**Comment by yurivict** [comment] 2019-10-07 15:29
Dependencies should be imported properly in the code without the need for workarounds.

**Comment by alalek** [comment] 2019-10-07 16:03
@yurivict Import code is already [here](https://github.com/opencv/opencv/blob/2.4.13.1/modules/python/src2/cv2.cpp#L1167) ([manual reference](https://docs.scipy.org/doc/numpy/reference/c-api.array.html?highlight=import_array#importing-the-api)).

Feel free to investigate and prepare fix for that (we don't have configured FreeBSD system).
Also I'm not sure that this can be fixed in OpenCV (probably numpy code should be improved instead).

**Comment by yurivict** [comment] 2019-10-08 00:37
I don't do Python.

**Comment by oholimoli** [comment] 2019-10-11 08:15
I downgraded to numpy 1.12.1 and now cv2 works fine, before that I installed via sudo apt-get install python-opencv

**Comment by TangeniThePyGuru** [comment] 2019-11-10 05:16
I solved this by doing a `pip install numpy` basically for me the NumPy package was not installed.

**Comment by Bfzanchetta** [comment] 2020-01-16 20:17
I installed numpy again using sudo and -U option.
I applied $sudo pip3 install -U numpy
Then it just worked.

**Comment by creimers** [comment] 2020-05-07 09:08
For me, the combination of `opencv_python==4.0.0.21` and `numpy==1.14.5` works.

**Comment by ebinzacharias** [comment] 2020-07-08 16:04
# similar issue. 

I had a file named numbers.py in the same folder. Removing this file solved my issue. 

Very strange, but worked !

**Comment by denzfarid** [comment] 2020-09-11 23:54
> For me, the combination of `opencv_python==4.0.0.21` and `numpy==1.14.5` works.

thank you

**Comment by ilkin94** [comment] 2020-11-11 22:55
For me only opencv_python==4.4.0.46 and numpy==1.19.3 works.

**Comment by mshabunin** [comment] 2020-11-12 11:00
Closing this since there is not enough infomration and the issue seem to be obsolete.

**Closed by mshabunin** 2020-11-12 11:00 UTC
Labels: category: python bindings, incomplete, priority: low

**Comment by njokipal** [comment] 2022-01-08 07:54
Even if this issue is closed as obsolete, I comment here as I came here via an internet search for the same `ImportError` and I'm assuming others might also come here later:

This isn't OpenCV issue, but I had a stupid coding mistake, where I had files named `cv.py` and `math.py` in my project with

```
opencv-python==4.5.5.62
numpy==1.22.0
```

I renamed the files to `cv_utils.py` and `math_utils.py` respectively and the issue went away for me (it seems the fault is actually just the `math.py` file in my project, but I renamed both just to be on the safe side)

**Comment by Us0457** [comment] 2022-05-01 05:32
> For me only opencv_python==4.4.0.46 and numpy==1.19.3 works.

Thank you very much.

**Comment by snjjay** [comment] 2022-06-11 11:51
Your Numpy library needs to be updated. This error is caused by a version of NUMPY that is outdated or incompatible. See here https://kodlogs.net/332/numpy-core-multiarray-failed-to-import-windows
