### ISSUE TITLE
protobuf error

### ISSUE THREAD

**Issue by jinfagang** [opencv/opencv#13973] opened 2019-03-05 09:49 UTC
master branch build error:

```
ruct std::atomic<long int>’ has no member named ‘GetNext’
   lifecycle_id_ = lifecycle_id_generator_.GetNext();
                                           ^~~~~~~
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:69:3: error: ‘NoBarrier_Store’ is not a member of ‘google::protobuf::internal’
   google::protobuf::internal::NoBarrier_Store(&hint_, 0);
   ^~~~~~
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:70:3: error: ‘NoBarrier_Store’ is not a member of ‘google::protobuf::internal’
   google::protobuf::internal::NoBarrier_Store(&threads_, 0);
   ^~~~~~
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:76:75: error: ‘InitBlock’ was not declared in this scope
     InitBlock(initial_block_, &thread_cache(), options_.initial_block_size);
                                                                           ^
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:77:5: error: ‘ThreadInfo’ was not declared in this scope
     ThreadInfo* info = NewThreadInfo(initial_block_);
     ^~~~~~~~~~
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:77:17: error: ‘info’ was not declared in this scope
     ThreadInfo* info = NewThreadInfo(initial_block_);
                 ^~~~
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:77:52: error: ‘NewThreadInfo’ was not declared in this scope
     ThreadInfo* info = NewThreadInfo(initial_block_);
                                                    ^
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:79:5: error: ‘NoBarrier_Store’ is not a member of ‘google::protobuf::internal’
     google::protobuf::internal::NoBarrier_Store(&threads_,
     ^~~~~~
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:80:80: error: ‘AtomicWord’ in namespace ‘google::protobuf::internal’ does not name a type
                                   reinterpret_cast<google::protobuf::internal::AtomicWord>(info));
                                                                                ^~~~~~~~~~
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:81:5: error: ‘NoBarrier_Store’ is not a member of ‘google::protobuf::internal’
     google::protobuf::internal::NoBarrier_Store(&space_allocated_,
     ^~~~~~
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:83:30: error: ‘CacheBlock’ was not declared in this scope
     CacheBlock(initial_block_);
                              ^
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:85:5: error: ‘NoBarrier_Store’ is not a member of ‘google::protobuf::internal’
     google::protobuf::internal::NoBarrier_Store(&space_allocated_, 0);
     ^~~~~~
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc: At global scope:
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:106:19: error: prototype for ‘google::protobuf::internal::ArenaImpl::Block* google::protobuf::internal::ArenaImpl::NewBlock(void*, google::protobuf::internal::ArenaImpl::Block*, size_t)’ does not match any in class ‘google::protobuf::internal::ArenaImpl’
 ArenaImpl::Block* ArenaImpl::NewBlock(void* me, Block* my_last_block,
                   ^~~~~~~~~
In file included from /usr/local/include/google/protobuf/arena.h:51:0,
                 from /media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:31:
/usr/local/include/google/protobuf/arena_impl.h:291:10: error: candidate is: google::protobuf::internal::ArenaImpl::Block* google::protobuf::internal::ArenaImpl::NewBlock(google::protobuf::internal::ArenaImpl::Block*, size_t)
   Block* NewBlock(Block* last_block, size_t min_bytes);
          ^~~~~~~~
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:106:12: error: ‘class google::protobuf::internal::ArenaImpl::Block’ is private within this context
 ArenaImpl::Block* ArenaImpl::NewBlock(void* me, Block* my_last_block,
            ^~~~~
In file included from /usr/local/include/google/protobuf/arena.h:51:0,
                 from /media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:31:
/usr/local/include/google/protobuf/arena_impl.h:215:25: note: declared private here
   class PROTOBUF_EXPORT Block {
                         ^~~~~
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:125:58: error: no ‘void google::protobuf::internal::ArenaImpl::InitBlock(google::protobuf::internal::ArenaImpl::Block*, void*, size_t)’ member function declared in class ‘google::protobuf::internal::ArenaImpl’
 void ArenaImpl::InitBlock(Block* b, void *me, size_t size) {
                                                          ^
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:125:27: error: ‘class google::protobuf::internal::ArenaImpl::Block’ is private within this context
 void ArenaImpl::InitBlock(Block* b, void *me, size_t size) {
                           ^~~~~
In file included from /usr/local/include/google/protobuf/arena.h:51:0,
                 from /media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:31:
/usr/local/include/google/protobuf/arena_impl.h:215:25: note: declared private here
   class PROTOBUF_EXPORT Block {
                         ^~~~~
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:139:63: error: no ‘google::protobuf::internal::ArenaImpl::CleanupChunk* google::protobuf::internal::ArenaImpl::ExpandCleanupList(google::protobuf::internal::ArenaImpl::CleanupChunk*, google::protobuf::internal::ArenaImpl::Block*)’ member function declared in class ‘google::protobuf::internal::ArenaImpl’
                                                       Block* b) {
                                                               ^
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:138:12: error: ‘struct google::protobuf::internal::ArenaImpl::CleanupChunk’ is private within this context
 ArenaImpl::CleanupChunk* ArenaImpl::ExpandCleanupList(CleanupChunk* cleanup,
            ^~~~~~~~~~~~
In file included from /usr/local/include/google/protobuf/arena.h:51:0,
                 from /media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:31:
/usr/local/include/google/protobuf/arena_impl.h:128:10: note: declared private here
   struct CleanupChunk {
          ^~~~~~~~~~~~
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:139:55: error: ‘class google::protobuf::internal::ArenaImpl::Block’ is private within this context
                                                       Block* b) {
                                                       ^~~~~
In file included from /usr/local/include/google/protobuf/arena.h:51:0,
                 from /media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:31:
/usr/local/include/google/protobuf/arena_impl.h:215:25: note: declared private here
   class PROTOBUF_EXPORT Block {
                         ^~~~~
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:155:8: error: ‘GOOGLE_PROTOBUF_ATTRIBUTE_ALWAYS_INLINE’ does not name a type
 inline GOOGLE_PROTOBUF_ATTRIBUTE_ALWAYS_INLINE
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc: In member function ‘void google::protobuf::internal::ArenaImpl::AddCleanup(void*, void (*)(void*))’:
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:170:38: error: ‘GetBlock’ was not declared in this scope
   return AddCleanupInBlock(GetBlock(0), elem, cleanup);
                                      ^
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:170:54: error: ‘AddCleanupInBlock’ was not declared in this scope
   return AddCleanupInBlock(GetBlock(0), elem, cleanup);
                                                      ^
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:170:54: error: return-statement with a value, in function returning 'void' [-fpermissive]
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc: In member function ‘void* google::protobuf::internal::ArenaImpl::AllocateAligned(size_t)’:
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:176:35: error: ‘GetBlock’ was not declared in this scope
   return AllocFromBlock(GetBlock(n), n);
                                   ^
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:176:39: error: ‘AllocFromBlock’ was not declared in this scope
   return AllocFromBlock(GetBlock(n), n);
                                       ^
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc: In member function ‘void* google::protobuf::internal::ArenaImpl::AllocateAlignedAndAddCleanup(size_t, void (*)(void*))’:
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:183:24: error: ‘GetBlock’ was not declared in this scope
   Block* b = GetBlock(n);
                        ^
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:184:34: error: ‘AllocFromBlock’ was not declared in this scope
   void* mem = AllocFromBlock(b, n);
                                  ^
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:185:36: error: ‘AddCleanupInBlock’ was not declared in this scope
   AddCleanupInBlock(b, mem, cleanup);
                                    ^
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc: At global scope:
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:189:8: error: ‘GOOGLE_PROTOBUF_ATTRIBUTE_ALWAYS_INLINE’ does not name a type
 inline GOOGLE_PROTOBUF_ATTRIBUTE_ALWAYS_INLINE
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:217:8: error: ‘GOOGLE_PROTOBUF_ATTRIBUTE_ALWAYS_INLINE’ does not name a type
 inline GOOGLE_PROTOBUF_ATTRIBUTE_ALWAYS_INLINE
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:231:51: error: no ‘google::protobuf::internal::ArenaImpl::Block* google::protobuf::internal::ArenaImpl::GetBlockSlow(void*, google::protobuf::internal::ArenaImpl::Block*, size_t)’ member function declared in class ‘google::protobuf::internal::ArenaImpl’
                                           size_t n) {
                                                   ^
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:230:12: error: ‘class google::protobuf::internal::ArenaImpl::Block’ is private within this context
 ArenaImpl::Block* ArenaImpl::GetBlockSlow(void* me, Block* my_full_block,
            ^~~~~
In file included from /usr/local/include/google/protobuf/arena.h:51:0,
                 from /media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:31:
/usr/local/include/google/protobuf/arena_impl.h:215:25: note: declared private here
   class PROTOBUF_EXPORT Block {
                         ^~~~~
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc: In member function ‘google::protobuf::uint64 google::protobuf::internal::ArenaImpl::SpaceAllocated() const’:
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:248:10: error: ‘NoBarrier_Load’ is not a member of ‘google::protobuf::internal’
   return google::protobuf::internal::NoBarrier_Load(&space_allocated_);
          ^~~~~~
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc: In member function ‘google::protobuf::uint64 google::protobuf::internal::ArenaImpl::SpaceUsed() const’:
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:252:3: error: ‘ThreadInfo’ was not declared in this scope
   ThreadInfo* info =
   ^~~~~~~~~~
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:252:15: error: ‘info’ was not declared in this scope
   ThreadInfo* info =
               ^~~~
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:253:24: error: ‘ThreadInfo’ does not name a type
       reinterpret_cast<ThreadInfo*>(google::protobuf::internal::Acquire_Load(&threads_));
                        ^~~~~~~~~~
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:253:34: error: expected ‘>’ before ‘*’ token
       reinterpret_cast<ThreadInfo*>(google::protobuf::internal::Acquire_Load(&threads_));
                                  ^
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:253:34: error: expected ‘(’ before ‘*’ token
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:253:35: error: expected primary-expression before ‘>’ token
       reinterpret_cast<ThreadInfo*>(google::protobuf::internal::Acquire_Load(&threads_));
                                   ^
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:253:37: error: ‘Acquire_Load’ is not a member of ‘google::protobuf::internal’
       reinterpret_cast<ThreadInfo*>(google::protobuf::internal::Acquire_Load(&threads_));
                                     ^~~~~~
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:253:89: error: expected ‘)’ before ‘;’ token
       reinterpret_cast<ThreadInfo*>(google::protobuf::internal::Acquire_Load(&threads_));
                                                                                         ^
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:259:43: error: cannot convert ‘google::protobuf::internal::ArenaImpl::Block::next’ from type ‘google::protobuf::internal::ArenaImpl::Block* (google::protobuf::internal::ArenaImpl::Block::)() const’ to type ‘google::protobuf::internal::ArenaImpl::Block*’
     for (Block* b = info->head; b; b = b->next) {
                                           ^~~~
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:260:31: error: ‘kHeaderSize’ was not declared in this scope
       space_used += (b->pos - kHeaderSize);
                               ^~~~~~~~~~~
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc: In member function ‘google::protobuf::uint64 google::protobuf::internal::ArenaImpl::FreeBlocks()’:
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:271:3: error: ‘ThreadInfo’ was not declared in this scope
   ThreadInfo* info =
   ^~~~~~~~~~
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:271:15: error: ‘info’ was not declared in this scope
   ThreadInfo* info =
               ^~~~
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:272:24: error: ‘ThreadInfo’ does not name a type
       reinterpret_cast<ThreadInfo*>(google::protobuf::internal::NoBarrier_Load(&threads_));
                        ^~~~~~~~~~
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:272:34: error: expected ‘>’ before ‘*’ token
       reinterpret_cast<ThreadInfo*>(google::protobuf::internal::NoBarrier_Load(&threads_));
                                  ^
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:272:34: error: expected ‘(’ before ‘*’ token
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:272:35: error: expected primary-expression before ‘>’ token
       reinterpret_cast<ThreadInfo*>(google::protobuf::internal::NoBarrier_Load(&threads_));
                                   ^
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:272:37: error: ‘NoBarrier_Load’ is not a member of ‘google::protobuf::internal’
       reinterpret_cast<ThreadInfo*>(google::protobuf::internal::NoBarrier_Load(&threads_));
                                     ^~~~~~
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:272:91: error: expected ‘)’ before ‘;’ token
       reinterpret_cast<ThreadInfo*>(google::protobuf::internal::NoBarrier_Load(&threads_));
                                                                                           ^
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:276:17: error: ‘next_info’ was not declared in this scope
     ThreadInfo* next_info = info->next;
                 ^~~~~~~~~
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:279:30: error: cannot convert ‘google::protobuf::internal::ArenaImpl::Block::next’ from type ‘google::protobuf::internal::ArenaImpl::Block* (google::protobuf::internal::ArenaImpl::Block::)() const’ to type ‘google::protobuf::internal::ArenaImpl::Block*’
       Block* next_block = b->next;
                              ^~~~
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:280:30: error: invalid use of member function ‘size_t google::protobuf::internal::ArenaImpl::Block::size() const’ (did you forget the ‘()’ ?)
       space_allocated += (b->size);
                          ~~~~^~~~~
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:280:34: error:   in evaluation of ‘operator+=(google::protobuf::uint64 {aka long unsigned int}, <unresolved overloaded function type>)’
       space_allocated += (b->size);
                                  ^
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:289:42: error: cannot convert ‘google::protobuf::internal::ArenaImpl::Block::size’ from type ‘size_t (google::protobuf::internal::ArenaImpl::Block::)() const {aka long unsigned int (google::protobuf::internal::ArenaImpl::Block::)() const}’ to type ‘size_t {aka long unsigned int}’
         options_.block_dealloc(b, b->size);
                                          ^
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc: In member function ‘void google::protobuf::internal::ArenaImpl::CleanupList()’:
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:303:3: error: ‘ThreadInfo’ was not declared in this scope
   ThreadInfo* info =
   ^~~~~~~~~~
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:303:15: error: ‘info’ was not declared in this scope
   ThreadInfo* info =
               ^~~~
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:304:24: error: ‘ThreadInfo’ does not name a type
       reinterpret_cast<ThreadInfo*>(google::protobuf::internal::NoBarrier_Load(&threads_));
                        ^~~~~~~~~~
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:304:34: error: expected ‘>’ before ‘*’ token
       reinterpret_cast<ThreadInfo*>(google::protobuf::internal::NoBarrier_Load(&threads_));
                                  ^
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:304:34: error: expected ‘(’ before ‘*’ token
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:304:35: error: expected primary-expression before ‘>’ token
       reinterpret_cast<ThreadInfo*>(google::protobuf::internal::NoBarrier_Load(&threads_));
                                   ^
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:304:37: error: ‘NoBarrier_Load’ is not a member of ‘google::protobuf::internal’
       reinterpret_cast<ThreadInfo*>(google::protobuf::internal::NoBarrier_Load(&threads_));
                                     ^~~~~~
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:304:91: error: expected ‘)’ before ‘;’ token
       reinterpret_cast<ThreadInfo*>(google::protobuf::internal::NoBarrier_Load(&threads_));
                                                                                           ^
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:309:24: error: ‘struct google::protobuf::internal::ArenaImpl::CleanupChunk’ has no member named ‘len’
       size_t n = list->len;
                        ^~~
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:310:46: error: ‘struct google::protobuf::internal::ArenaImpl::CleanupChunk’ has no member named ‘len’
       CleanupNode* node = &list->nodes[list->len - 1];
                                              ^~~
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc: At global scope:
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:319:12: error: ‘ThreadInfo’ in ‘class google::protobuf::internal::ArenaImpl’ does not name a type
 ArenaImpl::ThreadInfo* ArenaImpl::NewThreadInfo(Block* b) {
            ^~~~~~~~~~
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:330:12: error: ‘ThreadInfo’ in ‘class google::protobuf::internal::ArenaImpl’ does not name a type
 ArenaImpl::ThreadInfo* ArenaImpl::FindThreadInfo(void* me) {
            ^~~~~~~~~~
/media/jintain/sg/permanent/software/source_codes/opencv_git/sandbox/opencv/3rdparty/protobuf/src/google/protobuf/arena.cc:342:12: error: ‘ThreadInfo’ in ‘class google::protobuf::internal::ArenaImpl’ does not name a type
 ArenaImpl::ThreadInfo* ArenaImpl::GetThreadInfo(void* me, size_t n) {
            ^~~~~~~~~~

```

It's a fresh new opencv, but build with so much more errors..................... And it's about protobuf??????????????????????? what exactly wrong with this weired problem????????????????

**Comment by alalek** [comment] 2019-03-05 10:09
duplicate of #13328

**Closed by alalek** 2019-03-05 10:09 UTC
Labels: duplicate
