### ISSUE TITLE
Expose list of VideoCapture devices

### ISSUE THREAD

**Issue by Avasam** [opencv/opencv#23844] opened 2023-06-21 19:22 UTC
### Describe the feature and motivation

There is no way currently, within OpenCV, to list existing devices to let the user select them. This means that they must be obtained in a different manner (either by re-implementing manually, or using a third-party library), which may not match OpenCV's indexes and may not work on all platforms.

There is a workaround to try every indexes individually, but this has 4 main issues:
1. Some VideoCapture devices will freeze if opened and closed quickly or if it was already in use.
    - The popular SD capture card `GV-USB2` (confirmed myself)
    - I've had reports that an `AverMedia` capture card is affected as well
2. Some devices take a long time to boot, making this technique quite slow (like my `Logitech c920` webcam)
3. The total amount of devices is unknown, and usable devices may not be sequential. So we have to guess how many devices maximum the user may have, trying to balance between time spent or risking missing some
4. Even if you get all the IDs after this, you don't have access to the names to present to the user. (see #23537)

**Comment by mshabunin** [comment] 2023-06-22 14:33
It seems to be a duplicate of #4269

**Closed by mshabunin** 2023-06-22 14:33 UTC
Labels: feature, category: videoio(camera)

**Comment by Avasam** [comment] 2023-06-23 00:31
Looks like it is, thanks!
