### ISSUE TITLE
multidimensional issue with RNG::fill

### ISSUE THREAD

**Issue by mexuaz** [opencv/opencv#8544] opened 2017-04-07 19:26 UTC
K-Means example http://docs.opencv.org/trunk/de/d63/kmeans_8cpp-example.html#a14 which is already mentioned in the OpenCV 3 Learning Book declares that we could use RNG::fill method with multidimensional matrix but the following simple code demonstrates that  what you write for the second argument of the distribution parameter a and b in the Scalar the first one will be chosen for both. the following code in tested in OpenCV 3.2 in linux.

```
Mat img(600, 800, CV_8UC3);
    RNG rng(time(NULL));
    namedWindow("Result");

    std::cout << "version: " << CV_MAJOR_VERSION << "." << CV_MINOR_VERSION << std::endl;

    while(true) {
        Point2f ct(rng.uniform(0, img.cols), rng.uniform(0, img.rows));
        Mat samplePoints(100, 2, CV_32F);
        rng.fill(samplePoints, RNG::NORMAL,
                 Scalar(ct.x, ct.y),
                 Scalar(img.cols*0.05, img.rows*0.05));
        img.setTo(Scalar::all(255));
        for(int i = 0; i < samplePoints.rows; i++) {
            circle(img, Point(samplePoints.at<Point2f>(i)), 3, Scalar(255, 0, 0), FILLED, LINE_AA);
        }

        Point cti(ct);
        Point w(6, 6);
        rectangle(img, Rect(cti-w, cti+w), Scalar(0, 0, 255), FILLED, LINE_AA);

        imshow("Result", img);

        int key = waitKey(0);
        if(key == 27) {
            break;
        }
    }
    destroyAllWindows();
```
if the filled method designed to work this way the example should be corrected or the method should conform the example.
![screenshot from 2017-04-07 12-29-29](https://cloud.githubusercontent.com/assets/7892380/24816517/ed12a1c2-1b8d-11e7-8c3a-11b51be80603.png)
As it is clear from the image the distribution is in the diagonal of the image that is because  OpenCV reads a (ct.x, ct.x) rather than (ct.x, ct.y). This is also a matter in parameter b as well.

**Comment by berak** [comment] 2017-04-08 04:20
no, this is not a bug, you're using it the wrong way.

a Mat of Points should be declared like it is done in the sample code:

    Mat (100, 1, CV_32FC2); // a single row, 2 channels

not like:

    Mat (100, 2, CV_32); // a single channel, 2 rows, that's where you're wrong.

(you're also trying to access it as: `samplePoints.at<Point2f>(i)` which should throw an exception in debug mode (try it !))

the distribition parameters in RNG::fill() or randu() apply to channels, not rows.

    Mat m(5,1,CV_32FC2);
    randu(m, Scalar(0,0),Scalar(5,10));
    cerr << m << endl;
```[2.6514139, 1.9925919;
 2.0052972, 8.1438503;
 2.1856649, 2.4878969;
 3.8655252, 7.6209373;
 1.5389724, 7.0243168]
```

again, not a bug. could you close this issue (as it isn't one) ?

**Closed** 2017-04-08 05:21 UTC

**Comment by mexuaz** [comment] 2017-04-08 05:24
Thanks for the answer since the underlying data is the same I do not pay much attention between channels and columns but here it seems it really matters.
