### ISSUE TITLE
solvePnPGeneric Python Binding crash when reprojectionError is not passed as argument

### ISSUE THREAD

**Issue by vwvw** [opencv/opencv#16049] opened 2019-12-03 14:44 UTC
##### System information (version)

- OpenCV => 4.1.2
- Operating System / Platform => Linux / Ubuntu 18.04
- Compiler => :grey_question:

##### Detailed description

When running the code below that call `solvePnPGeneric` from Python the program crashes because the C++ code expect a different type for `reprojectionError`  from the one passed by `solvePnPGeneric` by default. The argument is however [documented](https://docs.opencv.org/master/d9/d0c/group__calib3d.html#ga624af8a6641b9bdb487f63f694e8bb90) as optional. Passing the argument with the correct type avoid the error. 

I suspect that the binding of the `solvePnPGeneric` function do not pass the correct argument type for `reprojectionError` by default.

The error:

```bash 
Traceback (most recent call last):
  File "error.py", line 15, in <module>
    obj_points, img_points, cameraMatrix, distCoeffs #, reprojectionError=r
cv2.error: OpenCV(4.1.2) /io/opencv/modules/calib3d/src/solvepnp.cpp:1017: error: (-2:Unspecified error) in function 'int cv::solvePnPGeneric(cv::InputArray, cv::InputArray, cv::InputArray, cv::InputArray, cv::OutputArrayOfArrays, cv::OutputArrayOfArrays, bool, cv::SolvePnPMethod, cv::InputArray, cv::InputArray, cv::OutputArray)'
> Type of reprojectionError must be CV_32FC1 or CV_64FC1!:
>     'type == CV_32FC1 || type == CV_64FC1'
> where
>     'reprojectionError.type()' is 0 (CV_8UC1)
```

This might be closely linked to #16040 which is about Java binding of solvePnPGeneric

##### Steps to reproduce
Run this code (OpenCV 4.1.2 / Python 3.6.8)
```python
import numpy as np
import cv2

obj_points = np.array([[0, 0, 0], [0, 1, 0], [1, 1, 0], [1, 0, 0]], dtype=np.float32)
img_points = np.array(
    [[700, 400], [700, 600], [900, 600], [900, 400]], dtype=np.float32
)

cameraMatrix = np.array(
    [[712.0634, 0, 800], [0, 712.540, 500], [0, 0, 1]], dtype=np.float32
)
distCoeffs = np.array([[0, 0, 0, 0]], dtype=np.float32)
#r = np.array([], dtype=np.float32)
x, r, t, e = cv2.solvePnPGeneric(
    obj_points, img_points, cameraMatrix, distCoeffs #, reprojectionError=r
)
print(e)
print(t)
```

The error can be bypassed by uncommenting the `#r = np.array([], dtype=np.float32)` lines.

Thanks for the amazing work and happy to help or provide more information!

**Comment by alalek** [comment] 2019-12-04 15:26
Python bindings is not able to pass default value for "OutputArray reprojectionError = noArray()" parameter.

Need to fix bindings generator. Corresponding test check is [here](https://github.com/opencv/opencv/blob/3.4.8/modules/python/test/test_misc.py#L53) (commented out).

**Comment by berak** [comment] 2019-12-04 18:48
> Python bindings is not able to pass default value for "OutputArray reprojectionError = noArray()" parameter.

i don't quite agree. i could reproduce it from c++:
```
	cv::Mat_<float> obj_points(4,3);   obj_points << 0, 0, 0,  0, 1, 0,  1, 1, 0,  1, 0, 0;
	cv::Mat_<float> img_points(4,2);   img_points << 700, 400,  700, 600,  900, 600,  900, 400;
	cv::Mat_<float> cameraMatrix(3,3); cameraMatrix << 712.0634, 0, 800,  0, 712.540, 500,  0, 0, 1;
	cv::Mat_<float> distCoeffs(1,4);   distCoeffs << 0, 0, 0, 0;

	Mat rep; // this is the conflicting CV_8UC1 
	vector<Mat> rvecs,tvecs;
        float r = cv::solvePnPGeneric( obj_points, img_points, cameraMatrix, distCoeffs, rvecs, tvecs, false, SOLVEPNP_UPNP, noArray(), noArray(), rep );

```
leading to:
```
>     'type == CV_32FC1 || type == CV_64FC1'
> where
>     'reprojectionError.type()' is 0 (CV_8UC1)
) in int cv::solvePnPGeneric(cv::InputArray, cv::InputArray, cv::InputArray, cv::InputArray, cv::OutputArrayOfArrays, cv::Output
ArrayOfArrays, bool, cv::SolvePnPMethod, cv::InputArray, cv::InputArray, cv::OutputArray), file C:\p\opencv\modules\calib3d\src\
solvepnp.cpp, line 1017
```
it's the very same thing [done in the python wrappers](https://gist.github.com/berak/7dd8a872b5bc9cf9893f8a1bec9aa201#file-pyopencv_generated_funcs-h-L26)

so let's look here:

https://github.com/opencv/opencv/blob/4c71dbf0af70e8728b8a791695b083540af72887/modules/calib3d/src/solvepnp.cpp#L1012-L1017

the default `noArray()` won't trigger `needed()`, but once we pass (a ref to) an empty Mat, we get past that check and it creates the wrong type (still CV_8U).

why not create a Mat of correct type / size like:

     reprojectionError.create(solutions, 1, CV_64FC1);

and remove the type check / assertion ?

**Comment by alalek** [comment] 2019-12-04 19:05
`OutputArray param = noArray()` is used in meaning of optional output parameter, which **should be calculated only if requested**. Calculation (which can be heavy) is guarded by `.needed()` check.

Python bindings is not able to work with `OutputArray` directly. They using `Mat` and the problem is in that (bindings generator and wrappers should be fixed).

However removal of type check can unlock calling of this function with empty `Mat` as `OutputArray` parameter:
- with `64F` type by default?
- or `max(_ipoint.depth(), _opoint.depth()) == CV_64F ? CV_64F : CV_32F`

**Comment by ganesh-k13** [comment] 2020-01-20 19:29
Hi @alalek , can I look into this issue?

**Comment by alalek** [comment] 2020-01-20 20:17
You can try to unlock function for empty "Mat".
Start from adding corresponding simple test (`modules/calib3d/misc/python/test/test_solvepnp.py`) - no need to check accuracy, just check that bindings work (non empty result of "expected" type).


---

But please avoid part of issue about:

> OutputArray param = noArray()

Mentor with strong Python bindings experience is required for this task.

**Comment by ganesh-k13** [comment] 2020-01-21 06:48
Ure @alalek, I'll do the following:
1. Add test in `modules/calib3d/misc/python/test/test_solvepnp.py`
2. Change this line https://github.com/opencv/opencv/blob/4c71dbf0af70e8728b8a791695b083540af72887/modules/calib3d/src/solvepnp.cpp#L1015
by adding max(_ipoint.depth(), _opoint.depth()) == CV_64F ? CV_64F : CV_32F for default `type`

**Closed** 2020-01-28 16:24 UTC
Labels: bug, category: python bindings, priority: normal
