### ISSUE TITLE
cv::cuda::GpuMat.convertTo() seems not to support in-place, while cv::Mat does

### ISSUE THREAD

**Issue by chacha21** [opencv/opencv#13092] opened 2018-11-09 13:10 UTC
Visual Studio 2017, Windows 7 64 bits, OpenCV 3.4.3
Cuda 10

the following code raises an exception :

```
  cv::cuda::GpuMat m(cv::Size(1280, 1024), CV_32FC1);
  cv::cuda::Stream stream;
  m.convertTo(m, CV_8UC1, 1, 0, stream);
  cv::cuda::threshold(m, m, 128, 255, cv::THRESH_BINARY, stream);
```

> OpenCV(3.4.3) Error: Gpu API call (an illegal memory access was encountered) in
> cv::cudev::grid_transform_detail::TransformDispatcher<true, Policy>::call, file
> e:\opencv-3.4.3\opencv\sources\modules\cudev\include\opencv2\cudev\grid\detail/t
> ransform.hpp, line 318

Using a second matrix as a destination for the convertTo() gets rid of the problem.

So it seems that convertTo() is no safe to use *in-place* with cuda::GpuMat, while the same code with cv::Mat would be ok.
Is it a bug or a missing documentation ?

**Comment by chacha21** [comment] 2018-11-30 22:42
Maybe a shared problem with  #13149 ?

**Comment by harsv** [comment] 2019-05-15 00:01
I am having similar problem with opencv 3.4, Cuda10, Ubuntu18.04
This code works:
` cv::cuda::GpuMat gpu_image;
	  gpu_image_init.convertTo(gpu_image, CV_32FC3, 1.0, 0);`
However, this does not works:
`  gpu_image_init.convertTo(gpu_image_init, CV_32FC3, 1.0, 0);`

In my case, the code runs but the resultant matrix has garbage values.

**Comment by nglee** [comment] 2020-07-08 18:31
I cannot reproduce this error on the latest 3.4 branch. (win10, vs2019, cuda10.2)
Although we are allowed to call `GpuMat::convertTo()` with one `GpuMat` for both input and output, it is not strictly an in-place conversion.
Inside `GpuMat::convertTo()`, it allocates device memory for result data.

**Comment by chacha21** [comment] 2020-07-08 18:54
As long as it does not crash, it is not a problem that it is not a real "in-place". I will check with my 4.3.0 build tomorrow

**Comment by chacha21** [comment] 2020-07-09 07:51
The bug (as mentionned in initial post) is still present in 4.3.0

**Comment by nglee** [comment] 2020-07-09 18:23
This is getting confusing. Even with Ubuntu 18.04(Jetson TX2) and the latest master branch build(4.4.0-pre), I wasn't able to reproduce the error. I've added the following googletest code to cudaarithm test codes and it seems to be working.
```
TEST(Issue13092, Issue13092)
{
    cv::cuda::GpuMat m(cv::Size(1280, 1024), CV_32FC1);
    cv::cuda::Stream stream;
    m.convertTo(m, CV_8UC1, 1, 0, stream);
    cv::cuda::threshold(m, m, 128, 255, cv::THRESH_BINARY, stream);
}
```
```
$ ./opencv_test_cudaarithm --gtest_filter=*13092*

...

deviceQuery, CUDA Driver = CUDART, CUDA Driver Version  = 10.0, CUDA Runtime Version = 10.0, NumDevs = 1

CTEST_FULL_OUTPUT
OpenCV version: 4.4.0-pre
OpenCV VCS version: 4.3.0-586-gd0e6d2438c
Build type: Release
Compiler: /usr/bin/c++  (ver 7.5.0)
Parallel framework: pthreads (nthreads=6)
CPU features: NEON? FP16?
OpenCL is disabled
TEST: Skip tests with tags: 'mem_6gb', 'verylong'
Note: Google Test filter = *13092*
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from Issue13092
[ RUN      ] Issue13092.Issue13092
[       OK ] Issue13092.Issue13092 (550 ms)
[----------] 1 test from Issue13092 (550 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (551 ms total)
[  PASSED  ] 1 test.
```
I'll try again with x64 machine tomorrow.

**Comment by chacha21** [comment] 2020-07-09 19:14
I forgot to mention that I now use CUDA 10.2 but  it is of less importance, this is still W7 64b

**Comment by nglee** [comment] 2020-07-17 04:28
After increasing the GpuMat size, I see the same issue. The GPU model is RTX 2080 Ti.

**Comment by mshabunin** [comment] 2020-07-23 11:12
Perhaps this issue is similar to #17840 which have been resolved by using CUDA function designed for in-place processing.

**Comment by nglee** [comment] 2020-07-29 16:08
@chacha21 @mshabunin 
I believe [this](https://github.com/nglee/opencv/commit/2241bfb0dfa788e0b516a7da9a1f70733f5431d3) can fix this issue.
Could you please take a look?

**Comment by chacha21** [comment] 2020-07-30 07:23
I confirm that it seems to fix the problem.

**Closed** 2020-08-14 21:47 UTC
Labels: category: gpu/cuda (contrib)
