### ISSUE TITLE
solvep3p issue

### ISSUE THREAD

**Issue by mht1421** [opencv/opencv#14565] opened 2019-05-15 08:52 UTC
Hi,

I am giving the function cv2.solveP3P 3 3D ref points (matrix of size 3x3 type float32) and 2 2D points (matrix of size 3x2 and type float32) camera matrix (3x3) distCoeffs(5,) and the flags= cv2.SOLVEPNP_AP3P.

But I am getting the error
cv2.error: OpenCV(4.1.0) /io/opencv/modules/calib3d/src/undistort.cpp:387: error: (-215:Assertion failed) CV_IS_MAT(_src) && CV_IS_MAT(_dst) && (_src->rows == 1 || _src->cols == 1) && (_dst->rows == 1 || _dst->cols == 1) && _src->cols + _src->rows - 1 == _dst->rows + _dst->cols - 1 && (CV_MAT_TYPE(_src->type) == CV_32FC2 || CV_MAT_TYPE(_src->type) == CV_64FC2) && (CV_MAT_TYPE(_dst->type) == CV_32FC2 || CV_MAT_TYPE(_dst->type) == CV_64FC2) in function 'cvUndistortPointsInternal'

I can't find the error.

**Comment by alalek** [comment] 2019-05-15 09:20
> solveP3P
> undistort.cpp

Probably duplicate of #14423 (but message is not the same)

Please provide complete minimal reproducer.

**Comment by catree** [comment] 2019-05-15 09:53
There are some notes in the [documentation](https://docs.opencv.org/4.1.0/d9/d0c/group__calib3d.html#ga549c2075fac14829ff4a58bc931c033d):

If you are using Python:

    - Numpy array slices won't work as input because solvePnP requires contiguous arrays (enforced by the assertion using cv::Mat::checkVector() around line 55 of modules/calib3d/src/solvepnp.cpp version 2.4.9)
    - The P3P algorithm requires image points to be in an array of shape (N,1,2) due to its calling of cv::undistortPoints (around line 75 of modules/calib3d/src/solvepnp.cpp version 2.4.9) which requires 2-channel information.
    - Thus, given some data D = np.array(...) where D.shape = (N,M), in order to use a subset of it as, e.g., imagePoints, one must effectively copy it into a new array: imagePoints = np.ascontiguousarray(D[:,:2]).reshape((N,1,2))

Probably the doc for `solveP3P` should be updated if it is confirmed.

**Comment by mht1421** [comment] 2019-05-22 10:09
yes it was a problem of the shape, thanks for the reply

**Closed** 2019-05-22 10:23 UTC
Labels: category: calib3d, invalid

**Comment by emerso2000** [comment] 2021-11-17 21:32
How did you solve this issue?
