### ISSUE TITLE
pkg-config file opencv.pc not update.

### ISSUE THREAD

**Issue by Moore123** [opencv/opencv#13245] opened 2018-11-22 05:22 UTC
##### System information (version)

- OpenCV => git version till [Wed Nov 21 15:54:42 2018] b6a447798ac0d56aac11dfff2d61d420260e7f19
- Operating System / Platform => Ubuntu 18.04.1 LTS
- Compiler => g++ (Ubuntu 5.5.0-12ubuntu1) 5.5.0 20171010

##### Detailed description

compiled done, with "make install" command
the opencv.pc in ${prefix}/lib/pkgconfig/opencv.pc should update
for pkg-config  --cflags output correctly

##### Steps to reproduce

make install
pkg-config --cflags opencv

   ``` should  prefer  ${prefix}/include/opencv4

**Comment by alalek** [comment] 2018-11-22 09:39
Looks like your opencv.pc file is from the previous installation (previous call of "make install"), so system configuration become not consistent.

See #12896
Duplicate of #13154

**Closed by alalek** 2018-11-22 09:39 UTC
Labels: category: build/install, question (invalid)

**Comment by sergiomb2** [comment] 2019-05-21 03:30
don't say that is deprecated please, all Fedora rpms packages can be driven by pkgconfig 
I got error just because package use [1]

[1] 
BuildRequires: pkgconfig(opencv)
