### ISSUE TITLE
libopencv_java3 library not found for x86_64

### ISSUE THREAD

**Issue by ashokbugude** [opencv/opencv#9464] opened 2017-08-25 04:28 UTC
I have downloaded the opencv sdk  which contains libraries for all architectures except x86_64 

I needed libopencv_java3.so file for x86_64 which is used in https://github.com/opencv/opencv/blob/master/modules/java/generator/src/java/android%2BStaticHelper.java

I have run below command
 cmake  -DCMAKE_TOOLCHAIN_FILE=../platforms/android/android.toolchain.cmake -DANDROID_ABI="x86_64" -DWITH_TBB=ON -DINSTALL_ANDROID_EXAMPLES=ON -DANDROID_NATIVE_API_LEVEL=9 

But libopencv_java3.so is not generated
Please help me in generating the library

**Comment by alalek** [comment] 2017-08-25 07:27
We [can't reproduce](http://pullrequest.opencv.org/buildbot/builders/master_pack-android/builds/10200) mentioned problem:
> -- Installing: /build/master_pack-android/build/o4a/install/sdk/native/libs/x86_64/libopencv_java3.so

You could start investigating this problem by comparing build logs from mentioned build.

Usage questions / build support requests should go to Users OpenCV Q/A forum: http://answers.opencv.org
Please return back if you determine clean reason of the problem and OpenCV code should have a fix for this.

**Closed by alalek** 2017-08-25 07:27 UTC
Labels: question (invalid)
