### ISSUE TITLE
Issue trying to build opencv using cmake in a docker

### ISSUE THREAD

**Issue by enjoykcc456** [opencv/opencv#17825] opened 2020-07-13 09:13 UTC
Hi, I have been trying to build opencv with dnn cuda in a docker but failed because of this issue. 
```
CMake Error at cmake/FindCUDNN.cmake:68 (file):
  file failed to open for reading (No such file or directory):

    /usr/lib/powerpc64le-linux-gnu/cudnn.h
Call Stack (most recent call first):
  cmake/OpenCVUtils.cmake:131 (find_package)
  cmake/OpenCVDetectCUDA.cmake:42 (find_host_package)
  cmake/OpenCVFindLibsPerf.cmake:43 (include)
  CMakeLists.txt:687 (include)


-- Could NOT find CUDNN: Found unsuitable version "..", but required is at least "7.5" (found /usr/lib/powerpc64le-linux-gnu)
```

It seems like cmake is trying to locate the cudnn.h, but it is not there. There is only libcudnn.so instead. 

```
root@70d2e4e71041:/tf/root# ll /usr/lib/powerpc64le-linux-gnu/libcud*
lrwxrwxrwx. 1 root root        12 Jul 13 08:53 /usr/lib/powerpc64le-linux-gnu/libcuda.so -> libcuda.so.1*
lrwxrwxrwx. 1 root root        20 Jul 13 08:53 /usr/lib/powerpc64le-linux-gnu/libcuda.so.1 -> libcuda.so.418.40.04*
-rwxr-xr-x. 1 root root  16371912 Mar 15  2019 /usr/lib/powerpc64le-linux-gnu/libcuda.so.418.40.04*
lrwxrwxrwx. 1 root root        17 Sep 23  2019 /usr/lib/powerpc64le-linux-gnu/libcudnn.so.7 -> libcudnn.so.7.6.4
-rw-r--r--. 1 root root 430647520 Sep 23  2019 /usr/lib/powerpc64le-linux-gnu/libcudnn.so.7.6.4

```
```
root@70d2e4e71041:/tf/root# nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:52_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
```
```
root@70d2e4e71041:/tf/root# apt-cache policy libcudnn7
libcudnn7:
  Installed: 7.6.4.38-1+cuda10.1
  Candidate: 7.6.5.32-1+cuda10.2
  Version table:
     7.6.5.32-1+cuda10.2 500
        500 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/ppc64el  Packages
     7.6.5.32-1+cuda10.1 500
        500 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/ppc64el  Packages
     7.6.5.32-1+cuda10.0 500
        500 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/ppc64el  Packages
 *** 7.6.4.38-1+cuda10.1 500
        500 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/ppc64el  Packages
        100 /var/lib/dpkg/status
```
cmake command:
```
RUN cmake -D CMAKE_BUILD_TYPE=RELEASE \
      -D CMAKE_INSTALL_PREFIX=/usr/local \
      -D INSTALL_PYTHON_EXAMPLES=ON \
      -D INSTALL_C_EXAMPLES=OFF \
      -D OPENCV_ENABLE_NONFREE=ON \
      -D WITH_CUDA=ON \
      -D WITH_CUDNN=ON \
      -D CUDNN_INCLUDE_DIR=/usr/lib/powerpc64le-linux-gnu \
      -D CUDNN_LIBRARY=/usr/lib/powerpc64le-linux-gnu \
      -D OPENCV_DNN_CUDA=ON \
      -D ENABLE_FAST_MATH=1 \
      -D CUDA_FAST_MATH=1 \
      -D CUDA_ARCH_BIN=7.0 \
      -D WITH_CUBLAS=1 \
      -D OPENCV_EXTRA_MODULES_PATH=/opencv_gpu_files/opencv_contrib/modules \
      -D HAVE_opencv_python3=ON \
      -D PYTHON_EXECUTABLE=/usr/bin/python3 \
      -D BUILD_EXAMPLES=ON ..
```

The docker image used is ibmcom/tensorflow-ppc64le:latest-gpu-py3-jupyter. I am able to use the image properly to do training with tensorflow. 
But just couldn't install opencv on it. Does anyone does know what can i do to solve this? Thanks a lot.

**Comment by mshabunin** [comment] 2020-07-13 09:36
Header files are usually provided by `-dev` packages, e.g. _libcudnn7-dev_. Please consult with with CUDA documentation.

I'm closing the issue since there is no evidence the problem is in OpenCV.

**Closed by mshabunin** 2020-07-13 09:36 UTC

**Comment by enjoykcc456** [comment] 2020-07-14 03:46
Hi, i am able to solve the cudnn issue after installing the `-dev` packages as mentioned, but i got the following issue:

```
Please set them or make sure they are set and tested correctly in the CMake files:  
CUDA_nppc_LIBRARY (ADVANCED)
```
The cmake command:
```
RUN cmake -D CMAKE_BUILD_TYPE=RELEASE \
  -D CMAKE_INSTALL_PREFIX=/usr/local \
  -D INSTALL_PYTHON_EXAMPLES=ON \
  -D INSTALL_C_EXAMPLES=OFF \
  -D OPENCV_ENABLE_NONFREE=ON \
  -D WITH_CUDA=ON \
  -D WITH_CUDNN=ON \
  -D CUDA_cublas_LIBRARY=/usr/lib/powerpc64le-linux-gnu \
  -D CUDA_cufft_LIBRARY=/usr/lib/powerpc64le-linux-gnu \
  -D OPENCV_DNN_CUDA=ON \
  -D ENABLE_FAST_MATH=1 \
  -D CUDA_FAST_MATH=1 \
  -D CUDA_ARCH_BIN=7.0 \
  -D WITH_CUBLAS=1 \
  -D OPENCV_EXTRA_MODULES_PATH=/opencv_gpu_files/opencv_contrib/modules \
  -D HAVE_opencv_python3=ON \
  -D PYTHON_EXECUTABLE=/usr/bin/python3 \
  -D BUILD_EXAMPLES=ON ..
```
Does anyone knows what i did wrong and what should i do to fix this? Thank you.
