### ISSUE TITLE
DNN not supporting Tensorflow Hub module?

### ISSUE THREAD

**Issue by wildpig22** [opencv/opencv#11577] opened 2018-05-23 12:22 UTC
##### System information (version)

- OpenCV => 3.4.1 pre-built release
- Tensorflow => 1.8.0 latest master
- Operating System / Platform => Windows 10 64bit
- Compiler => Visual Studio 2015

I have retrained an image classifier based on TFHub Mobilenet V2, using the following command:

`retrain.py --image_dir .\data --output_graph output.pb --output_labels labels.txt --tfhub_module https://tfhub.dev/google/imagenet/mobilenet_v2_100_224/feature_vector/1 --saved_model_dir .\export`

The resulting output.pb works fine with TF label image:

`tensorflow\examples\label_image\label_image.py --graph=.\output.pb --labels=.\labels.txt --input_layer=Placeholder --output_layer=final_result --input_height=224 --input_width=224 --image=.\111.jpg`

But when using OpenCV DNN module, it crashes at the following line:

`dnn::Net net = readNetFromTensorflow(modelFile);`

with error message:

`OpenCV(3.4.1) Error: Unspecified error (Unknown layer type Sub in op module_apply_default/hub_input/Sub) in cv::dnn::experimental_dnn_v4::'anonymous-namespace'::TFImporter::populateNet, file C:\build\master_winpack-build-win64-vc14\opencv\modules\dnn\src\tensorflow\tf_importer.cpp, line 1582`

Running optimize_for_inference.py and transform_graph does not help.

After some inspecting with tensorboard graph, it seems that one hub_input block caused this problem. 
![hub_input](https://user-images.githubusercontent.com/13673628/40423491-54cb0eaa-5ec5-11e8-8053-037d32c0a8d4.png)

Looks like TF Hub models have this block between Placeholder(input node) and the MobilenetV2 block, and the Sub operation is not supported by DNN.

Am I missing something here?

Here is my retrained model, load it with readNetFromTensorflow() to reproduce the problem
[output.zip](https://github.com/opencv/opencv/files/2030954/output.zip)

Any help is appreciated!

**Comment by dkurt** [comment] 2018-05-23 14:40
@wildpig22, partially, this is a duplicate of http://answers.opencv.org/question/175699/readnetfromtensorflow-fails-on-retrained-nn/. However the solution is a bit rough.

Please apply the following transformations to your model:
```python
import tensorflow as tf

from tensorflow.python.tools import optimize_for_inference_lib
from tensorflow.tools.graph_transforms import TransformGraph

with tf.gfile.FastGFile('output.pb', 'rb') as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())
    graph_def = optimize_for_inference_lib.optimize_for_inference(graph_def, ['Placeholder'], ['final_result'], tf.float32.as_datatype_enum)
    graph_def = TransformGraph(graph_def, ['module_apply_default/hub_input/Sub'], ['final_result'], ['remove_nodes(op=PlaceholderWithDefault)', 'strip_unused_nodes(type=float, shape=\"1,224,224,3\")', 'sort_by_execution_order'])
    with tf.gfile.FastGFile('inference_graph.pb', 'wb') as f:
        f.write(graph_def.SerializeToString())
```

It fuses different constant operations and removes preprocessing subgraph (Multiplication by 2 and subtraction of 1).

The following code let you check an accuracy:
```python
import numpy as np
import tensorflow as tf
import cv2 as cv

np.random.seed(324)
inp = np.random.uniform(-1.0, 1.0, [1, 224, 224, 3]).astype(np.float32)

with tf.gfile.FastGFile('inference_graph.pb', 'rb') as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())

with tf.Session() as sess:
    sess.graph.as_default()
    tf.import_graph_def(graph_def, name='')

    tfOut = sess.run(sess.graph.get_tensor_by_name('final_result:0'),
                     feed_dict={'module_apply_default/hub_input/Sub:0': inp})

net = cv.dnn.readNet('inference_graph.pb')
net.setInput(inp.transpose(0, 3, 1, 2))  # NHWC to NCHW
cvOut = net.forward()
print np.max(np.abs(cvOut - tfOut))
```

It gives `6.55651e-07` for me.

**Comment by wildpig22** [comment] 2018-05-24 07:00
Hi @dkurt, thanks for your prompt reply!

I have applied the transform, and on the same image the classification score is slightly different, with highest one being 0.8706076 vs 0.93370694, I assume that's because the pre-processing is removed?

Then I tried to load the transformed pb in DNN, and got this new error:

`OpenCV Error: Unspecified error (Unknown layer type Squeeze in op module_apply_default/hub_output/feature_vector/SpatialSqueeze) in cv::dnn::experimental_dnn_v3::'anonymous-namespace'::TFImporter::populateNet, file C:\projects\opencv-python\opencv\modules\dnn\src\tensorflow\tf_importer.cpp, line 1487`

Maybe because I'm using the pre-built(release 3.4.1) version, should I build the latest master source and try again?

**Comment by wildpig22** [comment] 2018-05-24 10:03
Update: now that I compiled from source and using opencv_world400.dll, and after some tweaking with blobFromImage() perameters, I got a slightly higher top score (0.942451) as compared to tensorflow (0.93370694)

To compare the scores:

`
Opencv, module_apply_default/hub_input/Sub as input
0.942451

tensorflow, module_apply_default/hub_input/Sub as input
0.870607

tensorflow, Placeholder as input
0.933706
`

I'm using the following peramaters:

`Mat inputBlob = blobFromImage(img, 2 / 255.F, Size(224, 224), Scalar(127.5, 127.5, 127.5), true, false);`

Is this to be expected? I assume that the Mul and Sub operations are to normalize the inputs values to [-1, 1], so by using 2.0/255 scaling and 127.5 subtraction we are getting the same effect?

**Comment by wildpig22** [comment] 2018-05-24 10:11
Also if I use the same transform, but using Placeholder as input, I got this new error:

`OpenCV(4.0.0-pre) Error: Assertion failed (C.type() == type, (((flags&GEMM_3_T) == 0 && C.rows == d_size.height && C.cols == d_size.width) || ((flags&GEMM_3_T) != 0 && C.rows == d_size.width && C.cols == d_size.height))) in cv::gemm, file E:\opencv-master\sources\modules\core\src\matmul.cpp, line 1588`

Did some debugging, turns out C.rows is 3 but d_size.height is 1.

I'm not sure if I'm doing the correct thing (using placeholder as input) here...

**Comment by dkurt** [comment] 2018-05-28 15:37
@wildpig22, I suggest you two ways:

1. Try changes from a PR https://github.com/opencv/opencv/pull/11607 and do not remove preprocessing subgraph:

```python
import tensorflow as tf

from tensorflow.python.tools import optimize_for_inference_lib
from tensorflow.tools.graph_transforms import TransformGraph

with tf.gfile.FastGFile('output.pb', 'rb') as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())
    graph_def = optimize_for_inference_lib.optimize_for_inference(graph_def, ['Placeholder'], ['final_result'], tf.float32.as_datatype_enum)
    graph_def = TransformGraph(graph_def, ['Placeholder'], ['final_result'], ['remove_nodes(op=PlaceholderWithDefault)', 'sort_by_execution_order'])
    with tf.gfile.FastGFile('inference_graph_preproc.pb', 'wb') as f:
        f.write(graph_def.SerializeToString())
```

```python
import numpy as np
import tensorflow as tf
import cv2 as cv

np.random.seed(324)
inp = np.random.uniform(0.0, 1.0, [224, 224, 3]).astype(np.float32)

with tf.gfile.FastGFile('inference_graph_preproc.pb', 'rb') as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())

with tf.Session() as sess:
    sess.graph.as_default()
    tf.import_graph_def(graph_def, name='')

    tfOut = sess.run(sess.graph.get_tensor_by_name('final_result:0'),
                     feed_dict={'Placeholder:0': inp.reshape(1, 224, 224, 3)})

net = cv.dnn.readNet('inference_graph_preproc.pb')
blob = cv.dnn.blobFromImage(inp, 1.0, (224, 224), (0.0, 0.0, 0.0), False, False)
net.setInput(blob)
cvOut = net.forward()
print np.max(np.abs(cvOut - tfOut))
```

2. Or use a current version of OpenCV and remove preprocessing subgraph (see https://github.com/opencv/opencv/issues/11577#issuecomment-391372527) but do preprocessing at `blobFromImage`:

```python
import numpy as np
import tensorflow as tf
import cv2 as cv

np.random.seed(324)
inp = np.random.uniform(0.0, 1.0, [224, 224, 3]).astype(np.float32)

with tf.gfile.FastGFile('inference_graph_preproc.pb', 'rb') as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())

with tf.Session() as sess:
    sess.graph.as_default()
    tf.import_graph_def(graph_def, name='')

    tfOut = sess.run(sess.graph.get_tensor_by_name('final_result:0'),
                     feed_dict={'Placeholder:0': inp.reshape(1, 224, 224, 3)})

net = cv.dnn.readNet('inference_graph_no_preproc.pb')
blob = cv.dnn.blobFromImage(inp, 2.0, (224, 224), (0.5, 0.5, 0.5), False, False)
net.setInput(blob)
cvOut = net.forward()
print np.max(np.abs(cvOut - tfOut))
```

**Closed** 2018-05-28 20:39 UTC
Labels: category: dnn

**Comment by wildpig22** [comment] 2018-05-30 08:06
@dkurt the PR works fine, now using Placeholder as input gives the same score. Thanks a lot!

And I just realized that your random generated test data has value range [0,1], while I'm using the actual image of [0,255]...thus different blobFromImage() params. Now I learned a little bit more about how blobFromImage() works, thanks again!
