### ISSUE TITLE
DNN: Adding Eltwise (-) layer support

### ISSUE THREAD

**Issue by dbrenn74** [opencv/opencv#17187] opened 2020-04-29 12:32 UTC
##### System information (version)

- OpenCV =>4.3
- Operating System / Platform => RedHat 7 64 Bit and Window 10
- Compiler => GCC 4.8.5 and Visual Studio 2015

##### Detailed description

Can Eltwise (-) support be added to the onnx importer? I've noticed that going from AlexNet Opset 6 to Opset 7 (generated from Matlab 2019) the very first layer ("data_Sub") changed from a "scale" operation to "eltwise (-)". I've seen on the support page for OpenCV that Eltwise (-) is not listed as a supported layer feature. What happens here is the the onnx importer defaults to Eltwise (+) which doesn't give us activation numbers that match our Matlab numbers

I made a change to the onnx_importer::populateNet (line 555) 
```.cpp
   constParams.blobs.push_back(blob);
```
to
```.cpp
constParams.blobs.push_back((isSub ? -1 : 1) * blob);
```
This seems to fix the issue for us and now OpenCVs activation numbers and inference match our MATLAB results. This seems like a relatively easy way to add Eltwise (-) support. However, being new to OpenCV I don't know the potential ramifications.

Sorry for the cross-post but I submitted here as well:
https://answers.opencv.org/question/229405/alexnet-opset6-to-opset7-eltwise-change

##### Steps to reproduce

Use OpenCV to run inference on an image using AlexNet Opset6
Forward network to just the "data_Sub" layer
Examine activation numbers

Use OpenCV to run inference on an image using AlexNet Opset 7
Forward network to just the "data_Sub" layer
Compare activation number between Opsets and you can see it defaults to addition

**Comment by shubhamcodez** [comment] 2020-08-04 08:23
how do I test it the changes I have made to verify eltwise layer support has been added?

**Comment by l-bat** [comment] 2020-08-20 12:36
@shubhamcodez  You need to create an `.onnx` model by [script](https://github.com/opencv/opencv_extra/blob/3.4/testdata/dnn/onnx/generate_onnx_models.py) then add a test in `test_onnx_importer.cpp`

**Comment by sl-sergei** [comment] 2020-08-26 16:32
@shubhamcodez @dbrenn74 can you please provide a reproducer (ONNX models)? I am unable to reproduce the issue with ONNX models converted from Pytorch or from official ONNX repository

**Comment by shubhamcodez** [comment] 2020-08-26 16:35
@sl-sergei what is a reproducer ? 
I tried contributing to the issue but I am new to Open Source .

**Comment by shubhamcodez** [comment] 2020-08-26 16:40
@sl-sergei same .
I am new to Open source Contribution , I just  implemented the changes suggested in the issue .

I couldn't create the test .

would be nice if you could help me on that .
Also, I removed the forked repository what do I do to get back to contributing to the issue.
I genuinely want to contribute but I don't understand most of the things happening here.

**Comment by sl-sergei** [comment] 2020-08-26 16:41
@shubhamcodez Any ONNX model described above (AlexNet from Matlab), that can highlight the issue (OpenCV doesn't work correctly with it). You added support for eltwise Sub operation, so maybe you have other models, that can't be loaded/used in OpenCV without your fix?

**Comment by dbrenn74** [comment] 2020-08-26 16:46
I have only found this issue when using MATLAB latest Opsets. Unfortunately, I'm hesitant to upload any MATLAB generated files due to potential licensing issues. However, you can register for a free trial of MATLAB and download their Neural Net packages to reproduce on your own.

**Comment by sl-sergei** [comment] 2020-08-26 16:53
@dbrenn74 I am sure that there is no potential issue in uploading .onnx files you generated yourself, especially when there is no commercial use. Also, you can just replace the weights in the network with random numbers

**Comment by dbrenn74** [comment] 2020-08-26 18:07
These onnx files are 238 MBs each. What's the recommended way to support uploads of files that large?

**Comment by dbrenn74** [comment] 2020-08-26 18:08
Don't know if this will help but here is a dump file of both onnx files compared
![AlexNetOpset6_vs_7](https://user-images.githubusercontent.com/64533889/91340181-8bd78980-e7a5-11ea-8c19-a0057c4c36f6.png)

**Comment by shubhamcodez** [comment] 2020-08-27 05:11
You can put it in Drive and share the link , if that works

**Comment by sl-sergei** [comment] 2020-08-27 08:24
@dbrenn74 Please, upload it to a private cloud drive, if possible, it will help us to apply fix and close the issue

**Comment by dbrenn74** [comment] 2020-08-27 13:18
@shubhamcodez Here is a link to download the MATLAB AlexNet Opsets 6 and 7
[https://mft.myngc.com/public/file/OECG5r6vzkODfQF-DJePmg/matlab_AlexNet_Opset6And7.zip](url)
It is password protected for now. Please provide a way for me to send you the password.

**Comment by sl-sergei** [comment] 2020-08-27 14:30
> @shubhamcodez Here is a link to download the MATLAB AlexNet Opsets 6 and 7
> [https://mft.myngc.com/public/file/OECG5r6vzkODfQF-DJePmg/matlab_AlexNet_Opset6And7.zip](url)
> It is password protected for now. Please provide a way for me to send you the password.

Please, contact me using via email sergeisl95@yandex.ru

**Comment by sl-sergei** [comment] 2020-08-28 19:47
@dbrenn74 Friendly reminder

**Comment by dbrenn74** [comment] 2020-08-31 12:12
@sl-sergei sent, did you receive?

**Closed** 2020-09-19 22:42 UTC
Labels: category: dnn, feature, good first issue, needs reproducer
