### ISSUE TITLE
BFmatcher with crossCheck=True doesn't cross check

### ISSUE THREAD

**Issue by crogrezen** [opencv/opencv#11855] opened 2018-06-29 11:56 UTC
##### System information (version)
- OpenCV => 3.4.0
- Operating System / Platform => Linux Ubuntu 16.04 X86 64 Bit
- Compiler => gcc 5.4

##### Detailed description

Running BFmatcher with crossCheck enabled doesn't really cross check. According to the documentation (https://docs.opencv.org/trunk/d3/da1/classcv_1_1BFMatcher.html#ac6418c6f87e0e12a88979ea57980c020)

> If crossCheck==true, then the knnMatch() method with k=1 will only return pairs (i,j) such that for i-th query descriptor the j-th descriptor in the matcher's collection is the nearest and vice versa, i.e. the BFMatcher will only return consistent pairs. 

I read this as, if *i* is closest to *j*, then *j* is also closest to *i*. I.e. this is symmetrical. However, this does not seem to be the case with the implemented algorithm. Also, if we switch the collections, i.e. queryDescriptors and trainDescriptors, we get different results, which is unexpected.

##### Steps to reproduce
To illustrate the first part of the issue, try the following
``` python
import numpy
import cv2

sources = numpy.array([[1, 1, 0], [1, 1, 1]], dtype=numpy.uint8)
targets = numpy.array([[1, 1, 1], [0, 0, 0]], dtype=numpy.uint8)
for si, source in enumerate(sources):
    for ti, target in enumerate(targets):
        print('%d -> %d: %d' % (si, ti, cv2.norm(source, target, cv2.NORM_HAMMING)))

bf = cv2.BFMatcher(cv2.NORM_HAMMING, crossCheck=True)
matches = bf.knnMatch(sources, targets, k=1)
print('-- crosscheck=True')
for match in matches:
    if match:
        print('%d -> %d: %f' % (match[0].queryIdx, match[0].trainIdx, match[0].distance))

bf_nocc = cv2.BFMatcher(cv2.NORM_HAMMING, crossCheck=False)
matches_nocc = bf.knnMatch(sources, targets, k=1)
print('-- crosscheck=False')
for match in matches_nocc:
    if match:
        print('%d -> %d: %f' % (match[0].queryIdx, match[0].trainIdx, match[0].distance))
```
This outputs
```
0 -> 0: 1
0 -> 1: 2
1 -> 0: 0
1 -> 1: 3
-- crossCheck=True
0 -> 1: 2.000000 <= Unexpected
1 -> 0: 0.000000
-- crossCheck=False
0 -> 0: 1.000000
1 -> 0: 0.000000
```
Here, the 0 -> 1 match when crossCheck=True is unexpected since source 0 is closer to target 0.

Also, if we switch the sources and targets arrays, we get
```
0 -> 0: 1
0 -> 1: 0
1 -> 0: 2
1 -> 1: 3
-- crossCheck=True
0 -> 1: 0.000000
-- crossCheck=False
0 -> 1: 0.000000
1 -> 0: 2.000000
```
Which is correct for crossCheck=True (as well as for crossCheck=False which I don't expect to be symmetrical).

Unless I have misunderstood how cross check is supposed to work, this appears to me to be an issue with the current implementation (there has been no updates on this algorithm since 3.4.0 as far as I can see)

For C++ sample code, see http://answers.opencv.org/question/194661/bfmatcher-with-crosscheck-doesnt-crosscheck/

**Comment by headdab** [comment] 2018-09-10 19:02
Looks like I just entered a bug #12484 which is a duplicate of this one.

**Comment by alexevans** [comment] 2018-10-31 20:08
So, these changes seem to work on the C++ and Python test code, but they fail on 3 of the perf tests. This appears to be because batchdistance with crosscheck == true is now flagging non-ideal pairs not previously found, per this issue. These three tests have an expected_min on ndix as 0, but since some non-ideal pairs were detected, acutal_min is -1 and the tests fail. I regenerated the test data locally following: [](https://github.com/opencv/opencv/wiki/HowToUsePerfTests), should I also submit a PR to opencv_extra with the new test data?

**Comment by LaurentBerger** [comment] 2018-10-31 21:15
@alexevans  may be you should write this comment in your PR send to @ alalek

**Comment by alalek** [comment] 2018-10-31 22:28
@alexevans Right! Please create PR into opencv_extra based on 3.4 branch: from the source branch with the same name ("Issue11855" from #12908)

**Closed** 2018-11-16 21:03 UTC
Labels: bug, category: features2d, category: ml
