### ISSUE TITLE
mousewheel not working 4.5.4

### ISSUE THREAD

**Issue by msproul** [opencv/opencv#22043] opened 2022-05-26 19:32 UTC
##### System information (version)

- OpenCV => 4.5.4
- Operating System / Platform => Linux 22.04 LTS 64 Bit
- Compiler => gcc

##### Detailed description
Since at least version 3.3.1, the EVENT_MOUSEWHEEL and EVENT_MOUSEHWHEEL have worked in linux despite the fact the the .h file says they are implemented in Windows Only.

With 4.5.4 on a new machine, the MOUSEWHEEL events do not work.

I went back to 4.5.1 and they work fine.

**Comment by alalek** [comment] 2022-05-26 19:51
Probably duplicate of #21853

**Closed** 2023-05-03 07:45 UTC
Labels: duplicate
