### ISSUE TITLE
opencv 4.5.1 minAreaRect

### ISSUE THREAD

**Issue by buptlihang** [opencv/opencv#19749] opened 2021-03-19 02:57 UTC
```
>>> cv2.__version__
'4.5.1'
>>> cv2.minAreaRect(np.array([[1,1],[1,10],[10,10],[10,1]]))
((5.5, 5.5), (9.0, 9.0), 90.0)
```

```
>>> cv2.__version__
'4.2.0'
>>> cv2.minAreaRect(np.array([[1,1],[1,10],[10,10],[10,1]]))
((5.5, 5.5), (9.0, 9.0), -90.0)
```

Shouldn't the angle information returned be [-90,0)?   4.5.1 is different from 4.2.0

**Comment by theroyalpekka** [comment] 2021-03-23 18:47
According to the documentation of OpenCV 4.5.1, Parameter `angle` of Constructor `RotatedRect()` is described as : `The rotation angle in a clockwise direction.` Which I think must be rotation angle in a anticlockwise direction from the X axes till the arc encounter a side of Rect.

**Comment by destinyzs** [comment] 2021-04-27 03:18
I met the same question.
```
>>> a = np.random.rand(4,2)*100
>>> cv2.minAreaRect(a.astype(np.int32))
((58.48832702636719, 38.68677520751953), (45.34313201904297, 49.8421630859375), -41.423667907714844)
>>> cv2.__version__
'4.2.0'
```

```
>>> a = np.random.rand(4,2)*100
>>> cv2.minAreaRect(a.astype(np.int32))
((51.9761962890625, 65.72982025146484), (65.569091796875, 75.58438110351562), 72.2842025756836)
>>> cv2.__version__
'4.5.1'
```

This caused the data processing code i wrote before to not work.

**Comment by AndrewG10i** [comment] 2021-04-27 08:40
Upgraded from 4.4.0 to 4.5.1 and got the similar issue with `minAreaRect()`.
In few words: the same code for the same image returns `-63` on the v4.4.0 vs. `45` on the v4.5.1.
Any ideas whether this is feature or bug?
Thanks!

**Comment by zhongzisha** [comment] 2021-04-30 00:35
Same issue. Looking forward to your advice.

**Comment by alalek** [comment] 2021-04-30 08:00
There are two types of issues:

- 90/180 degree rotation difference can't be fixed due to unspecified normalization rules of `RotatedRect`. Won't fix that part because there is no gold definition for such normalization. Update caller code instead. See here for details: #19472

- the other issues are related to bug in minAreaRect() itself. Please capture input and add minimal complete reproducer to the related issue here: #19769

---

Closing this issue as duplicate.

**Closed by alalek** 2021-04-30 08:00 UTC
Labels: duplicate, question (invalid tracker)

**Comment by Petros626** [comment] 2024-08-28 11:32
@alvoron I have now read through the topics that concern the problem with the `cv2.minAreaRect()` function. Then the problem has been solved in this pull request: https://github.com/opencv/opencv/pull/20533#issue-966290417 or not?

Because this repo here (https://github.com/ultralytics/ultralytics/issues/15771) is using the function and has problems to get the correct angle in their method: https://github.com/ultralytics/ultralytics/blob/4fe046e2d59c0377fcc4ab01634a2e71aa02069b/ultralytics/utils/ops.py#L529

Can you clarify me?
