### ISSUE TITLE
Linker error while trying to implement SURF_CUDA matcher.

### ISSUE THREAD

**Issue by sankethrit2013** [opencv/opencv#7107] opened 2016-08-12 17:30 UTC
##### System information (version)

- OpenCV => 3.1.0
- Operating System / Platform => Windows 10 / x64
- Compiler => Visual Studio 2013

##### Detailed description

I wrote my code based on the example given on opencv github page for SURF matcher using CUDA.

When I try to build, i get the following error:
```
1>Testing.obj : error LNK2019: unresolved external symbol "public: static struct cv::Ptr<class cv::cuda::DescriptorMatcher> __cdecl cv::cuda::DescriptorMatcher::createBFMatcher(int)" (?createBFMatcher@DescriptorMatcher@cuda@cv@@SA?AU?$Ptr@VDescriptorMatcher@cuda@cv@@@3@H@Z) referenced in function main
1>Testing.obj : error LNK2019: unresolved external symbol "public: __cdecl cv::cuda::SURF_CUDA::SURF_CUDA(void)" (??0SURF_CUDA@cuda@cv@@QEAA@XZ) referenced in function main
1>Testing.obj : error LNK2019: unresolved external symbol "public: int __cdecl cv::cuda::SURF_CUDA::defaultNorm(void)const " (?defaultNorm@SURF_CUDA@cuda@cv@@QEBAHXZ) referenced in function main
1>Testing.obj : error LNK2019: unresolved external symbol "public: void __cdecl cv::cuda::SURF_CUDA::downloadKeypoints(class cv::cuda::GpuMat const &,class std::vector<class cv::KeyPoint,class std::allocator<class cv::KeyPoint> > &)" (?downloadKeypoints@SURF_CUDA@cuda@cv@@QEAAXAEBVGpuMat@23@AEAV?$vector@VKeyPoint@cv@@V?$allocator@VKeyPoint@cv@@@std@@@std@@@Z) referenced in function main
1>Testing.obj : error LNK2019: unresolved external symbol "public: void __cdecl cv::cuda::SURF_CUDA::downloadDescriptors(class cv::cuda::GpuMat const &,class std::vector<float,class std::allocator<float> > &)" (?downloadDescriptors@SURF_CUDA@cuda@cv@@QEAAXAEBVGpuMat@23@AEAV?$vector@MV?$allocator@M@std@@@std@@@Z) referenced in function main
1>Testing.obj : error LNK2019: unresolved external symbol "public: void __cdecl cv::cuda::SURF_CUDA::operator()(class cv::cuda::GpuMat const &,class cv::cuda::GpuMat const &,class cv::cuda::GpuMat &,class cv::cuda::GpuMat &,bool)" (??RSURF_CUDA@cuda@cv@@QEAAXAEBVGpuMat@12@0AEAV312@1_N@Z) referenced in function main
1><computer_dir>\TestCode\x64\Debug\TestCode.exe : fatal error LNK1120: 6 unresolved externals
```

All libraries seem to be linked properly and I am not getting any error while writing the code. 

It would be great if anyone could say what the error is. Thanks!

**Comment by alalek** [comment] 2016-08-12 18:42
Full linker command line is required (list of all libraries)

**Comment by sankethrit2013** [comment] 2016-08-12 18:45
The only library that is in the linker command line is opencv_world310.lib. I do not have anyother file in the lib folder.

**Comment by alalek** [comment] 2016-08-12 18:58
`cv::cuda::SURF_CUDA` is placed in opencv_contrib:
https://github.com/opencv/opencv_contrib/blob/master/modules/xfeatures2d/src/surf.cuda.cpp

So opencv_world library is not enough.
How did you get and build OpenCV?

**Comment by sankethrit2013** [comment] 2016-08-12 19:04
I cloned opencv source files from github. Then used cmake to generate the files build files. The WITH_CUDA option was already checked. I checked the BUILD_opencv_world option and then built. Lastly i built the debug and release in visual studio. Somehow my files do not match the prebuilt binaries. So I copied the xfeatures2d folder form the prebuilt binaries and pasted in include folder.

I have followed most of the instructions I found online.

**Comment by alalek** [comment] 2016-08-12 20:05
> Somehow my files do not match the prebuilt binaries. 

I have no idea that you mean here.

Do you use CMake to build your application?

Could you please comment all used OpenCV code in your app (except include of opencv2/core.hpp) and post here output of this statement:
```
printf("%s\n", cv::getBuildInformation().c_str());
```

**Comment by sankethrit2013** [comment] 2016-08-12 20:52
What I meant was, my files in the include directory after building, do not match the files in the include directory of built files available online.

`#include "stdafx.h"
#include <opencv2/opencv_modules.hpp>
#include "opencv2/highgui/highgui.hpp"
#include "opencv2/imgproc/imgproc.hpp"
#include <opencv2/cudaimgproc.hpp>
#include <opencv2/cudafeatures2d.hpp>
#include <opencv2/cudaobjdetect.hpp>
#include <opencv2/xfeatures2d/cuda.hpp>
#include <iostream>

int main()
{
	cv::VideoCapture video("eyeClip2VeryShort.mov");
	int counter = 0;

	for (;;)
	{
		// Intializing the matrices
		cv::Mat prevFrame, nextFrame, tempVar1, tempVar2;
		
		// Getting frames
		video.set(CV_CAP_PROP_POS_FRAMES, counter);
		video >> prevFrame;
		tempVar1 = prevFrame.clone();
		counter++;

		video.set(CV_CAP_PROP_POS_MSEC, counter);
		video >> nextFrame;
		tempVar2 = nextFrame.clone();
		counter++;

		// Initializing gpu matrices
		cv::cuda::GpuMat gpuFrame1(tempVar1), gpuFrame2(tempVar2);
		cv::cuda::GpuMat keyGPU1, keyGPU2;
		cv::cuda::GpuMat descriptorGPUFrame1, descriptorGPUFrame2;
		
		// SURF properties
		double minHessian = 100.0;

		// Initializing the descriptor
		cv::cuda::SURF_CUDA surf;

		surf(gpuFrame1, cv::cuda::GpuMat(), keyGPU1, descriptorGPUFrame1);
		surf(gpuFrame2, cv::cuda::GpuMat(), keyGPU2, descriptorGPUFrame2);

		// Creating the matcher
		cv::Ptr<cv::cuda::DescriptorMatcher> gpuMatcher = cv::cuda::DescriptorMatcher::createBFMatcher(surf.defaultNorm());
		std::vector<cv::DMatch> matches;
		gpuMatcher->match(descriptorGPUFrame1, descriptorGPUFrame2, matches);

		// Getting keypoints to CPU from GPU
		std::vector<cv::KeyPoint> keyCPU1, keyCPU2;
		std::vector<float> descriptorCPUFrame1, descriptorCPUFrame2;

		surf.downloadKeypoints(keyGPU1, keyCPU1);
		surf.downloadKeypoints(keyGPU2, keyCPU2);
		surf.downloadDescriptors(descriptorGPUFrame1, descriptorCPUFrame1);
		surf.downloadDescriptors(descriptorGPUFrame2, descriptorCPUFrame2);

		// Displaying results
		cv::Mat img_matches;
		cv::drawMatches(cv::Mat(gpuFrame1), keyCPU1, cv::Mat(gpuFrame1), keyCPU2, matches, img_matches);

		cv::namedWindow("SURF", 0);
		cv::imshow("SURF", img_matches);
		cv::waitKey(0);
	}
	getchar();
	return 0;
}
`

Most of it is from the example given in the repository.

Output of the statement:


  General configuration for OpenCV 3.1.0 =====================================
  Version control:               3.1.0

  Platform:
    Host:                        Windows 6.1 AMD64
    CMake:                       3.3.1
    CMake generator:             Visual Studio 12 2013 Win64
    CMake build tool:            C:/Program Files (x86)/MSBuild/12.0/bin/MSBuild.exe
    MSVC:                        1800

  C/C++:
    Built as dynamic libs?:      YES
    C++ Compiler:                C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/x86_amd64/cl.exe  (ver 18.0.21005.1)
    C++ flags (Release):         /DWIN32 /D_WINDOWS /W4 /GR /EHa  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /wd4251 /wd4324 /wd4275 /wd4589 /MP4  /MD /O2 /Ob2 /D NDEBUG  /Zi
    C++ flags (Debug):           /DWIN32 /D_WINDOWS /W4 /GR /EHa  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /wd4251 /wd4324 /wd4275 /wd4589 /MP4  /D_DEBUG /MDd /Zi /Ob0 /Od /RTC1
    C Compiler:                  C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/x86_amd64/cl.exe
    C flags (Release):           /DWIN32 /D_WINDOWS /W3  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi    /MP4  /MD /O2 /Ob2 /D NDEBUG  /Zi
    C flags (Debug):             /DWIN32 /D_WINDOWS /W3  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi    /MP4  /D_DEBUG /MDd /Zi /Ob0 /Od /RTC1
    Linker flags (Release):      /machine:x64  /INCREMENTAL:NO  /debug
    Linker flags (Debug):        /machine:x64  /debug /INCREMENTAL
    Precompiled headers:         YES
    Extra dependencies:
    3rdparty dependencies:

  OpenCV modules:
    To be built:                 core flann imgproc ml photo video imgcodecs shape videoio highgui objdetect superres features2d calib3d stitching videostab world
    Disabled:                    -
    Disabled by dependency:      -
    Unavailable:                 cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev java python2 ts viz

  Windows RT support:            NO

  GUI:
    QT:                          NO
    Win32 UI:                    YES
    OpenGL support:              NO
    VTK support:                 NO

  Media I/O:
    ZLib:                        build (ver 1.2.8)
    JPEG:                        build (ver 90)
    WEBP:                        build (ver 0.3.1)
    PNG:                         build (ver 1.6.19)
    TIFF:                        build (ver 42 - 4.0.2)
    JPEG 2000:                   build (ver 1.900.1)
    OpenEXR:                     build (ver 1.7.1)
    GDAL:                        NO

  Video I/O:
    Video for Windows:           YES
    DC1394 1.x:                  NO
    DC1394 2.x:                  NO
    FFMPEG:                      YES (prebuilt binaries)
      codec:                     YES (ver 56.41.100)
      format:                    YES (ver 56.36.101)
      util:                      YES (ver 54.27.100)
      swscale:                   YES (ver 3.1.101)
      resample:                  NO
      gentoo-style:              YES
    GStreamer:                   NO
    OpenNI:                      NO
    OpenNI PrimeSensor Modules:  NO
    OpenNI2:                     NO
    PvAPI:                       NO
    GigEVisionSDK:               NO
    DirectShow:                  YES
    Media Foundation:            NO
    XIMEA:                       NO
    Intel PerC:                  NO

  Parallel framework:            Concurrency

  Other third-party libraries:
    Use IPP:                     9.0.1 [9.0.1]
         at:                     C:/builds/master_PackSlave-win64-vc12-shared/opencv/3rdparty/ippicv/unpack/ippicv_win
    Use IPP Async:               NO
    Use Eigen:                   NO
    Use Cuda:                    NO
    Use OpenCL:                  YES
    Use custom HAL:              NO

  OpenCL:
    Version:                     dynamic
    Include path:                C:/builds/master_PackSlave-win64-vc12-shared/opencv/3rdparty/include/opencl/1.2 C:/Program Files (x86)/AMD/clAmdFft/include C:/Program Files (x86)/AMD/clAmdBlas/include
    Use AMDFFT:                  YES
    Use AMDBLAS:                 YES

  Python 2:
    Interpreter:                 c:/python27-x64/python.exe (ver 2.7.5)

  Python 3:
    Interpreter:                 NO

  Python (for build):            c:/python27-x64/python.exe

  Java:
    ant:                         C:/Program Files (x86)/apache-ant/bin/ant.bat (ver 1.9.2)
    JNI:                         C:/Program Files/Java/jdk1.6.0_45/include C:/Program Files/Java/jdk1.6.0_45/include/win32 C:/Program Files/Java/jdk1.6.0_45/include
    Java wrappers:               NO
    Java tests:                  NO

  Matlab:                        Matlab not found or implicitly disabled

  Tests and samples:
    Tests:                       NO
    Performance tests:           NO
    C/C++ Examples:              NO

  Install path:                  C:/builds/master_PackSlave-win64-vc12-shared/build/install

  cvconfig.h is in:              C:/builds/master_PackSlave-win64-vc12-shared/build/opencv_build
-----------------------------------------------------------------

**Comment by alalek** [comment] 2016-08-12 21:31
From here:
```
  OpenCV modules:
    To be built:                 core flann imgproc ml photo video imgcodecs shape videoio highgui objdetect superres features2d calib3d stitching videostab world
    Disabled:                    -
    Disabled by dependency:      -
    Unavailable:                 cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev java python2 ts viz
```

You can see that there is no enabled CUDA or opencv_contrib (xfeatures2d) modules.


> C:/builds/master_PackSlave-win64-vc12-shared

Seems it is officially distributed binaries. There are only "main" modules and without CUDA. These binaries can't run mentioned sample which uses CUDA algorithms. Also they doesn't work with "other" includes.
It is not your custom OpenCV build. Also you should not mixup headers and libraries from different builds with different configurations.


I'm closing this because this is not a bug report.
Please request for help on Q/A user forum: http://answers.opencv.org

**Closed by alalek** 2016-08-12 21:31 UTC
Labels: invalid

**Comment by alalek** [comment] 2016-08-12 21:54
> Built as dynamic libs?:      YES

Also check your PATH environment variable. It is possible that wrong opencv_world.dll is loaded.

Or you can use static libraries to prevent DLL mix (BUILD_SHARED_LIBS=OFF CMake option).
