### ISSUE TITLE
Link to the ippicv failed.

### ISSUE THREAD

**Issue by I-n-v-i-n-c-i-b-l-e** [opencv/opencv#10457] opened 2017-12-28 14:41 UTC
##### System information (version)

- OpenCV => `3.4`
- Operating System / Platform => `Android x86 and Android x86_64`
- Compiler => `Android NDK GCC`

##### Detailed description

Link ipp library error.
```
Error:error: opencv/sdk/native/3rdparty/libs/x86/libippicv.a(jmp_icvippsSortRadixIndexAscend_32f_as.s.o): relocation R_386_GOTOFF against preemptible symbol icv_ippJumpIndexForMergedLibs cannot be used when making a shared object
Error:error: opencv/sdk/native/3rdparty/libs/x86/libippicv.a(jmp_icvippiNormDiff_L2_32f_C1MR_as.s.o): relocation R_386_GOTOFF against preemptible symbol icv_ippJumpIndexForMergedLibs cannot be used when making a shared object
Error:error: opencv/sdk/native/3rdparty/libs/x86/libippicv.a(jmp_icvippiSqrDistanceNormGetBufferSize_as.s.o): relocation R_386_GOTOFF against preemptible symbol icv_ippJumpIndexForMergedLibs cannot be used when making a shared object
More....
```

##### Steps to reproduce

Downlod [ OpenCV for Android SDK 3.4. 0 ](https://sourceforge.net/projects/opencvlibrary/files/opencv-android/3.4.0/opencv-3.4.0-android-sdk.zip/download)

Extract it to your project, and write cmake:
```cmake
cmake_minimum_required(VERSION 3.6)

set ( OpenCV_DIR "../opencv/sdk/native/jni")
find_package ( OpenCV REQUIRED )

include_directories ( ${OpenCV_INCLUDE_DIRS} )

add_library( image_analyze SHARED

             # Provides a relative path to your source file(s).
             src/main/cpp/image_analyze.cpp
             src/main/cpp/pattern_recognition.cpp
             src/main/cpp/pretreatment.cpp )

target_link_libraries( image_analyze ${OpenCV_LIBS} )
```
Then build, when link to the ippicv wiil be failed!

**Comment by alalek** [comment] 2017-12-28 14:53
duplicate of #10229

**Closed by alalek** 2017-12-28 14:53 UTC
Labels: category: android, category: build/install, duplicate
