### ISSUE TITLE
Problems with correctly reading video frames

### ISSUE THREAD

**Issue by trsh** [opencv/opencv#17257] opened 2020-05-10 16:48 UTC
- OpenCV => 4.2
- Operating System / Platform => Windows 64 Bit
- opencv-contrib-python 4.2.0.34
- opencv-python         4.2.0.34

##### Detailed description

Video is 06.933 sec long with 25 FPS, what makes 173 frames (observed in video player)

However :

```
cap = cv2.VideoCapture(video_path)
cap.get(cv2.CAP_PROP_FRAME_COUNT)
```
gives 172 frames. And while counting manual:
```
while(cap.isOpened()):
        ret, frame = cap.read()
        if ret == True:
            frame_index += 1
        else: 
            break
```

it can't go any further than 168 frame

Sadly I can't share the video file

**Comment by trsh** [comment] 2020-05-11 19:37
@alalek ??

**Comment by alalek** [comment] 2020-05-11 20:01
> Sadly I can't share the video file

Our help can't be efficient here.

Try:
- env: OPENCV_VIDEOIO_DEBUG=1
- env: OPENCV_FFMPEG_DEBUG=1
- extract frames from your video using FFmpeg and compare with OpenCV output (you may read extracted frames images through `imread()`): https://stackoverflow.com/questions/10957412/fastest-way-to-extract-frames-using-ffmpeg
- dump frames information and analyse them: https://stackoverflow.com/questions/27529930/get-video-frames-information-with-ffmpeg

---

We don't help with remote investigation of problems which we are not able to reproduce on our side (because it is very time consuming), but we can take a look on **the clear reason of the problem** and suggest some fix/workaround.

**Comment by trsh** [comment] 2020-05-12 13:29
@alalek : I talked to my colleagues again and we decided to upload the video after all
[video.zip](https://github.com/opencv/opencv/files/4615838/video.zip)

I hope this will bring some clarity for the problem

**Comment by trsh** [comment] 2020-05-14 18:51
@alalek 

`ffmpeg -i LUCKY_BRUNETTE.mp4 -qscale:v 1 filename_%06d.jpg` extracted 172 frames, what is 1 frame incorrect, but better then openCV.

**Comment by mshabunin** [comment] 2020-05-14 19:07
Duplicate of #15352

**Comment by alalek** [comment] 2020-05-29 19:46
Correct frames number is 172:
- frames extraction through `ffmpeg`
- `cap.get(cv2.CAP_PROP_FRAME_COUNT)` returns 172 too

Video stream is 1:

```
  Duration: 00:00:06.93, start: 0.000000, bitrate: 26676 kb/s
    Stream #0:0(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 317 kb/s (default)
    Metadata:
      creation_time   : 2020-04-27T07:51:47.000000Z
      handler_name    : #Mainconcept MP4 Sound Media Handler
    Stream #0:1(eng): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 1920x1080, 26491 kb/s, 25 fps, 25 tbr, 25k tbn, 50 tbc (default)
    Metadata:
      creation_time   : 2020-04-27T07:51:47.000000Z
      handler_name    : ?Mainconcept Video Media Handler
      encoder         : AVC Coding
```

OpenCV stops decoding after 168 frame.
Problem is that frames are not flushed from the decoder properly after the stream EOF (passed stream index 0 instead of 1).

PR with fix will be added soon.

**Closed** 2020-06-04 20:47 UTC
Labels: bug, category: videoio
