### ISSUE TITLE
OpenCV 3.1 MSER not thread-safe

### ISSUE THREAD

**Issue by light64** [opencv/opencv#7639] opened 2016-11-10 09:36 UTC
- OpenCV => 3.1.0-dev
- Operating System / Platform => Ubuntu 14.04 LTS 64-bit
- Compiler => gcc 4.8.4

It seems the Mser_Impl implementation of OpenCV 3.1.0-dev is not thread-safe for some reason.
When the Mser detection is started with OMP parallelization with 4-8 threads the program is stopped with a Segmentation fault error.
Each OMP thread holds its own instance of image, contours and bboxes, e.g.:

```
cv::Ptr<cv::MSER> mserD = cv::MSER::create(delta, ..., edgeBlurSize);

#pragma omp parallel for num_threads(8)
for (size_t image_id = 0; image_id < image_list.size(); image_id++) {
	
	cv::Mat image = cv::imread(image_list[image_id], cv::IMREAD_GRAYSCALE);

	std::vector<std::vector< cv::Point> > cur_contours;
	std::vector<cv::Rect> bboxes;

	mserD->detectRegions(image, cur_contours, bboxes);

	#pragma omp critical
	{
		// merge results
	}
}
```
Before I tried the last version of the OpenCV 2.4 branch and the Mser implementation using mserD->detect(...) worked perfectly with multithreading.

As segmentation faults are quite difficult to track down with multithreading I used valgrind.
Attached is the log file with some excerpts of the valgrind output.

It fails to read and write in updateTree, growHistory, checkAndCapture, etc. In all cases CompHistory is involved. In OpenCV 2.4 CompHistory does not exist in that form. I think this problem could only be solved by code analysis, as debugging with multithreading is irreproducible.

[log.txt](https://github.com/opencv/opencv/files/582951/log.txt)

**Comment by alalek** [comment] 2016-11-10 10:02
Almost all OpenCV algorithms are not thread-safe by design (for performance reasons and code complexity).

**Comment by light64** [comment] 2016-11-10 10:14
So far I have used various OpenCV implementations like BRISK, ORB and also MSER in the branch 2.4 and never had a problem with multithreading. The results also seemed quite reasonable and reproducible.
When I have a 40-CPU machine I would love to make use of all cores, by heading a different image for each thread over to the feature-detection or -description. When it is not thread-safe I can only process one image at a time.

**Comment by alalek** [comment] 2016-11-10 12:01
In general it is not very hard to add required synchronization primitives.
In your case try to move MSER algorithm creation into `for` body. It is not very efficient approach (thread-local initialization is more optimal via `private/firstprivate` OpenMP directives).

**Comment by light64** [comment] 2016-11-10 12:09
Letting each thread individually initialize MSER is what I also thought of already. Though our framework usually creates the appropriate Feature-Detector and -Descriptor objects already beforehand for design reasons. For testing I can move the creation right before detectRegions and see whether the Segfault also appears in that case.

**Comment by light64** [comment] 2016-11-10 13:56
Letting each thread create its own MSER object fails with the same result.
Now I'm really confused. Each thread has its own MSER, image, vector<vector<Point>> contours, and vector<Rect> bboxes.
I don't see another possibility for a race condition without shared variables.
Maybe that is a general issue of OpenCV 3, and other detectors also fail for multithreading, as MSER is now the first one I tried after upgrading to OpenCV 3.

**Comment by alalek** [comment] 2016-12-01 14:44
It is not a [bug](https://github.com/opencv/opencv/issues/7639#issuecomment-259649305).
Generic thread-safe implementation will be ineffective.

**Closed by alalek** 2016-12-01 14:44 UTC
Labels: RFC

**Comment by krayni** [comment] 2017-11-07 09:44
Dear all,
I try to test the text recognition in "multi-threading" (using parallel_for_) on a set of frames but I noticed that there is not speed ( independently on the number of thread).

My function is like

void text_recon(Mat &frameI)
{
//some code using  MSER and Morphological Text Extraction;
}
parallel_for_ (CV::range(0,listframes.size()), paralleltext(listframes));
