### ISSUE TITLE
Error readNetFromTensorflow with Faster rcnn network (opencv 3.4.3)

### ISSUE THREAD

**Issue by TBondat** [opencv/opencv#12702] opened 2018-09-30 08:31 UTC
##### System information (version)

- OpenCV => 3.4.3.18
- Operating System / Platform => Windows 7

##### Detailed description
When i try to load my custom faster rcnn network (faster_rcnn_resnet101_coco_2018_01_28, with 2 classes), i get the error message:
cv2.error: OpenCV(3.4.3) C:\projects\opencv-python\opencv\modules\dnn\src\tensorflow\tf_importer.cpp:533: error: (-2:Unspecified error) Input [detection_out/clip_by_value] for node [CropAndResize] not found in function 'cv::dnn::experimental_dnn_34_v7::`anonymous-namespace'::TFImporter::getConstBlob'

I have generated the pbtxt from tf_text_graph_faster_rcnn.py 3.4.3
I get this error if i try to use cv.dnn.readNetFromTensorflow  or also object_detection.py (3.4.3)
I saw some threads with similar errors but with previous releases, not opencv 3.4.3.

Any idea how to fix this?

**Comment by TBondat** [comment] 2018-10-18 06:32
cv.__version__ gives me 3.4.3 also.
a custom model faster rcnn inception was working with the same methodology.

i tested the default faster_rcnn_resnet101_coco_2018_01_28, the readNetFromTensorflow didnt crashed. i dont have prediction after, but it may be because of the parameters. 
So the problem could be from the pbtxt generation with tf_text_graph_faster_rcnn.py then, for this specific model?

**Comment by dkurt** [comment] 2018-10-18 06:36
@TBondat, Could you please provide a reference to generated `.pb` graph? It could be even randomly initialized one but for which we can reproduce the problem. Thank you!

**Comment by TBondat** [comment] 2018-10-23 06:00
i didn't succeed to upload the pb file on my github with Git LFS, so i put it on an other storage website, here: 
[https://www.partage-fichiers.com/upload/k1up6gfr](url)

and the corresponding .pbtxt generated from tf_text_graph_faster_rcnn.py:
[rcnnresnet.zip](https://github.com/opencv/opencv/files/2504673/rcnnresnet.zip)

thanks for the support!

**Comment by dkurt** [comment] 2018-10-23 06:11
@TBondat, [GitHub's Markdown](https://guides.github.com/features/mastering-markdown/) can help you format it:
```
http://github.com - automatic!
[GitHub](http://github.com)
```

**Comment by TBondat** [comment] 2018-10-23 06:32
got it, i switched the 2 strings... post is edited.

**Comment by dkurt** [comment] 2018-10-24 06:05
@TBondat, cannot reproduce your problem with a `.pbtxt` file generated by myself (please note that it's better to use `tf_text_graph_faster_rcnn.py` from the same version as your library).

```
python tf_text_graph_faster_rcnn.py --input rcnnresnet.pb --config pipeline.config --output graph.pbtxt
```
where `pipeline.config` is a file from `faster_rcnn_resnet101_coco_2018_01_28` package but with `num_classes: 2`
```python
import numpy as np
import cv2 as cv

inp = np.random.standard_normal([1, 3, 600, 800]).astype(np.float32)
net = cv.dnn.readNet('rcnnresnet.pb', 'graph.pbtxt')
net.setInput(inp)
out = net.forward()
print(out.shape)
```

But I confirm that your `rcnnresnet.pbtxt` gives me the same error. So the solution is to use OpenCV of the same version of your `.pbtxt` file or regenerate it.

**Comment by TBondat** [comment] 2018-10-25 08:13
ok, i will re-check the file i used for the conversion. That's strange, i did check the version i took to fit my opencv, but i will still redo the process. Could you attached the .pbtxt file you generated? so i have a comparison when i will retry?
thanks!

**Comment by dkurt** [comment] 2018-10-25 09:39
Sure, [graph.pbtxt.zip](https://github.com/opencv/opencv/files/2514245/graph.pbtxt.zip).

**Comment by dkurt** [comment] 2018-10-29 07:17
@TBondat, can we close this issue?

**Closed** 2018-10-29 12:14 UTC
Labels: category: dnn
