### ISSUE TITLE
Failed to infer shapes for FullyConnected layer (InceptionResnetV1/Bottleneck/MatMul) with error: New shapes [1,0] make Kernels(), Channels(0), Output depth(512), Groups(1) not matching weights size: 0 vs 917504

### ISSUE THREAD

**Issue by jaiatncson7** [opencv/opencv#14497] opened 2019-05-07 08:32 UTC
hi,
i have used Openvino MO to optimize facenet model to xml and bin file and load in my application, 
embedder = cv2.dnn.readNet(‘20180402-114759.xml’, ‘20180402-114759.bin’)
it gives the below error
terminate called after throwing an instance of ‘InferenceEngine::details::InferenceEngineException’
what(): Failed to infer shapes for FullyConnected layer (InceptionResnetV1/Bottleneck/MatMul) with error: New shapes [1,0] make Kernels(), Channels(0), Output depth(512), Groups(1) not matching weights size: 0 vs 917504
Aborted (core dumped)

Any idea how to fix this issue?

My system env:
Ubuntu 18.04
Installed Openvino toolkit to use NCS2 stick
Python & OpenCV:
$ python
Python 3.6.7 (default, Oct 22 2018, 11:32:17)
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

import cv2
cv2.version
'4.1.0-openvino'

**Comment by alalek** [comment] 2019-05-07 08:45
How to reproduce it?
Add step-by-step instruction:
- where did you get model?
- how it is converted? (parameters)

> NCS2 stick

Try with CPU plugin at first.

If it works with CPU only, then report problem here: https://github.com/opencv/dldt/issues

**Comment by jaiatncson7** [comment] 2019-05-07 08:55
I am trying to write an application to do face recognition with Intel NCS2 stick on Intel i7 PC. I have also installed Openvino toolkit to support for NCS2. So, to do face recognition, i have converted tensorflow facenet(https://github.com/davidsandberg/facenet) models to .bin and .xml using openvino model optimizer script as,
$ python ./mo_tf.py --input_model 20180402-114759.pb --freeze_placeholder_with_value "phase_train->False" --data-type FP16
And here is my test application.
----
import cv2
net = cv2.dnn.readNet('20180402-114759.bin', 20180402-114759.xml')
net.setPreferableTarget(cv2.dnn.DNN_TARGET_MYRIAD)
..
..
detections = net.forward()

terminate called after throwing an instance of 'InferenceEngine::details::InferenceEngineException'
  what():  Failed to infer shapes for FullyConnected layer (InceptionResnetV1/Bottleneck/MatMul) with error: New shapes [1,0] make Kernels(), Channels(0), Output depth(512), Groups(1) not matching weights size: 0 vs 917504
Aborted (core dumped)

**Comment by jaiatncson7** [comment] 2019-05-07 08:55
both with CPU and MYRIAD, i am getting this error.

**Comment by dkurt** [comment] 2019-05-14 07:37
@jaiatncson7, cannot reproduce the problem. Please try to run the following script:

```python
import cv2 as cv
import numpy as np

print(cv.__file__)

net = cv.dnn.readNet('20180402-114759.bin', '20180402-114759.xml')
net.setPreferableTarget(cv.dnn.DNN_TARGET_MYRIAD)

inp = np.random.standard_normal([1, 3, 160, 160]).astype(np.float32)

net.setInput(inp)
out = net.forward()
print(out.shape)
```

My output:
```
/opt/intel/openvino_2019.1.094/python/python3.5/cv2.cpython-35m-x86_64-linux-gnu.so
(1, 512)
```

**Comment by jaiatncson7** [comment] 2019-05-15 06:48
Hi @dkurt yes your script is working fine for me also and here is the output,
/home/jaiganesh/intel/openvino_2019.1.133/python/python3.6/cv2.cpython-36m-x86_64-linux-gnu.so
(1, 512)

So, i think the way i extract the blob may be wrong? i used cv2.dnn.blobFromImage() function to gett  the blob and then input to the "net.setInput()" function. Is this something wrong?

**Comment by jaiatncson7** [comment] 2019-05-15 07:25
My code is,
embedder = cv2.dnn.readNet('20180402-114759.bin', '20180402-114759.xml')
embedder.setPreferableTarget(cv2.dnn.DNN_TARGET_MYRIAD)

faceBlob = cv2.dnn.blobFromImage(face, 1.0 / 255,
			(96, 96), (0, 0, 0), swapRB=True, crop=False)
embedder.setInput(faceBlob)
vec = embedder.forward()

Error while run:
terminate called after throwing an instance of 'InferenceEngine::details::InferenceEngineException'
  what():  Failed to infer shapes for FullyConnected layer (InceptionResnetV1/Bottleneck/MatMul) with error: New shapes [1,0] make Kernels(), Channels(0), Output depth(512), Groups(1) not matching weights size: 0 vs 917504
Aborted (core dumped)

**Comment by dkurt** [comment] 2019-05-16 14:09
@jaiatncson7, you model accepts 1x3x160x160 inputs, not 1x3x96x96 ones.

**Comment by dkurt** [comment] 2019-05-18 09:25
Let me close this issue.

**Closed by dkurt** 2019-05-18 09:25 UTC
Labels: category: dnn, question (invalid tracker)

**Comment by jaiatncson7** [comment] 2019-06-03 03:23
Thanks @dkurt !
