### ISSUE TITLE
Cmake FindOpenCV 4.3 adds '-std=cxx11' to CUDA_FLAGS - Breaks current builds

### ISSUE THREAD

**Issue by JasonAlexander** [opencv/opencv#17355] opened 2020-05-23 21:05 UTC
Ubuntu 19 - Running Docker to build sources
Application that use CXX, CUDA, OpenCV, and CMake now fails CMake '--dryrun' along with app build.

> Cannot get compiler information:
> 	Compiler exited with error code 1: /usr/local/cuda/bin/nvcc -DCOMPILE_CUDA_COMPUTE_MAJOR=5 -DCOMPILE_CUDA_COMPUTE_MINOR=0  -DDEBUG -DDETERMINISTIC=7 -DGFLAGS_IS_A_DLL=0 -DSET_MAX_GPUS=32 -I/home/developer/Source/{app_name}./src -I/home/developer/Source/{app_name}./libraries/stlplus3/.. -isystem=/usr/include/opencv4 -g -Xcompiler=-fPIE -Xcompiler=-fopenmp -std=c++14 --compiler-options -use_fast_math --default-stream per-thread --expt-extended-lambda --expt-relaxed-constexpr -lcudart -lcudrand -lcudadevrt -lcublas_device -O0 -arch=sm_30 -gencode=arch=compute_50,code=sm_50 --ptxas-options=-v -std=c++11 --dryrun /tmp/compiler-file11223762320510418535.cu
> 	nvcc fatal   : redefinition of argument 'std'

CMakeList.txt does the standard find:
`message("-- Check for OpenCV")
find_package(OpenCV REQUIRED)
if (OPENCV_FOUND)
    message("-- Found OpenCV ${OpenCV_VERSION}: ${OpenCV_INCLUDE_DIRS}")
    message("    Libraries:  ${OpenCV_LIBS}")
else (OPENCV_FOUND)
    message(FATAL_ERROR "Can't find OpenCV. Please set OPENCV_INCLUDE_DIR & OPENCV_LIBRARY")
endif (OPENCV_FOUND)`

Which returns the follow in CMake output:
`-- Found OpenCV: /usr (found version "4.3.0") 
-- Found OpenCV 4.3.0: /usr/include/opencv4
    Libraries:  opencv_calib3d;opencv_core;opencv_dnn; ....`

Application adds CUDA/NVCC flags as follows:
`target_compile_options({app_name}
  PRIVATE
    $<$<BUILD_INTERFACE:$<COMPILE_LANGUAGE:CUDA>>:-std=c++14>
    $<$<BUILD_INTERFACE:$<COMPILE_LANGUAGE:CUDA>>:-use_fast_math>
....
`

The following is the **CUDA_FLAGS** line from _../CMakeFiles/{app_name}.dir/flags.make_
`CUDA_FLAGS = -g -Xcompiler=-fPIE   -Xcompiler=-fopenmp -std=c++14 --compiler-options -use_fast_math --default-stream per-thread --expt-extended-lambda --expt-relaxed-constexpr -lcudart -lcudrand -lcudadevrt -lcublas_device -O0 -arch=sm_30 -gencode=arch=compute_50,code=sm_50 --ptxas-options=-v -std=c++11`
This shows the addition of **-std=c++11** to the flags which is not present when using OpenCV 4.2.

I can comment out the section for **find_package(OpenCV REQUIRED)**, reset cache, and the extra std c11 is longer present.

This is not an issue in OpenCV 4.2. I found this error by downloading from github OpenCV 4.3 into a Docker container which builds the application and also OpenCV. 

Any feedback from the community would be much appreciated
-Jason

**Comment by JasonAlexander** [comment] 2020-05-24 14:10
@alalek I commented out the below line and rebuilt OpenCV. Everything seems to be back in order.
Would love to see this fix soon. 
-Jason

https://github.com/opencv/opencv/blob/01b2c5a77ca6dbef3baef24ebc0a5984579231d9/cmake/templates/OpenCVConfig.cmake.in#L286

**Comment by alalek** [comment] 2020-05-24 20:36
Suggested fix with line commenting is not acceptable.
Please provide complete minimal reproducer (similar to used app) and add information about used CUDA SDK version, so we can take a look on this in details.

**Comment by JasonAlexander** [comment] 2020-05-25 01:50
@alalek Please check this repo I spun up to show the issue. It has a simply CUDA saxpy example.
The folder 'info_files' should provide you with enough output.

https://github.com/JasonAlexander/openv_4.3_cmake_error

-Jason

**Comment by alalek** [comment] 2020-06-28 22:07
@JasonAlexander This sample demonstrates conflicts of compiler flags through:
- compiler features (modern CMake approach, these flags come from OpenCV through `cxx_std_11`)
- manual `target_compile_options()` with `$<$<BUILD_INTERFACE:$<COMPILE_LANGUAGE:CUDA>>:-std=c++14>`

This can't be solved by OpenCV CMake scripts. I believe such conflicts can be resolved by CMake only.

We only have workaround two lines below:
```
  if(DEFINED OPENCV_COMPILE_FEATURES)
    set(__compile_features ${OPENCV_COMPILE_FEATURES})
```
So you should define `OPENCV_COMPILE_FEATURES=""` for your project to disable compiler features from OpenCV.

---

BTW, Can't reproduce error by code from provided repository with CMake 3.17.3 and CUDA 10.2.89 (without suggested workaround).

**Closed** 2020-12-13 08:14 UTC
Labels: category: 3rdparty, category: build/install, category: gpu/cuda (contrib)
