### ISSUE TITLE
opencv read video raise error

### ISSUE THREAD

**Issue by JohnLoveMm** [opencv/opencv#20595] opened 2021-08-23 15:34 UTC
Today I use the opencv(python) to read a video,at the end of the video,there raise an error like this.
`OpenCV(4.5.1) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-6uw63ony\opencv\modules\highgui\src\window.cpp:376: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'cv::imshow'`
I sure it would not happen early,also I can use the return val (ret ) solve this problem,but I want know why it happened now.
Hope someone help me!

**Comment by berak** [comment] 2021-08-23 17:34
this is expected behavior, not a bug.
after you read the last valid frame of your movie, Videoapture will deliver empty / None frames
DO use that ret value to check ! (that's why it is there ...)

and please close this issue.

**Comment by sturkmen72** [comment] 2021-08-23 20:25
in OpenCV(4.5.1)  error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'cv::imshow'
in OpenCV(4.5.3)  error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'

[this line](https://github.com/opencv/opencv/blob/master/modules/highgui/src/window.cpp#L1014) should go to beginning of the function

**Closed** 2021-08-24 15:20 UTC
Labels: duplicate, invalid, question (invalid tracker)
