### ISSUE TITLE
opencv4.1.0  android build  erro

### ISSUE THREAD

**Issue by dreamsong2046** [opencv/opencv#14668] opened 2019-05-29 03:31 UTC
opencv4.1.0+NDK18+ubuntu16.04
build cmd:
./platforms/android/build_sdk.py  --config ndk-18-api-level-21.config.py --ndk_path  $ANDROID_NDK --sdk_path $ANDROID_SDK --extra_modules_path opencv_contrib/modules   workspace/

erro information:
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':face-detection'.
> NDK not configured. 
  Download it with SDK manager.
BUILD FAILED in 3s

ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "./platforms/android/build_sdk.py", line 364, in <module>
    builder.build_library(abi, do_install)
  File "./platforms/android/build_sdk.py", line 237, in build_library
    execute([self.ninja_path, '-j3', "install" if self.debug else "install/strip"])
  File "./platforms/android/build_sdk.py", line 23, in execute
    raise Fail("Child returned: %s" % retcode)
__main__.Fail: Child returned: 1

I have aleady config the path NDK18, even change NDK to 17,it also show the same build erro!

**Comment by arnaudbrejeon** [comment] 2019-06-24 17:26
Same issue on osx, I had to turn off BUILD_ANDROID_EXAMPLES and INSTALL_ANDROID_EXAMPLES in the config file to build the SDK.

**Comment by komakai** [comment] 2019-07-17 13:04
This error is coming from gradle which it seems is not checking the $ANDROID_NDK environment variable. A solution would be to tell gradle where to look by have the OpenCV Android build generate a `local.properties` file in the samples folder like
```
sdk.dir={the ANDROID_SDK directory}
ndk.dir={the ANDROID_NDK directory}
```

**Comment by hongzhi2015** [comment] 2020-05-17 02:49
Same issue with OpenCV4.3.0.
In my enrionment, I had to `export ANDROID_NDK_HOME=ndk_path` to build the SDK.

**Comment by komakai** [comment] 2020-06-04 11:59
After the introduction of the "NDK (Side by side)" feature in Android Studio 3.5 setting the `ANDROID_NDK` environment variable is no longer enough - we also have to set `ANDROID_NDK_HOME`
I have a PR to fix this

**Comment by alalek** [comment] 2020-06-17 11:03
Should be fixed by #17474

**Closed by alalek** 2020-06-17 11:03 UTC
Labels: category: build/install, platform: android

**Comment by alsaleem00** [comment] 2021-11-24 03:07
and then got this error :
A problem occurred configuring project ':face-detection'. 
>Invalid revision: 3.18.1-g262b901-dirty

but solved by [this](https://stackoverflow.com/questions/66540676/invalid-revision-3-18-1-cmake-in-android-studio)

**Comment by komakai** [comment] 2021-11-25 04:24
@alsaleem00 
I just tried a build with the latest Cmake downloaded from Android Studio with this command line:
`./opencv/platforms/android/build_sdk.py --use_android_buildtools --config ./opencv/platforms/android/ndk-22.config.py android_opencv opencv`
and that worked fine.
The problem is that the Gradle, Android Gradle Plugin and CMake versions need to be roughly in sync.
The error you are getting looks like it is caused by the Android Gradle Plugin being much older than the CMake version.
You can manually configure the Gradle version and the Android Gradle Plugin version in the config file like:
`    ABI("2", "armeabi-v7a", None, cmake_vars=dict(ANDROID_ABI='armeabi-v7a with NEON', ANDROID_GRADLE_PLUGIN_VERSION='<Preferred Plugin Version>', GRADLE_VERSION='<Preferred Gradle Version>', KOTLIN_PLUGIN_VERSION='1.5.10'))`
Unfortunately there is no easy way to query what the latest Android Gradle Plugin version and Gradle version is. Your best bet is to to create a new project in Android Studio and look at the values in the generated `build.gradle` file like:
`        classpath "com.android.tools.build:gradle:7.0.3"`
and the `grade-wrapper.properties` file:
`distributionUrl=https\://services.gradle.org/distributions/gradle-7.0.2-bin.zip`

**Comment by komakai** [comment] 2021-11-25 10:35
Footnote:
Running `cmake --version` gives me 
`cmake version 3.18.1-g262b901`
which is different from the `3.18.1-g262b901-dirty` which gave trouble.
Maybe Google fixed the `dirty` version suffix
