### ISSUE TITLE
Building OpenCV.js with projectPoints + solvePnP

### ISSUE THREAD

**Issue by kavikode** [opencv/opencv#15299] opened 2019-08-14 11:54 UTC
Porting to JavaScript: "Cannot register public name 'projectPoints' twice"

I did the following:

1. git clone https://github.com/opencv/opencv.git

2. git clone https://github.com/opencv/opencv_contrib.git

3. I added the following in def get_build_flags(self) of opencv/platforms/js/build_js.py:
        flags += "-s USE_PTHREADS=0 "

4. I enabled the build flag in def get_cmake_cmd(self): of opencv/platforms/js/build_js.py:`-DBUILD_opencv_calib3d` set to `ON`

5. I added the following def get_cmake_cmd(self): of opencv/platforms/js/build_js.py:`-DOPENCV_EXTRA_MODULES_PATH=~/opencv_contrib/modules`

6. I appended `js` inside ocv_define_module at the end of WRAP list of opencv/modules/calib3d/CMakeLists.txt. In opencv/modules/features2d/CMakeLists.txt and opencv_contrib/modules/aruco/CMakeLists.txt also I added  "js" parameter in ocv_define_module.

7. I added `solvePnP`and 'projectPoints' in the calib3d module in the opencv/modules/js/src/embindgen.py 

calib3d = {'': ['findHomography','calibrateCameraExtended', 'drawFrameAxes', 
'getDefaultNewCameraMatrix', 'initUndistortRectifyMap', 'solvePnP','projectPoints']}

8. I added the calib3d module to the makeWhiteList in the opencv/modules/js/src/embindgen.py

white_list = makeWhiteList([core, imgproc, objdetect, video, dnn, features2d, photo, aruco, calib3d])

9. I added "using namespace aruco;" in the opencv/modules/js/src/core_bindings.cpp

10. I built OpenCV.js using the following command: 
sudo python ./platforms/js/build_js.py build_js --emscripten_dir=${EMSCRIPTEN} --clean_build_dir --build_test

Before adding these wrappers, it compiled perfectly without errors. Now in my tests.html I have the following message:
Downloading...
tests.html:61 Running...
tests.html:61 Exception thrown, see JavaScript console
opencv.js:24 Uncaught 
BindingError
message: "Cannot register public name 'projectPoints' twice"
name: "BindingError"
stack: "BindingError: Cannot register public name 'projectPoints' twice↵    at BindingError.<anonymous> (http://localhost/opencv_js/docs/bin/opencv.js:24:9692639)↵    at new BindingError (eval at createNamedFunction (http://localhost/opencv_js/docs/bin/opencv.js:24:9692348), <anonymous>:4:34)↵    at throwBindingError (http://localhost/opencv_js/docs/bin/opencv.js:24:9697766)↵    at exposePublicSymbol (http://localhost/opencv_js/docs/bin/opencv.js:24:9703298)↵    at __embind_register_function (http://localhost/opencv_js/docs/bin/opencv.js:24:9727605)↵    at wasm-function[802]:8129↵    at wasm-function[75]:373↵    at Module.globalCtors (http://localhost/opencv_js/docs/bin/opencv.js:24:9762125)↵    at func (http://localhost/opencv_js/docs/bin/opencv.js:24:9597365)↵    at callRuntimeCallbacks (http://localhost/opencv_js/docs/bin/opencv.js:24:13606)"
__proto__: Error

So seems like the overload functions are preventing me from porting them to JavaScript.

Any suggestions please of how I can fix it?

Thanks in advance for your help.

**Comment by alalek** [comment] 2019-08-14 12:16
> I added
> I appended

There is no problem to provide PR with your changes.
At least, make easy to reproduce observed problem.

**Comment by kavikode** [comment] 2019-08-14 12:25
which version of OpenCV are you using please ?

**Comment by alalek** [comment] 2019-08-14 12:50
Please prepare PR/branch with your changes in code instead of modifications description.

> git clone
> version of OpenCV

You using 'master' branch (latest, OpenCV 4.x).

**Comment by kavikode** [comment] 2019-08-15 12:03
Thank you @alalek 

Please see 
https://github.com/opencv/opencv/pull/15311
https://github.com/opencv/opencv_contrib/pull/2228

**Comment by frastlin** [comment] 2019-08-21 01:21
Will this PR add solvePnP to OpenCv.js?
If so, I'll download it because solvePnP is the main function I need in my code and I can't find it in any other JS library.

**Comment by kavikode** [comment] 2019-08-21 11:00
it has not worked for me at that is why I was trying to get some help. Perhaps we can put both of our heads together to solve it. This is what I've done so far…

first of all, you need to get the latest emsdk 

1. git clone https://github.com/opencv/opencv.git

2. git clone https://github.com/opencv/opencv_contrib.git

Included flags for latest emscripten and modules from opencv_contrib
3. I added the following in def get_build_flags(self) of opencv/platforms/js/build_js.py:
        flags += "-s USE_PTHREADS=0 "

4. I enabled the build flag in def get_cmake_cmd(self): of opencv/platforms/js/build_js.py:`-DBUILD_opencv_calib3d` set to `ON`

5. I added `solvePnP`and 'projectPoints' in the calib3d module in the opencv/modules/js/src/embindgen.py 

calib3d = {'': ['findHomography','calibrateCameraExtended', 'drawFrameAxes', 
'getDefaultNewCameraMatrix', 'initUndistortRectifyMap', 'solvePnP','projectPoints']}

6.I built OpenCV.js using the following command: 
sudo python ./platforms/js/build_js.py build_js --emscripten_dir=${EMSCRIPTEN} --clean_build_dir --build_test

after building it, I was not able to use in HTML JavaScript.  perhaps, you can try

**Comment by Wenzhao-Xiang** [comment] 2019-08-24 10:50
@kavikode Seems there some bugs with `embindgen`.
I checked the `binding.cpp` generated by `embindgen.py`, and found there are indeed two bindings of `projectPoint`.

There is an ugly work around if you are anxious to enable it:

First,  just do what you have done.
Then, checkout `build_js/modules/js/binding.cpp` to delete the repeated binding functions.(include three wrapper `projectPoints_wrapper` and three binding function `function("projectPoints", select_overload<void(const cv::Mat&, cv::Mat&, const cv::Mat&, const cv::Mat&, const cv::Mat&, const cv::Mat&, double, cv::Mat&)>(&Wrappers::projectPoints_wrapper));`)
Finally, delete Line 70-79 of `opencv/modules/js/CMakeLists.txt`:
```
add_custom_command(
   OUTPUT ${bindings_cpp}
   COMMAND ${PYTHON_DEFAULT_EXECUTABLE} "${CMAKE_CURRENT_SOURCE_DIR}/src/embindgen.py" ${scripts_hdr_parser} ${bindings_cpp} "${CMAKE_CURRENT_BINARY_DIR}/headers.txt" "${CMAKE_CURRENT_SOURCE_DIR}/src/core_bindings.cpp"
   DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/src/core_bindings.cpp
   DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/src/embindgen.py
   DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/src/templates.py
   DEPENDS ${scripts_hdr_parser}
   #(not needed - generated by CMake) DEPENDS ${CMAKE_CURRENT_BINARY_DIR}/headers.txt
   DEPENDS ${opencv_hdrs}
   DEPENDS ${JS_HELPER})
```
And then, you can build `opencv.js`normally  with the building command.

**Comment by frastlin** [comment] 2019-08-31 00:19
@Wenzhao-Xiang could you please upload your built js file?

Where do you run embindgen.py to generate the binding.cpp? When you say to run the build command, you mean the "sudo python ./platforms/js/build_js.py build_js --emscripten_dir=${EMSCRIPTEN} --clean_build_dir --build_test" command?

**Comment by frastlin** [comment] 2019-08-31 19:11
I have managed to build the package following the instructions given to @kavikode just including solvePnP.
Now when I open the test console, I see no errors, even after running the test, but typing: console.log(cv.solvePnP) shows an undefined.
I looked in the binding.cpp file and see solvePnP.
What am I missing?

**Comment by frastlin** [comment] 2019-09-06 00:14
I have done some searching through past issues and see the following that may be useful:
[Adding photo module to JS build](https://github.com/opencv/opencv/pull/13300)
[OpenCV.js, build with ORB and features2d](https://github.com/opencv/opencv/issues/11300)
I'm going to go through what they did in the PRs and try to do the same for these two modules.

**Comment by kavikode** [comment] 2019-09-06 00:34
Thank you so much @Wenzhao-Xiang! I appreciate your time. 

1. What are the parameters that are used to build the .wasm file?

2. How do you call the exported functions contained in the .wasm file inside JavaScript because it is not being detected now? 

3. How can we include the face module to detect real-time facial landmarks to the JavaScript build because it is also creating errors and I am not sure where the bug occurs because I followed the same instructions? In fact, I tried FacemarkKazemi, FacemarkAAM, and FacemarkLBF.

Please help @Wenzhao-Xiang! I appreciate it

**Comment by frastlin** [comment] 2019-09-06 00:43
1. The WASM file is within the .js file when you add the --build_wasm.

    python ./platforms/js/build_js.py build_js --emscripten_dir=~/emsdk/fastcomp/emscripten/ --build_wasm

2. Most of the modules, like aruco and findHomography, are accessed through cv.findHomography after you do what the test file does and include it in a <script> tag. The SolvePnP does not seem to follow this trend though.

**Comment by kavikode** [comment] 2019-09-06 01:41
Yes, @frastlin I cannot call projectPoints and solvePnP even though the build was successful. 

Do you have an example of using those functions in your JavaScript file? @frastlin @Wenzhao-Xiang

**Comment by frastlin** [comment] 2019-09-06 01:57
No, I use the console in Chrome and type:

    > cv.solvePnP
    undefined

**Comment by kavikode** [comment] 2019-09-06 02:07
It does not work for me either. @frastlin Please let me know, if you find a solution.

**Comment by Wenzhao-Xiang** [comment] 2019-09-06 03:13
@kavikode @frastlin I'm not sure what you have missed.
But I can call them with the steps:
```js
console.log(cv.projectPoints);
VM10416:1 ƒ (){if(!proto[methodName].overloadTable.hasOwnProperty(arguments.length)){throwBindingError("Function '"+humanName+"' called with an invalid number of arguments ("+arguments.length+") - expects one of…
undefined

console.log(cv.solvePnP);
VM10472:1 ƒ (){if(!proto[methodName].overloadTable.hasOwnProperty(arguments.length)){throwBindingError("Function '"+humanName+"' called with an invalid number of arguments ("+arguments.length+") - expects one of…
undefined
```
However, I'm not sure whether them can work as expect, because I have no case.
Here is the file: [opencv.js.zip](https://github.com/opencv/opencv/files/3582079/opencv.js.zip)

**Comment by alalek** [comment] 2019-09-06 05:03
> projectPoints
> message: "Cannot register public name 'projectPoints' twice"

There are at least two functions with that name:
- cv::projectPoints()
- cv::fisheye::projectPoints()
- from opencv_contrib/ccalib

Not sure if current implementation of JS bindings support nested namespaces properly.

**Comment by frastlin** [comment] 2019-09-06 22:11
@Wenzhao-Xiang thank you this works great! I need to create a test. Do you think you could create a PR or something I can download to replicate the build?
I wonder if adding the sub-class would fix this problem?
Thank you!

**Comment by kavikode** [comment] 2019-09-06 22:29
thank you so much @Wenzhao-Xiang! I appreciate your time.

1. How was "Cannot register public name 'projectPoints' twice" resolved?

2. On a slightly different note, how can we include the dlib's facial landmark model library into the OpenCV.js build? 

3. How can we include the face module to detect real-time facial landmarks to the JavaScript build because it is also creating errors and I am not sure where the bug occurs because I followed the same instructions? In fact, I tried FacemarkKazemi, FacemarkAAM, and FacemarkLBF.

**Comment by frastlin** [comment] 2019-09-12 00:56
@Wenzhao-Xiang I managed to compile projectPoints following your instructions. I also added in Rodrigues.
My next task is to write some tests.
For the embindgen.py, should we open another issue about that? Who knows that module?
It's probably a couple line fix to check if the current function is within a nested namespace, but I haven't figured out the lines that do that particular check yet.

**Comment by frastlin** [comment] 2019-09-12 01:02
Note, I am getting the following warning when compiling these extra 3 functions:

emcc: warning: cannot represent a NaN literal '0x5c82490' with custom bit pattern in NaN-canonicalizing JS engines

**Comment by Rakeshvcr** [comment] 2019-09-20 06:04
@kavikode have you managed to include the FacemarkKazemi, I tried similar way of including the functions using this [Link](https://github.com/ganwenyao/opencv_js). When I checked in binding.cpp this functions are not included. If you found a solution please help me.

**Comment by frastlin** [comment] 2019-09-24 01:44
Hello,
I tested Rodrigues, solvePnP, and projectPoints, and they all work.
I'm writing the unittests for the 3 functions and I'm running into a problem:
The tests run too fast.
I tried adding an await function to cv.Rodrigues, but it still goes too fast.
How can I wait until after the function runs before checking if the function gave the correct result?
Here is the test code from my inserted test from line 45 of test_calib3d.js:

	QUnit.test('Rodrigues', function(assert) {
	const rvec0 = cv.matFromArray(1, 3, cv.CV_64F, [1,1,1])
	let rMat0 = new cv.Mat()
	let rvec1 = new cv.Mat()
	
	//Args: input Mat, output Mat. The function mutates the output Mat, so the function does not return anything.
	//cv.Rodrigues (InputArray=src, OutputArray=dst, OutputArray jacobian=noArray())
	cv.Rodrigues(rvec0, rMat0)
	
	window.result1 = rvec1.data64F
	assert.ok(rvec1.data64F.length == 3)
	//assert.ok(1.01 > rvec1.data64F[0] > 0.9)
	//Answer should be around 1: 0.9999999999999999
	});

**Comment by kavikode** [comment] 2019-09-24 01:49
Can you please write down the steps one by one of how you included Rodrigues, solvePnP, and projectPoints? @Brandon

**Comment by frastlin** [comment] 2019-09-24 17:41
Hello,
Steps to compile these 3 functions is as follows:

1. 
git clone https://github.com/opencv/opencv.git
2. 
git clone https://github.com/opencv/opencv_contrib.git
3. I added the following in def get_build_flags(self) of opencv/platforms/js/build_js.py:
flags += "-s USE_PTHREADS=0 "
4. I enabled the build flag in def get_cmake_cmd(self): of opencv/platforms/js/build_js.py:-DBUILD_opencv_calib3d set to ON
5. I added the following def get_cmake_cmd(self): of opencv/platforms/js/build_js.py:-DOPENCV_EXTRA_MODULES_PATH=~/opencv_contrib/modules
6. I appended js inside ocv_define_module at the end of WRAP list of opencv/modules/calib3d/CMakeLists.txt. In opencv/modules/features2d/CMakeLists.txt and opencv_contrib/modules/aruco/CMakeLists.txt also I added "js" parameter in ocv_define_module.
7. I added solvePnP, Rodrigues, and 'projectPoints' in the calib3d module in the opencv/modules/js/src/embindgen.py

	calib3d = {'': ['findHomography','calibrateCameraExtended', 'drawFrameAxes', 'getDefaultNewCameraMatrix', 'initUndistortRectifyMap', 'Rodrigues', 'solvePnP', 'projectPoints']


8. I added the calib3d module to the makeWhiteList in the opencv/modules/js/src/embindgen.pywhite_list = makeWhiteList([core, imgproc, objdetect, video, dnn, features2d, photo, aruco, calib3d])
9. I added "using namespace aruco;" in the opencv/modules/js/src/core_bindings.cpp
10. I built OpenCV.js using the following command:
python ./platforms/js/build_js.py build_js --emscripten_dir=${EMSCRIPTEN} --build_test
11. Deleted 3 repeated lines of the wrapper functions from build_js/modules/js/binding.cpp that start with:
projectPoints_wrapper
12. Deleted 3 more repeated lines of the binding functions from the same above file build_js/modules/js/binding.cpp that start with:

	function("projectPoints", select_overload<void(const cv::Mat&, cv::Mat&, const cv::Mat&, const cv::Mat&, const cv::Mat&, const cv::Mat&, double, cv::Mat&)>(&Wrappers::projectPoints_wrapper));)

13. Deleted Line 70-79 of opencv/modules/js/CMakeLists.txt:
~~~
add_custom_command(
   OUTPUT ${bindings_cpp}
   COMMAND ${PYTHON_DEFAULT_EXECUTABLE} "${CMAKE_CURRENT_SOURCE_DIR}/src/embindgen.py" ${scripts_hdr_parser} ${bindings_cpp} "${CMAKE_CURRENT_BINARY_DIR}/headers.txt" "${CMAKE_CURRENT_SOURCE_DIR}/src/core_bindings.cpp"
   DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/src/core_bindings.cpp
   DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/src/embindgen.py
   DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/src/templates.py
   DEPENDS ${scripts_hdr_parser}
   #(not needed - generated by CMake) DEPENDS ${CMAKE_CURRENT_BINARY_DIR}/headers.txt
   DEPENDS ${opencv_hdrs}
   DEPENDS ${JS_HELPER})
~~~
14. Ran:
python ./platforms/js/build_js.py build_js --emscripten_dir=${EMSCRIPTEN} --build_test
15. Started a server in the build_js/bin folder and visited localhost/port/tests.html.
16. Hit ctrl+F5 to clean refresh the page.
17. Type cv.solvePnP in the browser console to view the properties of solvePnP.

Hope this helps! Please try the test I posted above and let me know if you know how to delay the test for Rodrigues to finish. I'm thinking the only way to do this is by doing a setTimeout and resolve a promise when the result Mat has filled.
Thanks,

**Comment by ThorstenBux** [comment] 2019-10-05 07:04
@frastlin I can verify that your build steps work. Looking at the tests there is a test function for Rodrigues which runs successfully. What is the issue with your test? Maybe I can support

**Comment by frastlin** [comment] 2019-10-05 16:12
Sorry, I got it working and submitted a PR:
https://github.com/opencv/opencv/pull/15595#event-2668119469
I have unittests for solvePnP, but I haven't had time to clean them up and make a PR.
If someone could investigate the bug for projectPoints building twice, that would be amazing.
Also, what is the goal with OpenCV and compiling modules? Sajjad Taheri published in his paper that he wanted to allow people to build OpenCV.js how they wanted. I assume this means the official build will be the largest possible build. The problem is I am not sure unittests will work if the module is not included in the build.

**Comment by seranus** [comment] 2020-12-07 21:42
@Wenzhao-Xiang there where changes to the build script, do you have time to check it now how to edit CMakeLists.txt bindings.cpp moved but I found it end edited the function but I don't know how to edit the new CMake file

**Comment by mzwtjp** [comment] 2021-02-05 09:32
Sorry jumping in.

I had similar issue and this is what I have done to workaround using latest master, to enable projectPoints(), are in the following 2 places.
I found solvePnP() was already there.

1) Add projectPoints name

File: opencv/platforms/js/opencv_js.config.py

(Added projectPoints and decomposeProjectionMatrix to calib3d)

calib3d = {'': ['findHomography', 'calibrateCameraExtended', 'drawFrameAxes', 'estimateAffine2D', \
                'getDefaultNewCameraMatrix', 'initUndistortRectifyMap', 'Rodrigues', \
                'solvePnP', 'solvePnPRansac', 'solvePnPRefineLM', 'projectPoints', 'decomposeProjectionMatrix']}

2) Add following two lines       

file: opencv/modules/js/generator/embindgen.py

def add_func(self, decl):
    namespace, classes, barename = self.split_decl_name(decl[0])
    cpp_name = "::".join(namespace + classes + [barename])
>    if (len(namespace) > 1) and namespace[1] == u'fisheye':
>        return

But I just wonder 2) above disables fisheye::projectPoints() function to be registered (?) and so it is not a desired fix?

**Comment by keroiber** [comment] 2021-09-23 07:43
I have a fix for the bindings generator that adds the namespace as perfix to the global function, so we get both "fisheye_projectPoints" and "projectPoints". For aruco (i've activated this, too) the functions are also prefixed with "aruco_". So no name clash anymore. I can prepare a PR.

**Comment by gredin** [comment] 2021-09-23 15:08
@keroiber I'm interested in your solution. Could you open a PR or share the implementation details?

**Comment by kavikode** [comment] 2021-09-24 01:17
please share the implementation

**Comment by keroiber** [comment] 2021-09-24 07:34
Here it is: #20743

**Closed** 2021-10-04 22:31 UTC
Labels: category: javascript (js)
