### ISSUE TITLE
Add OpenCv.js to npm

### ISSUE THREAD

**Issue by frastlin** [opencv/opencv#15340] opened 2019-08-19 23:14 UTC
##### System information (version)
- OpenCV => 3.4.7

##### Detailed description

Could [OpenCv.js](https://docs.opencv.org/3.4.7/d5/d10/tutorial_js_root.html) please be added to [npm](https://www.npmjs.com) and instructions to install it such as:

    npm install opencvjs --save

please be placed in the [Using OpenCv.js tutorial?](https://docs.opencv.org/3.4.7/d0/d84/tutorial_js_usage.html)

npm is the main package index for all javascript projects, both browser and Node, and including OpenCv.js there will increase its accessibility to developers significantly.

**Comment by alalek** [comment] 2019-08-20 05:26
duplicate of #15315

**Closed by alalek** 2019-08-20 05:26 UTC
Labels: duplicate
