### ISSUE TITLE
Android Camera2 not working

### ISSUE THREAD

**Issue by zeshaoaaa** [opencv/opencv#11501] opened 2018-05-11 02:19 UTC
#### System information (version)

- OpenCV => 3.1
- Operating System / Platform => Windows 64 Bit
- IDE => Android Studio

#### Description

` StreamConfigurationMap map = characteristics.get(CameraCharacteristics.SCALER_STREAM_CONFIGURATION_MAP);
            int bestWidth = 0, bestHeight = 0;
            float aspect = (float) width / height;
            android.util.Size[] sizes = map.getOutputSizes(ImageReader.class);
`

The problem is cause by the getOutputSizes return null. But I can't debug the StreamConfigurationMap Class. Is there anyone know how to solve it? Thanks in advance!

#### Error Info

05-11 10:13:54.132 29590-29590/com.example.administrator.myapplication E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                         Process: com.example.administrator.myapplication, PID: 29590
                                                                                         java.lang.RuntimeException: Interrupted while setCameraPreviewSize.
                                                                                             at org.opencv.android.JavaCamera2View.connectCamera(JavaCamera2View.java:320)
                                                                                             at org.opencv.android.CameraBridgeViewBase.onEnterStartedState(CameraBridgeViewBase.java:360)
                                                                                             at org.opencv.android.CameraBridgeViewBase.processEnterState(CameraBridgeViewBase.java:321)
                                                                                             at org.opencv.android.CameraBridgeViewBase.checkCurrentState(CameraBridgeViewBase.java:313)
                                                                                             at org.opencv.android.CameraBridgeViewBase.surfaceChanged(CameraBridgeViewBase.java:198)
                                                                                             at android.view.SurfaceView.updateWindow(SurfaceView.java:688)
                                                                                             at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:202)
                                                                                             at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
                                                                                             at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2391)
                                                                                             at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1318)
                                                                                             at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6728)
                                                                                             at android.view.Choreographer$CallbackRecord.run(Choreographer.java:802)
                                                                                             at android.view.Choreographer.doCallbacks(Choreographer.java:605)
                                                                                             at android.view.Choreographer.doFrame(Choreographer.java:574)
                                                                                             at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:788)
                                                                                             at android.os.Handler.handleCallback(Handler.java:815)
                                                                                             at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                                             at android.os.Looper.loop(Looper.java:194)
                                                                                             at android.app.ActivityThread.main(ActivityThread.java:5898)
                                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                                             at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1019)
                                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:814)
                                                                                          Caused by: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
                                                                                             at org.opencv.android.JavaCamera2View.calcPreviewSize(JavaCamera2View.java:265)
                                                                                             at org.opencv.android.JavaCamera2View.connectCamera(JavaCamera2View.java:300)

##### Activity

package com.example.administrator.myapplication;

import android.content.Context;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.widget.TextView;
import android.widget.Toast;

import org.opencv.android.BaseLoaderCallback;
import org.opencv.android.CameraBridgeViewBase;
import org.opencv.android.InstallCallbackInterface;
import org.opencv.android.JavaCamera2View;
import org.opencv.android.LoaderCallbackInterface;
import org.opencv.android.OpenCVLoader;
import org.opencv.core.Core;
import org.opencv.core.CvType;
import org.opencv.core.Mat;
import org.opencv.imgproc.Imgproc;

public class MainActivity extends AppCompatActivity implements CameraBridgeViewBase.CvCameraViewListener2 {

    Mat mat1, mat2, mat3;

    CameraBridgeViewBase base;

    BaseLoaderCallback callback;

    // Used to load the 'native-lib' library on application startup.
    static {
        System.loadLibrary("native-lib");
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        base = findViewById(R.id.camera);
        base.setCvCameraViewListener(this);

        callback = new BaseLoaderCallback(this) {
            @Override
            public void onManagerConnected(int status) {
                super.onManagerConnected(status);
                switch (status) {
                    case BaseLoaderCallback.SUCCESS:
                        base.enableView();
                        toast("BaseLoaderCallback.SUCCESS");
                        break;
                }
            }

            @Override
            public void onPackageInstall(int operation, InstallCallbackInterface callback) {
                super.onPackageInstall(operation, callback);
            }
        };

    }

    private void toast(final String msg) {
        runOnUiThread(new Runnable() {
            @Override
            public void run() {
                Toast.makeText(getApplicationContext(), msg, Toast.LENGTH_LONG).show();
            }
        });
    }

    /**
     * A native method that is implemented by the 'native-lib' native library,
     * which is packaged with this application.
     */
    public native String stringFromJNI();

    @Override
    public void onCameraViewStarted(int width, int height) {
        Toast.makeText(this, "onCameraViewStarted", Toast.LENGTH_LONG).show();
        mat1 = new Mat(width, height, CvType.CV_8UC4);
        mat2 = new Mat(width, height, CvType.CV_8UC4);
        mat3 = new Mat(width, height, CvType.CV_8UC4);
    }

    @Override
    public void onCameraViewStopped() {
        Toast.makeText(this, "onCameraViewStopped", Toast.LENGTH_LONG).show();
        mat1.release();
        mat2.release();
        mat3.release();
    }

    @Override
    public Mat onCameraFrame(CameraBridgeViewBase.CvCameraViewFrame inputFrame) {
        toast("onCameraFrame");
        mat1 = inputFrame.rgba();

        //Core.transpose(mat1, mat2);

        //Imgproc.resize(mat2, mat2, mat3.size(),0, 0,0 );

        //Core.flip(mat3, mat1, 1);

        return mat1;
    }

    @Override
    protected void onPause() {
        super.onPause();
        if (base != null) {
            base.disableView();
        }
    }

    @Override
    protected void onResume() {
        super.onResume();
        if (!OpenCVLoader.initDebug()) {
            Toast.makeText(this, "Load Failed", Toast.LENGTH_LONG).show();
        } else {
            callback.onManagerConnected(LoaderCallbackInterface.SUCCESS);
            Toast.makeText(this, "Load Success", Toast.LENGTH_LONG).show();
        }
    }
}

##### XML

<?xml version="1.0" encoding="utf-8"?>
<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context="com.example.administrator.myapplication.MainActivity">

    <org.opencv.android.JavaCamera2View
        android:id="@+id/camera"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

</android.support.constraint.ConstraintLayout>

**Comment by alalek** [comment] 2018-05-11 07:01
- Output of `adb logcat` (only related to app).
- Android API level?
- Device model?

**Comment by zeshaoaaa** [comment] 2018-05-12 08:32
@alalek 
Thanks for your replay. 
When I change the ImageReader.class to ImageFormat.JPEG，then it works. But the preview is mess up.

* Android API Level ：22
* Device Model：Meizu MX 5
============================Log cat===============================
05-12 16:27:14.435 829-1089/? I/Sensors: HAL:resetDataRates mEnabled=4101
05-12 16:27:14.435 829-1089/? I/Sensors: HAL:resetDataRates wanted=5000000
05-12 16:27:14.436 1037-1037/? I/FlashlightController: onFlashLight call back called --- enabled = false
05-12 16:27:14.440 9048-9048/? I/CameraFramework: Camera framework getParameters =3dnr-mode=on;3dnr-mode-values=on,off;afeng-max-focus-step=1023;afeng-min-focus-step=0;aflamp-mode=off;aflamp-mode-values=off,on,auto;antibanding=off;antibanding-values=off,50hz,60hz,auto;auto-exposure-lock-supported=true;auto-whitebalance-lock-supported=true;brightness=middle;brightness-values=low,middle,high;brightness_value=0;burst-num=1;cap-mode=normal;cap-mode-values=normal,face_beauty,continuousshot,smileshot,bestshot,autorama,mav,asd,motiontrack;capfname=/sdcard/DCIM/cap00;contrast=middle;contrast-values=low,middle,high;cshot-indicator=true;cshot-indicator-supported=true;dynamic-frame-rate=true;dynamic-frame-rate-supported=true;edge=middle;edge-values=low,middle,high;effect=none;effect-values=none,mz_lively,mz_moonlight,mz_black_and_white,mz_blue,mz_pink,mz_film,mz_natural,mz_dawn,mz_sakura,mz_dreamy,mz_bright,maroon,black_and_white,film,oxidize,leaf,violet,light_yellow,azure,viridity,wood,pale_green,fading,corn_field,olive_yellow,toy,pale_blue,clay_bank,sunny,moon,dew,aqua,vine,sky,peach,sunny_2rd,jade,wood_2rd,orange,ash;eng-mfll-e=false;eng-mfll-s=true;eng-s-shad-t=0;eng-shad-t=0;exposure-compensation=0;exposure-compensation-step=1.0;fb-enlarge-eye=0;fb-enlarge-eye-max=4;fb-enlarge-eye-min=-4;fb-extreme-beauty=true;fb-extreme-beauty-supported=true;fb-face-pos=-2000:-2000;fb-sharp=0;fb-sharp-max=12;fb-sharp-max-values=12;fb-sharp-min=-12;fb-sharp-min-values=-12;fb-skin-color=0;fb-skin-color-max=12;fb-skin-color-max-values=12;fb-skin-color-min=-12;fb-skin-color-min-values=-12;fb-slim-face=0;fb-slim-face-max=12;fb-slim-face-max-values=12;fb-slim-face-min=-12;fb-slim-face-min-values=-12;fb-smooth-level=0;fb-smooth-level-max=12;fb-smooth-level-max-values=12;fb-smooth-level-min=-12;fb-smooth-level-min-values=-12;fb-touch-pos=-2000:-2000;feature-max-fps=24@VFB+EIS;flash-duty-max=1;flash-duty-min=0;flash-duty-value=-1;flash-mode=off;flash-mode-values=off,on,auto,red-eye,torch;flash-step-max=0;flash-step-min=0;focal-length=4.73;focus-distances=0.95,1.9,Infinity;focus-fs-fi=0;focus-fs-fi-max=65535;focus-fs-fi-min=0;focus-mode=auto;focus-mode-values=auto,macro,infinity,continuous-picture,continuous-video,manual,fullscan;gesture-shot=false;gesture-shot-supported=true;horizontal-view-angle=63;hue=middle;hue-values=low,middle,high;iso-speed=auto;iso-speed-values=auto,100,200,400,800,1600;jpeg-quality=100;jpeg-thumbnail-height=128;jpeg-thumbnail-quality=100;jpeg-thumbnail-size-values=0x0,160x96,160x128;jpeg-thumbnail-width=160;m-sr-g=0;m-ss=0;max-exposure-compensation=3;max-num-detected-faces-hw=15;max-num-detected-faces-sw=0;max-num-focus-areas=1;max-num-metering-areas=9;max-num-ot=1;max-zoom=10;mfb=off;mfb-values=off,mfll,ais;min-exposure-compensation=-3;mnr-e=0;mnr-s=true;mtk-123-shad-s=true;mtk-awb-s=true;mtk-cam-mode=0;mtk-heartbeat-monitor-supported=true;mtk-shad-s=true;native-pip=false;native-pip-supported=true;picture-format=jpeg;picture-format-values=jpeg;picture-size=2560x1920;picture-size-values=320x240,640x480,1024x768,1280x720,1280x768,1280x960,1600x1200,2048x1536,2336x1760,2560x1440,2560x1920,2624x1968,2672x1504,2896x1632,3264x2448,3648x2192,4080x2448,4608x2592,4672x3504,5248x3936;pip-fps-zsd-off=30;pip-fps-zsd-on=15;preferred-preview-size-for-video=1920x1088;preview-format=yuv420sp;preview-format-values=yuv420sp,yuv420p,yuv420i-yyuvyy-3plane;preview-fps-range=5000,60000;preview-fps-range-values=(5000,60000);preview-frame-rate=30;preview-frame-rate-values=10,20,15,24,30,102;preview-size=640x480;preview-size-values=176x144,320x240,352x288,480x320,480x368,640x480,720x480,800x480,800x600,864x480,960x540,960x720,1280x720,1536x1152,1920x1080,1920x1088,1920x1152;rotation=0;saturation=middle;saturation-values=low,middle,high;scene-mode=auto;scene-mode-values=auto,portrait,landscape,night,night-portrait,theatre,beach,snow,sunset,steadyphoto,fireworks,sports,party,candlelight,hdr,normal;sen-mode-s=0;sensor-type=252;shutter-value=0;shutter-value-supported=0,200,500,1000,2000,5000,10000,20000,50000,100000,200000,300000,400000,500000,600000,800000,1000000,
05-12 16:27:14.448 829-1089/? I/Sensors: HAL:resetDataRates mEnabled=4101
05-12 16:27:14.448 829-1089/? I/Sensors: HAL:resetDataRates wanted=5000000
05-12 16:27:14.449 331-9088/? E/GLConsumer: hongxu transact end
05-12 16:27:14.449 829-1091/? I/Sensors: HAL:resetDataRates mEnabled=4101
05-12 16:27:14.449 829-1091/? I/Sensors: HAL:resetDataRates wanted=33000000
05-12 16:27:14.451 9048-9048/? I/JavaCamera2View: calcPreviewSize: 1080x1686
05-12 16:27:14.451 9048-9076/? I/JavaCamera2View: createCameraPreviewSession(-1x-1)
05-12 16:27:14.458 9048-9048/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.example.administrator.opencvtest2, PID: 9048
                                                 java.lang.RuntimeException: Interrupted while setCameraPreviewSize.
                                                     at com.example.administrator.opencvtest2.MyJavaCamera2View.connectCamera(MyJavaCamera2View.java:321)
                                                     at org.opencv.android.CameraBridgeViewBase.onEnterStartedState(CameraBridgeViewBase.java:360)
                                                     at org.opencv.android.CameraBridgeViewBase.processEnterState(CameraBridgeViewBase.java:321)
                                                     at org.opencv.android.CameraBridgeViewBase.checkCurrentState(CameraBridgeViewBase.java:313)
                                                     at org.opencv.android.CameraBridgeViewBase.surfaceChanged(CameraBridgeViewBase.java:198)
                                                     at android.view.SurfaceView.updateWindow(SurfaceView.java:688)
                                                     at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:202)
                                                     at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
                                                     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2391)
                                                     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1318)
                                                     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6728)
                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:802)
                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:605)
                                                     at android.view.Choreographer.doFrame(Choreographer.java:574)
                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:788)
                                                     at android.os.Handler.handleCallback(Handler.java:815)
                                                     at android.os.Handler.dispatchMessage(Handler.java:104)
                                                     at android.os.Looper.loop(Looper.java:194)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5898)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1019)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:814)
                                                  Caused by: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
                                                     at com.example.administrator.opencvtest2.MyJavaCamera2View.calcPreviewSize(MyJavaCamera2View.java:266)
                                                     at com.example.administrator.opencvtest2.MyJavaCamera2View.connectCamera(MyJavaCamera2View.java:301)
                                                     at org.opencv.android.CameraBridgeViewBase.onEnterStartedState(CameraBridgeViewBase.java:360) 
                                                     at org.opencv.android.CameraBridgeViewBase.processEnterState(CameraBridgeViewBase.java:321) 
                                                     at org.opencv.android.CameraBridgeViewBase.checkCurrentState(CameraBridgeViewBase.java:313) 
                                                     at org.opencv.android.CameraBridgeViewBase.surfaceChanged(CameraBridgeViewBase.java:198) 
                                                     at android.view.SurfaceView.updateWindow(SurfaceView.java:688) 
                                                     at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:202) 
                                                     at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944) 
                                                     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2391) 
                                                     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1318) 
                                                     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6728) 
                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:802) 
                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:605) 
                                                     at android.view.Choreographer.doFrame(Choreographer.java:574) 
                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:788) 
                                                     at android.os.Handler.handleCallback(Handler.java:815) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:104) 
                                                     at android.os.Looper.loop(Looper.java:194) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5898) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:372) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1019) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:814) 
05-12 16:27:14.459 829-5235/? W/ActivityManager:   Force finishing activity 1 com.example.administrator.opencvtest2/.MainActivity
05-12 16:27:14.473 331-9087/? E/MtkCam/HalSensor: [get_boot_mode] fail to open: /sys/class/BOOT/BOOT/boot/boot_mode
                                                   (get_boot_mode){#102:vendor/mediatek/proprietary/platform/mt6795/hardware/mtkcam/hal/sensor/HalSensor.cpp}
05-12 16:27:14.473 331-9087/? I/Drv/HWsync: Drv/HWsync[getInstance] singleton[0xf4454900],getpid[0x0000014b],gettid[0x0000237f] 
05-12 16:27:14.473 331-9087/? I/Drv/HWsync: Drv/HWsync[init] +, usercnt(0),srIdxNum(0)
05-12 16:27:14.473 331-9087/? I/Drv/HWsync: Drv/HWsync[init] -, usercnt(1),srIdxNum(1)
05-12 16:27:14.473 331-9087/? I/MtkCam/Utils/Profile: {CamProfile}[DefaultCam1Device::powerOnSensor] Sensor Hal -: (0-th) ===> [start-->now: 71 ms]

**Comment by alalek** [comment] 2019-04-12 11:00
duplicate of #11325, should be fixed by #13840

**Closed by alalek** 2019-04-12 11:00 UTC
Labels: incomplete, platform: android

**Comment by bosch-iot-suite** [comment] 2025-02-04 20:00
https://stackdev.space/questions/android-opencv-javacamera2view-initialization-error I struggled with the same issue and found a way out
