### ISSUE TITLE
Error while loading pytorch model in opencv

### ISSUE THREAD

**Issue by themechanicalcoder** [opencv/opencv#16662] opened 2020-02-25 03:58 UTC
While reading the CRNN model from [meijieru](https://github.com/meijieru/crnn.pytorch)
in OpenCV, I got the following error

```
import cv2
net = cv2.dnn.readNetFromTorch("crnn.pth")
```
```
error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\dnn\src\torch\torch_importer.cpp:1022: error: (-213:The function/feature is not implemented) Unsupported Lua type in function 'cv::dnn::dnn4_v20191202::TorchImporter::readObject'
```
[model link](https://www.dropbox.com/s/dboqjk20qjkpta3/crnn.pth?dl=0)
How to fix this error?

##### System information (version)

- OpenCV = 4.2.0
- Operating System / Platform => Windows 64 Bit

**Comment by dkurt** [comment] 2020-02-25 05:04
Please read the documentation for readNetFromTorch method: https://docs.opencv.org/master/d6/d0f/group__dnn.html#ga65a1da76cb7d6852bdf7abbd96f19084. It is used for Torch models, not PyTorch. For PyTorch you need yo convert it to ONNX and use readNet.

**Comment by themechanicalcoder** [comment] 2020-02-25 05:28
I wrote this code for converting the model into ONNX 
```
import torch.onnx
 
# Loading the input PyTorch model and mapping the tensors to CPU
device = torch.device('cpu')
model = torch.load('crnn.pth', map_location=device)
 
# Generate a dummy input that is consistent with the network's architecture
dummy_input = torch.randn(1, 1, 32, 100)
 
# Export into an ONNX model using the PyTorch model and the dummy input
torch.onnx.export(model, dummy_input, "crnn.onnx")
```

and I got the following error

```
Traceback (most recent call last):

  File "<ipython-input-7-4e3fc98cedf4>", line 11, in <module>
    torch.onnx.export(model, dummy_input, "crnn.onnx")

  File "C:\Users\goura\Anaconda3\envs\deep_learning\lib\site-packages\torch\onnx\__init__.py", line 27, in export
    return utils.export(*args, **kwargs)

  File "C:\Users\goura\Anaconda3\envs\deep_learning\lib\site-packages\torch\onnx\utils.py", line 104, in export
    operator_export_type=operator_export_type)

  File "C:\Users\goura\Anaconda3\envs\deep_learning\lib\site-packages\torch\onnx\utils.py", line 281, in _export
    example_outputs, propagate)

  File "C:\Users\goura\Anaconda3\envs\deep_learning\lib\site-packages\torch\onnx\utils.py", line 224, in _model_to_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args, training)

  File "C:\Users\goura\Anaconda3\envs\deep_learning\lib\site-packages\torch\onnx\utils.py", line 184, in _trace_and_get_graph_from_model
    orig_state_dict_keys = _unique_state_dict(model).keys()

  File "C:\Users\goura\Anaconda3\envs\deep_learning\lib\site-packages\torch\jit\__init__.py", line 200, in _unique_state_dict
    state_dict = module.state_dict(keep_vars=keep_vars)

AttributeError: 'collections.OrderedDict' object has no attribute 'state_dict'
```

**Comment by berak** [comment] 2020-02-25 09:42
`torch.load()` loads a state_dict, not a model.
assuming [this repo](https://github.com/meijieru/crnn.pytorch) , try:

```
import torch
import models.crnn as crnn

model = crnn.CRNN(32, 1, 37, 256)
model.load_state_dict(torch.load("crnn.pth"))
device = torch.device('cpu')
model = torch.load('crnn.pth', map_location=device)
dummy_input = torch.randn(1, 1, 32, 100)
torch.onnx.export(model, dummy_input, "crnn.onnx")

import cv2
net=cv2.dnn.readNet("crnn.onnx")
```

```
error: OpenCV(4.2.0) /io/opencv/modules/dnn/src/dnn.cpp:562: error: (-2:Unspecified error) Can't create layer "82" of type "ConstantOfShape" in function 'getLayerInstance'
```

**Comment by themechanicalcoder** [comment] 2020-02-26 01:32
@berak  I get the same error after converting to onnx and reading the model in OpenCV. Any idea how to fix it?

**Comment by dkurt** [comment] 2020-02-26 08:30
@themechanicalcoder, please use `cv::dnn::readNet` with a file with `.onnx` extension or `cv::dnn::readNetFromONNX` if it's not `*.onnx`.

**Comment by themechanicalcoder** [comment] 2020-02-26 13:53
when running the code which berak provided in  the above comment I get the following error
```
import torch
import models.crnn as crnn

model = crnn.CRNN(32, 1, 37, 256)
model.load_state_dict(torch.load("crnn.pth"))

dummy_input = torch.randn(1, 1, 37, 256)
torch.onnx.export(model, dummy_input, "crnn.onnx")

import cv2
net=cv2.dnn.readNet("crnn.onnx")
```

I get the following error

```
D:\all_libraries\crnn.pytorch-master\models\crnn.py:72: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert h == 1, "the height of conv must be 1"
Traceback (most recent call last):
  File "D:/all_libraries/crnn.pytorch-master/test.py", line 11, in <module>
    net=cv2.dnn.readNet("crnn.onnx")
cv2.error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\dnn\src\dnn.cpp:562: error: (-2:Unspecified error) Can't create layer "82" of type "ConstantOfShape" in function 'cv::dnn::dnn4_v20191202::LayerData::getLayerInstance'

```

**Comment by berak** [comment] 2020-02-26 14:40
![onnx_dot](https://user-images.githubusercontent.com/854416/75353035-fcf7bc00-58aa-11ea-8148-efeb7e1031a5.jpg)

it seems to generate the initial weights for the hidden LSTM layers.

currently trying to add a custom ConstantOfShape layer to cv::dnn, but it's a bit weird.

(from [the tutorial](https://docs.opencv.org/master/dc/db1/tutorial_dnn_custom_layers.html) ): 
> Custom layers import from TensorFlow is designed to put all layer's attr into cv::dnn::LayerParams but input Const blobs into cv::dnn::Layer::blobs. In our case resize's output shape will be stored in layer's blobs[0].

i'm seing something similar, the  `cv::dnn::LayerParams &params` passed in the constructor have `[0]` and `[2,1,256]` blobs, which nicely fit the

     %82 : Float(2, 1, 256) = onnx::ConstantOfShape[value={0}](%81) # /usr/local/lib/python3.6/dist-packages/torch/nn/modules/rnn.py:549:0
 
description from the onnx export, but ` getMemoryShapes()` in my custom layer has empty inputs.
and it still throws:

    OpenCV(4.2.0-dev) Error: Assertion failed (inputs.size() == 1) in getMemoryShapes, file C:\p\opencv\modules\dnn\src\layers\slice_layer.cpp, line 136
a few layers later

<details><summary>current attempt:</summary>

```
class ConstantOfShapeLayer : public cv::dnn::Layer
{
public:
    ConstantOfShapeLayer(const cv::dnn::LayerParams &params) : Layer(params)
    {
        cout << params.blobs[0].type() << params.blobs[0] << endl;
        cout << params.blobs[1].type() << params.blobs[1] << endl;
        float value = params.blobs[0].at<float>(0,0);
        int sz[] = {
            params.blobs[1].at<int>(0,0),
            params.blobs[1].at<int>(1,0),
            params.blobs[1].at<int>(2,0)
        };
        _const = Mat(3,sz,CV_32F,Scalar(value));
        cout << _const.size << endl;
    }
    static cv::Ptr<cv::dnn::Layer> create(cv::dnn::LayerParams& params)
    {
        return cv::Ptr<cv::dnn::Layer>(new ConstantOfShapeLayer(params));
    }
    virtual bool getMemoryShapes(const std::vector<std::vector<int> > &inputs,
                                 const int requiredOutputs,
                                 std::vector<std::vector<int> > &outputs,
                                 std::vector<std::vector<int> > &internals) const CV_OVERRIDE
    {
        CV_UNUSED(requiredOutputs); CV_UNUSED(internals);
        //CV_Assert(inputs.size());
        std::vector<int> out {
            _const.size[0],
            _const.size[1],
            _const.size[2]
        };
        outputs.push_back(out);
        return false;
    }
    virtual void forward(cv::InputArrayOfArrays inputs_arr,
                         cv::OutputArrayOfArrays outputs_arr,
                         cv::OutputArrayOfArrays internals_arr) CV_OVERRIDE
    {
        std::vector<cv::Mat> inputs, outputs;
        inputs_arr.getMatVector(inputs);
        outputs_arr.getMatVector(outputs);
        outputs.push_back(_const);
    }
private:
    Mat _const;
};
\```

<details>

**Comment by themechanicalcoder** [comment] 2020-02-27 15:49
@berak can we use a custom layer for ```Slice```  as well to remove the error?

**Comment by berak** [comment] 2020-02-27 16:11
opencv's dnn already has  a `Slice` layer. if i debug, it's `sliceRanges` are all read in correctly, but the inputs are not linked to the weights (on the left in image below). not sure, if the weights are even parsed / read into the dnn
![onnx_dot](https://user-images.githubusercontent.com/854416/75462142-115bb780-5984-11ea-9028-c401a8e47053.png)

**Comment by berak** [comment] 2020-03-07 10:06
a much simpler :
```
model = torch.nn.LSTM(256, 2, 1, bidirectional=False)
model.eval()
dummy_input = torch.randn(1, 37, 256)
torch.onnx.export(model, dummy_input, "crnn.onnx", verbose=True)

import cv2
net=cv2.dnn.readNet("crnn.onnx")
```

will already show all problems mentioned above:

* missing / unconnected ConstantOfShape layer (and imho, we have to rewire the  inputs in the importer, so no easy  custom layer possible)

* unconnected Slice layer inputs (constants, hopefully  https://github.com/opencv/opencv/pull/16715 will fix it)
 
* there is no bidirectional LSTM in opencv (we'd have to build one by combining 2 LSTMs, forward/reverse), also the onnx importer needs to know about it (does not even know about simple LSTM, currently)

<hr>

all in all, a ton of work, almost good for a GSOC slot on its own.

**Comment by sunice-nyy** [comment] 2020-03-16 07:17
@themechanicalcoder I have the same problem, are you fix it? use readNet or read readNetFromONNX. 
Unspecified error (Can't create layer "76" of type "ConstantOfShape") in cv::dnn::dnn4_v20191202::LayerData::getLayerInstance

**Comment by berak** [comment] 2020-03-16 07:52
@sunice-nyy  https://github.com/opencv/opencv/pull/16817 will hopefully fix it

**Comment by dkurt** [comment] 2020-03-16 08:03
Sorry! Just missed to link this issue to the PR. Will add support for bidirectional LSTM soon.

**Comment by saraansh1999** [comment] 2020-03-16 16:13
So will this fix the problem and make crnn a viable solution in time for gsoc?

**Comment by dkurt** [comment] 2020-03-16 19:55
@saraansh1999, I believe that this fix will enable the `crnn` model nothing will remain for the summer :)

**Comment by saraansh1999** [comment] 2020-03-16 20:30
Since @berak  mentioned that there is no bidirectional LSTM in opencv yet. So are solutions using bidirectional LSTM feasible to take up for the summer?

**Comment by berak** [comment] 2020-03-22 12:41
i just tried https://github.com/opencv/opencv/pull/16817 and it can at least *read* the crnn.onnx correctly ;)

thanks, @dkurt !!

**Comment by dkurt** [comment] 2020-03-22 13:00
@berak, Just added few fixes to run the model from https://github.com/opencv/opencv/issues/12533 and going to check a model from this issue.

BTW, does anybody want to prepare a sample for this model? I think it will be nice contribution.

**Comment by themechanicalcoder** [comment] 2020-03-22 13:27
> @berak, Just added few fixes to run the model from #12533 and going to check a model from this issue.
> 
> BTW, does anybody want to prepare a sample for this model? I think it will be nice contribution.
> 
> the following code at least produces output shapes:
> 
> ```python
> import numpy as np
> import cv2 as cv
> net = cv.dnn.readNet("crnn.onnx")
> inp = np.random.standard_normal([1, 1, 37, 256]).astype(np.float32)
> net.setInput(inp)
> out = net.forward()
> print(out.shape)
> ```
> 
> ```
> (65, 1, 37)
> ```
@dkurt  I was thinking to use it for the GSOC project [text rec](https://github.com/opencv/opencv/wiki/GSoC_2020#idea-reviseimprove-text--digit-recognition-samples) for scene text recognition and write a sample during the GSOC period. But if the model is working I can contribute a C++ sample before the GSOC period and continue working on the project during the GSOC period.

**Comment by berak** [comment] 2020-03-25 15:41
amazing news ;)

using the [model from meijieru](https://github.com/meijieru/crnn.pytorch) (and resp. preprocessing) i could reproduce results on the demo.png there:
![crnn](https://user-images.githubusercontent.com/854416/77555294-64f3ef00-6eb7-11ea-84a6-576f03d84a17.png)

```
    dnn::Net net = dnn::readNet("crnn.onnx");
    Mat in = imread("demo.png",0);
    in.convertTo(in,CV_32F,1.0/255);
    in -= 0.5;
    in /= 0.5;
    resize(in,in,Size(100, 32)); // fixed !
    Mat blob = blobFromImage(in);
    net.setInput(blob);
    Mat res = net.forward(); // 26 x 1 x 37
    string alphabet = "0123456789abcdefghijklmnopqrstuvwxyz"; // 10 nums + 26 letters + 1 = 37

    for (size_t r=0; r<res.size[0]; r++) {
        Mat slice = Mat(1,res.size[2],CV_32F,res.ptr<float>(r));
        Point p; double m;
        minMaxLoc(slice, 0, &m, 0, &p);
        char c = p.x>0 ? alphabet[p.x-1] : '-'; // '-' == no detection
        cout << r << "\t" << c << "\t" << p << "\t" << m << endl;
    }

0       a       [11, 0] -84.5621
1       -       [0, 0]  -64.7243
2       -       [0, 0]  -57.1287
3       -       [0, 0]  -41.7201
4       -       [0, 0]  -55.4314
5       -       [0, 0]  -63.6334
6       v       [32, 0] -100.808
7       -       [0, 0]  -46.9045
8       -       [0, 0]  -60.1601
9       a       [11, 0] -79.15
10      -       [0, 0]  -56.0937
11      i       [19, 0] -83.8074
12      -       [0, 0]  -60.5409
13      l       [22, 0] -88.1379
14      -       [0, 0]  -69.5504
15      a       [11, 0] -74.0695
16      -       [0, 0]  -61.5555
17      b       [12, 0] -85.9853
18      b       [12, 0] -35.0758
19      -       [0, 0]  -77.5764
20      l       [22, 0] -73.1142
21      l       [22, 0] -67.7525
22      e       [15, 0] -71.5772
23      -       [0, 0]  -61.0475
24      -       [0, 0]  -60.4686
25      -       [0, 0]  -60.5497
```

imho, we can close this issue ;)

**Comment by themechanicalcoder** [comment] 2020-03-26 09:17
@berak I built the OpenCV master branch and I am still getting  error 
code
```
#include<iostream>
#include <opencv2/imgproc.hpp>
#include <opencv2/highgui.hpp>
#include <opencv2/dnn.hpp>

using namespace std;
using namespace cv;
using namespace dnn;

int main(){
    dnn::Net net = dnn::readNet("crnn.onnx");
    Mat in = imread("demo1.png",0);
    in.convertTo(in,CV_32F,1.0/255);
    in -= 0.5;
    in /= 0.5;
    resize(in,in,Size(100, 32)); // fixed !
    Mat blob = blobFromImage(in);
    net.setInput(blob);
    Mat res = net.forward(); // 26 x 1 x 37
    string alphabet = "0123456789abcdefghijklmnopqrstuvwxyz"; // 10 nums + 26 letters + 1 = 37

    for (size_t r=0; r<res.size[0]; r++) {
        Mat slice = Mat(1,res.size[2],CV_32F,res.ptr<float>(r)); // 37 one-hot encoded pins
        Point p; double m;
        minMaxLoc(slice, 0, &m, 0, &p);
        char c = p.x>0 ? alphabet[p.x-1] : '-'; // '-' == no detection
        cout << r << "\t" << c << "\t" << p << "\t" << m << endl;
    }
}
```

error
```
[ERROR:0] global /home/themechanicalcoder/Desktop/opencv/modules/dnn/src/dnn.cpp (3268) getLayerShapesRecursively OPENCV/DNN: [Reshape]:(71): getMemoryShapes() throws exception. inputs=1 outputs=1/1 blobs=0
[ERROR:0] global /home/themechanicalcoder/Desktop/opencv/modules/dnn/src/dnn.cpp (3271) getLayerShapesRecursively     input[0] = [ 1 512 1 26 ]
[ERROR:0] global /home/themechanicalcoder/Desktop/opencv/modules/dnn/src/dnn.cpp (3275) getLayerShapesRecursively     output[0] = [ ]
[ERROR:0] global /home/themechanicalcoder/Desktop/opencv/modules/dnn/src/dnn.cpp (3281) getLayerShapesRecursively Exception message: OpenCV(4.3.0-pre) /home/themechanicalcoder/Desktop/opencv/modules/dnn/src/layers/reshape_layer.cpp:113: error: (-215:Assertion failed) total(srcShape, srcRange.start, srcRange.end) == maskTotal in function 'computeShapeByReshapeMask'

terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.3.0-pre) /home/themechanicalcoder/Desktop/opencv/modules/dnn/src/layers/reshape_layer.cpp:113: error: (-215:Assertion failed) total(srcShape, srcRange.start, srcRange.end) == maskTotal in function 'computeShapeByReshapeMask'
```
OperatingSystem-Ubuntu
GCC 7.5.0

**Comment by dkurt** [comment] 2020-03-26 09:21
@themechanicalcoder, make sure you have https://github.com/opencv/opencv/pull/16890

**Comment by themechanicalcoder** [comment] 2020-03-26 09:25
> @themechanicalcoder, make sure you have #16890

I built the master branch only is this PR not merged into the master branch?

**Comment by berak** [comment] 2020-03-26 10:08
@themechanicalcoder -- no, not in the master branch yet, either wait a few days for the next merge, or use current 3.4 branch (`git checkout 3.4`)

**Comment by themechanicalcoder** [comment] 2020-04-01 09:20
@dkurt  @berak I am building OpenCV using the tutorial from [here](https://linuxize.com/post/how-to-install-opencv-on-ubuntu-18-04/) I have tried 3.4 branch but I get the same error.
I used ``` git checkout 3.4``` before building and I have the same error.
```
[ERROR:0] OPENCV/DNN: [Reshape]:(71): getMemoryShapes() throws exception. inputs=1 outputs=1/1 blobs=0
[ERROR:0]     input[0] = [ 1 512 1 26 ]
[ERROR:0]     output[0] = [ ]
[ERROR:0] Exception message: OpenCV(3.4.10-pre) /home/themechanicalcoder/opencv_build/opencv/modules/dnn/src/layers/reshape_layer.cpp:107: error: (-215:Assertion failed) total(srcShape, srcRange.start, srcRange.end) == maskTotal in function 'computeShapeByReshapeMask'

terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(3.4.10-pre) /home/themechanicalcoder/opencv_build/opencv/modules/dnn/src/layers/reshape_layer.cpp:107: error: (-215:Assertion failed) total(srcShape, srcRange.start, srcRange.end) == maskTotal in function 'computeShapeByReshapeMask'

Aborted (core dumped)

```
Am I doing  something wrong while building because I still cannot run the code provided by @berak 
and I have the dnn_onnx_lstm pr by dkurt here is the output of ```git log```
![dnn_lstm_onnx](https://user-images.githubusercontent.com/34737471/78120694-01724000-7428-11ea-9a82-ecb2eb7d441d.png)

**Comment by dkurt** [comment] 2020-04-01 10:40
The problem is that there us a type in model conversion. You need to have 1x1x32x100 input tensor.

**Comment by PhoenixChen98** [comment] 2020-04-11 09:17
Does the crnn onnx model support dynamic input? Must the image size be fixed?

**Comment by themechanicalcoder** [comment] 2020-04-11 10:34
> Does the crnn onnx model support dynamic input? Must the image size be fixed?
Once you have converted it to ONNX format you have to use the same size of input as your dummy input.

**Comment by PhoenixChen98** [comment] 2020-04-11 11:35
> Once you have converted it to ONNX format you have to use the same size of input as your dummy input.
@themechanicalcoder Thanks.

**Closed** 2020-05-07 05:14 UTC
Labels: category: dnn, feature

**Comment by double-vane** [comment] 2020-08-18 09:50
@berak 你好，精度相比pth，会有损失吗？谢谢

**Comment by themechanicalcoder** [comment] 2020-11-29 12:30
@berak actually I am trying to develop a basic android app using this. So can I use BI-LSTM in that ?

**Comment by berak** [comment] 2020-11-29 13:20
@themechanicalcoder the java version is just a wrapper around opencv c++ code, as long as you have the resp. pr's, it must work

**Comment by hhhhhhogan** [comment] 2021-02-25 08:54
> readNet

hello，I met the same error,and when I use the model from meijieru  transform .pth to .onnx,I got error.Would you mind telling me how you convert .pth to .onnx?
