### ISSUE TITLE
YOLOv7 load model issue with OpenCV

### ISSUE THREAD

**Issue by prateekgml** [opencv/opencv#22220] opened 2022-07-09 15:59 UTC
I am using Colab where OpenCV version is 4.1.2 and while trying to do inference of a YOLOv7 model I got following error:
`error: OpenCV(4.1.2) /io/opencv/modules/dnn/src/darknet/darknet_io.cpp:554: error: (-212:Parsing error) Unsupported activation: logistic in function 'ReadDarknetFromCfgStream'`

And above error came in this line of code `net = cv2.dnn.readNet('/content/gdrive/MyDrive/yolov7/yolov7-obj.cfg', '/content/gdrive/MyDrive/yolov7/weights/yolov7-obj_final.weights')`

The weight and cfg file can be used from the following official links: [https://raw.githubusercontent.com/AlexeyAB/darknet/master/cfg/yolov7-tiny.cfg](url) and [https://github.com/AlexeyAB/darknet/releases/download/yolov4/yolov7-tiny.weights](url)

**Comment by alalek** [comment] 2022-07-09 17:00
> 4.1.2

outdated release. You need to upgrade.

---

duplicate of #22215

**Closed by alalek** 2022-07-09 17:00 UTC
Labels: duplicate

**Comment by berak** [comment] 2022-07-10 14:13
> 4.1.2

you can use

    !pip install opencv-python==4.6.0.66

to upgrade it on colab (dont forget to restart the runtime !)

**Comment by prateekgml** [comment] 2022-07-11 05:29
@berak Thanks it solved my issue.
