### ISSUE TITLE
How to resolve that opencv still use cudnnGetConvolutionForwardAlgorithm

### ISSUE THREAD

**Issue by cainsmile** [opencv/opencv#21015] opened 2021-11-06 11:42 UTC
Cudnn8.0 remove function "cudnnGetConvolutionForwardAlgorithm", but OpenCV still use it. So how to resolve it?

**Comment by alalek** [comment] 2021-11-06 14:20
duplicate of #17496

**Closed by alalek** 2021-11-06 14:20 UTC
Labels: duplicate
