### ISSUE TITLE
can't set windows fullscreen

### ISSUE THREAD

**Issue by synsis** [opencv/opencv#18644] opened 2020-10-22 09:43 UTC
##### System information (version)
- OpenCV => 4.1.1
- Operating System / Platform => ubuntu 18.4  jetson nano xavier vx jetpack 4.4 DP[l4T 32.4.2]
- Compiler => g++

##### Detailed description

The code to set the windows fullscreen is not work when in jetson nano xavier vx.
And the code to freeratio the windows is also not work in this platform.
It is aarch64 frame.

**Comment by synsis** [comment] 2020-10-22 09:47
I mean the code like this:
cv::setWindowProperty("img", cv::WND_PROP_FULLSCREEN,cv::WINDOW_FULLSCREEN);

**Comment by alalek** [comment] 2020-10-22 09:50
Properties are optional and/or may have U/I backend-specific behavior (or no handling at all).

Check `cv::getBuildinformation()` about used U/I backend.

**Comment by synsis** [comment] 2020-10-22 11:44
> Properties are optional and/or may have U/I backend-specific behavior (or no handling at all).
> 
> Check `cv::getBuildInformation()` about used U/I backend.

I checked the GUI,it shows
GUI:
  GTK+: YES(ver 2.24.32)
    GThread: YES(ver 2.56.4)
    GtkGlExt: No

Is there anything I can do to enable the fullscreen fuction?

**Comment by alalek** [comment] 2021-11-30 11:47
I believe it is duplicate of #10438

**Closed by alalek** 2021-11-30 11:47 UTC
Labels: priority: low, category: highgui-gui, incomplete
