### ISSUE TITLE
OpenCV does not respect exif orientation in PNG file

### ISSUE THREAD

**Issue by codars** [opencv/opencv#16579] opened 2020-02-13 20:52 UTC
##### System information (version)

- OpenCV => 4.2
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015

##### Detailed description

PNG format starts to [support EXIF information](http://ftp-osl.osuosl.org/pub/libpng/documents/pngext-1.5.0.html#C.eXIf) since 2017, but somehow using IMREAD_COLOR to read a PNG file does not respect the orientation

Attached Capture.png and Capture.jpg are two images both with same EXIF orientation information, try both and you can see the difference.

##### Steps to reproduce

```.cpp
    // C++ code example
    cv::Mat cvImgColor = cv::imread("Capture.png", cv::IMREAD_COLOR);
    // Expected: cols = 333, rows = 280
    // Actual: cols = 280, rows = 333
```
![tempsnip](https://user-images.githubusercontent.com/25216338/74476683-b6dc3a80-4e5e-11ea-88fd-d7bd190662df.png)

![Capture](https://user-images.githubusercontent.com/25216338/74476650-a2983d80-4e5e-11ea-9973-9643ef88bea8.png)

![Capture](https://user-images.githubusercontent.com/25216338/74477113-89dc5780-4e5f-11ea-8b14-710e018ea7b2.jpg)

**Comment by Infinity8sailor** [comment] 2020-02-24 04:56
`Python 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> import cv2
>>> img1=cv2.imread(r"C:\Users\.......\screenshots\sand_2.jpg",0)  #normal image 
>>> img2=cv2.imread(r"C:\Users\........\screenshots\sand_2p.jpg",0) #rotated 90 cc (edited on windows)
>>> img3=cv2.imread(r"C:\Users\........\screenshots\sand_2lp.jpg",0)#rotated 90 cc (edited online)
>>> np.shape(img1)  
(183, 275)
>>> np.shape(img2)
(275, 183)  #expected to be (183,275)
>>> np.shape(img3)
(275, 183) #expected to be (183,275)
`
looks like it returns converted matrix.....

**Comment by Infinity8sailor** [comment] 2020-02-25 10:21
hey i am not getting that affected file 
can you  (@alalek  )please help  where i should be searching that file???

**Comment by CodArs-van** [comment] 2020-02-25 18:10
@Infinity8sailor Hi, the affected file is the second png in my description, the 2nd image and 3rd image are png/jpg with exif information

**Comment by pandeykriti** [comment] 2020-03-09 10:11
Is this issue still open!?(@alalek )

**Comment by OsamaNabih** [comment] 2020-03-18 21:49
I've been working on this issue for a few days now. I'm extremely familiar with both the exif format now and the code that parses it. The problem is, the current code assumes the exif format found inside the JPG images only. However, PNG's format is different from JPG's, not only can it be found in any arbitrary place between IHDR and IEND, moreover, some of the tags that exist in JPG EXIF chunk were discarded, most notably the APP0 and APP1.
I am still trying to figure out how to best adjust the code, I don't want to mess with the gfrmt_png files, I'd prefer the EXIF part was handled after the actual reading of the image, similar to what is currently done for JPEG. However the current ExifReader class is built around the JPEG format.
Any guidance as to how to approach this will be helpful.

**Comment by alalek** [comment] 2020-03-18 22:33
@OsamaNabih Thank you for looking on this!

> the current code assumes the exif format found inside the JPG images only

Looks like you are right.

Not sure that we can properly adapt current `ExifReader` for other formats, at least in a reliable way (we must avoid false positives here).

Perhaps we should extend `BaseImageDecoder` to support reading of EXIF data (probably as part of `.readHeader()`).

Format-specific reader should be able to properly find EXIF chunk of data (own code or through underlying I/O library like `png_get_eXIf_1@libpng`).

Some common code (if format is the same) can be used to decode EXIF buffer. We can try to reuse some part of current `ExifReader` as `ExifDecoder` for that.

**Comment by OsamaNabih** [comment] 2020-03-18 22:49
The tiff reading parts (most of the functions in exif.hpp/cpp) may be reused, however, for the functionality pointed to in this issue (using imread), it only cares about the orientation tag.
Another question I have is that as far as I understand the EXIF format in the PNG specification doesn't have a length field, does this mean we'll be basically reading all the file to search for the exif chunk then continue until there's nothing left to read? Doesn't sound great.
For the **BaseImageDecoder** part, do you mean extending it in grfmt_base or grfmt_png?

**Comment by OsamaNabih** [comment] 2020-03-19 17:38
My bad about not including the length, while it's true it doesn't give bytes to read like the JPEG, there's a number of tiff headers to read, so we won't be going on indefinitely.

**Comment by souradeepmajumdar05** [comment] 2020-09-13 20:51
is this issue is still open? i would like to work on it.

**Comment by SanjayMarreddi** [comment] 2020-09-17 16:52
@codars Is this Issue still Open ? I would like to work on it. Could you please assign this to me !

Thanks and regards,
Sanjay Marreddi

**Comment by sturkmen72** [comment] 2020-09-17 17:34
there is my crude PR https://github.com/opencv/opencv/pull/17753 about image loading. i believe anyone want to work on EXIF should see it.

**Comment by shubhamcodez** [comment] 2021-01-01 06:11
> @OsamaNabih Thank you for looking on this!
> 
> > the current code assumes the exif format found inside the JPG images only
> 
> Looks like you are right.
> 
> Not sure that we can properly adapt current `ExifReader` for other formats, at least in a reliable way (we must avoid false positives here).
> 
> Perhaps we should extend `BaseImageDecoder` to support reading of EXIF data (probably as part of `.readHeader()`).
> 
> Format-specific reader should be able to properly find EXIF chunk of data (own code or through underlying I/O library like `png_get_eXIf_1@libpng`).
> 
> Some common code (if format is the same) can be used to decode EXIF buffer. We can try to reuse some part of current `ExifReader` as `ExifDecoder` for that.


if the issue is format specific, why not just rotate the image by 90 degrees for PNG. 

This may sound trivial but, I went through Exif's documentation and a few more repos on the same problem. 
If it's happening for every PNG file, isn't it easier to rotate the image when its format is png. 

Alternatively, it can be done after implementing the function too by, checking if output orientation was same as the required orientation. Converting it to JPEG would be inefficient I guess.

or We could implement what you have suggested if it's not trivial as I think it is. I would love to work on it.

**Comment by raaldrid** [comment] 2021-02-01 20:48
Hi @alalek, I have a PR for this issue https://github.com/opencv/opencv/pull/19439.  FYI The new test cases are dependent on image files added to opencv_extra in PR https://github.com/opencv/opencv_extra/pull/843.  I am not sure how to appropriately make pull requests reflecting that dependency.  Thank you.

**Closed** 2021-02-12 22:42 UTC
Labels: category: imgcodecs, effort: few days, feature, good first issue
