### ISSUE TITLE
Python crash when calling readNetFromTensorflow

### ISSUE THREAD

**Issue by Mowstyl** [opencv/opencv#15943] opened 2019-11-18 22:57 UTC
##### System information (version)

- OpenCV => 4.1.2
- Operating System / Platform => Windows 7 64 bit
- Compiler => Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32

##### Detailed description

I've tuned a pre-trained tensorflow model using the object_detection API.
After freezing the model and using the "tf_text_graph_ssd.py" script (the pre-trained model I used was SSD_inception_v2_coco) I generated the graph.pbtxt file.
Each time I try to load the model with
```cv.readNetFromTensorflow("frozen_inference_graph.pb", "graph.pbtxt")```
Windows immediately says Python stopped working and crashes.
The same thing happens when I try to use it in C++.

##### Steps to reproduce

```
import cv2 as cv
cv.readNetFromTensorflow("frozen_inference_graph.pb", "graph.pbtxt")
```
[frozen_inference_graph.pb](https://mega.nz/#!cEIDVIwS!P5hCTRA2MAAjkQLV6dfd0F4ZJf1ZbZBZkcVrQEfzmyg)
[graph_and_config.zip](https://github.com/opencv/opencv/files/3860944/graph_and_config.zip)

**Comment by Mowstyl** [comment] 2019-11-19 12:04
##### Also happens on
- OpenCV => 4.1.2-dev (just compiled from source)
- Operating System / Platform => Ubuntu 19.10 64 bit
- Compiler => Python 3.7.5rc1 (default, Oct  8 2019, 16:47:45)

**Comment by GPhilo** [comment] 2019-11-20 12:58
Having the same issue on a SSD MobileNet v2 network. Generating a new pbtxt from the original pretrained checkpoint & pipeline.conf works. I also tried using my retrained network's pipeline.conf and the pretrained checkpoint and that also seems to work (no segfault in readNetFromTensorflow). The problem seems to be specific to using the new frozen_inference_graph.pb.

**Comment by Mowstyl** [comment] 2019-11-20 13:18
I was about to post the same, I've tried to use the SSD MobileNet v2 COCO network and the same error appears.
I've also created two more frozen graphs by using the optimize_for_inference tool on the graph I posted, and another one by using the TransformGraph tool to do some cleaning.
The same error for both of them.

**Comment by GPhilo** [comment] 2019-11-20 13:47
Ok, I can confirm that the error seems to be related to the newly-generated frozen_inference_graph.pb.

To reproduce the error on the released SSD MobileNet V2 checkpoint (NOTE: I'm using the latest master version of the TF Object Detection API):

1) Generate a new frozen model, starting from the checkpoint in the Model Zoo:

`python object_detection/export_inference_graph.py --pipeline_config_path path/to/ssd_mobilenet_v2_coco_2018_03_29/pipeline.config --trained_checkpoint_prefix path/to/ssd_mobilenet_v2_coco_2018_03_29/model.ckpt --output_directory path/to/ssd_mobilenet_v2_coco_2018_03_29/deploy`

2) Follow the instructions from [the OpenCV + TF Object Detection API guide](https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API):
`python scripts/tf_text_graph_ssd.py --input path/to/ssd_mobilenet_v2_coco_2018_03_29/deploy/frozen_inference_graph.pb --output path/to/ssd_mobilenet_v2_coco_2018_03_29/deploy/opencv_graph.pbtxt --config path/to/ssd_mobilenet_v2_coco_2018_03_29/deploy/pipeline.config`

3) Attempt to load the combination `path/to/ssd_mobilenet_v2_coco_2018_03_29/deploy/frozen_inference_model.pb` + `path/to/ssd_mobilenet_v2_coco_2018_03_29/deploy/opencv_graph.pbtxt`

This results in Segfault (from python, at least).

**Comment by dkurt** [comment] 2020-01-03 11:15
Can reproduce the problem with the `graph.pbtxt` from issue's description. However with the latest state of OpenCV everything works fine. Please try to regenerate `graph.pbtxt` file. Thanks!

let me close it for now

**Closed by dkurt** 2020-01-03 11:15 UTC
Labels: bug, category: dnn, priority: normal

**Comment by GPhilo** [comment] 2020-01-13 11:09
Hello, I can confirm that generating the file with the updated python scripts from the linked tutorial and loading them with a C++ build of OpenCV's master works. Thanks for looking into this!

**Comment by GentBinaku** [comment] 2020-01-30 13:58
I need help with I have stuck with this issue 3 days now, if I can't solve it maybe I loose my job

**Comment by dkurt** [comment] 2020-01-30 14:19
@GentBinaku, Can you add more technical details instead? Can you share a model& Have you tried to regenerate a `.pbtxt` file as mentioned in https://github.com/opencv/opencv/issues/15943#issuecomment-570544454?

**Comment by GentBinaku** [comment] 2020-01-30 14:28
Ok I will write a complete setup.

I have been given a tensorFiles which should be read.

frozen_inference_graph.pb and pipeline.config( Can't share these files sorry).

First step sort the graph.

import tensorflow as tf
from tensorflow.tools.graph_transforms import TransformGraph

```
with tf.gfile.FastGFile('frozen_inference_graph.pb', 'rb') as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())
    graph_def = TransformGraph(graph_def, ['image_tensor'], ['detection_boxes', 'detection_classes', 'detection_scores', 'num_detections'], ['sort_by_execution_order'])
    with tf.gfile.FastGFile('sorted_inference_graph.pb', 'wb') as f:
        f.write(graph_def.SerializeToString())
```
Which produces 
sorted_inference_graph.pb

Then 
sorted_inference_graph.pb

python3 tf_text_graph_ssd.py --input=sorted_inference_graph.pb --output=mygraph.pbtxt --config pipeline.config

Generate the pbtxt file, which we put through:

` net = cv::dnn::readNetFromTensorflow(tensorflowWeightFile,tensorflowConfigFile);`

This produces a error 

**Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6d493a7 in cv::dnn::dnn4_v20191202::(anonymous namespace)::TFImporter::populateNet(cv::dnn::dnn4_v20191202::Net) ()
   from /usr/local/lib/libopencv_dnn.so.4.2**

Checking the OpenCV branch to be sure it's master.

Branch Master 
Version 4.2.0

```
root@gentbinaku:/opt/opencv_build/opencv# git remote show origin
* remote origin
  Fetch URL: https://github.com/opencv/opencv.git
  Push  URL: https://github.com/opencv/opencv.git
  HEAD branch: master
  Remote branches:
    2.4    tracked
    3.4    tracked
    master tracked
  Local branch configured for 'git pull':
    master merges with remote master
  Local ref configured for 'git push':
    master pushes to master (local out of date

```

TF Version
```
root@gentbinaku:/opt/opencv_build/opencv#  python3 -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
v1.15.0-rc3-22-g590d6ee 1.15.0
```

**Comment by dkurt** [comment] 2020-01-30 14:41
@GentBinaku, can you use `tf_text_graph_ssd.py` from **the latest** master branch?

> dnn4_v20191202

that means you source code can be 2 months old: 

https://github.com/opencv/opencv/blob/4b0132ed7a7ca2c704b4c9abee8e2f6e180bd791/modules/dnn/include/opencv2/dnn/version.hpp#L9

**Comment by GentBinaku** [comment] 2020-01-30 14:54
Yes I did that didn't work either

**Comment by dkurt** [comment] 2020-01-30 14:58
@GentBinaku, Maybe you can try to apply this patch https://github.com/opencv/opencv/pull/16270? Or even better to rebuild OpenCV from master or share resulting `.pbtxt`?

**Comment by GentBinaku** [comment] 2020-01-30 15:46
Still nothing, sorry but I am required but NDA to not share the files.

**Comment by dkurt** [comment] 2020-01-30 16:07
@GentBinaku, try to create `.pbtxt` using `tf_text_graph_ssd.py` from origin `frozen_inference_graph.pb`. Make sure you use the latest `.py` script and OpenCV installation. Use them as well during import: `readNet("frozen_inference_graph.pb", "graph.pbtxt")`.

There is no change to debug it remotely unless you provide stacktrace or something useful.

**Comment by GentBinaku** [comment] 2020-01-31 08:29
python3 tf_text_graph_ssd.py --input=frozen_inference_graph.pb --output=mygraph.pbtxt --config pipeline.config
Scale: [0.200000-0.950000]
Aspect ratios: [1.0, 2.0, 0.5, 3.0, 0.33329999]
Reduce boxes in the lowest layer: True
Number of classes: 5
Number of layers: 6
box predictor: convolutional
Input image size: 300x300
Traceback (most recent call last):
  File "tf_text_graph_ssd.py", line 399, in <module>
    createSSDGraph(args.input, args.config, args.output)
  File "tf_text_graph_ssd.py", line 236, in createSSDGraph
    assert(graph_def.node[0].op == 'Placeholder')
AssertionError

I get this error without sorting the graph

**Comment by mungaip** [comment] 2020-02-03 13:06
Hi! 
I have encountered the same issue as @GentBinaku. I also get the assertion error when running the tf_text_graph_ssd.py script so have to sort the graph. I have attached the resulting pbtxt file and the source frozen_graph.pb and config. 

I compared the resulting pbtxt file with the [ssd_mobilenet_v2_coco_2018_03_29.pbtxt](https://github.com/opencv/opencv_extra/blob/master/testdata/dnn/ssd_mobilenet_v2_coco_2018_03_29.pbtxt), and noticed that all the Preprocessor and FeatureExtractor nodes are missing in my fine_tuned_graph.pbtxt file. I think that the segmentation fault occurs due to these missing nodes.

[graph_and_configs.zip](https://github.com/opencv/opencv/files/4147997/graph_and_configs.zip)

**Comment by dkurt** [comment] 2020-02-03 13:33
@mungaip, your model consists of quantization nodes, `FakeQuantWithMinMaxVars`. Just for interest, have you quantized it or this is new TensorFlow behavior?

![image](https://user-images.githubusercontent.com/25801568/73657204-d75c0600-46a2-11ea-866e-dbad1587e76e.png)

**Comment by mungaip** [comment] 2020-02-03 13:41
@dkurt that's true sorry! I performed transfer learning on an already quantised model. I'll try again on the non-quant ssd_mobilenet_v2 and see if it makes a difference.

**Comment by dkurt** [comment] 2020-02-03 13:51
@mungaip, I think that this example would be also useful, thanks anyway!

**Comment by mungaip** [comment] 2020-02-04 12:31
Hi @dkurt, I trained a normal ssd_mobilenet_v2 and the tf_text_graph_ssd.py script worked fine! The only issue I faced was that the readNetFromTensorflow dnn module couldn't recognise the types "FusedBatchNormV3" and "AddV2" when creating the layers. I worked around it by changing the strings to "FusedBatchNorm" and "Add" respectively in the pbtxt file. I'm using OpenCV 4.1.1. Is this something that is fixed in newer OpenCV versions?

**Comment by dkurt** [comment] 2020-02-04 14:07
@mungaip, yes, support of these layers has been added.

**Comment by diliprc96** [comment] 2020-10-09 04:48
Hi @mungaip @dkurt 

I am facing the same issue. I trained a SSD MobileNet v2 from a pretrained model. and generated the pbtxt file from tf_text_graph_ssd.py script. I have performed this many times in my system and was able to run inference.

I used a different machine now. and stuck with this. please get me through. 

Also let me know how to check if pre-trained model is already quantized. I am unaware how to find that.
