### ISSUE TITLE
DNN opencl

### ISSUE THREAD

**Issue by lhxy1991** [opencv/opencv#14897] opened 2019-06-26 09:37 UTC
- OpenCV => :net.forward() error:
- Operating System / Platform => :android imx8:
Hi，I use DNN with opencl to detect object ,tiny-yolov2, but when run net.forward() ,it's ANR ,Here is the log:

2019-05-23 23:38:51.987 15259-15259/? A/DEBUG: pid: 14020, tid: 15200, name: Thread-359  >>> com.pateonavi.naviapp <<<
2019-05-23 23:38:51.987 15259-15259/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xfffffffc
2019-05-23 23:38:51.987 15259-15259/? A/DEBUG:     r0  b5883600  r1  b59dd750  r2  a6c80d70  r3  c86c1a20
2019-05-23 23:38:51.987 15259-15259/? A/DEBUG:     r4  b5883600  r5  fffffff8  r6  a6c80d00  r7  00000000
2019-05-23 23:38:51.987 15259-15259/? A/DEBUG:     r8  c86c1a20  r9  a6c80d70  r10 b59dd750  r11 b5883784
2019-05-23 23:38:51.987 15259-15259/? A/DEBUG:     ip  f32b4d00  sp  a6c80ce8  lr  a8dd25b9  pc  a8dd6b46
2019-05-23 23:38:51.996 15259-15259/? A/DEBUG: backtrace:
2019-05-23 23:38:51.996 15259-15259/? A/DEBUG:     #00 pc 0060eb46  /data/app/com.pateonavi.naviapp-BkrRCt9MMasrSsmw12ksMg==/lib/arm/libopencv_java3.so
2019-05-23 23:38:51.996 15259-15259/? A/DEBUG:     #01 pc 0061238d  /data/app/com.pateonavi.naviapp-BkrRCt9MMasrSsmw12ksMg==/lib/arm/libopencv_java3.so
2019-05-23 23:38:51.996 15259-15259/? A/DEBUG:     #02 pc 00612677  /data/app/com.pateonavi.naviapp-BkrRCt9MMasrSsmw12ksMg==/lib/arm/libopencv_java3.so
2019-05-23 23:38:51.996 15259-15259/? A/DEBUG:     #03 pc 005c5405  /data/app/com.pateonavi.naviapp-BkrRCt9MMasrSsmw12ksMg==/lib/arm/libopencv_java3.so
2019-05-23 23:38:51.996 15259-15259/? A/DEBUG:     #04 pc 005c6265  /data/app/com.pateonavi.naviapp-BkrRCt9MMasrSsmw12ksMg==/lib/arm/libopencv_java3.so
2019-05-23 23:38:51.996 15259-15259/? A/DEBUG:     #05 pc 005b1337  /data/app/com.pateonavi.naviapp-BkrRCt9MMasrSsmw12ksMg==/lib/arm/libopencv_java3.so
2019-05-23 23:38:51.996 15259-15259/? A/DEBUG:     #06 pc 005b2331  /data/app/com.pateonavi.naviapp-BkrRCt9MMasrSsmw12ksMg==/lib/arm/libopencv_java3.so
2019-05-23 23:38:51.996 15259-15259/? A/DEBUG:     #07 pc 005b6287  /data/app/com.pateonavi.naviapp-BkrRCt9MMasrSsmw12ksMg==/lib/arm/libopencv_java3.so (cv::dnn::experimental_dnn_34_v11::Net::forward(cv::String const&)+250)
2019-05-23 23:38:51.996 15259-15259/? A/DEBUG:     #08 pc 0001bb80  /data/app/com.pateonavi.naviapp-BkrRCt9MMasrSsmw12ksMg==/lib/arm/libimageproc.so (ImageProcessor::classify(cv::Mat)+352)

Here is the code:
cv::Mat blob = cv::dnn::blobFromImage(result,1/255.f,cv::Size(224,224),cv::Scalar(),false,true);
     my_net.setInput(blob);
     cv::String outputNames = getOutputsNames();
     cv::Mat output= my_net.forward();

I use the opencvforandroidSDK ,it is correct ,but i compule it with opencl ,it is error ,
Can you give me some help?
Thanks!

**Comment by alalek** [comment] 2019-06-26 10:41
Build with debug information and capture stacktraces with symbols.

> android imx8

We don't have that, so priority => low.

You should run OpenCV tests on that device at first.

duplicate of #14753

**Closed** 2019-11-10 11:11 UTC
Labels: category: dnn, incomplete, needs investigation, platform: android, priority: low
