### ISSUE TITLE
TFLite importer: add support to SPLIT operation

### ISSUE THREAD

**Issue by dmartinez-quercus** [opencv/opencv#24965] opened 2024-02-05 10:50 UTC
### Describe the feature and motivation

I'm trying to import a TFLite model by using OpenCV (4.9.0) DNN module and it seems the "SPLIT" operation cannot be parsed. The "SPLIT" operation is commonly used in newer CNNs, so it would be nice to import TFLite models that use it.

`[ERROR:0@0.022] global tflite_importer.cpp:244 populateNet DNN/TFLite: Problem during import of operator [SPLIT]:(MartzNet/tf.split_12/split) (8/138). Exception: OpenCV(4.9.0-dev) /home/user/Software/opencv/modules/dnn/src/tflite/tflite_importer.cpp:238: error: (-213:The function/feature is not implemented) Unsupported operator type SPLIT in function 'populateNet'
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.9.0-dev) /home/user/Software/opencv/modules/dnn/src/tflite/tflite_importer.cpp:238: error: (-213:The function/feature is not implemented) Unsupported operator type SPLIT in function 'populateNet'`

**Comment by stephenm7777** [comment] 2024-03-03 09:39
Has anyone fixed this? If not, I'd like to give it a shot.

**Comment by Garvanand** [comment] 2024-03-04 07:06
### we can use TensorFlow's tflite_convert tool to convert the TFLite model to TensorFlow's Frozen Graph format (.pb) or ONNX (.onnx)

tflite_convert --output_file=model.pb --output_format=TFLITE --graph_def_file=model.tflite

**Comment by Garvanand** [comment] 2024-03-04 07:08
### By converting the TFLite model to a format supported by OpenCV, we can bypass the limitation of unsupported operations like "SPLIT" and perform inference using OpenCV's DNN module.

If the issue is still open, kindly assign the issue to me so that I can work upon it an raise a PR and close the issue

**Comment by swapnachoudhary43** [comment] 2024-03-21 10:12
Instead of using OpenCV for running the TFLite model, run the model directly using TensorFlow Lite. OpenCV project by adding support for the "SPLIT" operation in the TFLite importer.

**Comment by dmartinez-quercus** [comment] 2024-03-21 10:43
> Instead of using OpenCV for running the TFLite model, run the model directly using TensorFlow Lite. OpenCV project by adding support for the "SPLIT" operation in the TFLite importer.

I'm aware of this option. However, it is still very convenient to have support to this operation when loading TFLite models. I'm working in a project that involves loading multiple models in different formats (quantized TFLite models, Darknet, ONNX,..) and using OpenCV DNN is a good option to avoid adding multiple and "heavy" NN backends into the same C++ project.

**Comment by dmartinez-quercus** [comment] 2024-03-21 10:44
> Instead of using OpenCV for running the TFLite model, run the model directly using TensorFlow Lite. OpenCV project by adding support for the "SPLIT" operation in the TFLite importer.

I'm aware of this option. However, it is still very convenient to have support to this operation when loading TFLite models. I'm working in a project that involves loading multiple models in different formats (quantized TFLite models, Darknet, ONNX,..) and using OpenCV DNN is a good option to avoid adding multiple and "heavy" NN backends into the same C++ project.

**Closed** 2024-03-29 08:21 UTC
Labels: feature, good first issue, category: dnn
