### ISSUE TITLE
SBM_Sample.cpp: Multiple issues

### ISSUE THREAD

**Issue by A-l-e-x-a-n-d-e-r** [opencv/opencv#10736] opened 2018-01-31 08:09 UTC
##### System information (version)

- OpenCV => 3.4.0
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017 Express

##### Detailed description
Various problems with the coding of SBM_Sample.cpp.

Quoted from [here](http://answers.opencv.org/question/183414/sbm_samplecpp-is-this-disparity-map-correct/):
1. The default images should be changed from the rubberwhale images (optical flow test images) to rectified left and right images (e.g. aloeL.jpg and aloeR.jpg).
2. An appropriate minDisparity and numDisparities should be updated to match the new default images. (e.g. numDisparities = 16x10 instead of 16x5)
3. Program ignores its image parameters - if this is intentional, then remove mention of parameters. If it is not, then add and test support for them.
4. Any references to the example should be found and updated, and if there's a test that runs this program, the test should be updated as well.

##### Steps to reproduce
Look at the code of SBM_Sample.cpp

**Comment by akhandait** [comment] 2018-01-31 17:37
@alalek @A-l-e-x-a-n-d-e-r 
I looked into it. The rubberwhale images do not appear to be stereo camera left and right images as correctly pointed out here - [http://answers.opencv.org/question/183414/sbm_samplecpp-is-this-disparity-map-correct/](url).
The default images should be changed to the ones mentioned above along with their path which is currently "../data/[image.jpg]" which is incorrect.
The above images are supposed to be defaults but are the only ones which the program considers as it ignores the given parameters.

I would make the above corrections but will need some initial directions if there are any tests that run this program and need to be corrected as well.

**Comment by alalek** [comment] 2018-01-31 18:45
This file is located in tutorials_code directory. This means that it should be used for documentation snippets, but actually it doesn't (I see no references on this file).

We already have [stereo sample](https://github.com/opencv/opencv/blob/3.4.0/samples/cpp/stereo_match.cpp). We should not have multiple samples with duplicated functionality, so perhaps we should drop this orphaned snippet.

BTW, Original [commit](https://github.com/opencv/opencv/commit/8c04ae8c30b13dc55d864883e1514a143dd2e043#diff-5468625fc4d4095a6db872171175fffd) (from 2011, there is no corresponding documentation page).

**Comment by akhandait** [comment] 2018-01-31 18:49
Okay, so should I delete the file and make a commit or will you do it?

**Comment by alalek** [comment] 2018-01-31 18:50
I will.

**Comment by opalmirror** [comment] 2018-01-31 18:58
@akhandait I'd love it if you fixed this. I was quoted in the initial issue posting, and if you don't want to fix this I'll be happy to - let me know.

I looked at this a little bit more.

I don't believe there are any other references to SBM_Sample in the opencv, contrib and extra repos. The SBM_Sample.cpp is automatically picked up by cmake and added to the documentation build. There are no tests referring to the sample file. So, I think only SBM_Sample.cpp needs to be corrected.

Here's one possible approach going forward:

Problems 1 and 3 - breaking of the reading of parameters and the introduction of the inappropriate rubberwhale input images - seem to have come in the most recent commit affecting this file, just before OpenCV version 3.3.0 - _89480801b some improvements on tutorials_ .

I'd think that, for a first commit, reverting SBM_Sample.cpp to it's pre-last-commit state would be in order.

Optionally - as a second commit, recommendation 2 could be handled by defaulting to a reasonable default pair of files, if no image arguments are given, along with a matching/appropriate numDisparities (16*10 for aloe[LR].jpg).

An (optional) third commit could add parameter support for other numDisparities (rounding to a multiple of 16, as required by the cv::StereoBM algorithm), since this tends to be very specific to the disparity range of any particular left/right image pair.

**Comment by opalmirror** [comment] 2018-01-31 19:01
I had said more on correcting SBM_Sample.cpp, but just rethought that - I agree it's better to just delete this orphaned example and refer people to  [stereo sample](https://github.com/opencv/opencv/blob/3.4.0/samples/cpp/stereo_match.cpp).

**Comment by opalmirror** [comment] 2018-01-31 19:05
The worst problems (1 and 3 in the list) were introduced in git commit 89480801b8 , first released in 3.3.0 - not sure how they passed review. Just mentioning here to document finding the root cause.

**Comment by sturkmen72** [comment] 2018-01-31 19:40
>We should not have multiple samples with duplicated functionality

i just want to remind there are many couples of samples.

like 
https://github.com/opencv/opencv/blob/master/samples/cpp/edge.cpp

https://github.com/opencv/opencv/blob/master/samples/cpp/tutorial_code/ImgTrans/CannyDetector_Demo.cpp

---
https://github.com/opencv/opencv/blob/master/samples/cpp/drawing.cpp

https://github.com/opencv/opencv/blob/master/samples/cpp/tutorial_code/core/Matrix/Drawing_2.cpp

---

etc...

**Comment by vpisarev** [comment] 2018-02-01 12:23
:+1:

**Closed** 2018-02-01 12:27 UTC
Labels: category: documentation, category: samples
