### ISSUE TITLE
MFX: Unsupported extension

### ISSUE THREAD

**Issue by nedo99** [opencv/opencv#17790] opened 2020-07-09 13:34 UTC
Hi,

Running opencv installed via OpenVINO on Windows and it cannot read video. Tried several formats (MP4, AVI, etc), but still getting:
`
MFX: Unsupported extension
[ WARN:0] global opencv\modules\videoio\src\cap_msmf.cpp (680) CvCapture_MSMF::initStream Failed to set mediaType (stream 0, (352x288 @ 25) MFVideoFormat_RGB32(unsupported media type)
`
I tried installing various codecs but I still have the issue. 

Platform info:
```
4.3.0-14-g9a54a3273 (OpenVINO/2020.3)
releases/openvino/2020.3
9a54a3273da58e5992a7cf4bed1e30277f26dd22

General configuration for OpenCV 4.3.0-openvino-2020.3.0 =====================================
  Version control:               9a54a3273da58e5992a7cf4bed1e30277f26dd22

  Platform:
    Host:                        Windows 10.0.18363 AMD64
    CMake:                       3.14.5
    CMake generator:             Visual Studio 14 2015 Win64
    MSVC:                        1900
```

Any help?

Regards,
Nedim

**Comment by mshabunin** [comment] 2020-07-10 10:02
Duplicate of #17400

Please build the latest _master_ branch version or wait for OpenVINO 2020.4 (OpenCV 4.4.0)

**Closed by mshabunin** 2020-07-10 10:02 UTC
