### ISSUE TITLE
VideoCapture has Memory leak in opencv4.0.0

### ISSUE THREAD

**Issue by yanchao12122** [opencv/opencv#13255] opened 2018-11-23 02:12 UTC
- OpenCV => 4.0.0
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015

In the following code, 
the memory will increase slowly along with the time elapsed.

```
int main()
{
	cv::VideoCapture cap;
	cv::Mat frame;
	while (true) {
		cap.open(0);
		cap >> frame;
		cv::imshow("vidoe", frame);
		cv::waitKey(10);
		cap.release();
	}
	return 0;
}
```

**Comment by peters** [comment] 2018-11-26 09:20
@yanchao12122 Could you please verify the following

1) If you remove `cv::imshow("vidoe", frame);` is the memory leak still present?

```cxx
int main()
{
	cv::VideoCapture cap;
	cv::Mat frame;
	while (true) {
		cap.open(0);
		cap >> frame;
		cap.release();
	}
	return 0;
}
```

2) If you only open capture once, is the memory leak still present?

```cxx
int main()
{
	cv::VideoCapture cap;
	cv::Mat frame;
	cap.open(0);
	while (true) 
        {
	      if(!cap.read(frame))
              {
                  break;
              }
	}
	return 0;
}
````

**Comment by yanchao12122** [comment] 2018-11-27 13:06
1.  I have test the following code  in win10, vs2015, the memory still increase all the time.
```
int main()
{
	cv::VideoCapture cap;
	cv::Mat frame;
	while (true) {
		cap.open(0);
		cap >> frame;
		cap.release();
	}
	return 0;
}
```

2.  If I only open capture once, there is no memory leak existing.

**Comment by peters** [comment] 2018-11-28 10:32
@yanchao12122 Which backend are you using?

**Comment by alalek** [comment] 2018-12-01 03:32
https://docs.opencv.org/3.4/d0/da7/videoio_overview.html

Debug flags: https://docs.opencv.org/3.4/de/db1/group__videoio__registry.html

**Comment by yanchao12122** [comment] 2018-12-01 06:07
I don't specify any backend, just use the default.

**Comment by alalek** [comment] 2018-12-01 09:35
"Default" is auto selection which result depends on concrete environment. We need to know what backend is used.

**Comment by yanchao12122** [comment] 2018-12-01 10:11
I have test the backed using "cap.open(0, cv::CAP_DSHOW)",
the memory leak just happened with this backed.

**Comment by Bleach665** [comment] 2018-12-05 22:11
I confirm memory leak. Not sure about DSHOW, but MSMF backend consume a lot of memory.
If DSHOW used mem leak is (or is it not leak) 5 Kb per 1000 iteration. 1 time (from 3) app was terminated, unfortunately I dont remember error code.
And if MSMF used - 550 Mb(1) memory leak for 1000 iteration.
Also if used MSMF 
````cap.release();````
produce to std output warning
````[ WARN:0] terminating async callback````, 
sometime [ WARN:x], x=1..5

OpenCV 3.4 build ccf96b9e050a1d99cf5f053d13958dc39d4b5609
Win 10 x64, VS 15.9.2

Code for test:
```
cv::VideoCapture cap;
cv::Mat frame;
int iBackend = cv::CAP_MSMF;//or CAP_MSMF
cap.open(0, iBackend);
cap >> frame;
cap.release();
std::cout << "wait Enter";
getchar(); //check mem size here
std::cout << "start";
for (int i = 0; i < 1000;++i) {
	cap.open(0, iBackend);
	cap >> frame;
	cap.release();
}
std::cout << "end"; //end here
getchar();
```

**Comment by SecT0uch** [comment] 2019-02-06 12:30
Exactly same problem than @Bleach665 using 4.0.0 Windows 10 x64

**Comment by filippk** [comment] 2019-03-05 14:33
Same problem, opencv 4.0.1 Windows 10x64 MSVS 2015

**Comment by SecT0uch** [comment] 2019-03-05 15:13
@alalek what info do you need?

**Comment by alalek** [comment] 2019-03-06 10:24
MSVS memory profiler is not able to show exact reason of the problem.
Some callbacks are not destroyed (refcount is not zero), but reason is unclear because 97% callbacks were released successfully and OpenCV's references are released.
Callback's memory consumption is about few kB, but leak is about several Mb. Also most part of allocations are not available via MSVS memory profiler.

> [ WARN:0] terminating async callback,
sometime [ WARN:x], x=1..5

0,1..5 numbers mean threadID. So, the last reference of Callback has been released from some worker threads (perhaps created by MSMF).

General usage work well:
- single VideoCapture open
- read multiple frames
- significant leaks are not observed

---

Currently, leak is observed with periodic opening/closing of VideoCapture only.
It is not primary scheme of OpenCV usage, so priority of this is low.

**Comment by yinguobing** [comment] 2019-03-07 01:21
Good to know the leak is confirmed. We had switch to thread pool to avoiding frequently creating/destroying thread with VideoCapture. This could be a temporary option.

**Comment by mshabunin** [comment] 2020-02-12 11:29
Can not reproduce with latest _master_ branch version, neither DSHOW, not MSMF backends do not show any leaks:

CAP_DSHOW
<img width="409" alt="mem_dshow" src="https://user-images.githubusercontent.com/3304494/74331089-f72ab280-4da3-11ea-9dff-32b1a68e6336.png">

CAP_MSMF
<img width="411" alt="mem_msmf" src="https://user-images.githubusercontent.com/3304494/74331092-f85bdf80-4da3-11ea-8491-9f553fc73453.png">

Is this problem still valid?

**Comment by fogelton** [comment] 2020-02-12 13:27
I think there it is on your graphs, it is small, the open procedure is causing it, it was msmf in my case. try to run it for a day to see the difference. bugs usually do not disappear on their own...

**Comment by mshabunin** [comment] 2020-02-14 13:37
I've been able to reproduce small leak with MSMF backend, ~3-4 Kb per camera open-read-close operation. I've not found any evidences of leaks in OpenCV, so it could be a problem in MediaFoundation. In order to prove or deny this we need standalone example application based only on MediaFoundation which will perform same operations and check it for leaks.

**Comment by linchiyu** [comment] 2020-08-01 18:54
Had this issue on opencv4*, 3.4.4
When installed opencv 3.4.2.16 the warning disappeared

**Closed** 2020-12-13 07:44 UTC
Labels: category: 3rdparty, category: videoio(camera), incomplete, needs investigation, platform: win32, priority: low

**Comment by Jasurbek-Tursunov** [comment] 2025-01-07 08:59
Memory leak of 300-400 MB at 75 iterations of reading

Debian 12 
OpenCV 4.10
GCC 12.2
VideoCapture Backend FFMPEG

This code is golang code using GoCV, but everything related to golang has been tested using a profiler.

`func processing(inputPath string) {
	input, err := gocv.VideoCaptureFile(inputPath)
	if err != nil {
		fmt.Print(err)
		return
	}
	defer input.Close()

	frame := gocv.NewMat()
	defer frame.Close()

	for {
		if !input.Read(&frame) {
			break
		}
	}
}`
