### ISSUE TITLE
cudnn 9.0 support...

### ISSUE THREAD

**Issue by jiapei100** [opencv/opencv#25192] opened 2024-03-10 05:13 UTC
### Describe the feature and motivation

```bash
[ 33%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/layers/recurrent_layers.cpp.o
cd ....../opencv/build/modules/dnn && /usr/bin/c++ -DCVAPI_EXPORTS -DCV_CUDA4DNN=1 -DENABLE_PLUGINS -DOPENCV_DNN_EXTERNAL_PROTOBUF=1 -DPROTOBUF_USE_DLLS -DVK_NO_PROTOTYPES -D_USE_MATH_DEFINES -D__OPENCV_BUILD=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I....../opencv/build/3rdparty/ippicv/ippicv_lnx/icv/include -I....../opencv/build -I/usr/include/vulkan -I....../opencv/modules/dnn/include -I....../opencv/build/modules/dnn -I....../opencv_contrib/modules/cudev/include -I....../opencv/modules/core/include -I....../opencv/modules/imgproc/include -isystem /usr/include/eigen3/Eigen -isystem /usr/local/cuda/include -isystem /usr/include/eigen3 -fsigned-char -ffast-math -fno-finite-math-only -W -Wall -Wreturn-type -Wnon-virtual-dtor -Waddress -Wsequence-point -Wformat -Wformat-security -Winit-self -Wpointer-arith -Wsign-promo -Wuninitialized -Wsuggest-override -Wno-delete-non-virtual-dtor -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -Wno-long-long -pthread -fno-omit-frame-pointer -pg -g  -msse -msse2 -msse3 -fvisibility=hidden -fvisibility-inlines-hidden -fopenmp -Wno-deprecated -Wno-missing-declarations -Wno-shadow -Wno-unused-parameter -Wno-sign-compare -Wno-undef -Wno-invalid-offsetof -O3 -DNDEBUG  -DNDEBUG -std=c++17 -fPIC -MD -MT modules/dnn/CMakeFiles/opencv_dnn.dir/src/layers/recurrent_layers.cpp.o -MF CMakeFiles/opencv_dnn.dir/src/layers/recurrent_layers.cpp.o.d -o CMakeFiles/opencv_dnn.dir/src/layers/recurrent_layers.cpp.o -c ....../opencv/modules/dnn/src/layers/recurrent_layers.cpp
In file included from ....../opencv/modules/dnn/src/layers/../cuda4dnn/primitives/../../cuda4dnn/csl/cudnn.hpp:8,
                 from ....../opencv/modules/dnn/src/layers/../cuda4dnn/primitives/../../op_cuda.hpp:12,
                 from ....../opencv/modules/dnn/src/layers/../cuda4dnn/primitives/recurrent_cells.hpp:8,
                 from ....../opencv/modules/dnn/src/layers/recurrent_layers.cpp:49:
....../opencv/modules/dnn/src/layers/../cuda4dnn/primitives/../csl/cudnn/recurrent.hpp: In instantiation of ‘cv::dnn::cuda4dnn::csl::cudnn::RNNDescriptor<T>::RNNDescriptor(const cv::dnn::cuda4dnn::csl::cudnn::Handle&, RNNMode, int, int, bool, const cv::dnn::cuda4dnn::csl::cudnn::DropoutDescriptor&) [with T = __half]’:
....../opencv/modules/dnn/src/layers/../cuda4dnn/primitives/../csl/tensor_ops.hpp:541:23:   required from ‘cv::dnn::cuda4dnn::csl::LSTM<T>::LSTM(cv::dnn::cuda4dnn::csl::cudnn::Handle, const params_type&) [with T = __half]’
....../opencv/modules/dnn/src/layers/../cuda4dnn/primitives/recurrent_cells.hpp:48:21:   required from ‘cv::dnn::cuda4dnn::LSTMOp<T>::LSTMOp(cv::dnn::cuda4dnn::csl::Stream, cv::dnn::cuda4dnn::csl::cudnn::Handle, const cv::Mat&, const cv::Mat&, const cv::Mat&, const cv::dnn::cuda4dnn::RNNConfiguration&) [with T = __half]’
....../opencv/modules/dnn/src/layers/../cuda4dnn/primitives/../../op_cuda.hpp:194:37:   required from ‘cv::Ptr<cv::dnn::dnn4_v20231225::BackendNode> cv::dnn::make_cuda_node(int, Args&& ...) [with NodeType = cuda4dnn::LSTMOp; Args = {cuda4dnn::csl::Stream, cuda4dnn::csl::cudnn::Handle, cv::Mat&, cv::Mat&, cv::Mat&, cuda4dnn::RNNConfiguration&}]’
....../opencv/modules/dnn/src/layers/recurrent_layers.cpp:763:48:   required from here
....../opencv/modules/dnn/src/layers/../cuda4dnn/primitives/../csl/cudnn/recurrent.hpp:122:58: error: ‘cudnnSetRNNDescriptor_v6’ was not declared in this scope; did you mean ‘cudnnSetRNNDescriptor_v8’?
  122 |             CUDA4DNN_CHECK_CUDNN(cudnnSetRNNDescriptor_v6(
....../opencv/modules/dnn/src/layers/../cuda4dnn/primitives/../../cuda4dnn/csl/cudnn/cudnn.hpp:22:53: note: in definition of macro ‘CUDA4DNN_CHECK_CUDNN’
   22 |     ::cv::dnn::cuda4dnn::csl::cudnn::detail::check((call), CV_Func, __FILE__, __LINE__)
      |                                                     ^~~~
....../opencv/modules/dnn/src/layers/../cuda4dnn/primitives/../csl/cudnn/recurrent.hpp: In instantiation of ‘size_t cv::dnn::cuda4dnn::csl::cudnn::getRNNWorkspaceSize(const Handle&, const RNNDescriptor<T>&, int, const TensorDescriptorsArray<T>&) [with T = __half; size_t = long unsigned int]’:
....../opencv/modules/dnn/src/layers/../cuda4dnn/primitives/../csl/tensor_ops.hpp:553:58:   required from ‘cv::dnn::cuda4dnn::csl::LSTM<T>::LSTM(cv::dnn::cuda4dnn::csl::cudnn::Handle, const params_type&) [with T = __half]’
....../opencv/modules/dnn/src/layers/../cuda4dnn/primitives/recurrent_cells.hpp:48:21:   required from ‘cv::dnn::cuda4dnn::LSTMOp<T>::LSTMOp(cv::dnn::cuda4dnn::csl::Stream, cv::dnn::cuda4dnn::csl::cudnn::Handle, const cv::Mat&, const cv::Mat&, const cv::Mat&, const cv::dnn::cuda4dnn::RNNConfiguration&) [with T = __half]’
....../opencv/modules/dnn/src/layers/../cuda4dnn/primitives/../../op_cuda.hpp:194:37:   required from ‘cv::Ptr<cv::dnn::dnn4_v20231225::BackendNode> cv::dnn::make_cuda_node(int, Args&& ...) [with NodeType = cuda4dnn::LSTMOp; Args = {cuda4dnn::csl::Stream, cuda4dnn::csl::cudnn::Handle, cv::Mat&, cv::Mat&, cv::Mat&, cuda4dnn::RNNConfiguration&}]’
....../opencv/modules/dnn/src/layers/recurrent_layers.cpp:763:48:   required from here
....../opencv/modules/dnn/src/layers/../cuda4dnn/primitives/../csl/cudnn/recurrent.hpp:166:50: error: ‘cudnnGetRNNWorkspaceSize’ was not declared in this scope; did you mean ‘cudnnGetRNNWeightSpaceSize’?
  166 |     CUDA4DNN_CHECK_CUDNN(cudnnGetRNNWorkspaceSize(handle.get(), rnnDesc.get(), seqLength,
....../opencv/modules/dnn/src/layers/../cuda4dnn/primitives/../../cuda4dnn/csl/cudnn/cudnn.hpp:22:53: note: in definition of macro ‘CUDA4DNN_CHECK_CUDNN’
   22 |     ::cv::dnn::cuda4dnn::csl::cudnn::detail::check((call), CV_Func, __FILE__, __LINE__)
      |                                                     ^~~~
....../opencv/modules/dnn/src/layers/../cuda4dnn/primitives/../csl/cudnn/recurrent.hpp: In instantiation of ‘cv::dnn::cuda4dnn::csl::cudnn::RNNDescriptor<T>::RNNDescriptor(const cv::dnn::cuda4dnn::csl::cudnn::Handle&, RNNMode, int, int, bool, const cv::dnn::cuda4dnn::csl::cudnn::DropoutDescriptor&) [with T = float]’:
....../opencv/modules/dnn/src/layers/../cuda4dnn/primitives/../csl/tensor_ops.hpp:541:23:   required from ‘cv::dnn::cuda4dnn::csl::LSTM<T>::LSTM(cv::dnn::cuda4dnn::csl::cudnn::Handle, const params_type&) [with T = float]’
....../opencv/modules/dnn/src/layers/../cuda4dnn/primitives/recurrent_cells.hpp:48:21:   required from ‘cv::dnn::cuda4dnn::LSTMOp<T>::LSTMOp(cv::dnn::cuda4dnn::csl::Stream, cv::dnn::cuda4dnn::csl::cudnn::Handle, const cv::Mat&, const cv::Mat&, const cv::Mat&, const cv::dnn::cuda4dnn::RNNConfiguration&) [with T = float]’
....../opencv/modules/dnn/src/layers/../cuda4dnn/primitives/../../op_cuda.hpp:196:37:   required from ‘cv::Ptr<cv::dnn::dnn4_v20231225::BackendNode> cv::dnn::make_cuda_node(int, Args&& ...) [with NodeType = cuda4dnn::LSTMOp; Args = {cuda4dnn::csl::Stream, cuda4dnn::csl::cudnn::Handle, cv::Mat&, cv::Mat&, cv::Mat&, cuda4dnn::RNNConfiguration&}]’
....../opencv/modules/dnn/src/layers/recurrent_layers.cpp:763:48:   required from here
....../opencv/modules/dnn/src/layers/../cuda4dnn/primitives/../csl/cudnn/recurrent.hpp:122:58: error: ‘cudnnSetRNNDescriptor_v6’ was not declared in this scope; did you mean ‘cudnnSetRNNDescriptor_v8’?
  122 |             CUDA4DNN_CHECK_CUDNN(cudnnSetRNNDescriptor_v6(
....../opencv/modules/dnn/src/layers/../cuda4dnn/primitives/../../cuda4dnn/csl/cudnn/cudnn.hpp:22:53: note: in definition of macro ‘CUDA4DNN_CHECK_CUDNN’
   22 |     ::cv::dnn::cuda4dnn::csl::cudnn::detail::check((call), CV_Func, __FILE__, __LINE__)
      |                                                     ^~~~
....../opencv/modules/dnn/src/layers/../cuda4dnn/primitives/../csl/cudnn/recurrent.hpp: In instantiation of ‘size_t cv::dnn::cuda4dnn::csl::cudnn::getRNNWorkspaceSize(const Handle&, const RNNDescriptor<T>&, int, const TensorDescriptorsArray<T>&) [with T = float; size_t = long unsigned int]’:
....../opencv/modules/dnn/src/layers/../cuda4dnn/primitives/../csl/tensor_ops.hpp:553:58:   required from ‘cv::dnn::cuda4dnn::csl::LSTM<T>::LSTM(cv::dnn::cuda4dnn::csl::cudnn::Handle, const params_type&) [with T = float]’
....../opencv/modules/dnn/src/layers/../cuda4dnn/primitives/recurrent_cells.hpp:48:21:   required from ‘cv::dnn::cuda4dnn::LSTMOp<T>::LSTMOp(cv::dnn::cuda4dnn::csl::Stream, cv::dnn::cuda4dnn::csl::cudnn::Handle, const cv::Mat&, const cv::Mat&, const cv::Mat&, const cv::dnn::cuda4dnn::RNNConfiguration&) [with T = float]’
....../opencv/modules/dnn/src/layers/../cuda4dnn/primitives/../../op_cuda.hpp:196:37:   required from ‘cv::Ptr<cv::dnn::dnn4_v20231225::BackendNode> cv::dnn::make_cuda_node(int, Args&& ...) [with NodeType = cuda4dnn::LSTMOp; Args = {cuda4dnn::csl::Stream, cuda4dnn::csl::cudnn::Handle, cv::Mat&, cv::Mat&, cv::Mat&, cuda4dnn::RNNConfiguration&}]’
....../opencv/modules/dnn/src/layers/recurrent_layers.cpp:763:48:   required from here
....../opencv/modules/dnn/src/layers/../cuda4dnn/primitives/../csl/cudnn/recurrent.hpp:166:50: error: ‘cudnnGetRNNWorkspaceSize’ was not declared in this scope; did you mean ‘cudnnGetRNNWeightSpaceSize’?
  166 |     CUDA4DNN_CHECK_CUDNN(cudnnGetRNNWorkspaceSize(handle.get(), rnnDesc.get(), seqLength,
....../opencv/modules/dnn/src/layers/../cuda4dnn/primitives/../../cuda4dnn/csl/cudnn/cudnn.hpp:22:53: note: in definition of macro ‘CUDA4DNN_CHECK_CUDNN’
   22 |     ::cv::dnn::cuda4dnn::csl::cudnn::detail::check((call), CV_Func, __FILE__, __LINE__)
      |                                                     ^~~~
....../opencv/modules/dnn/src/layers/../cuda4dnn/primitives/../csl/cudnn/recurrent.hpp: In instantiation of ‘void cv::dnn::cuda4dnn::csl::cudnn::LSTMForward(const Handle&, const RNNDescriptor<T>&, const FilterDescriptor<T>&, cv::dnn::cuda4dnn::csl::DevicePtr<const T>, const TensorDescriptorsArray<T>&, cv::dnn::cuda4dnn::csl::DevicePtr<const T>, const TensorDescriptor<T>&, cv::dnn::cuda4dnn::csl::DevicePtr<const T>, const TensorDescriptor<T>&, cv::dnn::cuda4dnn::csl::DevicePtr<const T>, int, const TensorDescriptorsArray<T>&, cv::dnn::cuda4dnn::csl::DevicePtr<T>, cv::dnn::cuda4dnn::csl::DevicePtr<T>, cv::dnn::cuda4dnn::csl::WorkspaceInstance) [with T = float]’:
....../opencv/modules/dnn/src/layers/../cuda4dnn/primitives/../csl/tensor_ops.hpp:563:34:   required from ‘void cv::dnn::cuda4dnn::csl::LSTM<T>::inference(cv::dnn::cuda4dnn::csl::TensorView<T>, cv::dnn::cuda4dnn::csl::TensorSpan<T>, cv::dnn::cuda4dnn::csl::TensorSpan<T>, cv::dnn::cuda4dnn::csl::TensorView<T>, cv::dnn::cuda4dnn::csl::TensorView<T>, cv::dnn::cuda4dnn::csl::TensorView<T>, cv::dnn::cuda4dnn::csl::WorkspaceInstance) [with T = float]’
....../opencv/modules/dnn/src/layers/../cuda4dnn/primitives/recurrent_cells.hpp:79:23:   required from ‘void cv::dnn::cuda4dnn::LSTMOp<T>::forward(const std::vector<cv::Ptr<cv::dnn::dnn4_v20231225::BackendWrapper> >&, const std::vector<cv::Ptr<cv::dnn::dnn4_v20231225::BackendWrapper> >&, cv::dnn::cuda4dnn::csl::Workspace&) [with T = float]’
....../opencv/modules/dnn/src/layers/../cuda4dnn/primitives/recurrent_cells.hpp:63:10:   required from here
....../opencv/modules/dnn/src/layers/../cuda4dnn/primitives/../csl/cudnn/recurrent.hpp:182:50: error: ‘cudnnRNNForwardInference’ was not declared in this scope
  182 |     CUDA4DNN_CHECK_CUDNN(cudnnRNNForwardInference(handle.get(), rnnDesc.get(), seqLength,
....../opencv/modules/dnn/src/layers/../cuda4dnn/primitives/../../cuda4dnn/csl/cudnn/cudnn.hpp:22:53: note: in definition of macro ‘CUDA4DNN_CHECK_CUDNN’
   22 |     ::cv::dnn::cuda4dnn::csl::cudnn::detail::check((call), CV_Func, __FILE__, __LINE__)
      |                                                     ^~~~
....../opencv/modules/dnn/src/layers/../cuda4dnn/primitives/../csl/cudnn/recurrent.hpp: In instantiation of ‘void cv::dnn::cuda4dnn::csl::cudnn::LSTMForward(const Handle&, const RNNDescriptor<T>&, const FilterDescriptor<T>&, cv::dnn::cuda4dnn::csl::DevicePtr<const T>, const TensorDescriptorsArray<T>&, cv::dnn::cuda4dnn::csl::DevicePtr<const T>, const TensorDescriptor<T>&, cv::dnn::cuda4dnn::csl::DevicePtr<const T>, const TensorDescriptor<T>&, cv::dnn::cuda4dnn::csl::DevicePtr<const T>, int, const TensorDescriptorsArray<T>&, cv::dnn::cuda4dnn::csl::DevicePtr<T>, cv::dnn::cuda4dnn::csl::DevicePtr<T>, cv::dnn::cuda4dnn::csl::WorkspaceInstance) [with T = __half]’:
....../opencv/modules/dnn/src/layers/../cuda4dnn/primitives/../csl/tensor_ops.hpp:563:34:   required from ‘void cv::dnn::cuda4dnn::csl::LSTM<T>::inference(cv::dnn::cuda4dnn::csl::TensorView<T>, cv::dnn::cuda4dnn::csl::TensorSpan<T>, cv::dnn::cuda4dnn::csl::TensorSpan<T>, cv::dnn::cuda4dnn::csl::TensorView<T>, cv::dnn::cuda4dnn::csl::TensorView<T>, cv::dnn::cuda4dnn::csl::TensorView<T>, cv::dnn::cuda4dnn::csl::WorkspaceInstance) [with T = __half]’
....../opencv/modules/dnn/src/layers/../cuda4dnn/primitives/recurrent_cells.hpp:79:23:   required from ‘void cv::dnn::cuda4dnn::LSTMOp<T>::forward(const std::vector<cv::Ptr<cv::dnn::dnn4_v20231225::BackendWrapper> >&, const std::vector<cv::Ptr<cv::dnn::dnn4_v20231225::BackendWrapper> >&, cv::dnn::cuda4dnn::csl::Workspace&) [with T = __half]’
....../opencv/modules/dnn/src/layers/../cuda4dnn/primitives/recurrent_cells.hpp:63:10:   required from here
....../opencv/modules/dnn/src/layers/../cuda4dnn/primitives/../csl/cudnn/recurrent.hpp:182:50: error: ‘cudnnRNNForwardInference’ was not declared in this scope
  182 |     CUDA4DNN_CHECK_CUDNN(cudnnRNNForwardInference(handle.get(), rnnDesc.get(), seqLength,
....../opencv/modules/dnn/src/layers/../cuda4dnn/primitives/../../cuda4dnn/csl/cudnn/cudnn.hpp:22:53: note: in definition of macro ‘CUDA4DNN_CHECK_CUDNN’
   22 |     ::cv::dnn::cuda4dnn::csl::cudnn::detail::check((call), CV_Func, __FILE__, __LINE__)
      |                                                     ^~~~
make[2]: *** [modules/dnn/CMakeFiles/opencv_dnn.dir/build.make:10634: modules/dnn/CMakeFiles/opencv_dnn.dir/src/layers/recurrent_layers.cpp.o] Error 1
make[2]: Leaving directory '....../opencv/build'
make[1]: *** [CMakeFiles/Makefile2:4141: modules/dnn/CMakeFiles/opencv_dnn.dir/all] Error 2
make[1]: Leaving directory '....../opencv/build'
make: *** [Makefile:169: all] Error 2
```

### Additional context

When is your timeline for **opencv-5.0**? 
**opencv-5.0** will be compatible with **cudnn 9.0**, right?

**Comment by opencv-alalek** [comment] 2024-03-10 06:07
duplicate of #24983

There is no reason to target that support to 5.x. At least because it is applicable for 4.x too (no blockers are determined).

Primary list of tasks for 5.0 is here: https://github.com/orgs/opencv/projects/1

**Closed by opencv-alalek** 2024-03-10 06:07 UTC
Labels: duplicate
