### ISSUE TITLE
ctest failed in opencv@4.5.3 on centos8_aarch64

### ISSUE THREAD

**Issue by Tom-python0121** [opencv/opencv#20496] opened 2021-08-04 06:55 UTC
Hello,I meet a problem:ctest failed in opencv@4.5.3 on centos8_aarch64.
### Steps to reproduce the issue

```console
[root@centos8 opencv-4.5.3]#wget -T 30 -O opencv_extra.tar.gz http://172.19.16.223/estuary/opencv_extra.tar.gz
[root@centos8 opencv-4.5.3]#tar -zxvf opencv_extra.tar.gz
[root@centos8 opencv-4.5.3]#mkdir build
[root@centos8 opencv-4.5.3]#cd build
[root@centos8 build3]#cmake .. -DBUILD_TESTS=ON -DOPENCV_TEST_DATA_PATH=../opencv_extra/testdata
[root@centos8 build3]#make -j128
[root@centos8 build3]#ctest -j128 -E '(opencv_test_dnn|opencv_test_objdetect|opencv_perf_objdetect|opencv_sanity_objdetect|opencv_test_gapi)'
Test project /root/8/opencv/build
      Start  1: opencv_test_core
      Start  2: opencv_perf_core
      Start  3: opencv_sanity_core
      Start  4: opencv_test_flann
      Start  5: opencv_test_imgproc
      Start  6: opencv_perf_imgproc
      Start  7: opencv_sanity_imgproc
      Start  8: opencv_test_ml
      Start  9: opencv_test_photo
      Start 10: opencv_perf_photo
      Start 11: opencv_sanity_photo
      Start 12: opencv_perf_dnn
      Start 13: opencv_sanity_dnn
      Start 14: opencv_test_features2d
      Start 15: opencv_perf_features2d
      Start 16: opencv_sanity_features2d
      Start 17: opencv_test_imgcodecs
      Start 18: opencv_perf_imgcodecs
      Start 19: opencv_sanity_imgcodecs
      Start 20: opencv_test_videoio
      Start 21: opencv_perf_videoio
      Start 22: opencv_sanity_videoio
      Start 23: opencv_test_calib3d
      Start 24: opencv_perf_calib3d
      Start 25: opencv_sanity_calib3d
      Start 26: opencv_test_highgui
      Start 27: opencv_test_stitching
      Start 28: opencv_perf_stitching
      Start 29: opencv_sanity_stitching
      Start 30: opencv_test_video
      Start 31: opencv_perf_video
      Start 32: opencv_sanity_video
      Start 33: opencv_perf_gapi
      Start 34: opencv_sanity_gapi
 1/34 Test  #4: opencv_test_flann ................   Passed    1.00 sec
 2/34 Test  #9: opencv_test_photo ................***Failed    0.99 sec
 3/34 Test #10: opencv_perf_photo ................***Failed    0.99 sec
 4/34 Test #11: opencv_sanity_photo ..............***Failed    0.98 sec
 5/34 Test #18: opencv_perf_imgcodecs ............   Passed    0.92 sec
 6/34 Test #19: opencv_sanity_imgcodecs ..........   Passed    0.87 sec
 7/34 Test #21: opencv_perf_videoio ..............***Failed    0.82 sec
 8/34 Test #22: opencv_sanity_videoio ............***Failed    0.78 sec
 9/34 Test #26: opencv_test_highgui ..............***Failed    0.46 sec
10/34 Test #27: opencv_test_stitching ............***Failed    0.40 sec
11/34 Test #16: opencv_sanity_features2d .........***Failed    8.08 sec
12/34 Test #13: opencv_sanity_dnn ................***Failed   12.80 sec
13/34 Test #30: opencv_test_video ................***Failed   16.67 sec
14/34 Test #20: opencv_test_videoio ..............***Failed   18.96 sec
15/34 Test  #8: opencv_test_ml ...................***Failed   20.60 sec
16/34 Test #29: opencv_sanity_stitching ..........***Failed   20.46 sec
17/34 Test #32: opencv_sanity_video ..............***Failed   21.01 sec
18/34 Test #25: opencv_sanity_calib3d ............***Failed   32.25 sec
19/34 Test #14: opencv_test_features2d ...........***Failed   67.56 sec
20/34 Test #17: opencv_test_imgcodecs ............***Failed   74.98 sec
21/34 Test #23: opencv_test_calib3d ..............***Failed  164.01 sec
22/34 Test  #5: opencv_test_imgproc ..............***Failed  213.12 sec
23/34 Test #12: opencv_perf_dnn ..................***Failed  262.93 sec
24/34 Test  #1: opencv_test_core .................***Failed  292.19 sec
25/34 Test #15: opencv_perf_features2d ...........***Failed  294.41 sec
26/34 Test  #7: opencv_sanity_imgproc ............***Failed  311.62 sec
27/34 Test #31: opencv_perf_video ................***Failed  316.94 sec
28/34 Test  #3: opencv_sanity_core ...............***Failed  345.97 sec
29/34 Test #28: opencv_perf_stitching ............***Failed  388.06 sec
30/34 Test #34: opencv_sanity_gapi ...............***Failed  391.92 sec
31/34 Test #24: opencv_perf_calib3d ..............***Failed  592.26 sec
32/34 Test #33: opencv_perf_gapi .................***Failed  949.87 sec
33/34 Test  #6: opencv_perf_imgproc ..............***Failed  1179.59 sec
34/34 Test  #2: opencv_perf_core .................   Passed  1676.38 sec

12% tests passed, 30 tests failed out of 34

Label Time Summary:
Accuracy             = 870.93 sec*proc (12 tests)
Main                 = 7680.85 sec*proc (34 tests)
Performance          = 5663.17 sec*proc (11 tests)
Sanity               = 1146.76 sec*proc (11 tests)
opencv_calib3d       = 788.51 sec*proc (3 tests)
opencv_core          = 2314.54 sec*proc (3 tests)
opencv_dnn           = 275.73 sec*proc (2 tests)
opencv_features2d    = 370.05 sec*proc (3 tests)
opencv_flann         =   1.00 sec*proc (1 test)
opencv_gapi          = 1341.79 sec*proc (2 tests)
opencv_highgui       =   0.46 sec*proc (1 test)
opencv_imgcodecs     =  76.77 sec*proc (3 tests)
opencv_imgproc       = 1704.33 sec*proc (3 tests)
opencv_ml            =  20.60 sec*proc (1 test)
opencv_photo         =   2.96 sec*proc (3 tests)
opencv_stitching     = 408.93 sec*proc (3 tests)
opencv_video         = 354.62 sec*proc (3 tests)
opencv_videoio       =  20.57 sec*proc (3 tests)

Total Test time (real) = 1676.44 sec

The following tests FAILED:
          1 - opencv_test_core (Failed)
          3 - opencv_sanity_core (Failed)
          5 - opencv_test_imgproc (Failed)
          6 - opencv_perf_imgproc (Failed)
          7 - opencv_sanity_imgproc (Failed)
          8 - opencv_test_ml (Failed)
          9 - opencv_test_photo (Failed)
         10 - opencv_perf_photo (Failed)
         11 - opencv_sanity_photo (Failed)
         12 - opencv_perf_dnn (Failed)
         13 - opencv_sanity_dnn (Failed)
         14 - opencv_test_features2d (Failed)
         15 - opencv_perf_features2d (Failed)
         16 - opencv_sanity_features2d (Failed)
         17 - opencv_test_imgcodecs (Failed)
         20 - opencv_test_videoio (Failed)
         21 - opencv_perf_videoio (Failed)
         22 - opencv_sanity_videoio (Failed)
         23 - opencv_test_calib3d (Failed)
         24 - opencv_perf_calib3d (Failed)
         25 - opencv_sanity_calib3d (Failed)
         26 - opencv_test_highgui (Failed)
         27 - opencv_test_stitching (Failed)
         28 - opencv_perf_stitching (Failed)
         29 - opencv_sanity_stitching (Failed)
         30 - opencv_test_video (Failed)
         31 - opencv_perf_video (Failed)
         32 - opencv_sanity_video (Failed)
         33 - opencv_perf_gapi (Failed)
         34 - opencv_sanity_gapi (Failed)
Errors while running CTest
```
Can you tell me why it has such a problem? How to fix it?

**Comment by asmorkalov** [comment] 2021-08-04 08:13
CTest wrapper for OpenCV tests produces xml reports in JUnit format. Please check your build folder for reports and most probably you'll find the failure reason there.

**Comment by alalek** [comment] 2021-08-04 08:20
Your steps look correct. However, CTest way is not well maintained and not used on public CI.

`opencv_test_highgui` is likely failed due to missing GUI setup (it is not able to show windows from console, you need some tricks like `xvfb-run`).
`opencv_test_photo` - it is hard to say that is wrong here without logs. Perhaps it is caused by FP computation difference between platforms (x86 / ARM).

**Comment by Tom-python0121** [comment] 2021-08-04 08:20
Too many errors are reported in my test cases. Is it because many compilation options of my cmake are not enabled?

**Comment by Tom-python0121** [comment] 2021-08-04 08:35
Have you ever tested it on other platforms that are successful?

**Comment by Tom-python0121** [comment] 2021-08-06 02:58
I found that so many cases failed because of a problem with my compilation parameter -DOPENCV_TEST_DATA_PATH. Now I retested it and only two cases failed:
```console
root@centos8:~#spack install --keep-stage -v opencv@4.5.3
root@centos8:~#spack load opencv@4.5.3
root@centos8:~#spack cd opencv@4.5.3
root@centos8:spack-src#export LD_LIBRARY_PATH=/home/spack/opt/spack/linux-ubuntu18.04-aarch64/gcc-7.5.0/opencv-4.5.3-iakgpjdq72lxxha2mmokltmnw3dyor2b/lib
root@centos8:spack-src#export CPATH=/home/spack/opt/spack/linux-ubuntu18.04-aarch64/gcc-7.5.0/opencv-4.5.3-iakgpjdq72lxxha2mmokltmnw3dyor2b/include
root@centos8:spack-stage-opencv-4.5.3-iakgpjdq72lxxha2mmokltmnw3dyor2b#wget -T 30 -O opencv_extra.tar.gz http://172.19.16.223/estuary/opencv_extra.tar.gz
root@centos8:spack-stage-opencv-4.5.3-iakgpjdq72lxxha2mmokltmnw3dyor2b#tar -zxvf opencv_extra.tar.gz
root@centos8:spack-stage-opencv-4.5.3-iakgpjdq72lxxha2mmokltmnw3dyor2b#cd spack-src
root@centos8:spack-src#mkdir build
root@centos8:spack-src#cd build
root@centos8:build#. ../../spack-build-env.txt
root@centos8:build#export ACLOCAL_PATH=/home/spack/opt/spack/linux-ubuntu18.04-aarch64/gcc-7.5.0/pkgconf-1.7.3-wzqfkxjzvw2b4soe2pkpoyhqwi6c3bkk/share/aclocal
root@centos8:build#cmake .. -DBUILD_TESTS=ON -DOPENCV_TEST_DATA_PATH=../opencv_extra/testdata
root@centos8:build#make -j96
root@centos8:build#ctest -j96 -E '(opencv_test_dnn|opencv_test_objdetect|opencv_perf_objdetect|opencv_sanity_objdetect|opencv_test_gapi)'
Test project /home/stage/root/spack-stage-opencv-4.5.3-iakgpjdq72lxxha2mmokltmnw3dyor2b/spack-src/build
      Start  1: opencv_test_core
      Start  2: opencv_perf_core
      Start  3: opencv_sanity_core
      Start  4: opencv_test_flann
      Start  5: opencv_test_imgproc
      Start  6: opencv_perf_imgproc
      Start  7: opencv_sanity_imgproc
      Start  8: opencv_test_ml
      Start  9: opencv_test_photo
      Start 10: opencv_perf_photo
      Start 11: opencv_sanity_photo
      Start 12: opencv_perf_dnn
      Start 13: opencv_sanity_dnn
      Start 14: opencv_test_features2d
      Start 15: opencv_perf_features2d
      Start 16: opencv_sanity_features2d
      Start 17: opencv_test_imgcodecs
      Start 18: opencv_perf_imgcodecs
      Start 19: opencv_sanity_imgcodecs
      Start 20: opencv_test_videoio
      Start 21: opencv_perf_videoio
      Start 22: opencv_sanity_videoio
      Start 23: opencv_test_calib3d
      Start 24: opencv_perf_calib3d
      Start 25: opencv_sanity_calib3d
      Start 26: opencv_test_highgui
      Start 27: opencv_test_stitching
      Start 28: opencv_perf_stitching
      Start 29: opencv_sanity_stitching
      Start 30: opencv_test_video
      Start 31: opencv_perf_video
      Start 32: opencv_sanity_video
      Start 33: opencv_perf_gapi
      Start 34: opencv_sanity_gapi
 1/34 Test  #4: opencv_test_flann ................   Passed    0.07 sec
 2/34 Test #19: opencv_sanity_imgcodecs ..........   Passed    0.06 sec
 3/34 Test #22: opencv_sanity_videoio ............   Passed    0.05 sec
 4/34 Test #26: opencv_test_highgui ..............***Failed    0.05 sec
 5/34 Test #18: opencv_perf_imgcodecs ............   Passed    0.20 sec
 6/34 Test #21: opencv_perf_videoio ..............   Passed    0.24 sec
 7/34 Test #11: opencv_sanity_photo ..............   Passed    2.14 sec
 8/34 Test #20: opencv_test_videoio ..............   Passed    5.71 sec
 9/34 Test #13: opencv_sanity_dnn ................   Passed    6.48 sec
10/34 Test #25: opencv_sanity_calib3d ............   Passed   12.00 sec
11/34 Test #27: opencv_test_stitching ............   Passed   15.40 sec
12/34 Test #10: opencv_perf_photo ................   Passed   19.24 sec
13/34 Test #30: opencv_test_video ................   Passed   46.21 sec
14/34 Test #32: opencv_sanity_video ..............   Passed   57.53 sec
15/34 Test  #9: opencv_test_photo ................***Failed   71.74 sec
16/34 Test #17: opencv_test_imgcodecs ............   Passed   79.19 sec
17/34 Test #12: opencv_perf_dnn ..................   Passed  108.54 sec
18/34 Test  #5: opencv_test_imgproc ..............   Passed  122.36 sec
19/34 Test #16: opencv_sanity_features2d .........   Passed  123.17 sec
20/34 Test  #8: opencv_test_ml ...................   Passed  127.46 sec
21/34 Test  #1: opencv_test_core .................   Passed  145.59 sec
22/34 Test #29: opencv_sanity_stitching ..........   Passed  170.10 sec
23/34 Test #23: opencv_test_calib3d ..............   Passed  172.95 sec
24/34 Test  #7: opencv_sanity_imgproc ............   Passed  181.32 sec
25/34 Test #14: opencv_test_features2d ...........   Passed  191.75 sec
26/34 Test  #3: opencv_sanity_core ...............   Passed  200.51 sec
27/34 Test #34: opencv_sanity_gapi ...............   Passed  230.95 sec
28/34 Test #24: opencv_perf_calib3d ..............   Passed  319.27 sec
29/34 Test #31: opencv_perf_video ................   Passed  352.93 sec
30/34 Test #33: opencv_perf_gapi .................   Passed  882.05 sec
31/34 Test  #2: opencv_perf_core .................   Passed  1311.77 sec
32/34 Test  #6: opencv_perf_imgproc ..............   Passed  1354.96 sec
33/34 Test #28: opencv_perf_stitching ............   Passed  1374.76 sec
34/34 Test #15: opencv_perf_features2d ...........   Passed  1820.31 sec

94% tests passed, 2 tests failed out of 34

Label Time Summary:
Accuracy             = 978.48 sec*proc (12 tests)
Main                 = 9507.06 sec*proc (34 tests)
Performance          = 7544.28 sec*proc (11 tests)
Sanity               = 984.30 sec*proc (11 tests)
opencv_calib3d       = 504.23 sec*proc (3 tests)
opencv_core          = 1657.86 sec*proc (3 tests)
opencv_dnn           = 115.02 sec*proc (2 tests)
opencv_features2d    = 2135.23 sec*proc (3 tests)
opencv_flann         =   0.07 sec*proc (1 test)
opencv_gapi          = 1113.00 sec*proc (2 tests)
opencv_highgui       =   0.05 sec*proc (1 test)
opencv_imgcodecs     =  79.45 sec*proc (3 tests)
opencv_imgproc       = 1658.63 sec*proc (3 tests)
opencv_ml            = 127.46 sec*proc (1 test)
opencv_photo         =  93.13 sec*proc (3 tests)
opencv_stitching     = 1560.25 sec*proc (3 tests)
opencv_video         = 456.67 sec*proc (3 tests)
opencv_videoio       =   6.00 sec*proc (3 tests)

Total Test time (real) = 1820.34 sec

The following tests FAILED:
          9 - opencv_test_photo (Failed)
         26 - opencv_test_highgui (Failed)
Errors while running CTest
root@centos8:build#cd test-reports/accuracy
root@centos8:accuracy#vim opencv_test_photo.xml
……
<properties>
<property name="ocl_memory_usage" value="0"/>
</properties>
    </testcase>
    <testcase name="bug_18180" status="run" time="0.001" classname="Photo_CalibrateRobertson">
      <failure message="unknown file&#x0A;C++ exception with description &quot;OpenCV(4.5.3) /home/stage/root/spack-stage-opencv-4.5.3-iakgpjdq72lxxha2mmokltmnw3dyor2b/spack-src/modules/photo/src/merge.cpp:335: error: (-215:Assertion failed) response.rows == LDR_SIZE &amp;&amp; response.cols == 1 &amp;&amp; response.channels() == channels in function &apos;process&apos;&#x0A;&quot; thrown in the test body." type=""><![CDATA[unknown file
C++ exception with description "OpenCV(4.5.3) /home/stage/root/spack-stage-opencv-4.5.3-iakgpjdq72lxxha2mmokltmnw3dyor2b/spack-src/modules/photo/src/merge.cpp:335: error: (-215:Assertion failed) response.rows == LDR_SIZE && response.cols == 1 && response.channels() == channels in function 'process'
" thrown in the test body.]]></failure>
    </testcase>
  </testsuite>
  <testsuite name="Photo_Inpaint" tests="1" failures="0" disabled="0" errors="0" time="0.358">
    <testcase name="regression" status="run" time="0.358" classname="Photo_Inpaint">
<properties>
<property name="ocl_memory_usage" value="0"/>
……
root@centos8:accuracy#vim opencv_test_highgui.xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites tests="3" failures="3" disabled="0" errors="0" timestamp="2021-08-06T10:07:24" time="0.001" cv_version="4.5.3" cv_version_build="4.5.3" cv_vcs_version="unknown" cv_build_type="Release" cv_build_type_build="Release" cv_compiler="/home/spack/lib/spack/env/gcc/g++  (ver 7.5.0)" cv_parallel_framework="pthreads" cv_parallel_threads="96" cv_cpu_features="NEON FP16" cv_ocl="disabled" test_tags="" test_tags_skip="mem_6gb,verylong" test_tags_force="" name="AllTests">
  <testsuite name="Highgui_GUI" tests="3" failures="3" disabled="0" errors="0" time="0.001">
    <testcase name="regression" status="run" time="0.001" classname="Highgui_GUI">
      <failure message="/home/stage/root/spack-stage-opencv-4.5.3-iakgpjdq72lxxha2mmokltmnw3dyor2b/spack-src/modules/highgui/test/test_gui.cpp:70&#x0A;Expected: destroyAllWindows() doesn&apos;t throw an exception.&#x0A;  Actual: it throws." type=""><![CDATA[/home/stage/root/spack-stage-opencv-4.5.3-iakgpjdq72lxxha2mmokltmnw3dyor2b/spack-src/modules/highgui/test/test_gui.cpp:70
Expected: destroyAllWindows() doesn't throw an exception.
  Actual: it throws.]]></failure>
      <failure message="/home/stage/root/spack-stage-opencv-4.5.3-iakgpjdq72lxxha2mmokltmnw3dyor2b/spack-src/modules/highgui/test/test_gui.cpp:71&#x0A;Expected: namedWindow(window_name) doesn&apos;t throw an exception.&#x0A;  Actual: it throws." type=""><![CDATA[/home/stage/root/spack-stage-opencv-4.5.3-iakgpjdq72lxxha2mmokltmnw3dyor2b/spack-src/modules/highgui/test/test_gui.cpp:71
Expected: namedWindow(window_name) doesn't throw an exception.
  Actual: it throws.]]></failure>
<properties>
<property name="ocl_memory_usage" value="0"/>
</properties>
    </testcase>
    <testcase name="trackbar_unsafe" status="run" time="0" classname="Highgui_GUI">
      <failure message="/home/stage/root/spack-stage-opencv-4.5.3-iakgpjdq72lxxha2mmokltmnw3dyor2b/spack-src/modules/highgui/test/test_gui.cpp:150&#x0A;Expected: destroyAllWindows() doesn&apos;t throw an exception.&#x0A;  Actual: it throws." type=""><![CDATA[/home/stage/root/spack-stage-opencv-4.5.3-iakgpjdq72lxxha2mmokltmnw3dyor2b/spack-src/modules/highgui/test/test_gui.cpp:150
Expected: destroyAllWindows() doesn't throw an exception.
  Actual: it throws.]]></failure>
      <failure message="/home/stage/root/spack-stage-opencv-4.5.3-iakgpjdq72lxxha2mmokltmnw3dyor2b/spack-src/modules/highgui/test/test_gui.cpp:151&#x0A;Expected: namedWindow(window_name) doesn&apos;t throw an exception.&#x0A;  Actual: it throws." type=""><![CDATA[/home/stage/root/spack-stage-opencv-4.5.3-iakgpjdq72lxxha2mmokltmnw3dyor2b/spack-src/modules/highgui/test/test_gui.cpp:151
Expected: namedWindow(window_name) doesn't throw an exception.
  Actual: it throws.]]></failure>
<properties>
<property name="ocl_memory_usage" value="0"/>
</properties>
    </testcase>
    <testcase name="trackbar" status="run" time="0" classname="Highgui_GUI">
      <failure message="/home/stage/root/spack-stage-opencv-4.5.3-iakgpjdq72lxxha2mmokltmnw3dyor2b/spack-src/modules/highgui/test/test_gui.cpp:188&#x0A;Expected: destroyAllWindows() doesn&apos;t throw an exception.&#x0A;  Actual: it throws." type=""><![CDATA[/home/stage/root/spack-stage-opencv-4.5.3-iakgpjdq72lxxha2mmokltmnw3dyor2b/spack-src/modules/highgui/test/test_gui.cpp:188
Expected: destroyAllWindows() doesn't throw an exception.
  Actual: it throws.]]></failure>
      <failure message="/home/stage/root/spack-stage-opencv-4.5.3-iakgpjdq72lxxha2mmokltmnw3dyor2b/spack-src/modules/highgui/test/test_gui.cpp:189&#x0A;Expected: namedWindow(window_name) doesn&apos;t throw an exception.&#x0A;  Actual: it throws." type=""><![CDATA[/home/stage/root/spack-stage-opencv-4.5.3-iakgpjdq72lxxha2mmokltmnw3dyor2b/spack-src/modules/highgui/test/test_gui.cpp:189
Expected: namedWindow(window_name) doesn't throw an exception.
  Actual: it throws.]]></failure>
<properties>
<property name="ocl_memory_usage" value="0"/>
</properties>
    </testcase>
  </testsuite>
</testsuites>
```
I want to know how to fix these two use cases?

**Comment by mshabunin** [comment] 2021-08-06 06:47
See comment by @alalek above. 

I'm closing this issue as it doesn't seem to be an actual problem. Please create a new one with specific details of a problem if you find it.

**Closed by mshabunin** 2021-08-06 06:47 UTC
Labels: test, priority: low, incomplete
