### ISSUE TITLE
Error compiling OpenCV from source

### ISSUE THREAD

**Issue by feng716** [opencv/opencv#18492] opened 2020-10-02 09:39 UTC
# version
   System ==> windows x86_64.  
   opencv:==>download from OpenCV website.  
   First use cmake to download, and then use GCC to compile in CMD.  

# Error reporting:  
gcc: error: long: No such file or directory
D:\MinGW_x86_64\bin\windres.exe: preprocessing failed.
mingw32-make[2]: *** [modules\world\CMakeFiles\opencv_world.dir\build.make:6680: modules/world/CMakeFiles/opencv_world.dir/vs_version.rc.obj] Error 1.
mingw32-make[1]: *** [CMakeFiles\Makefile2:3415: modules/world/CMakeFiles/opencv_world.dir/all] Error 2.
mingw32-make: *** [Makefile:181: all] Error 2.
## After setting the environment variables and configuration files, we are stuck in this step.
# :(

**Comment by berak** [comment] 2020-10-02 10:25
duplicate of  (#16990,  #17065, #10572) 

@feng716 , it's a problem with the windres.exe, that comes with the mingw toolchain.

it fails to parse something like `OPENCV_ALLOCATOR_STATS_TYPE=long long` and thinks the 2nd long is a filename

as a workaround, you could disable the allocator stats by adding

    -DOPENCV_ENABLE_ALLOCATOR_STATS=OFF

to your cmake cmdline

**Comment by feng716** [comment] 2020-10-02 11:24
@berak I don't seem to understand what you mean. Do you want to add entry in cmake or enter the command line?

**Comment by berak** [comment] 2020-10-02 13:10
add it to your cmake cmdline arguments, or, if using cmake-gui, edit or add a new entry there

**Comment by feng716** [comment] 2020-10-03 06:08
##### @berak thank you! I solved the problem

**Comment by berak** [comment] 2020-10-03 06:45
@feng716  -- nice ! you might close this issue now ...

**Comment by feng716** [comment] 2020-10-04 10:41
@berak But I had a new problem. My VSCode has been written“ lunch.json " tasks.json ""c_ cpp_ properties.json "Etc., but GCC still reports an error when compiling.

**Comment by feng716** [comment] 2020-10-04 10:47
@berak 
![image](https://user-images.githubusercontent.com/65810132/95013295-07183f00-0672-11eb-8f96-a6c47e733a6c.png)

**Comment by berak** [comment] 2020-10-04 11:21
we cannot help you configuring your ide, but if you use opencv4.4.1, you need to link libs like -lopencv_core441

also, please ask further questions on https://answers.opencv.org, (this is the library bug tracker)e

**Comment by feng716** [comment] 2020-10-04 13:02
# @berak OK, I'll try

**Comment by feng716** [comment] 2020-10-05 05:13
@berak I used the windows command prompt to compile the file, but I still reported an error.
![image](https://user-images.githubusercontent.com/65810132/95042429-67f45580-070c-11eb-966f-90a56191c20a.png)

**Comment by feng716** [comment] 2020-10-05 05:17
@berak I changed the G + + compiler, but still reported an error.
![image](https://user-images.githubusercontent.com/65810132/95042618-11d3e200-070d-11eb-9728-7d89736df1d8.png)

**Comment by berak** [comment] 2020-10-05 06:39
now you're not linking *any* opencv libs ....

please:

* don't post screenshots of code or errors *anywhere* (paste as text)
* close this issue, there is no opencv bug to report
* ask further questions on https://answers.opencv.org/questions/

**Closed** 2020-10-05 07:02 UTC
Labels: duplicate
