### ISSUE TITLE
ios build failed

### ISSUE THREAD

**Issue by greenhaixia** [opencv/opencv#22405] opened 2022-08-20 04:19 UTC
mac system: m1 12.5.1 (21G83)
Python 2.7.16
opencv: 4.x
opencv_contrib: 4.x

> #import "Headers/opencv2.h"
>         ^
> /Users/green/Desktop/github/ios/build/build-arm64-iphoneos/lib/Release/opencv2.framework/Headers/opencv2.h:217:9: note: in file included from /Users/green/Desktop/github/ios/build/build-arm64-iphoneos/lib/Release/opencv2.framework/Headers/opencv2.h:217:
> #import <opencv2/TEBLID.h>
>         ^
> /Users/green/Desktop/github/ios/build/build-arm64-iphoneos/lib/Release/opencv2.framework/Headers/TEBLID.h:21:5: error: redefinition of enumerator 'SIZE_256_BITS'
>     SIZE_256_BITS = 102,
>     ^
> /Users/green/Desktop/github/ios/build/build-arm64-iphoneos/lib/Release/opencv2.framework/Headers/BEBLID.h:22:5: note: previous definition is here
>     SIZE_256_BITS = 101
>     ^
> <module-includes>:1:9: note: in file included from <module-includes>:1:
> #import "Headers/opencv2.h"
>         ^
> /Users/green/Desktop/github/ios/build/build-arm64-iphoneos/lib/Release/opencv2.framework/Headers/opencv2.h:217:9: note: in file included from /Users/green/Desktop/github/ios/build/build-arm64-iphoneos/lib/Release/opencv2.framework/Headers/opencv2.h:217:
> #import <opencv2/TEBLID.h>
>         ^
> /Users/green/Desktop/github/ios/build/build-arm64-iphoneos/lib/Release/opencv2.framework/Headers/TEBLID.h:22:5: error: redefinition of enumerator 'SIZE_512_BITS'
>     SIZE_512_BITS = 103
>     ^
> /Users/green/Desktop/github/ios/build/build-arm64-iphoneos/lib/Release/opencv2.framework/Headers/BEBLID.h:21:5: note: previous definition is here
>     SIZE_512_BITS = 100,
>     ^
> <unknown>:0: error: could not build Objective-C module 'opencv2'
> Command EmitSwiftModule failed with a nonzero exit code
> 
> error: emit-module command failed with exit code 1 (use -v to see invocation)
> ** BUILD FAILED **
> 
> 
> The following build commands failed:
>         CompileSwift normal arm64 /Users/green/Desktop/github/ios/build/build-arm64-iphoneos/modules/objc_bindings_generator/ios/gen/objc/imgcodecs/ImgcodecsExt.swift (in target 'opencv2' from project 'opencv2')
>         CompileSwift normal arm64 /Users/green/Desktop/github/ios/build/build-arm64-iphoneos/modules/objc_bindings_generator/ios/gen/objc/imgproc/ImgprocExt.swift (in target 'opencv2' from project 'opencv2')
>         CompileSwift normal arm64 /Users/green/Desktop/github/ios/build/build-arm64-iphoneos/modules/objc_bindings_generator/ios/gen/objc/ml/MlExt.swift (in target 'opencv2' from project 'opencv2')
>         CompileSwift normal arm64 /Users/green/Desktop/github/ios/build/build-arm64-iphoneos/modules/objc_bindings_generator/ios/gen/objc/text/TextExt.swift (in target 'opencv2' from project 'opencv2')
>         CompileSwift normal arm64 /Users/green/Desktop/github/ios/build/build-arm64-iphoneos/modules/objc_bindings_generator/ios/gen/objc/video/VideoExt.swift (in target 'opencv2' from project 'opencv2')
>         CompileSwift normal arm64 /Users/green/Desktop/github/ios/build/build-arm64-iphoneos/modules/objc_bindings_generator/ios/gen/objc/videoio/VideoioExt.swift (in target 'opencv2' from project 'opencv2')
>         CompileSwift normal arm64 /Users/green/Desktop/github/ios/build/build-arm64-iphoneos/modules/objc_bindings_generator/ios/gen/objc/wechat_qrcode/Wechat_qrcodeExt.swift (in target 'opencv2' from project 'opencv2')
>         CompileSwift normal arm64 /Users/green/Desktop/github/ios/build/build-arm64-iphoneos/modules/objc_bindings_generator/ios/gen/objc/xfeatures2d/Xfeatures2dExt.swift (in target 'opencv2' from project 'opencv2')
>         CompileSwift normal arm64 /Users/green/Desktop/github/ios/build/build-arm64-iphoneos/modules/objc_bindings_generator/ios/gen/objc/ximgproc/XimgprocExt.swift (in target 'opencv2' from project 'opencv2')
>         CompileSwift normal arm64 /Users/green/Desktop/github/ios/build/build-arm64-iphoneos/modules/objc_bindings_generator/ios/gen/objc/aruco/ArucoExt.swift (in target 'opencv2' from project 'opencv2')
>         CompileSwift normal arm64 /Users/green/Desktop/github/ios/build/build-arm64-iphoneos/modules/objc_bindings_generator/ios/gen/objc/calib3d/Calib3dExt.swift (in target 'opencv2' from project 'opencv2')
>         CompileSwift normal arm64 /Users/green/Desktop/github/ios/build/build-arm64-iphoneos/modules/objc_bindings_generator/ios/gen/objc/core/ByteVectorExt.swift (in target 'opencv2' from project 'opencv2')
>         CompileSwift normal arm64 /Users/green/Desktop/github/ios/build/build-arm64-iphoneos/modules/objc_bindings_generator/ios/gen/objc/core/CoreExt.swift (in target 'opencv2' from project 'opencv2')
>         CompileSwift normal arm64 /Users/green/Desktop/github/ios/build/build-arm64-iphoneos/modules/objc_bindings_generator/ios/gen/objc/dnn/DnnExt.swift (in target 'opencv2' from project 'opencv2')
>         CompileSwift normal arm64 /Users/green/Desktop/github/ios/build/build-arm64-iphoneos/modules/objc_bindings_generator/ios/gen/objc/face/FaceExt.swift (in target 'opencv2' from project 'opencv2')
>         CompileSwift normal arm64 /Users/green/Desktop/github/ios/build/build-arm64-iphoneos/modules/objc_bindings_generator/ios/gen/objc/features2d/Features2dExt.swift (in target 'opencv2' from project 'opencv2')
>         CompileSwift normal arm64 /Users/green/Desktop/github/ios/build/build-arm64-iphoneos/modules/objc_bindings_generator/ios/gen/objc/core/CvTypeExt.swift (in target 'opencv2' from project 'opencv2')
>         CompileSwift normal arm64 /Users/green/Desktop/github/ios/build/build-arm64-iphoneos/modules/objc_bindings_generator/ios/gen/objc/core/DoubleVectorExt.swift (in target 'opencv2' from project 'opencv2')
>         CompileSwift normal arm64 /Users/green/Desktop/github/ios/build/build-arm64-iphoneos/modules/objc_bindings_generator/ios/gen/objc/core/FloatVectorExt.swift (in target 'opencv2' from project 'opencv2')
>         CompileSwift normal arm64 /Users/green/Desktop/github/ios/build/build-arm64-iphoneos/modules/objc_bindings_generator/ios/gen/objc/objdetect/ObjdetectExt.swift (in target 'opencv2' from project 'opencv2')
>         CompileSwift normal arm64 /Users/green/Desktop/github/ios/build/build-arm64-iphoneos/modules/objc_bindings_generator/ios/gen/objc/photo/PhotoExt.swift (in target 'opencv2' from project 'opencv2')
>         CompileSwift normal arm64 /Users/green/Desktop/github/ios/build/build-arm64-iphoneos/modules/objc_bindings_generator/ios/gen/objc/structured_light/Structured_lightExt.swift (in target 'opencv2' from project 'opencv2')
>         CompileSwift normal arm64 /Users/green/Desktop/github/ios/build/build-arm64-iphoneos/modules/objc_bindings_generator/ios/gen/objc/core/IntVectorExt.swift (in target 'opencv2' from project 'opencv2')
>         CompileSwift normal arm64 /Users/green/Desktop/github/ios/build/build-arm64-iphoneos/modules/objc_bindings_generator/ios/gen/objc/core/MatExt.swift (in target 'opencv2' from project 'opencv2')
>         CompileSwift normal arm64 /Users/green/Desktop/github/ios/build/build-arm64-iphoneos/modules/objc_bindings_generator/ios/gen/objc/core/Typealiases.swift (in target 'opencv2' from project 'opencv2')
>         EmitSwiftModule normal arm64 (in target 'opencv2' from project 'opencv2')
>         CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'opencv2' from project 'opencv2')
> (27 failures)
> ============================================================
> ERROR: Command '[u'xcodebuild', u'BITCODE_GENERATION_MODE=bitcode', u'IPHONEOS_DEPLOYMENT_TARGET=9.0', u'ARCHS=arm64', u'-sdk', u'iphoneos', u'-configuration', u'Release', u'-parallelizeTargets', u'-jobs', '8', u'-target', u'ALL_BUILD', u'build']' returned non-zero exit status 65
> ============================================================
> Traceback (most recent call last):
>   File "opencv/platforms/ios/build_framework.py", line 181, in build
>     self._build(outdir)
>   File "opencv/platforms/ios/build_framework.py", line 139, in _build
>     self.buildOne(target[0], target[1], main_build_dir, cmake_flags)
>   File "opencv/platforms/ios/build_framework.py", line 329, in buildOne
>     execute(buildcmd + ["-target", "ALL_BUILD", "build"], cwd = builddir + "/modules/objc/framework_build")
>   File "/Users/green/Desktop/github/opencv/platforms/apple/cv_build_utils.py", line 13, in execute
>     retcode = check_call(cmd, cwd = cwd)
>   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 190, in check_call
>     raise CalledProcessError(retcode, cmd)
> CalledProcessError: Command '[u'xcodebuild', u'BITCODE_GENERATION_MODE=bitcode', u'IPHONEOS_DEPLOYMENT_TARGET=9.0', u'ARCHS=arm64', u'-sdk', u'iphoneos', u'-configuration', u'Release', u'-parallelizeTargets', u'-jobs', '8', u'-target', u'ALL_BUILD', u'build']' returned non-zero exit status 65
>

**Comment by alalek** [comment] 2022-08-20 17:22
duplicate of #22206

**Closed by alalek** 2022-08-20 17:22 UTC
