### ISSUE TITLE
conversion from '<unnamed>::ufixedpoint32' to 'unsigned char' is ambiguous

### ISSUE THREAD

**Issue by X010** [opencv/opencv#11792] opened 2018-06-19 12:58 UTC
[ 54%] /data/apps/opencv/opencv-3.4.1/modules/imgproc/src/smooth.cpp: In function 'void cv::vlineSmooth1N(const FT* const*, const FT*, int, ET*, int) [with ET = unsigned char, FT = <unnamed>::ufixedpoint16]':
/data/apps/opencv/opencv-3.4.1/modules/imgproc/src/smooth.cpp:2676: error: conversion from '<unnamed>::ufixedpoint32' to 'unsigned char' is ambiguous
/data/apps/opencv/opencv-3.4.1/modules/imgproc/src/fixedpoint.inl.hpp:223: note: candidates are: <unnamed>::ufixedpoint32::operator float() const
/data/apps/opencv/opencv-3.4.1/modules/imgproc/src/fixedpoint.inl.hpp:222: note:                 <unnamed>::ufixedpoint32::operator double() const
/data/apps/opencv/opencv-3.4.1/modules/imgproc/src/fixedpoint.inl.hpp:221: note:                 <unnamed>::ufixedpoint32::operator ET() const [with ET = unsigned char]
/data/apps/opencv/opencv-3.4.1/modules/imgproc/src/smooth.cpp: In function 'void cv::vlineSmooth1N1(const FT* const*, const FT*, int, ET*, int) [with ET = unsigned char, FT = <unnamed>::ufixedpoint16]':
/data/apps/opencv/opencv-3.4.1/modules/imgproc/src/smooth.cpp:2693: error: conversion from 'const<unnamed>::ufixedpoint16' to 'unsigned char' is ambiguous
/data/apps/opencv/opencv-3.4.1/modules/imgproc/src/fixedpoint.inl.hpp:289: note: candidates are: <unnamed>::ufixedpoint16::operator float() const
/data/apps/opencv/opencv-3.4.1/modules/imgproc/src/fixedpoint.inl.hpp:288: note:                 <unnamed>::ufixedpoint16::operator double() const
/data/apps/opencv/opencv-3.4.1/modules/imgproc/src/fixedpoint.inl.hpp:287: note:                 <unnamed>::ufixedpoint16::operator ET() const [with ET = unsigned char]
/data/apps/opencv/opencv-3.4.1/modules/imgproc/src/smooth.cpp: In function 'void cv::vlineSmooth3N(const FT* const*, const FT*, int, ET*, int) [with ET = unsigned char, FT = <unnamed>::ufixedpoint16]':
/data/apps/opencv/opencv-3.4.1/modules/imgproc/src/smooth.cpp:2740: error: conversion from '<unnamed>::ufixedpoint32' to 'unsigned char' is ambiguous
/data/apps/opencv/opencv-3.4.1/modules/imgproc/src/fixedpoint.inl.hpp:223: note: candidates are: <unnamed>::ufixedpoint32::operator float() const
/data/apps/opencv/opencv-3.4.1/modules/imgproc/src/fixedpoint.inl.hpp:222: note:                 <unnamed>::ufixedpoint32::operator double() const
/data/apps/opencv/opencv-3.4.1/modules/imgproc/src/fixedpoint.inl.hpp:221: note:                 <unnamed>::ufixedpoint32::operator ET() const [with ET = unsigned char]
Building CXX object modules/imgproc/CMakeFiles/opencv_imgproc.dir/src/approx.cpp.o
/data/apps/opencv/opencv-3.4.1/modules/imgproc/src/smooth.cpp: In function 'void cv::vlineSmooth5N(const FT* const*, const FT*, int, ET*, int) [with ET = unsigned char, FT = <unnamed>::ufixedpoint16]':
/data/apps/opencv/opencv-3.4.1/modules/imgproc/src/smooth.cpp:2816: error: conversion from '<unnamed>::ufixedpoint32' to 'unsigned char' is ambiguous
/data/apps/opencv/opencv-3.4.1/modules/imgproc/src/fixedpoint.inl.hpp:223: note: candidates are: <unnamed>::ufixedpoint32::operator float() const
/data/apps/opencv/opencv-3.4.1/modules/imgproc/src/fixedpoint.inl.hpp:222: note:                 <unnamed>::ufixedpoint32::operator double() const
/data/apps/opencv/opencv-3.4.1/modules/imgproc/src/fixedpoint.inl.hpp:221: note:                 <unnamed>::ufixedpoint32::operator ET() const [with ET = unsigned char]
/data/apps/opencv/opencv-3.4.1/modules/imgproc/src/smooth.cpp: In function 'void cv::vlineSmooth(const FT* const*, const FT*, int, ET*, int) [with ET = unsigned char, FT = <unnamed>::ufixedpoint16]':
/data/apps/opencv/opencv-3.4.1/modules/imgproc/src/smooth.cpp:2919: error: conversion from '<unnamed>::ufixedpoint32' to 'unsigned char' is ambiguous
/data/apps/opencv/opencv-3.4.1/modules/imgproc/src/fixedpoint.inl.hpp:223: note: candidates are: <unnamed>::ufixedpoint32::operator float() const
/data/apps/opencv/opencv-3.4.1/modules/imgproc/src/fixedpoint.inl.hpp:222: note:                 <unnamed>::ufixedpoint32::operator double() const
/data/apps/opencv/opencv-3.4.1/modules/imgproc/src/fixedpoint.inl.hpp:221: note:                 <unnamed>::ufixedpoint32::operator ET() const [with ET = unsigned char]
[ 54%] Built target opencv_ml
[ 54%] Building CXX object modules/imgproc/CMakeFiles/opencv_imgproc.dir/src/spatialgradient.cpp.o
[ 54%] Building CXX object modules/imgproc/CMakeFiles/opencv_imgproc.dir/src/intersection.cpp.o
make[2]: *** [modules/imgproc/CMakeFiles/opencv_imgproc.dir/src/smooth.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [modules/imgproc/CMakeFiles/opencv_imgproc.dir/all] Error 2

**Comment by alalek** [comment] 2018-06-19 13:53
duplicate of #11562 #11393 
Fixed here: #11395

You should try latest code from maintenance 3.4 branch before filling an issue. Only future releases will be improved, because there is no way to amend already released code (like 3.4.1).

**Closed by alalek** 2018-06-19 13:53 UTC
Labels: duplicate

**Comment by tangjie77wd** [comment] 2018-08-25 03:59
@X010 @alalek 
Hello,guys ! I am suffering from the same issue 'smooth.cpp:2676: error: conversion from '<unnamed>::ufixedpoint32' to 'unsigned char' is ambiguous' when i make OpenCV 3.4.1 . How did you solved this issue. Any help will be much appraciate!

**Comment by Tanicgit** [comment] 2020-12-30 08:57
gcc version > 4.8.3
