### ISSUE TITLE
compile error in Parallel

### ISSUE THREAD

**Issue by skn123** [opencv/opencv#9351] opened 2017-08-12 02:06 UTC
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

##### Steps to reproduce

/home/naths/srcs/opencv/modules/core/src/parallel.cpp:442:19: error: use of
      undeclared identifier 'Range'
            pbody(Range(i, i + 1));
                  ^
1 error generated.
modules/core/CMakeFiles/opencv_core.dir/build.make:1268: recipe for target 'modules/core/CMakeFiles/opencv_core.dir/src/parallel.cpp.o' failed
make[2]: *** [modules/core/CMakeFiles/opencv_core.dir/src/parallel.cpp.o] Error 1

Latest pull from Master

**Comment by alalek** [comment] 2017-08-12 20:08
Please add "using namespace cv;" in the beginning of this file after includes.

**Comment by DSsoto** [comment] 2017-08-12 23:36
Was just about to post this same Issue. Fixed by prepending `cv::` to `Range` in a couple of places. How was this not caught by continuous integration?

**Comment by mshabunin** [comment] 2017-08-13 09:28
@DSsoto , unfortunately we don't have builds with OpenMP backend enabled in our CI.

**Comment by prakamya-mishra** [comment] 2017-08-13 13:54
Hey , I want to start contributing to opencv. I have cloned the repository . now I want to start solving an issue , can anyone guide me.
Thanks for your time.

**Comment by mshabunin** [comment] 2017-08-13 19:04
@prakamya-mishra , first you have to reproduce the issue. I guess it can be done by [compiling OpenCV](http://docs.opencv.org/3.3.0/df/d65/tutorial_table_of_content_introduction.html) with `-DWITH_OPENMP=ON` cmake option.

**Comment by prakamya-mishra** [comment] 2017-08-14 03:43
Sorry but I have a silly Question due to which I am having trouble in contributing to opencv.
I have the code cloned in my laptop, now if I want to start contributing then I should know that if there is something wrong in the code, that I get to know from GitHub issues, but how do I check it, I mean how and where should I run the opencv code? can you briefly explain my the workflow cycle from selecting an issue to working on it to testing on it then to PR.

**Comment by mshabunin** [comment] 2017-08-14 07:43
@prakamya-mishra , please take a look at the article which describes the contribution process: https://github.com/opencv/opencv/wiki/How_to_contribute

**Closed** 2017-08-14 10:31 UTC
Labels: bug, category: build/install, easy
