### ISSUE TITLE
VideoCapture rewrite multicast flux when trying to read more than one flux

### ISSUE THREAD

**Issue by D3lt4lph4** [opencv/opencv#10252] opened 2017-12-07 15:08 UTC
Hi all,

##### System information (version)
- OpenCV => 3.3.0
- Operating System / Platform => Ubuntu 16.04.3 LTS
- Compiler => python 3.5.2

##### Detailed description

When trying to display multiple flux with VideoCapture one of the flux "takes the lead" and is shown in all the windows. 

The problem occurs when trying to display multiple windows in one script as well as when starting multiple scripts to read different flux.

I am using opencv 3.3.0 compiled with the following (otherwise I can't run the VideoCapture function):
```bash
cmake -D CMAKE_BUILD_TYPE=RELEASE -D INSTALL_C_EXAMPLES=OFF -D INSTALL_PYTHON_EXAMPLES=OFF -D OPENCV_EXTRA_MODULES_PATH=/home/bdeguerre/Documents/opencv/opencv_contrib/modules -D BUILD_EXAMPLES=OFF -D BUILD_opencv_python2=ON -D WITH_FFMPEG=ON -D WITH_CUDA=0 -DENABLE_CXX11=ON -DWITH_LIBV4L=ON -D CMAKE_INSTALL_PREFIX=/usr/local BUILD_NEW_PYTHON_SUPPORT=ON -D WITH_QT=OFF -D CMAKE_SHARED_LINKER_FLAGS=-Wl,-Bsymbolic ..
```
And using ffmpeg (n3.4) configured with the following line:
```bash
./configure --enable-pic --extra-ldexeflags=-pie
```
VLC is able to read all the different sdp files without any problems.

If I have two scripts, starting one will display the correct video, then starting the second will either make the to windows display the first video or the second (the final displayed video is always the same (i.e video1), the start order of the scripts doesn't matter).

Also if I use opencv available on the official repos with some c++ code I get the same behavior. If one of the displayed image is set to gray and the other is not (still in two different programs), the same image is displayed except for the fact that one is gray and the other is not. 

##### Steps to reproduce

Here is the python script: 

```python 
import cv2

if __name__=="__main__":

    # video2 = cv2.VideoCapture('sdp_239.25.38.51.50010.sdp')
    video1 = cv2.VideoCapture('sdp_239.25.38.36.50010.sdp')

    while True:
        isRunning1, image1 = video1.read()
        # isRunning2, image2 = video2.read()
        if isRunning1:
            cv2.imshow('toto', image1)
            cv2.waitKey(10)
            pass
        # if isRunning2:
        #     cv2.imshow('azertyuiop', image2)
        #     cv2.waitKey(10)
        pass
```

here is the c++ file:

```c++
#include "opencv2/opencv.hpp"

using namespace cv;

int main(int, char**)
{
    VideoCapture cap("sdp_239.25.38.12.50010.sdp"); // open the default camera
    if(!cap.isOpened())  // check if we succeeded
        return -1;

    namedWindow("1",1);
    for(;;)
    {
        Mat frame;
        cap >> frame; // get a new frame from camera
        // Go to black&white
        // cvtColor(frame, frame, COLOR_BGR2GRAY);
        imshow("1", frame);
        if(waitKey(30) >= 0) break;
    }
    // the camera will be deinitialized automatically in VideoCapture destructor
    return 0;
}
```
And here are two examples of sdp files I use :
First:
```sdp
v=0
o=- -0 0 IN IP4 127.0.0.1
s=sdp_239.25.38.12.50010_v2.sdp
c=IN IP4 239.25.38.12
t=0 0
m=video 50010 RTP/AVP 101
a=rtpmap:101 MP4V-ES/90000
```
Second:
```sdp
v=0
o=- -0 0 IN IP4 127.0.0.1
s=sdp_239.25.38.51.50010_v2.sdp
c=IN IP4 239.25.38.51
t=0 0
m=video 50010 RTP/AVP 101
a=rtpmap:101 MP4V-ES/90000
```

Thanks for any help you can provide !

**Comment by D3lt4lph4** [comment] 2017-12-08 09:15
Do I dare ask why this was marked as a question ? This clearly looks like a bug to me... 

I just realized I haven't mention it in the previous comment, but the function works well with .mp4 files.

I am not asking for a full answer if I'm in the wrong place, but at least more than just a tag would be nice and appreciated. Just so I know what to change or were to go.

Thanks !

**Comment by alalek** [comment] 2017-12-08 09:42
Because this looks like an usage question about configuration of remote video capturing.
- there is no enough information to detect problem in OpenCV (.mp4 files works well)
- it looks like ffmpeg-related hack (like gstreamer manual pipelines) which is not officially supported (in the meaning of testing) and there are no **known** limitations of this approach.
- we are not able to reproduce this problem (additional setup is required)

Without clear reason of problem and related knowledge what should be fixed in OpenCV, we can't help here.


> VLC is able to read

Try to play with tools from your ffmpeg build at first.

**Closed** 2018-01-18 13:51 UTC
Labels: category: videoio, question (invalid)

**Comment by D3lt4lph4** [comment] 2018-01-25 12:52
Sorry for taking so long, I was assigned to other tasks and didn't have time to work that again until now.

So, the configuration changed a bit : 
opencv 3.3.1 build using this command : 
```bash
cmake -D CMAKE_BUILD_TYPE=RELEASE -D INSTALL_C_EXAMPLES=OFF -D INSTALL_PYTHON_EXAMPLES=OFF -D OPENCV_EXTRA_MODULES_PATH=/data/opencv/opencv_contrib/modules -D BUILD_EXAMPLES=OFF -D BUILD_opencv_python2=ON -D WITH_FFMPEG=ON -D WITH_CUDA=0 -DENABLE_CXX11=ON -DWITH_LIBV4L=ON -D CMAKE_INSTALL_PREFIX=/usr/local BUILD_NEW_PYTHON_SUPPORT=ON -D WITH_QT=OFF -D CMAKE_SHARED_LINKER_FLAGS=-Wl,-Bsymbolic ..
```
And ffmpeg n.3.4.1 build using:
```bash
./configure --prefix="/data/ffmpeg/ffmpeg_build"  --extra-cflags="-I/data/ffmpeg/ffmpeg_build/include" --extra-ldflags="-L/data/ffmpeg/ffmpeg_build/lib" --bindir="/data/ffmpeg/bin" --enable-nonfree --enable-pic --enable-shared
```

So, it works fine with ffplay, I can display two flux using the previous sdp files, but I cannot display two different flux (same sdp files) with opencv (one overwrite the other).

I looked a bit in the opencv code and it looks like the call to 
```c++
int err = avformat_open_input(&ic, _filename, file_iformat, &dict);
```
in cap_ffmpeg_impl.hpp causes the bug. When the second program goes to that function, the windows start to display the wrong videos. And I don't know if this is opencv or ffmpeg that causes it.
