### ISSUE TITLE
InputSize cannot be set for TextDetectionModel [Android / Java binding]

### ISSUE THREAD

**Issue by rr-rv** [opencv/opencv#20199] opened 2021-06-02 10:50 UTC
##### System information (version)
OpenCV => 4.2.5
Operating System / Platform => Android 10
Compiler => Visual Studio 2019 / Android Studio

##### Detailed description

When running a "DetectTextRectangles" from a "TextDetectionModel_EAST"
it throws the exception:
Org.Opencv.Core.CvException: 'cv::Exception: OpenCV(4.5.2) /build/master_pack-android/opencv/modules/dnn/src/model.cpp:96: error: (-201:Incorrect size of input array) Input size not specified in function 'processFrame'

##### Steps to reproduce
NB: The code might look a bit weird as it is c# in a Xamarin.Android project.

```            MatOfRotatedRect textboxesMat = new MatOfRotatedRect();
            TextDetectionModel_EAST detector = new TextDetectionModel_EAST(EastTextDetectionPath);
            detector.SetInputSize(640, 640);
            detector.DetectTextRectangles(img, textboxesMat);
```

or

```            MatOfRotatedRect textboxesMat = new MatOfRotatedRect();
            TextDetectionModel_EAST detector = new TextDetectionModel_EAST(EastTextDetectionPath);
            Size siz = new Size(640, 640);
            detector.SetInputParams(1.0, siz);
            detector.DetectTextRectangles(img, textboxesMat);
```

if you do it "the hard way" it works

```           float scoreThresh = 0.5f;
            float nmsThresh = 0.4f;
            Size siz = new Size(640, 640);
            Net net = Dnn.ReadNetFromTensorflow(EastTextDetectionPath);

            Mat blob = Dnn.BlobFromImage(img, 1.0, siz);

            net.SetInput(blob);

            JavaList<Mat> outs = new JavaList<Mat>();
            JavaList<string> outNames = new JavaList<string>();
            outNames.Add("feature_fusion/Conv_7/Sigmoid");
            outNames.Add("feature_fusion/concat_3");
            net.Forward(outs, outNames);
```

**Comment by alalek** [comment] 2021-07-15 20:26
Perhaps duplicate of #19915
Try this fix #20343 or 4.5.3 release

**Closed by alalek** 2021-07-15 20:26 UTC
Labels: bug, category: dnn, category: java bindings, duplicate, platform: android
