### ISSUE TITLE
Cmkae config incomplete, Help me how to fix.

### ISSUE THREAD

**Issue by shravankumar147** [opencv/opencv#7979] opened 2017-01-08 07:01 UTC
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDA_CUDA_LIBRARY (ADVANCED)
    linked by target "example_gpu_alpha_comp" in directory /home/shravankumar/apps/opencv-3.2.0/samples/gpu
    linked by target "example_gpu_bgfg_segm" in directory /home/shravankumar/apps/opencv-3.2.0/samples/gpu
    linked by target "example_gpu_cascadeclassifier" in directory /home/shravankumar/apps/opencv-3.2.0/samples/gpu
    linked by target "example_gpu_cascadeclassifier_nvidia_api" in directory /home/shravankumar/apps/opencv-3.2.0/samples/gpu
    linked by target "example_gpu_driver_api_multi" in directory /home/shravankumar/apps/opencv-3.2.0/samples/gpu
    linked by target "example_gpu_driver_api_stereo_multi" in directory /home/shravankumar/apps/opencv-3.2.0/samples/gpu
    linked by target "example_gpu_farneback_optical_flow" in directory /home/shravankumar/apps/opencv-3.2.0/samples/gpu
    linked by target "example_gpu_generalized_hough" in directory /home/shravankumar/apps/opencv-3.2.0/samples/gpu
    linked by target "example_gpu_hog" in directory /home/shravankumar/apps/opencv-3.2.0/samples/gpu
    linked by target "example_gpu_houghlines" in directory /home/shravankumar/apps/opencv-3.2.0/samples/gpu
    linked by target "example_gpu_morphology" in directory /home/shravankumar/apps/opencv-3.2.0/samples/gpu
    linked by target "example_gpu_multi" in directory /home/shravankumar/apps/opencv-3.2.0/samples/gpu
    linked by target "example_gpu_opengl" in directory /home/shravankumar/apps/opencv-3.2.0/samples/gpu
    linked by target "example_gpu_optical_flow" in directory /home/shravankumar/apps/opencv-3.2.0/samples/gpu
    linked by target "example_gpu_opticalflow_nvidia_api" in directory /home/shravankumar/apps/opencv-3.2.0/samples/gpu
    linked by target "example_gpu_pyrlk_optical_flow" in directory /home/shravankumar/apps/opencv-3.2.0/samples/gpu
    linked by target "example_gpu_stereo_match" in directory /home/shravankumar/apps/opencv-3.2.0/samples/gpu
    linked by target "example_gpu_stereo_multi" in directory /home/shravankumar/apps/opencv-3.2.0/samples/gpu
    linked by target "example_gpu_super_resolution" in directory /home/shravankumar/apps/opencv-3.2.0/samples/gpu
    linked by target "example_gpu_surf_keypoint_matcher" in directory /home/shravankumar/apps/opencv-3.2.0/samples/gpu
    linked by target "example_gpu_video_reader" in directory /home/shravankumar/apps/opencv-3.2.0/samples/gpu
    linked by target "example_gpu_video_writer" in directory /home/shravankumar/apps/opencv-3.2.0/samples/gpu

-- Configuring incomplete, errors occurred!

**Comment by alalek** [comment] 2017-01-09 05:25
Try to disable CUDA via CMake option `-DWITH_CUDA=OFF` (probably you have unsupported version)

**Comment by shravankumar147** [comment] 2017-01-09 06:30
Thanks, I'll try that.

**Comment by alalek** [comment] 2017-01-12 10:29
Duplicate of #6577

**Closed by alalek** 2017-01-12 10:29 UTC
Labels: category: build/install, category: gpu (cuda), duplicate
