### ISSUE TITLE
i have bug of resize

### ISSUE THREAD

**Issue by sy-project** [opencv/opencv#19864] opened 2021-04-06 09:25 UTC
i use ubuntu20.04, cmake 3.16.3, Opencv 4.5.1-dev.

what should i do?

error code:
terminate called after throwing an instance of cv::Exception
 what(): OpenCV(4.5.1-dev) /home/myCom/opencv/opencv-master/modules/imgproc/src/resize.cpp:4051: error: (-215:Assertion failed) !ssize.empty() in funtion 'resize'
terminate called after throwing an instance of cv::Exception
 what(): OpenCV(4.5.1-dev) /home/myCom/opencv/opencv-master/modules/imgproc/src/resize.cpp:4054: error: (-215:Assertion failed) inv_scale_x > 0 in funtion 'resize'

**Comment by iAmJuan550** [comment] 2021-04-06 10:25
@alalek when you put invalid tracker label, you should explain why you are giving it that label. You did the same to my question without any explanation.

**Comment by berak** [comment] 2021-04-06 10:42
> when you put invalid tracker label, you should explain why you are giving it that label.

@iAmJuan550, since this is not about an opencv library bug (but about an error in your own code), please kindly

* close this issue
* re-ask on https://forum.opencv.org/ , (adding resp. code to reproduce it), we can help you much better from there !

**Comment by sturkmen72** [comment] 2021-04-06 12:12
you are facing the case below
```
    Mat src; // src is still empty
    resize(src, src, Size(), 0.5, 0.5); // here will be (-215:Assertion failed)
```

and for the solution be sure the source is not empty
```
    Mat src(100,100,CV_8U); // src is not empty
    resize(src, src, Size(), 0.5, 0.5); // runs well
```

you can check by `src.empty()`

**Closed** 2021-07-11 13:33 UTC
Labels: question (invalid tracker)
