### ISSUE TITLE
QR code detectAndDecode return NULL

### ISSUE THREAD

**Issue by llxxhm** [opencv/opencv#15635] opened 2019-10-04 05:16 UTC
![test](https://user-images.githubusercontent.com/10462227/66182795-03418d80-e6a9-11e9-9a02-1978de83bbde.jpg)
detectAndDecode return NULL

**Comment by dkurt** [comment] 2019-10-04 05:51
@llxxhm, Please specify OpenCV version.

You may also try the latest merged PR https://github.com/opencv/opencv/pull/15356.

**Comment by llxxhm** [comment] 2019-10-04 06:01
@dkurt OpenCV4.1.1

**Comment by alalek** [comment] 2019-10-24 08:52
@llxxhm Please check with latest release: OpenCV 4.1.2

**Comment by llxxhm** [comment] 2019-11-05 02:21
@alalek Opencv4.1.2 had the same problems; detectAndDecode return NULL
![image](https://user-images.githubusercontent.com/10462227/68173439-f40a7400-ffb5-11e9-9dd0-aef855644996.png)

**Comment by GArik** [comment] 2019-11-08 13:24
This issue can be closed as a duplicate of #13311, I guess

**Comment by dkurt** [comment] 2020-02-03 13:00
@APrigarina,May I ask you to try to run multiple codes detector on the image?

**Comment by APrigarina** [comment] 2020-02-05 12:02
@dkurt @llxxhm, I ran multiple detection on this image, but there is a mismatch to the standard template of qr-code(missing white border and given qr-codes are cut)

**Comment by asmorkalov** [comment] 2020-02-14 07:56
@dkurt Could we close the ticket with "not an issue" status than?

**Comment by dkurt** [comment] 2020-02-14 08:06
I feel confident that left QRCore is not valid but why another one is not detected is not clear for me. Despite it has no enough white border pixels at the top and left, can we check that background is not quantized to white pixels?

**Comment by APrigarina** [comment] 2020-02-14 15:54
@dkurt This QR-code doesn't match the standard at the top (the ratio of white and black pixels must be 1:1:3:1:1 from all sides in three position patterns which are used to find QR-code on the picture)

**Comment by SimpleVlad** [comment] 2020-02-14 16:46
![66182795-03418d80-e6a9-11e9-9a02-1978de83bbde](https://user-images.githubusercontent.com/39303687/74550526-95647700-4f62-11ea-918c-5d304acde024.png)

Yes, we can see this

**Comment by dkurt** [comment] 2020-07-28 07:13
Left QR code does not match specifications (at lest 4 white modules around QR).

**Closed by dkurt** 2020-07-28 07:13 UTC
Labels: Hackathon, category: objdetect, incomplete
