### ISSUE TITLE
[Feature Request] - Image Format Support: High Efficiency Image File Format (HEIF)

### ISSUE THREAD

**Issue by HotDenim** [opencv/opencv#19265] opened 2021-01-05 17:52 UTC
Would like to request support for the following image format (loading, saving). Support for image _data, metadata (Exif/XMP)_, and all other features.

High Efficiency Image File Format (HEIF)  - [Based on H.265 video codec]

**Comment by Glandos** [comment] 2021-01-06 13:08
It seems to be a duplicate of #14534

**Closed** 2021-01-06 13:14 UTC
Labels: category: imgcodecs, duplicate, feature
