### ISSUE TITLE
Wavelet support in OpenCV

### ISSUE THREAD

**Issue by MGarvinNYC** [opencv/opencv#19895] opened 2021-04-12 22:29 UTC
Use of wavelets is rapidly increasing for many applications in denoising, image compression, edge-detection, etc, it makes sense for OpenCV to add support.  It should be every bit as useful as Fourier/spectral transforms, given that many applications involve the three processes above.

**Comment by alalek** [comment] 2021-04-13 10:23
duplicate of #4540

**Closed by alalek** 2021-04-13 10:23 UTC
Labels: category: imgproc, feature

**Comment by MGarvinNYC** [comment] 2021-04-14 01:26
Not sure why this was closed.  #4560 is almost 6 years old, and was never followed up. Things have changed a since then; wavelets are becoming a predominant analysis tool, especially in image processing.  Given the huge functionality available, this is a rather large omission from OpenCV.  It seemed like it should be reconsidered after all these years.
