### ISSUE TITLE
VideoWriter "List of Codecs" link goes to the wrong page

### ISSUE THREAD

**Issue by ronthalanki** [opencv/opencv#22534] opened 2022-09-19 18:25 UTC
# OpenCV Documentation 

When you click on the link in the following line in the documentation "List of codes can be obtained at [Video Codecs by FOURCC](http://www.fourcc.org/codecs.php) page", you get redirected to the wrong page.

This is in the VideoWriter section of the documentation. https://docs.opencv.org/2.4/modules/highgui/doc/reading_and_writing_images_and_video.html#videocapture

**Comment by alalek** [comment] 2022-09-19 19:20
Duplicate of #22504

"2.4" is EOL: https://github.com/opencv/opencv/wiki/Branches

**Closed by alalek** 2022-09-19 19:20 UTC
Labels: duplicate
