### ISSUE TITLE
Faster object detection using Non-machine learning algorithms

### ISSUE THREAD

**Issue by praneeth0609** [opencv/opencv#20289] opened 2021-06-21 10:28 UTC
Hello Every one,

I'm trying to implement some detection models which can detected an object very fast.

The concept is like, I'm using PTZ camera to detect the object and tracking . I will give Azimuth and elevation of target to PTZ camera. After that the camera should move to that particular Azimuth and Elevation and need to detect the object. object might be moving airplane/bird, once the algorithm detects any object I will apply classification algorithm for object classification.
please suggest me the best algorithm for this type of application.

The camera field of view may have different kinds of backgrounds(Tree/sky/both tree & sky/buildings etc.), even though the algorithm should detect any moving object detect.
The algorithm should detect the object very fast.
I'm trying to implement the detection model in python.
any pre implemented/OpenCV-python based detection algorithms are there for this type of applications..?
please suggest me the best object detection method.
Thanks in advance.

**Comment by berak** [comment] 2021-06-21 15:03
hello, you reached the opencv *bug tracker* (wrong place for your problem) , please :
* kindly close this issue (not a bug)
* ask instead on https://forum.opencv.org/ , where we can help you much better, 
<br>
 thank you.

**Closed** 2021-07-11 14:33 UTC
Labels: question (invalid tracker)
