### ISSUE TITLE
[feature] Provide the form `pkg>::comp` or `pkg::pkg` of IMPORTED targets for CMake.

### ISSUE THREAD

**Issue by hwhsu1231** [opencv/opencv#22211] opened 2022-07-08 08:02 UTC
### Feature Request

OpenCV already provides its own **IMPORTED** library targets. For example:

```
opencv_calib3d
opencv_core
opencv_dnn
opencv_features2d
opencv_flann
opencv_gapi
opencv_highgui
...
```

However, I hope OpenCV can provide this form `pkg::comp` or `pkg::pkg` of **IMPORTED** library targets. For example:

```
opencv::calib3d
opencv::core
opencv::dnn
opencv::features2d
opencv::flann
opencv::gapi
opencv::highgui
...
```

Because lots of other libraries take it.

### Some examples of other libraries

- [`fmt::fmt`](https://github.com/fmtlib/fmt/blob/8.1.1/CMakeLists.txt#L245)
- [`CLI11::CLI11`](https://github.com/CLIUtils/CLI11/blob/v2.2.0/CMakeLists.txt#L156)
- [`libevent::core`](https://github.com/libevent/libevent/blob/release-2.1.12-stable/cmake/LibeventConfig.cmake.in#L30)
- [`Poco::Data`](https://github.com/pocoproject/poco/blob/poco-1.11.3-release/Data/CMakeLists.txt#L21)
- [`spdlog::spdlog`](https://github.com/gabime/spdlog/blob/v1.9.2/CMakeLists.txt#L162)
- [`Qt6::Core`](https://doc.qt.io/qt-6/qtcore-index.html#building-with-cmake)
- [`protobuf::libprotobuf`](https://github.com/protocolbuffers/protobuf/blob/v3.21.2/cmake/libprotobuf.cmake#L134)
- [`Boost::regex`](https://github.com/boostorg/regex/blob/boost-1.79.0/CMakeLists.txt#L12)
- [`Eigen3::Eigen`](https://gitlab.com/libeigen/eigen/-/blob/3.4/CMakeLists.txt#L597)
- ...etc

**Comment by alalek** [comment] 2022-07-08 08:34
duplicate of #13117

**Closed by alalek** 2022-07-08 08:34 UTC
Labels: duplicate
