### ISSUE TITLE
Error while loading DeepLabv3+ xception_65 using OpenCV DNN C++: Input layer not found: Shape_4 in function 'connect'

### ISSUE THREAD

**Issue by kHarshit** [opencv/opencv#15336] opened 2019-08-19 12:18 UTC
##### System information (version)

- OpenCV => 4.1.1
- Operating System / Platform => Linux
- Compiler => gcc/g++

##### Detailed description

I'm trying to load the pretrained [DeepLabv3+ xception_65 model](http://download.tensorflow.org/models/deeplabv3_cityscapes_train_2018_02_06.tar.gz) available from [Tensorflow repository](https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/model_zoo.md#deeplab-models-trained-on-cityscapes) using OpenCV DNN C++. It throws the following error:

```
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.1.1) /content/opencv-4.1.1/modules/dnn/src/tensorflow/tf_importer.cpp:544: error: (-2:Unspecified error) Input layer not found: Shape_4 in function 'connect'
```

##### Steps to reproduce

```
#include <opencv2/opencv.hpp>
#include <opencv2/dnn.hpp>
#include "iostream"

#include <opencv2/dnn/layer.details.hpp>  // CV_DNN_REGISTER_LAYER_CLASS

using namespace cv;
using namespace cv::dnn;

int main()
{
    // Original frozen model
    //std::string model = "deeplabv3_cityscapes_train/frozen_inference_graph.pb";
    	
    // Read image
    cv::Mat imgOrig = cv::imread("000001.png", cv::IMREAD_COLOR);
    imgOrig.convertTo(imgOrig, CV_8UC3);

    // Resize image
    cv::Mat img;
    cv::resize(imgOrig, img, cv::Size(513, 513));

    // Read model
    cv::dnn::Net graph = cv::dnn::readNetFromTensorflow(model);

    // Get blob from image
    cv::Mat blob = cv::dnn::blobFromImage(img, 4.0, cv::Size(513, 513), cv::Scalar(), true, false);
     
    // Set the input tensor
    std::string inBlobName = "ImageTensor";
    graph.setInput(blob, inBlobName);

    cv::Mat detectionOut = graph.forward();
    
    std::cout << "Worked fine!";
   
    return 0;
}
```

---

Even when I use [`pbtxt`](https://drive.google.com/drive/folders/1B83G3uA-OP18j0Rr9so343gSBbxaio5x?usp=sharing) file as well while loading model by
`cv::dnn::Net graph = cv::dnn::readNetFromTensorflow(model, pbtxt_file);` created using

```
# Read the graph.
with tf.gfile.FastGFile('deeplabv3_cityscapes_train/frozen_inference_graph.pb', 'rb') as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())

# Remove Const nodes.
for i in reversed(range(len(graph_def.node))):
    if graph_def.node[i].op == 'Const':
        del graph_def.node[i]

    for attr in ['T', 'data_format', 'Tshape', 'N', 'Tidx', 'Tdim',
                 'use_cudnn_on_gpu', 'Index', 'Tperm', 'is_training',
                 'Tpaddings']:
        if attr in graph_def.node[i].attr:
            del graph_def.node[i].attr[attr]

# Save as text.
tf.train.write_graph(graph_def, "", "frozen_inference_graph.pbtxt", as_text=True)
```
the error is same.

**Comment by dkurt** [comment] 2019-08-19 19:31
Looks like duplicate of https://github.com/opencv/opencv/issues/15046

**Closed by dkurt** 2019-08-19 19:31 UTC

**Comment by kHarshit** [comment] 2019-08-20 09:58
@dkurt It's a different error. When I view the graph, there are nodes named `Shape`, `Shape_1`, `Shape_2` and `Shape_3` only, but the error says `Shape_4`, which isn't there.

![deeplab_xception65_graph](https://user-images.githubusercontent.com/20869671/63334795-c4a27e80-c359-11e9-9beb-c3fa91f4ba38.png)

And, also, I check `.pbtxt` file, it has a node named `strided_slice_7` which takes input `Shape_4`, but it isn't defined earlier in the file because it had a `Const` operation *(check below)* thus was removed during creation of pbtxt file.
```
node {
  name: "strided_slice_7"
  op: "StridedSlice"
  input: "Shape_4"
  input: "strided_slice_7/stack"
  input: "strided_slice_7/stack_1"
  input: "strided_slice_7/stack_2"
...
```

[Check files here](https://drive.google.com/drive/folders/1B83G3uA-OP18j0Rr9so343gSBbxaio5x?usp=sharing)

But, when I read `.pb` file in python and check, I get `Shape_4` defined 
```
In [12]: gf = tf.GraphDef()                                                                                                                                                     

In [13]: gf.ParseFromString(open('frozen_inference_graph.pb','rb').read())                                                                                                      
Out[13]: 8771639

In [14]: for i in gf.node: 
    ...:     if i.name == 'Shape_4': 
    ...:         print(i) 
    ...:                                                                                                                                                                        
name: "Shape_4"
op: "Const"
attr {
  key: "_output_shapes"
  value {
    list {
      shape {
        dim {
          size: 4
        }
      }
    }
  }
}
attr {
  key: "dtype"
  value {
    type: DT_INT32
  }
}
attr {
  key: "value"
  value {
    tensor {
      dtype: DT_INT32
      tensor_shape {
        dim {
          size: 4
        }
      }
      tensor_content: "\001\000\000\000\001\004\000\000\001\010\000\000\003\000\000\000"
    }
  }
}
```

I'm not getting why the error `Input layer not found: Shape_4 in function 'connect'` would come, even when it's present in `.pb` file. Or does that mean that it's not present in OpenCV?

Also, if `Shape_4` is present in `.pb` file, then why isn't visible in the model's graph?

**Comment by Zrufy** [comment] 2020-02-13 08:12
@kHarshit i have the same error from my pb after the conversion.
have you figure out the solution for this problem?
Because I have tried many solutions but none has brought me the expected result.

**Comment by YanaShpot** [comment] 2020-07-05 13:51
I have the same error with another DeepLab model (saved like a frozen inference graph as well). I use the last version of OpenCV and Windows.  @dkurt could you suggest something, please?

**Comment by dkurt** [comment] 2020-07-06 03:11
@YanaShpot, please don't use closed issues. Try to find existing solution using search by issues , try the latest master branch or check the guides (https://github.com/opencv/opencv/wiki/TensorFlow-text-graphs)
