### ISSUE TITLE
Building Android arm64-v8a using c++_static as stl failed

### ISSUE THREAD

**Issue by WissamAhmed** [opencv/opencv#9437] opened 2017-08-22 15:22 UTC
##### System information (version)
Example
- OpenCV => 3.3
- Operating System / Platform => Windows 64 Bit
- NDK=>r13b
-Android SDK=> 25

##### Detailed description

building opencv for Android arm64-v8a using NDK = r13b, SDk=>25 
here is the build command 
cmake -G "Unix Makefiles" -DANDROID_ABI=arm64-v8a -DANDROID_STL=c++_static  -DCMAKE_TOOLCHAIN_FILE=..\..\..\sources\platforms\android\android.toolchain.cmake ..\..\..\sources

make -j8

it give me compile time error 
[  3%] Building CXX object 3rdparty/libtiff/CMakeFiles/libtiff.dir/tif_stream.cxx.o
In file included from opencv-3.3.0/sources/3rdparty/libtiff/tif_stream.cxx:31:0:
opencv-3.3.0/sources/3rdparty/libtiff/tiffio.hxx:34:20: fatal error: iostream: No such file or directory
 #include <iostream>
                    ^
compilation terminated.
make[2]: *** [3rdparty/libtiff/CMakeFiles/libtiff.dir/tif_stream.cxx.o] Error 1
make[1]: *** [3rdparty/libtiff/CMakeFiles/libtiff.dir/all] Error 2
make: *** [all] Error

**Comment by alalek** [comment] 2017-08-22 15:36
Try to use Android NDK r15 with builtin CMake toolchain (from [$NDK/build/cmake/](https://developer.android.com/ndk/guides/cmake.html)) in case of non-default STLs.

**Comment by ptc-wahmed** [comment] 2017-08-22 16:01
I tried to use NDK r15c , but still the same error

**Comment by alalek** [comment] 2017-08-22 16:28
Duplicate of #8742

**Comment by asmorkalov** [comment] 2024-01-10 14:22
Not relevant for 4.9.0+ and modern SDK. Build command for test:
```
cmake -GNinja  -DANDROID_STL=c++_static  -DANDROID_NATIVE_API_LEVEL=24 -DANDROID_MIN_SDK_VERSION=24 -DWITH_ANDROID_NATIVE_CAMERA=ON -DWITH_ANDROID_MEDIANDK=ON -DANDROID_ABI=arm64-v8a -DCMAKE_TOOLCHAIN_FILE=/home/alexander/Android2/ndk/25.2.9519653/build/cmake/android.toolchain.cmake -DANDROID_NDK=/home/alexander/Android2/ndk/25.2.9519653 -DANDROID_SDK=/home/alexander/Android2/ ../opencv-master && ninja
```

**Closed** 2024-01-10 14:23 UTC
Labels: duplicate, category: build/install, platform: android
