### ISSUE TITLE
Missing indentation in python code in rotated bounding boxes tutorial breaks example code

### ISSUE THREAD

**Issue by JulianRagan** [opencv/opencv#24402] opened 2023-10-13 20:10 UTC
### Describe the doc issue

The python code lacks proper indentation which causes incorrect operation of loops in the example and gives broken results. As well as causes confusion when following the code.

The bad code is available since version 3.4.2 (link https://docs.opencv.org/3.4.2/de/d62/tutorial_bounding_rotated_ellipses.html), most likely in all versions up to current 5.0.0-pre (link https://docs.opencv.org/5.x/de/d62/tutorial_bounding_rotated_ellipses.html)

### Fix suggestion

The code for thresh_callback should be reformatted, perhaps like below (caveat: I am not an experienced python programmer)

```python
def thresh_callback(val):
    threshold = val

    canny_output = cv.Canny(src_gray, threshold, threshold * 2)

    contours, _ = cv.findContours(canny_output, cv.RETR_TREE, cv.CHAIN_APPROX_SIMPLE)

    # Find the rotated rectangles and ellipses for each contour
    minRect = [None] * len(contours)
    minEllipse = [None] * len(contours)
    for i, c in enumerate(contours):
        minRect[i] = cv.minAreaRect(c)
        if c.shape[0] > 5:
            minEllipse[i] = cv.fitEllipse(c)
    # Draw contours + rotated rects + ellipses

    drawing = np.zeros((canny_output.shape[0], canny_output.shape[1], 3), dtype=np.uint8)

    for i, c in enumerate(contours):
        color = (rng.randint(0, 256), rng.randint(0, 256), rng.randint(0, 256))
        # contour
        cv.drawContours(drawing, contours, i, color)
        # ellipse
        if c.shape[0] > 5:
            cv.ellipse(drawing, minEllipse[i], color, 2)
        # rotated rectangle
        box = cv.boxPoints(minRect[i])
        box = np.intp(box)  # np.intp: Integer used for indexing (same as C ssize_t; normally either int32 or int64)
        cv.drawContours(drawing, [box], 0, color)

    cv.imshow('Contours', drawing)
```
As a side note, the C++ and Java code could also benefit from reformatting.

**Comment by opencv-alalek** [comment] 2023-10-14 04:20
duplicate of #24391

**Closed by opencv-alalek** 2023-10-14 04:20 UTC
Labels: duplicate, category: documentation
