### ISSUE TITLE
calcHist fails to assign to pre-allocated array

### ISSUE THREAD

**Issue by tgarc** [opencv/opencv#5244] opened 2015-08-25 01:55 UTC
Whenever I pass a preallocated array to calcHist that is _not_ a float32 dtype, the preallocated array simply doesn't get written to and no exception is raised.

I'm reporting this issue for the python bindings, opencv 2.4.8. Not sure if problem is present in current version, but I didn't see any issues about this, so this may be still in the latest version too.

``` python
>>> img
array([[ 2, 10,  3, 10,  9],
       [ 9,  3,  4, 21, 22],
       [ 5,  8, 18, 24, 13],
       [ 5, 15, 14, 20, 15],
       [ 7,  2,  0, 13, 18]], dtype=uint8)
>>> b = np.zeros(16,dtype=np.float64)  # try passing a float64 dtype
>>> cv2.calcHist([img],[0],None,[16],[0,256],b);
>>> b # no updates!
array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.])
>>> b = np.zeros(16,dtype=np.float32) # use a float32 dtype instead
>>> cv2.calcHist([img],[0],None,[16],[0,256],b);
>>> b # success!
array([ 19.,   6.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.], dtype=float32)
```

**EDIT** turns out that for 3-channel data, assignment doesn't work at all (oddly there's no problem with 2 channel data)

``` python
>>> img = np.tile(img,3).reshape(5,5,3)
>>> b = np.zeros((16,16,16),dtype=np.float32)  # use the float32 dtype that calcHist expects
>>> cv2.calcHist([img],[0,1,2],None,[16,16,16],[0,256,0,256,0,256],b);
>>> (b == 0).all()
True
```

**UPDATE** I confirmed this bug also exists in the 3.0.0 release

**Comment by ilya-lavrenov** [comment] 2016-07-15 09:19
BTW, tested the same via C++ code, everything is fine:
```
TEST(Imgproc_Hist, Mat64f)
{
   uchar data[] =
   { 2, 10,  3, 10,  9,
     9,  3,  4, 21, 22,
     5,  8, 18, 24, 13,
     5, 15, 14, 20, 15,
     7,  2,  0, 13, 18 };

    cv::Mat source(5, 5, CV_8UC1, data);
    cv::Mat hist(16, 1, CV_64FC1, cv::Scalar::all(0));

    const std::vector<int> channels(1, 0);
    std::vector<float> ranges(2, 0);
    std::vector<int> histSize(1, 16);

    ranges[1] = 256;

    cv::calcHist(std::vector<Mat>(1, source), channels, noArray(), hist, histSize, ranges, false);

    std::cout << hist << std::endl;
}
```
The output is:
```
Note: Google Test filter = *Mat64f*
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from Imgproc_Hist
[ RUN      ] Imgproc_Hist.Mat64f
[19;
 6;
 0;
 0;
 0;
 0;
 0;
 0;
 0;
 0;
 0;
 0;
 0;
 0;
 0;
 0]
[       OK ] Imgproc_Hist.Mat64f (3 ms)
[----------] 1 test from Imgproc_Hist (3 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (3 ms total)
[  PASSED  ] 1 test.

```

**Comment by VadimLevin** [comment] 2019-11-14 08:32
Hello, @tgarc

I have investigated this issue and found out that the problem is lurking in the construction of the output Mat object.
If provided array can hold the result (has correct underlying data type, shape and other things) its memory will be used, otherwise (e.g. it is None) new memory is allocated and Mat is constructed in different location. In Python we can only mutate input arguments, but can not change them completely.

If we have a close look into the @ilya-lavrenov C++ check, we can notice that type of the matrix elements is changed to `CV_32FC1` after the `cv::calcHist` call and if compare addresses of the data we can notice that they also differ.

```
[ RUN      ] Imgproc_Hist_Calc.calcHist_Mat64f
Expected equality of these values:
  p
    Which is: 0x560c9e9638c0
  hist.data
    Which is: 0x560c9e901380
Expected equality of these values:
  hist.type()
    Which is: 5
  (((6) & ((1 << 3) - 1)) + (((1)-1) << 3))
    Which is: 6
[  FAILED  ] Imgproc_Hist_Calc.calcHist_Mat64f (0 ms)
[ RUN      ] Imgproc_Hist_Calc.calcHist_Mat32f
[       OK ] Imgproc_Hist_Calc.calcHist_Mat32f (0 ms)
```


**Possible solutions:**

1. Interface of the generated functions should be changed to have only input arguments and return value.

    Pros:

        - Follow Pythons idiom about function arguments

    Cons:

        - Completely breaks the API of the wrapped functions.

2. Always copy input arguments.

    Pros:

        - Solves the problem.

    Cons:

        - May lead to confusion due to C/C++ and Python difference
        - May break user code that relies on the argument mutation

    This solution leaves open question: Should parameter be checked on correct type if it is ignored?

3. Leave as it is.


@alalek What do you think about it?

**Comment by alalek** [comment] 2019-11-14 09:22
Python bindings can't reassign inputs.
Outputs are always returned through regular "return".

These "output" inputs are considered as a suggestion for reuse for reserved buffer. They are optional  in Python.

Refer to [specification of calcHist](https://docs.opencv.org/3.4/d6/dc7/group__imgproc__hist.html#ga4b2b5fd75503ff9e6844cc4dcdaed35d) in Python:

> hist = cv.calcHist(images, channels, mask, histSize, ranges[, hist[, accumulate]])

So sample code is wrong and should be fixed in this way:
```.diff
-cv2.calcHist([img],[0],None,[16],[0,256],b);
+b = cv2.calcHist([img],[0],None,[16],[0,256],b);
```

or better to avoid "input" `b` parameter.

Also you can try this to understand how it works currently (`b` is ignored due mismatched buffer):
```
c = cv2.calcHist([img],[0],None,[16],[0,256],b);
print(b)
print(c)
```

**Closed by alalek** 2019-11-14 09:22 UTC
Labels: category: python bindings, question (invalid tracker)
