### ISSUE TITLE
resized img mismatch on ubuntu and mobile 

### ISSUE THREAD

**Issue by KevinZ1992** [opencv/opencv#16304] opened 2020-01-08 07:48 UTC
Hi,all.I tried run ML on mobile.When resize  2560x1440 img to 224x224,the result of pixels mismatch on ubuntu and mobile .The resized img with size  of 2048x1152 are all the same.

- OpenCV => 3.4.2
- Operating System / Platform => ubuntu 18.04
- Compiler => Visual Studio 2019 (version 1.41)

- OpenCV =>  3.4.2
- Operating System / Platform => Android
- Compiler => :Android Studio 3.5.3

**Comment by dkurt** [comment] 2020-01-08 11:33
Closing it unless we have a reproducer

**Closed** 2020-01-08 11:32 UTC

**Comment by KevinZ1992** [comment] 2020-01-08 12:03
Here are the main code and test picture, so you can&nbsp; reproduce it.



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Dmitry Kurtaev"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月8日(星期三) 晚上7:33
收件人:&nbsp;"opencv/opencv"<opencv@noreply.github.com&gt;;
抄送:&nbsp;"小曼"<156162726@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [opencv/opencv] resized img mismatch on ubuntu and mobile  (#16304)




Closing it unless we have a reproducer

**Comment by KevinZ1992** [comment] 2020-01-13 03:10
Hi,can you&nbsp; reproduce it&nbsp; or give a reply?


__________________________________________________________________



Here are the main code and test picture, so you can&nbsp; reproduce it.




------------------ 原始邮件 ------------------
发件人:&nbsp;"Dmitry Kurtaev"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月8日(星期三) 晚上7:33
收件人:&nbsp;"opencv/opencv"<opencv@noreply.github.com&gt;;
抄送:&nbsp;"小曼"<156162726@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [opencv/opencv] resized img mismatch on ubuntu and mobile  (#16304)




Closing it unless we have a reproducer

**Comment by dkurt** [comment] 2020-01-13 07:02
@KevinZ1992, please open GitHub page and check that there is no code or links here.

**Comment by KevinZ1992** [comment] 2020-01-13 07:08
This is my code and test picture.
[#16304.zip](https://github.com/opencv/opencv/files/4052389/16304.zip)

**Comment by dkurt** [comment] 2020-01-16 09:31
@KevinZ1992, we cannot due to broken .zip archive. Please check it.

**Comment by KevinZ1992** [comment] 2020-01-16 09:36
[#16304.zip](https://github.com/opencv/opencv/files/4070333/16304.zip)
Sorry,please check again.

**Comment by dkurt** [comment] 2020-01-16 10:32
JPEG is not bitexact format which can lead to different decoded images with different versions of libjpg and target platforms.
