### ISSUE TITLE
Darknet importer: unable to import clasification configuration file darknet19.cfg

### ISSUE THREAD

**Issue by isra60** [opencv/opencv#16623] opened 2020-02-20 12:25 UTC
Using one of the cfg file from darknet repo. (darknet-19 for classification not detection).

https://github.com/AlexeyAB/darknet/blob/master/cfg/darknet19.cfg

opencv/modules/dnn/src/darknet/darknet_io.cpp:678: error: (-212:Parsing error) Unknown layer type: sse in function 'ReadDarknetFromCfgStream'

Seems to be in cost layer...

[cost]
type=sse

**Comment by dkurt** [comment] 2020-02-20 13:00
@isra60, try to remove this layer - it's training only.

**Comment by isra60** [comment] 2020-02-20 13:23
I remove it but then when I try

`cv::dnn::Net net = cv::dnn::readNet(modelConfiguration, modelWeights);

    net.setPreferableBackend(GetAnalyticsParameters()->GetDNNBackend());
    net.setPreferableTarget(GetAnalyticsParameters()->GetDNNTarget());

    std::cout << net.dump() << std::endl;`

terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.2.0-dev) /opencv/modules/dnn/src/dnn.cpp:3781: error: (-2:Unspecified error) Requested set input in function 'dump'

**Comment by dkurt** [comment] 2020-02-20 13:46
@isra60, as pointed in the error message, you should set some input before `dump`

We already fixed that for future releases in https://github.com/opencv/opencv/pull/16516

**Comment by isra60** [comment] 2020-02-20 16:22
but.... I'm using master branch (4.2.0.-dev) this still should be happen???

**Comment by dkurt** [comment] 2020-02-20 17:19
Cannot reproduce it with weights from https://pjreddie.com/media/files/darknet19.weights and `.cfg` from issue description (3.4 branch):
```python
import cv2 as cv

net = cv.dnn.readNet('darknet19.cfg', 'darknet19.weights')
print(net.dump())
```

**Comment by isra60** [comment] 2020-02-21 07:44
OK, seems working for me too (My repo was not fully updated sorry).

Is there any tutorial of how to process the detections from the net and also how to prepare the input blob??

**Comment by dkurt** [comment] 2020-02-21 09:06
@isra60, `darknet19` is not detection network - it's classification one.

Please follow tutorials https://docs.opencv.org/master/d2/d58/tutorial_table_of_content_dnn.html or samples https://github.com/opencv/opencv/tree/master/samples/dnn

**Comment by dkurt** [comment] 2020-02-21 20:59
Can we close this issue?

**Comment by alalek** [comment] 2020-02-21 21:25
I believe we can try to improve DarkNet importer to ignore "Cost" training-only layers.
Any thoughts?

**Comment by ashishkrshrivastava** [comment] 2020-02-22 05:46
@alalek , Maybe either setting `"Identity"` layer for `"Cost"` layer or ignoring while parsing would work.

**Comment by dkurt** [comment] 2020-02-22 06:57
That's good idea

**Comment by ashishkrshrivastava** [comment] 2020-02-22 12:57
@alalek , @dkurt 
while parsing
```
[cost]
type=sse
```
the parameter `type` is interpreted as layer type. producing error. 
`darknet_io.cpp:762: error: (-212:Parsing error) Unknown layer type: sse in function 'ReadDarknetFromCfgStream'`
Because here we are storing layer type with key "type".
https://github.com/opencv/opencv/blob/102ef39a27bfc277d82045e5c5e0d4b1251294df/modules/dnn/src/darknet/darknet_io.cpp#L552-L559
And here "type" parameter is getting stored with key "type" itself. 
https://github.com/opencv/opencv/blob/102ef39a27bfc277d82045e5c5e0d4b1251294df/modules/dnn/src/darknet/darknet_io.cpp#L562-L575
So ignoring while parsing until "[" i.e. next layer is seen is better option ? Am I right ?

**Comment by dkurt** [comment] 2020-02-22 19:19
There are just three entries of "type" so we probably can replace it to something like "layer_type" to not to mix with "type" as layer attribute.

**Comment by ashishkrshrivastava** [comment] 2020-02-23 11:42
Thanks, got it.

**Closed** 2020-02-25 13:19 UTC
Labels: category: dnn
