### ISSUE TITLE
Memory leak detected in the OpenCV unit test Flann_LshTable.badarg

### ISSUE THREAD

**Issue by AndreiVF** [opencv/opencv#6131] opened 2016-02-17 12:15 UTC
In the unit test `Flann_LshTable.badarg` the index memory of the `lsh` `Index` instance gets lost due to a thrown C++ exception in the `Index` class constructor.

STEPS TO REPRODUCE:

Git:

```
branch: master
commit: 6f51dd12589343e567ffd615a9bad3900ed4228b

```
Machine:

```
$ uname -a
Linux andrei 3.16.0-60-generic #80~14.04.1-Ubuntu SMP Wed Jan 20 13:37:48 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
$ g++ --version
g++ (Ubuntu 4.8.5-2ubuntu1~14.04.1) 4.8.5
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:        14.04
Codename:       trusty
```

Build and run the OpenCV test:

```
$ cmake ../opencv -DCMAKE_BUILD_TYPE=Debug -DENABLE_SSE=OFF -DENABLE_SSE2=OFF -DENABLE_SSE3=OFF -DENABLE_SSSE3=OFF -DWITH_OPENCL=OFF
$ make -j8
$ ./bin/opencv_test_flann --gtest_output=xml:opencv_test_flann.xml
CTEST_FULL_OUTPUT
OpenCV version: 3.1.0-dev
OpenCV VCS version: 6f51dd1-dirty
Build type: debug
Parallel framework: pthreads
CPU features: 
OpenCL is disabled
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from Flann_LshTable
[ RUN      ] Flann_LshTable.badarg
[       OK ] Flann_LshTable.badarg (5 ms)
[----------] 1 test from Flann_LshTable (5 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (5 ms total)
[  PASSED  ] 1 test.
```

OBSERVED BEHAVIOR:

The test is happy. However, during the construction of the `lsh` instance in `modules/flann/test/test_lshtable_badarg.cpp:60` an exception throw is provoked to test bad argument passing. In particular,` _index->buildIndex()` at `modules/flann/src/miniflann.cpp:321` throws an exception. Unfortunately, the `cv::flann:Index` destructor is consequently not invoked then and the allocated index is leaked. If this exception is used in a "happy flow" of the program, it may lead to a bigger loss of memory. Below is a detailed report from the dynamic analysis tool Pareon Verify (http://pareonverify.com/), including source locations for the allocation, last access and last reference, as well as call stacks for each of them.

EXPECTED BEHAVIOR:

When throwing the `Error::StsBadArg` exception, the allocated index is deleted, for example, using `Index::release()`.

PAREON VERIFY REPORT:

```
[M0181] Memory leak detected:
  the heap object of size 72 allocated through a call to `operator new(unsigned long)' in
    function void cv::flann::buildIndex_<cvflann::HammingLUT, cvflann::Index<cvflann::HammingLUT> >(void*&, cv::Mat const&, cv::flann::IndexParams const&, cvflann::HammingLUT const&) at /opencv/modules/flann/src/miniflann.cpp:320
    called from function void cv::flann::buildIndex<cvflann::HammingLUT>(void*&, cv::Mat const&, cv::flann::IndexParams const&, cvflann::HammingLUT const&) at /opencv/modules/flann/src/miniflann.cpp:328
    called from function cv::flann::Index::build(cv::_InputArray const&, cv::flann::IndexParams const&, cvflann::flann_distance_t) at /opencv/modules/flann/src/miniflann.cpp:377
    called from function cv::flann::Index::Index(cv::_InputArray const&, cv::flann::IndexParams const&, cvflann::flann_distance_t) at /opencv/modules/flann/src/miniflann.cpp:351
    called from function CV_LshTableBadArgTest::Caller::operator()() const at /opencv/modules/flann/test/test_lshtable_badarg.cpp:60
    called from function int cvtest::BadArgTest::run_test_case<CV_LshTableBadArgTest::Caller>(int, std::string const&, CV_LshTableBadArgTest::Caller) at /opencv/modules/ts/include/opencv2/ts.hpp:501
    called from function CV_LshTableBadArgTest::run(int) at /opencv/modules/flann/test/test_lshtable_badarg.cpp:77
    called from function cvtest::BaseTest::safe_run(int) at /opencv/modules/ts/src/ts.cpp:216
    called from function Flann_LshTable_badarg_Test::Body() at /opencv/modules/flann/test/test_lshtable_badarg.cpp:91
    called from function Flann_LshTable_badarg_Test::TestBody() at /opencv/modules/flann/test/test_lshtable_badarg.cpp:91
    called from function void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) at /opencv/modules/ts/src/ts_gtest.cpp:3578
    called from function void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) at /opencv/modules/ts/src/ts_gtest.cpp:3614
    called from function testing::Test::Run() at /opencv/modules/ts/src/ts_gtest.cpp:3650
    called from function testing::TestInfo::Run() at /opencv/modules/ts/src/ts_gtest.cpp:3826
    called from function testing::TestCase::Run() at /opencv/modules/ts/src/ts_gtest.cpp:3944
    called from function testing::internal::UnitTestImpl::RunAllTests() at /opencv/modules/ts/src/ts_gtest.cpp:5823
    called from function bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) at /opencv/modules/ts/src/ts_gtest.cpp:3578
    called from function bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) at /opencv/modules/ts/src/ts_gtest.cpp:3614
    called from function testing::UnitTest::Run() at /opencv/modules/ts/src/ts_gtest.cpp:5434
    called from function RUN_ALL_TESTS() at /opencv/modules/ts/include/opencv2/ts/ts_gtest.h:20122
    called from function main at /opencv/modules/flann/test/test_main.cpp:3
    ^^^ application start ^^^
  together with a cyclic connected group of objects (17 objects, 2592 bytes)
  have become unreachable.
  This object was last accessible as the result of the call to function `operator new(unsigned long)' in
    function void cv::flann::buildIndex_<cvflann::HammingLUT, cvflann::Index<cvflann::HammingLUT> >(void*&, cv::Mat const&, cv::flann::IndexParams const&, cvflann::HammingLUT const&) at /opencv/modules/flann/src/miniflann.cpp:320
    called from function void cv::flann::buildIndex<cvflann::HammingLUT>(void*&, cv::Mat const&, cv::flann::IndexParams const&, cvflann::HammingLUT const&) at /opencv/modules/flann/src/miniflann.cpp:328
    called from function cv::flann::Index::build(cv::_InputArray const&, cv::flann::IndexParams const&, cvflann::flann_distance_t) at /opencv/modules/flann/src/miniflann.cpp:377
    called from function cv::flann::Index::Index(cv::_InputArray const&, cv::flann::IndexParams const&, cvflann::flann_distance_t) at /opencv/modules/flann/src/miniflann.cpp:351
    called from function CV_LshTableBadArgTest::Caller::operator()() const at /opencv/modules/flann/test/test_lshtable_badarg.cpp:60
    called from function int cvtest::BadArgTest::run_test_case<CV_LshTableBadArgTest::Caller>(int, std::string const&, CV_LshTableBadArgTest::Caller) at /opencv/modules/ts/include/opencv2/ts.hpp:501
    called from function CV_LshTableBadArgTest::run(int) at /opencv/modules/flann/test/test_lshtable_badarg.cpp:77
    called from function cvtest::BaseTest::safe_run(int) at /opencv/modules/ts/src/ts.cpp:216
    called from function Flann_LshTable_badarg_Test::Body() at /opencv/modules/flann/test/test_lshtable_badarg.cpp:91
    called from function Flann_LshTable_badarg_Test::TestBody() at /opencv/modules/flann/test/test_lshtable_badarg.cpp:91
    called from function void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) at /opencv/modules/ts/src/ts_gtest.cpp:3578
    called from function void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) at /opencv/modules/ts/src/ts_gtest.cpp:3614
    called from function testing::Test::Run() at /opencv/modules/ts/src/ts_gtest.cpp:3650
    called from function testing::TestInfo::Run() at /opencv/modules/ts/src/ts_gtest.cpp:3826
    called from function testing::TestCase::Run() at /opencv/modules/ts/src/ts_gtest.cpp:3944
    called from function testing::internal::UnitTestImpl::RunAllTests() at /opencv/modules/ts/src/ts_gtest.cpp:5823
    called from function bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) at /opencv/modules/ts/src/ts_gtest.cpp:3578
    called from function bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) at /opencv/modules/ts/src/ts_gtest.cpp:3614
    called from function testing::UnitTest::Run() at /opencv/modules/ts/src/ts_gtest.cpp:5434
    called from function RUN_ALL_TESTS() at /opencv/modules/ts/include/opencv2/ts/ts_gtest.h:20122
    called from function main at /opencv/modules/flann/test/test_main.cpp:3
    ^^^ application start ^^^
  This object was last accessed by:
  the read in
    function cvflann::Index<cvflann::HammingLUT>::buildIndex() at /opencv/modules/flann/include/opencv2/flann/flann_base.hpp:132
    called from function void cv::flann::buildIndex_<cvflann::HammingLUT, cvflann::Index<cvflann::HammingLUT> >(void*&, cv::Mat const&, cv::flann::IndexParams const&, cvflann::HammingLUT const&) at /opencv/modules/flann/src/miniflann.cpp:321
    called from function void cv::flann::buildIndex<cvflann::HammingLUT>(void*&, cv::Mat const&, cv::flann::IndexParams const&, cvflann::HammingLUT const&) at /opencv/modules/flann/src/miniflann.cpp:328
    called from function cv::flann::Index::build(cv::_InputArray const&, cv::flann::IndexParams const&, cvflann::flann_distance_t) at /opencv/modules/flann/src/miniflann.cpp:377
    called from function cv::flann::Index::Index(cv::_InputArray const&, cv::flann::IndexParams const&, cvflann::flann_distance_t) at /opencv/modules/flann/src/miniflann.cpp:351
    called from function CV_LshTableBadArgTest::Caller::operator()() const at /opencv/modules/flann/test/test_lshtable_badarg.cpp:60
    called from function int cvtest::BadArgTest::run_test_case<CV_LshTableBadArgTest::Caller>(int, std::string const&, CV_LshTableBadArgTest::Caller) at /opencv/modules/ts/include/opencv2/ts.hpp:501
    called from function CV_LshTableBadArgTest::run(int) at /opencv/modules/flann/test/test_lshtable_badarg.cpp:77
    called from function cvtest::BaseTest::safe_run(int) at /opencv/modules/ts/src/ts.cpp:216
    called from function Flann_LshTable_badarg_Test::Body() at /opencv/modules/flann/test/test_lshtable_badarg.cpp:91
    called from function Flann_LshTable_badarg_Test::TestBody() at /opencv/modules/flann/test/test_lshtable_badarg.cpp:91
    called from function void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) at /opencv/modules/ts/src/ts_gtest.cpp:3578
    called from function void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) at /opencv/modules/ts/src/ts_gtest.cpp:3614
    called from function testing::Test::Run() at /opencv/modules/ts/src/ts_gtest.cpp:3650
    called from function testing::TestInfo::Run() at /opencv/modules/ts/src/ts_gtest.cpp:3826
    called from function testing::TestCase::Run() at /opencv/modules/ts/src/ts_gtest.cpp:3944
    called from function testing::internal::UnitTestImpl::RunAllTests() at /opencv/modules/ts/src/ts_gtest.cpp:5823
    called from function bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) at /opencv/modules/ts/src/ts_gtest.cpp:3578
    called from function bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) at /opencv/modules/ts/src/ts_gtest.cpp:3614
    called from function testing::UnitTest::Run() at /opencv/modules/ts/src/ts_gtest.cpp:5434
    called from function RUN_ALL_TESTS() at /opencv/modules/ts/include/opencv2/ts/ts_gtest.h:20122
    called from function main at /opencv/modules/flann/test/test_main.cpp:3
    ^^^ application start ^^^
This message was produced for run 1.
```

**Comment by bryanjp3** [comment] 2016-02-23 16:13
I took a look at this bug hoping it would be easy to fix as I am new to the project. The problem is that the exception prevents a destructor containing delete from executing. I doubt there is a simple way to fix this without refactoring or using smart pointers.

**Comment by AndreiVF** [comment] 2016-02-24 11:02
Thanks for looking into this bug report, @bryanjp3 !

Since the destructor is not invoked, perhaps, a fix should catch the exception, delete the index to avoid the memory leak and re-throw the exception in the constructor itself:

```
diff --git a/modules/flann/src/miniflann.cpp b/modules/flann/src/miniflann.cpp
index 7d81438..790a8db 100644
--- a/modules/flann/src/miniflann.cpp
+++ b/modules/flann/src/miniflann.cpp
@@ -318,7 +318,16 @@ buildIndex_(void*& index, const Mat& data, const IndexParams& params, const Dist
 
     ::cvflann::Matrix<ElementType> dataset((ElementType*)data.data, data.rows, data.cols);
     IndexType* _index = new IndexType(dataset, get_params(params), dist);
-    _index->buildIndex();
+    try
+    {
+      _index->buildIndex();
+    }
+    catch (const cv::Exception &e)
+      {
+        // Building _index failed, deallocate the _index memory, because no destructor will be called
+        delete _index;
+        throw;
+      }
     index = _index;
 }

```

As a side remark, I believe that the exception cv::Exception is thrown in `modules/flann/include/opencv2/flann/lsh_table.h:271` in `LshTable::initialize()`.

With this patch applied I do not get this memory leak error message from Pareon Verify.

**Comment by bryanjp3** [comment] 2016-02-25 20:32
HI @AndreiVF I verified that your patch works with Visual Leak Detector. I can post the outputs if desired but it's a mess. I was thinking about replacing the dynamically allocated pointers with `cv::Ptr` but the nested try and catch block is a valid solution and might be worth a pull request.

Just a note my compiler gives me a warning about `e` in the catch block being an unreferenced local variable. This can be easily fixed by changing `throw;` to `throw e;` which do the same thing.

**Comment by AndreiVF** [comment] 2016-02-25 21:03
Sounds good, @bryanjp3! `throw e` is indeed a better choice.

**Comment by AndreiVF** [comment] 2016-03-02 14:35
@bryanjp3 , do you plan to make a pull request? I myself cannot do it because I'm not familiar with the OpenCV development flow. Thanks in advance!

**Comment by ilya-lavrenov** [comment] 2016-07-12 08:55
@AndreiVF, @bryanjp3, thanks for your help in finding this bug. I've incorporated your suggestions in MR https://github.com/opencv/opencv/pull/6882.

**Closed** 2016-07-12 10:49 UTC
Labels: bug, category: flann
