### ISSUE TITLE
opencv-4.4.0\modules\videoio\src\cap_msmf.cpp (682) CvCapture_MSMF::initStream Failed to set mediaType (stream 0, (640x480 @ 30) MFVideoFormat_RGB24(unsupported media type)

### ISSUE THREAD

**Issue by AlexandreBourrieau** [opencv/opencv#18304] opened 2020-09-09 16:48 UTC
##### System information (version)

[OpenCV1.zip](https://github.com/opencv/opencv/files/5196784/OpenCV1.zip)

Hello,

I make an example program with opencv on my main computer (windows 10 x64) with opencv4.4.0, visual c++ 2019 and it work fine on the main computer. I have compiled sources files as explain on the opencv site.

When i try to run it on a windows 7 x64 computer after importing all the dll (core440, videoio,  ....) , i got the error :
...opencv-4.4.0\modules\videoio\src\cap_msmf.cpp (682) CvCapture_MSMF::initStream Failed to set mediaType (stream 0, (640x480 @ 30) MFVideoFormat_RGB24(unsupported media type)

I am serarching all other the web for few hours now but found nothing helping me... Does someone here have a solution ?

Thanks !

```
#include "opencv2/imgcodecs.hpp"
#include "opencv2/highgui.hpp"
#include "opencv2/imgproc.hpp"
#include <string>
#include <opencv2/core.hpp>
#include <opencv2/videoio.hpp>
#include <iostream>
#include <stdio.h>

using namespace cv;
using namespace std;

int main(int argc, char** argv)
{
	double Fiducial_Diameter = 0.5;
	Mat src;


	if (argc < 3) {
		cerr << "ERROR! Argument missing\n";
		return -1;
	}
	string num  = argv[1];
	string diam = argv[2];

	VideoCapture cap;
	int deviceID = stoi(num);				// 0 = open default camera
	int apiID = cv::CAP_ANY;				// 0 = autodetect default API


		
	// open selected camera using selected API
	cap.open(deviceID, apiID);
	// check if we succeeded
	if (!cap.isOpened()) {
		cerr << "ERROR! Unable to open camera\n";
		return -1;
	}
	//--- GRAB AND WRITE LOOP
	cout << "Start grabbing" << endl
		<< "Press any key to terminate" << endl;
	for (;;)
	{
		// wait for a new frame from camera and store it into 'frame'
		cap.read(src);
		// check if we succeeded
		if (src.empty()) {
			cerr << "ERROR! blank frame grabbed\n";
			break;
		}
		// show live and wait for a key with timeout long enough to show images
	// Get center of the image
		Point CenterOfImage = Point(src.size().width / 2, src.size().height / 2);
		circle(src, CenterOfImage, stoi(diam), Scalar(0, 255, 000), 1, LINE_AA);
		

		imshow("Live", src);
		if (waitKey(5) >= 0)
			break;
	}
	return EXIT_SUCCESS;
}
```

**Comment by bharathreddy3468** [comment] 2020-09-15 05:22
> ##### System information (version)
> [OpenCV1.zip](https://github.com/opencv/opencv/files/5196784/OpenCV1.zip)
> 
> Hello,
> 
> I make an example program with opencv on my main computer (windows 10 x64) with opencv4.4.0, visual c++ 2019 and it work fine on the main computer. I have compiled sources files as explain on the opencv site.
> 
> When i try to run it on a windows 7 x64 computer after importing all the dll (core440, videoio, ....) , i got the error :
> ...opencv-4.4.0\modules\videoio\src\cap_msmf.cpp (682) CvCapture_MSMF::initStream Failed to set mediaType (stream 0, (640x480 @ 30) MFVideoFormat_RGB24(unsupported media type)
> 
> I am serarching all other the web for few hours now but found nothing helping me... Does someone here have a solution ?
> 
> Thanks !
> 
> ```
> #include "opencv2/imgcodecs.hpp"
> #include "opencv2/highgui.hpp"
> #include "opencv2/imgproc.hpp"
> #include <string>
> #include <opencv2/core.hpp>
> #include <opencv2/videoio.hpp>
> #include <iostream>
> #include <stdio.h>
> 
> using namespace cv;
> using namespace std;
> 
> int main(int argc, char** argv)
> {
> 	double Fiducial_Diameter = 0.5;
> 	Mat src;
> 
> 
> 	if (argc < 3) {
> 		cerr << "ERROR! Argument missing\n";
> 		return -1;
> 	}
> 	string num  = argv[1];
> 	string diam = argv[2];
> 
> 	VideoCapture cap;
> 	int deviceID = stoi(num);				// 0 = open default camera
> 	int apiID = cv::CAP_ANY;				// 0 = autodetect default API
> 
> 
> 		
> 	// open selected camera using selected API
> 	cap.open(deviceID, apiID);
> 	// check if we succeeded
> 	if (!cap.isOpened()) {
> 		cerr << "ERROR! Unable to open camera\n";
> 		return -1;
> 	}
> 	//--- GRAB AND WRITE LOOP
> 	cout << "Start grabbing" << endl
> 		<< "Press any key to terminate" << endl;
> 	for (;;)
> 	{
> 		// wait for a new frame from camera and store it into 'frame'
> 		cap.read(src);
> 		// check if we succeeded
> 		if (src.empty()) {
> 			cerr << "ERROR! blank frame grabbed\n";
> 			break;
> 		}
> 		// show live and wait for a key with timeout long enough to show images
> 	// Get center of the image
> 		Point CenterOfImage = Point(src.size().width / 2, src.size().height / 2);
> 		circle(src, CenterOfImage, stoi(diam), Scalar(0, 255, 000), 1, LINE_AA);
> 		
> 
> 		imshow("Live", src);
> 		if (waitKey(5) >= 0)
> 			break;
> 	}
> 	return EXIT_SUCCESS;
> }
> ```

same problem here on the win 7 64bit

**Comment by mshabunin** [comment] 2020-09-15 10:11
Try `apiID = CAP_DSHOW`.

Duplicate of #18044
See https://github.com/opencv/opencv/issues/18044#issuecomment-669821025

**Closed by mshabunin** 2020-09-15 10:11 UTC
Labels: category: videoio, category: videoio(camera), incomplete, platform: win32
