### ISSUE TITLE
Can't create cv::cuda::CascadeClassifier

### ISSUE THREAD

**Issue by IDontKnower** [opencv/opencv#14919] opened 2019-06-27 19:44 UTC
## System information (version)
- OpenCV => 4.1.1-pre
- Operating System / Platform => Windows 10 64 Bit
- Compiler => Visual Studio 2019

##### Detailed description

Trying to load _cv::cuda::CascadeClassifier_, get error on create:

> OpenCV(4.1.1-pre) D:\opencv-master\modules\core\include\opencv2/core/private.cuda.hpp:113: error: (-213:The function/feature is not implemented) The called functionality is disabled for current build or platform in function 'throw_no_cuda'

##### Steps to reproduce
`int main()
{
String path = "absolute_path_to\\haarcascade_frontalface_alt2_cuda.xml";
try
{
Ptr <cv::cuda::CascadeClassifier> cascade_gpu = cv::cuda::CascadeClassifier::create(path);
}
catch (Exception& e)
{
cout << e.msg;
}
}`

getCudaEnabledDeviceCount() == 0 method return 1
Build info below

> General configuration for OpenCV 4.1.1-pre =====================================
 Version control:               unknown
Extra modules:
Location (extra):            D:/opencv_contrib-master/modules
Version control (extra):     unknown
Platform:
Timestamp:                   2019-06-26T21:39:05Z
Host:                        Windows 10.0.17763 AMD64
CMake:                       3.15.0-rc1
CMake generator:             Visual Studio 16 2019
CMake build tool:            D:/IDE Files/VS Community 2019/MSBuild/Current/Bin/MSBuild.exe
MSVC:                        1921
CPU/HW features:
Baseline:                    SSE SSE2 SSE3
requested:                 SSE3
Dispatched code generation:  SSE4_1 SSE4_2 FP16 AVX AVX2 AVX512_SKX
requested:                 SSE4_1 SSE4_2 AVX FP16 AVX2 AVX512_SKX
SSE4_1 (15 files):         + SSSE3 SSE4_1
SSE4_2 (2 files):          + SSSE3 SSE4_1 POPCNT SSE4_2
FP16 (1 files):            + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 AVX
AVX (4 files):             + SSSE3 SSE4_1 POPCNT SSE4_2 AVX
AVX2 (28 files):           + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2
AVX512_SKX (4 files):      + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2 AVX_512F AVX512_COMMON AVX512_SKX
 C/C++:
Built as dynamic libs?:      YES
C++ Compiler:                D:/IDE Files/VS Community 2019/VC/Tools/MSVC/14.21.27702/bin/Hostx64/x64/cl.exe  (ver 19.21.27702.2)
C++ flags (Release):         /DWIN32 /D_WINDOWS /W4 /GR  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise     /EHa /wd4127 /wd4251 /wd4324 /wd4275 /wd4512 /wd4589 /MP8   /MD /O2 /Ob2 /DNDEBUG
C++ flags (Debug):           /DWIN32 /D_WINDOWS /W4 /GR  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise     /EHa /wd4127 /wd4251 /wd4324 /wd4275 /wd4512 /wd4589 /MP8   /MDd /Zi /Ob0 /Od /RTC1
C Compiler:                  D:/IDE Files/VS Community 2019/VC/Tools/MSVC/14.21.27702/bin/Hostx64/x64/cl.exe
C flags (Release):           /DWIN32 /D_WINDOWS /W3  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise       /MP8    /MD /O2 /Ob2 /DNDEBUG
C flags (Debug):             /DWIN32 /D_WINDOWS /W3  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise       /MP8  /MDd /Zi /Ob0 /Od /RTC1
Linker flags (Release):      /machine:x64  /INCREMENTAL:NO
Linker flags (Debug):        /machine:x64  /debug /INCREMENTAL
ccache:                      NO
Precompiled headers:         YES
Extra dependencies:          cudart_static.lib nppc.lib nppial.lib nppicc.lib nppicom.lib nppidei.lib nppif.lib nppig.lib nppim.lib nppist.lib nppisu.lib nppitc.lib npps.lib cublas.lib cufft.lib -LIBPATH:C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/lib/x64
3rdparty dependencies:
OpenCV modules:
To be built:                 aruco bgsegm bioinspired calib3d ccalib core cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev datasets dpm face features2d flann fuzzy gapi hfs highgui img_hash imgcodecs imgproc line_descriptor ml objdetect optflow phase_unwrapping photo plot quality reg rgbd saliency shape stereo stitching structured_light superres surface_matching tracking ts video videoio videostab xfeatures2d ximgproc xobjdetect xphoto
Disabled:                    world
Disabled by dependency:      dnn_objdetect text
Unavailable:                 cnn_3dobj cvv dnn freetype hdf java js matlab ovis python2 python3 sfm viz
Applications:                tests perf_tests apps
Documentation:               NO
Non-free algorithms:         NO
Windows RT support:            NO
GUI:
Win32 UI:                    YES
VTK support:                 NO
Media I/O:
ZLib:                        build (ver 1.2.11)
JPEG:                        build-libjpeg-turbo (ver 2.0.2-62)
WEBP:                        build (ver encoder: 0x020e)
PNG:                         build (ver 1.6.37)
TIFF:                        build (ver 42 - 4.0.10)
JPEG 2000:                   build (ver 1.900.1)
OpenEXR:                     build (ver 2.3.0)
HDR:                         YES
SUNRASTER:                   YES
PXM:                         YES
PFM:                         YES
Video I/O:
DC1394:                      NO
FFMPEG:                      YES (prebuilt binaries)
avcodec:                   YES (58.35.100)
avformat:                  YES (58.20.100)
avutil:                    YES (56.22.100)
swscale:                   YES (5.3.100)
avresample:                YES (4.0.0)
GStreamer:                   NO
DirectShow:                  YES
Media Foundation:            YES
DXVA:                      YES
Parallel framework:            Concurrency
Trace:                         YES (with Intel ITT)
Other third-party libraries:
Intel IPP:                   2019.0.0 Gold [2019.0.0]
at:                   D:/opencv-master/build/3rdparty/ippicv/ippicv_win/icv
Intel IPP IW:                sources (2019.0.0)
at:                D:/opencv-master/build/3rdparty/ippicv/ippicv_win/iw
Lapack:                      NO
Eigen:                       NO
Custom HAL:                  NO
NVIDIA CUDA:                   YES (ver 10.1, CUFFT CUBLAS)
NVIDIA GPU arch:             30 35 37 50 52 60 61 70 75
NVIDIA PTX archs:
cuDNN:                         NO
OpenCL:                        YES (NVD3D11)
Include path:                D:/opencv-master/3rdparty/include/opencl/1.2
Link libraries:              Dynamic load
Python (for build):            D:/IDE Files/Python3.7/python.exe
Java:
ant:                         NO
JNI:                         NO
Java wrappers:               NO
Java tests:                  NO
 Install to:                    D:/opencv-master/build/install
-----------------------------------------------------------------
CPU CascadeClassifire works well
Can someone help?

**Comment by alalek** [comment] 2019-06-27 19:53
duplicate of https://github.com/opencv/opencv_contrib/issues/2048

**Closed by alalek** 2019-06-27 19:53 UTC
Labels: duplicate
