### ISSUE TITLE
error when use FaceRecognizerSF conduct alignCrop

### ISSUE THREAD

**Issue by gxxzs** [opencv/opencv#22567] opened 2022-09-26 09:23 UTC
##### System information (version)

- OpenCV => 4.5.4
- Operating System / Platform => ubuntu 16.04
- Compiler => QT59

segmentation fault

```
  Mat img = imread("/home/zs/face_landmark/output/test.jpg");
  // 第三步：初始化FaceDetectorYN
  cv::String fd_modelPath = "/home/zs/face_landmark/models/face_detector_models/yunet.onnx";
//  cv::String fr_modelPath = "/home/zs/face_landmark/models/face_detector_models/face_recognizer_fast.onnx";
  cv::String fr_modelPath = "/home/zs/face_landmark/models/face_detector_models/face_recognition_sface_2021dec.onnx";

  Ptr<FaceDetectorYN> faceDetector = FaceDetectorYN::create(fd_modelPath, "", img.size());
  Ptr<FaceRecognizerSF> faceRecognizer = FaceRecognizerSF::create(fr_modelPath, "");

  Mat faces;
  faceDetector->detect(img, faces);

 Mat aligned_face1, aligned_face2;
 Mat feature1, feature2;
  std::cout<<faces.rows<<std::endl;

//  faceRecognizer->feature(faces, feature1);
  faceRecognizer->alignCrop(img, faces.row(0), aligned_face1);

```

CMakeLists.txt
```
add_executable(face_detection src/face_detection.cpp)
target_link_libraries(face_detection ${catkin_LIBRARIES}   ${OpenCV_LIBRARIES}
    /usr/local/opencv454/lib/libopencv_highgui.so
    /usr/local/opencv454/lib/libopencv_core.so
    /usr/local/opencv454/lib/libopencv_imgproc.so
    /usr/local/opencv454/lib/libopencv_imgcodecs.so
    /usr/local/opencv454/lib/libopencv_dnn.so
    /usr/local/opencv454/lib/libopencv_objdetect.so)
```

**Comment by fengyuentau** [comment] 2022-09-26 09:40
Thank you for the feedback! Could you provide your run log? Just want to ensure faces is not empty.

**Comment by fengyuentau** [comment] 2022-09-26 09:40
Thank you for the feedback! Could you provide your run log? Just want to ensure faces is not empty.

**Comment by gxxzs** [comment] 2022-09-27 01:25
> Thank you for the feedback! Could you provide your run log? Just want to ensure faces is not empty.

> Thank you for the feedback! Could you provide your run log? Just want to ensure faces is not empty.
I am sure the faces is not empty. I run 

visualize(img,faces);

void visualize(Mat& input, Mat& faces)
{
  int thickness = 2;
  //  std::string fpsString = cv::format("FPS : %.2f", (float)fps);
  //  if (frame >= 0)
  //    cout << "Frame " << frame << ", ";
  //  cout << "FPS: " << fpsString << endl;
  for (int i = 0; i < faces.rows; i++)
  {
    // Print results
    cout << "Face " << i
         << ", top-left coordinates: (" << faces.at<float>(i, 0) << ", " << faces.at<float>(i, 1) << "), "
         << "box width: " << faces.at<float>(i, 2)  << ", box height: " << faces.at<float>(i, 3) << ", "
         << "score: " << cv::format("%.2f", faces.at<float>(i, 14))
         << endl;
    // Draw bounding box
    rectangle(input, Rect2i(int(faces.at<float>(i, 0)), int(faces.at<float>(i, 1)), int(faces.at<float>(i, 2)), int(faces.at<float>(i, 3))), Scalar(0, 255, 0), thickness);
    // Draw landmarks
    rectangle(input, Rect2i(int(faces.at<float>(i, 4)), int(faces.at<float>(i, 5)), int(3), int(3)), Scalar(255, 0, 0), 2);
    rectangle(input, Rect2i(int(faces.at<float>(i, 6)), int(faces.at<float>(i, 7)), int(3), int(3)), Scalar(0, 0, 255), 2);
    rectangle(input, Rect2i(int(faces.at<float>(i, 8)), int(faces.at<float>(i, 9)), int(3), int(3)), Scalar(0, 255, 0), 2);
    rectangle(input, Rect2i(int(faces.at<float>(i, 10)), int(faces.at<float>(i, 11)), int(3), int(3)), Scalar(255, 0, 255), 2);
    rectangle(input, Rect2i(int(faces.at<float>(i, 12)), int(faces.at<float>(i, 13)), int(3), int(3)), Scalar(0, 255, 255), 2);
  }
  //  putText(input, fpsString, Point(0, 15), FONT_HERSHEY_SIMPLEX, 0.5, Scalar(0, 255, 0), 2);
}

I save the img, the keypoints in faces was drawn on the picture.

**Comment by gxxzs** [comment] 2022-09-27 02:24
> 
This is the test image. Thanks!
![test](https://user-images.githubusercontent.com/32094632/192416807-f2d2b28d-d356-4576-88a6-18dcd0298164.jpg)

**Comment by fengyuentau** [comment] 2022-09-27 03:26
Tested with the latest opencv and could not reproduce your error.

**Comment by gxxzs** [comment] 2022-09-27 04:06
> Tested with the latest opencv and could not reproduce your error.
Dose your opencv version 4.6.0?
can you send your reproduce peoject to me ? May I can figure out where the error happens by comparing with your peoject. My Email address is: zhangshuaihenan@163.com.Thanks!

**Comment by fengyuentau** [comment] 2022-09-27 06:41
I just modified the `$opencv/samples/dnn/face_detect.cpp` to run with your test image:

```cpp
int main(int argc, char** argv)
{
    CommandLineParser parser(argc, argv,
        "{help  h           |            | Print this message}"
        "{image1 i1         |            | Path to the input image1. Omit for detecting through VideoCapture}"
        "{image2 i2         |            | Path to the input image2. When image1 and image2 parameters given then the program try to find a face on both images and runs face recognition algorithm}"
        "{video v           | 0          | Path to the input video}"
        "{scale sc          | 1.0        | Scale factor used to resize input video frames}"
        "{fd_model fd       | face_detection_yunet_2021dec.onnx| Path to the model. Download yunet.onnx in https://github.com/opencv/opencv_zoo/tree/master/models/face_detection_yunet}"
        "{fr_model fr       | face_recognition_sface_2021dec.onnx | Path to the face recognition model. Download the model at https://github.com/opencv/opencv_zoo/tree/master/models/face_recognition_sface}"
        "{score_threshold   | 0.9        | Filter out faces of score < score_threshold}"
        "{nms_threshold     | 0.3        | Suppress bounding boxes of iou >= nms_threshold}"
        "{top_k             | 5000       | Keep top_k bounding boxes before NMS}"
        "{save s            | false      | Set true to save results. This flag is invalid when using camera}"
    );
    if (parser.has("help"))
    {
        parser.printMessage();
        return 0;
    }

    String fd_modelPath = parser.get<String>("fd_model");
    std::cout << fd_modelPath << std::endl;
    String fr_modelPath = parser.get<String>("fr_model");
    std::cout << fr_modelPath << std::endl;

    float scoreThreshold = parser.get<float>("score_threshold");
    float nmsThreshold = parser.get<float>("nms_threshold");
    int topK = parser.get<int>("top_k");

    bool save = parser.get<bool>("save");
    float scale = parser.get<float>("scale");

    double cosine_similar_thresh = 0.363;
    double l2norm_similar_thresh = 1.128;

    Ptr<FaceDetectorYN> detector = FaceDetectorYN::create(fd_modelPath, "", Size(320, 320), scoreThreshold, nmsThreshold, topK);
    Ptr<FaceRecognizerSF> faceRecognizer = FaceRecognizerSF::create(fr_modelPath, "");

    TickMeter tm;

    // If input is an image
    if (parser.has("image1"))
    {
        String input1 = parser.get<String>("image1");
        Mat image1 = imread(input1);
        if (image1.empty())
        {
            std::cerr << "Cannot read image: " << input1 << std::endl;
            return 2;
        }

        int imageWidth = int(image1.cols * scale);
        int imageHeight = int(image1.rows * scale);
        resize(image1, image1, Size(imageWidth, imageHeight));
        tm.start();

        //! [inference]
        // Set input size before inference
        detector->setInputSize(image1.size());

        Mat faces1;
        detector->detect(image1, faces1);
        if (faces1.rows < 1)
        {
            std::cerr << "Cannot find a face in " << input1 << std::endl;
            return 1;
        }
        //! [inference]

        tm.stop();
        // Draw results on the input image
        visualize(image1, -1, faces1, tm.getFPS());

        // Save results if save is true
        cout << "Saving result.jpg...\n";
        imwrite("result.jpg", image1);


        //! [facerecognizer]
        // Aligning and cropping facial image through the first face of faces detected.
        Mat aligned_face1, aligned_face2;
        faceRecognizer->alignCrop(image1, faces1.row(0), aligned_face1);

        // Run feature extraction with given aligned_face
        Mat feature1, feature2;
        faceRecognizer->feature(aligned_face1, feature1);
        feature1 = feature1.clone();
    }
    return 0;
}
```

Build with `-DBUILD_EXAMPLES=ON` to enable samples.

**Comment by asmorkalov** [comment] 2023-06-13 11:55
@gxxzs @fengyuentau May I close the issue?

**Comment by fengyuentau** [comment] 2023-06-13 12:41
> @gxxzs @fengyuentau May I close the issue?

Yes. Let me close.

**Closed by fengyuentau** 2023-06-13 12:41 UTC
Labels: category: objdetect
