### ISSUE TITLE
Opencv Compiling issue at 20%

### ISSUE THREAD

**Issue by gigiati** [opencv/opencv#10531] opened 2018-01-06 15:51 UTC
> 
> [ 20%] Built target opencv_test_optflow_pch_dephelp
> [ 20%] Generating precomp.hpp
> [ 20%] Generating precomp.hpp.gch/opencv_highgui_RELEASE.gch
> [ 20%] Linking CXX static library ../../lib/libopencv_stitching_pch_dephelp.a
> [ 20%] Built target opencv_stitching_pch_dephelp
> [ 20%] Generating precomp.hpp
> [ 20%] Generating precomp.hpp.gch/opencv_core_RELEASE.gch
> In file included from /usr/include/c++/6/bits/stl_algo.h:59:0,
>                  from /usr/include/c++/6/algorithm:62,
>                  from /home/pi/opencv-3.1.0/modules/core/include/opencv2/core/base.hpp:53,
>                  from /home/pi/opencv-3.1.0/modules/core/include/opencv2/core.hpp:54,
>                  from /home/pi/opencv-3.1.0/modules/core/include/opencv2/core/utility.hpp:52,
>                  from /home/pi/opencv-3.1.0/build/modules/core/precomp.hpp:49:
> /usr/include/c++/6/cstdlib:75:25: fatal error: stdlib.h: No such file or directory
>  #include_next <stdlib.h>
>                          ^
> compilation terminated.
> modules/core/CMakeFiles/pch_Generate_opencv_core.dir/build.make:62: recipe for target 'modules/core/precomp.hpp.gch/opencv_core_RELEASE.gch' failed
> make[2]: *** [modules/core/precomp.hpp.gch/opencv_core_RELEASE.gch] Error 1
> CMakeFiles/Makefile2:2014: recipe for target 'modules/core/CMakeFiles/pch_Generate_opencv_core.dir/all' failed
> make[1]: *** [modules/core/CMakeFiles/pch_Generate_opencv_core.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> [ 20%] Linking CXX static library ../../lib/libopencv_test_stitching_pch_dephelp.a
> [ 20%] Built target opencv_test_stitching_pch_dephelp
> [ 20%] Linking CXX static library ../../lib/libopencv_perf_stitching_pch_dephelp.a
> [ 20%] Built target opencv_perf_stitching_pch_dephelp
> [ 20%] Built target pch_Generate_opencv_highgui
> Makefile:160: recipe for target 'all' failed
> make: *** [all] Error 2
> 

Has you can see i hav a trouble with trying to compile.

Someone can help me?

thanks to anyone can give me a way to compil all 💃

**Comment by sergiud** [comment] 2018-01-06 17:24
There's something wrong with your build environment if standard headers cannot be found.

**Comment by gigiati** [comment] 2018-01-06 17:26
Hello, thanks for your reponse.

i have follow this way to install opencv

https://www.pyimagesearch.com/2016/04/18/install-guide-raspberry-pi-3-raspbian-jessie-opencv-3/

I spossible to confirm this is the good way to do ?

Thanks

**Comment by alalek** [comment] 2018-01-06 17:58
duplicate of #6517 and [others](https://github.com/opencv/opencv/issues?utf8=%E2%9C%93&q=is%3Aissue+include_next+)

**Closed by alalek** 2018-01-06 17:58 UTC
Labels: category: build/install, duplicate
