### ISSUE TITLE
Add Unicode file name support in modules/imgcodecs/src/loadsave.cpp with _wfopen

### ISSUE THREAD

**Issue by defrag257** [opencv/opencv#7237] opened 2016-09-05 16:40 UTC
##### System information (version)

- OpenCV => 3.1
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015

##### Detailed description

Why C programming language sucks is that char is only required to contain ASCII, not UTF-8.

In Windows, _FILE *fopen(const char *filename, const char *mode);_ only accepts Windows-1252, which has only 256 characters, while Unicode has 1112064. To use Unicode, The wide-char version _FILE *_wfopen(const wchar_t *filename, const wchar_t *mode);_ is required.

I suggest to add two alternative functions *imread_w* and *imwrite_w*, which accept wchar_t, in only Windows builds.

**Comment by StevenPuttemans** [comment] 2016-09-08 08:34
For suggestions, the fastest way to get them in is providing a pull request with the forementioned suggestion. If not, I am afraid that adding this will drop down on the priority list quite fast!

**Comment by alalek** [comment] 2016-09-08 14:38
Duplicate of #4242 and #4292

**Closed by alalek** 2016-09-08 14:38 UTC
Labels: duplicate
