### ISSUE TITLE
Absdiff segfaults on Android armv7-neon

### ISSUE THREAD

**Issue by Tomin1** [opencv/opencv#6247] opened 2016-03-13 16:50 UTC
OpenCV segfaults on Android (armv7-neon) when trying to get absdiff. Even this simple line causes it to crash:
`Core.absdiff(Mat.zeros(10, 10, CvType.CV_8UC3), Mat.zeros(10, 10, CvType.CV_8UC3), new Mat(10, 10, CvType.CV_8UC3));`
I have also tried it with other matrices that are created from real images and that is how I bumped into this. If you think Mat.zeros matrices are the problem, then please try to create other matrices and test with them, I'm quite sure you'll have a SIGSEGV in that case too.

I don't know if this problem happens with any other hardware or on anything other than Android. I need this function for a project work class in my university. I did search this bug tracker and OpenCV answers for this problem and I found this:
http://stackoverflow.com/questions/35843940/opencv-3-1-0-absdiff-does-not-work
Someone else had the same problem.
### Please state the information for your system
- OpenCV version: 3.1.0
- Host OS: Linux (Fedora 23) and Android Studio 1.5.1
- Target OS: Android 6.0.1, Nexus 7 (2013) -> armv7-neon, used OpenCV Manager from Play store
### In which part of the OpenCV library you got the issue?
- core
### Expected behaviour

```
/? I/System.out: Calculate absdiff!
/? I/System.out: Absdiff calculated!
```
### Actual behaviour

```
/? I/System.out: Calculate absdiff!
/? A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x16 in tid 26933 (v.my.opencvtest)
```
### Additional description

You can use the code below, just create a new Android project insert OpenCV and add the needed parts from the code.
### Code example to reproduce the issue

```
package test.opencv.my.opencvtest;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;

import org.opencv.android.BaseLoaderCallback;
import org.opencv.android.LoaderCallbackInterface;
import org.opencv.android.OpenCVLoader;
import org.opencv.core.Core;
import org.opencv.core.CvType;
import org.opencv.core.Mat;

public class MainActivity extends AppCompatActivity {

    private BaseLoaderCallback mLoaderCallback = new BaseLoaderCallback(this) {
        @Override
        public void onManagerConnected(int status) {
            switch (status) {
                case LoaderCallbackInterface.SUCCESS:
                {
                    // Testing code, if this crashes, we have a bug
                    System.out.println("Calculate absdiff!");
                    Core.absdiff(Mat.zeros(10, 10, CvType.CV_8UC3), Mat.zeros(10, 10, CvType.CV_8UC3), new Mat(10, 10, CvType.CV_8UC3));
                    System.out.println("Absdiff calculated!");
                } break;
                default:
                {
                    super.onManagerConnected(status);
                } break;
            }
        }
    };

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
    }

    @Override
    public void onResume()
    {
        super.onResume();
        OpenCVLoader.initAsync(OpenCVLoader.OPENCV_VERSION_3_1_0, this, mLoaderCallback);
    }
}
```
### Edits

Sorry, accidentally wrote armv8 not armv7. I corrected it now.

**Comment by Tomin1** [comment] 2016-03-14 18:48
I rebuilt opencv_engine.apk and replaced the OpenCV Manager on the Nexus 7 and it doesn't crash anymore. I used the armeabi-v7a which is the arm7-neon build if I've understood correctly. The code I used was git tag 3.1.0 and I had to fix cmake scripts a little because of cmake 3.4 (on Fedora 23): http://stackoverflow.com/questions/26841603/arm-linux-androideabi-bin-ld-fatal-error-soname-must-take-a-non-empty-argume

I guess that the apk file on Play store might be broken.

**Comment by NeilDG** [comment] 2016-03-16 04:56
Confirmed reproducible on Lenovo P70. I can't compute for PSNR now. :(

**Comment by NeilDG** [comment] 2016-03-16 06:16
The build provided in the OpenCV Android SDK (OpenCV_3.1.0_Manager_3.10_armeabi-v7a.apk) is working.

**Comment by Tecaa** [comment] 2016-08-07 06:51
@Tomin1 ,  Would you share your 3.10 rebuilted version?

**Comment by Tomin1** [comment] 2016-08-07 07:20
@Tecaa I'm not sure why you'd need it if the version distributed with Android SDK works just fine. You can download that from OpenCV website.

Anyway, if you need this for some reason, here it is: https://dl.dropboxusercontent.com/u/4305182/linked/opencv_engine-armeabi-v7a.apk (I will keep the link alive for at least a week)

**Comment by Tecaa** [comment] 2016-08-07 07:31
Ok thanks, you have reasons. I have taked 3.0 version of Android SDK and works perfect! I improve my aplication from 3[s] (using fors to do manually absdiff) to 77 [ms]. Thanks you very much!

**Comment by grenobnik** [comment] 2016-08-07 12:45
Same here, my app crashes on Core.absdiff(frame1, frame2, frameDiff) on LG G2 when using OpenCV Manager from Google Play and works fine with OpenCV_3.1.0_Manager_3.10_armeabi-v7a.apk provided with OpenCV-android-sdk. Could it be fixed soon?

**Comment by ayogan2** [comment] 2016-08-12 03:45
I seem to be facing the same issue on an Samsung Galaxy Note 5

**Comment by mako2501** [comment] 2016-09-08 12:21
Same problem on XPeria L, opencv manager from opencv-android-sdk apk solve problem. 
Who can upload fixed version of manager to Google Play?

**Comment by davidmigloz** [comment] 2017-01-04 17:33
Any progress with this? As I can see, OpenCV Manager from Google Play has not yet been updated...

**Comment by mickod** [comment] 2017-12-29 15:46
To add to @davidmigloz question - this seems to have been an issue for a while and the OpenCv version on Google play has not been updated. Does this mean that openCV on Android is not commonly used, or is it being used in some way that avoids this problem? If its the latter, then if someone could point us in the right direction that would be great!

**Comment by rahmabouka** [comment] 2018-09-24 17:08
how to solve this problem using adb ??

**Comment by mshabunin** [comment] 2018-09-25 11:16
Closing this since OpenCV Manager has been removed from the Play store.

**Closed by mshabunin** 2018-09-25 11:16 UTC
Labels: bug, platform: android
