### ISSUE TITLE
Mobilenet-SSD output error results with OpenCL

### ISSUE THREAD

**Issue by yiran-THU** [opencv/opencv#10465] opened 2017-12-29 09:36 UTC
##### System information (version)
- OpenCV => 3.4.0
- Operating System / Platform => Windows 10 64 Bit
- Compiler => Visual Studio 2015
- Cmake => 3.9.6

##### Detailed description
I have tried to run this [program](https://github.com/opencv/opencv/blob/master/samples/dnn/ssd_mobilenet_object_detection.cpp),    but the detection results of this program are wrong if I set "opencl" as true in 
```
const char* params  
    = "{ help           | false | print usage         }"  
      "{ proto          | MobileNetSSD_deploy.prototxt | model configuration }"  
      "{ model          | MobileNetSSD_deploy.caffemodel | model weights }"  
      "{ camera_device  | 0     | camera device number }"  
      "{ video          |   1.jpg    | video or image for detection}"  
      "{ out            |       | path to output video file}"  
      "{ min_confidence | 0.2   | min confidence      }"  
      "{ opencl         | true | enable OpenCL }"  
;.
```     
The following picture is detection result with OpenCL.   
![error](https://user-images.githubusercontent.com/16274710/34433749-469b3326-ecbc-11e7-8fe8-ad471edd9059.png)  
The dimension of Mat detection obtained with  `Mat detection = net.forward("detection_out"); ` is "1,1,100,7". This is obviously wrong.   
The inputBlob in  `net.setInput(inputBlob, "data");` has been checked, it is right.  
I think the problem is in `Mat detection = net.forward("detection_out"); `  
   
    
     
However ,when I set `net.setPreferableTarget(DNN_TARGET_CPU);`,the detection result with CPU is right.  
This is the right detection result.
![right](https://user-images.githubusercontent.com/16274710/34433934-9e878728-ecbd-11e7-8a51-100e915d2195.png)
  
  
Besides, when I input VGG net 's prototxt and caffemodel instead, the detection result is also right.  
##### Steps to reproduce
I download Mobilenet-ssd 's caffemodel and prototxt from [here](https://github.com/chuanqi305/MobileNet-SSD) ,and they work well without OpenCL.

I build OpenCV  with OpenCL, with caffe, without CUDA.  
The process of building OpenCV goes well, no warnings ,no errors.  
I have set OpenCV path and OpencL path properly in VS2015 setting.  

What do I have to do to improve the speed of ssd with OpenCL?

I am looking forward to your reply.
Thank you!

**Comment by dkurt** [comment] 2017-12-29 10:51
@yiran-THU one thing I know is that MobileNet-SSD from TensorFlow is not working working well now with OpenCL backend. I just wanted to open an issue about it. But we had no problems with MobileNet-SSD from Caffe (test `OCL_Reproducibility_MobileNet_SSD.Accuracy`) until now. I'll try to reproduce it.

**Comment by atlury** [comment] 2017-12-29 12:40
@yiran-THU 

Check this.

https://github.com/01org/caffe/issues/101

Seems similar issue was resolved for Mobilenet SSD

**Comment by dkurt** [comment] 2017-12-29 16:42
@yiran-THU, please specify build information from https://docs.opencv.org/master/db/de0/group__core__utils.html#ga0ae377100bc03ce22322926bba7fdbb5.

**Comment by yiran-THU** [comment] 2017-12-30 01:23
@dkurt  Here is my building information.
```
General configuration for OpenCV 3.4.0 =====================================
  Version control:               unknown

  Extra modules:
    Location (extra):            C:/lib/opencv_contrib/modules
    Version control (extra):     unknown

  Platform:
    Timestamp:                   2017-12-28T03:33:02Z
    Host:                        Windows 10.0.14393 AMD64
    CMake:                       3.9.6
    CMake generator:             Visual Studio 14 2015 Win64
    CMake build tool:            C:/Program Files (x86)/MSBuild/14.0/bin/MSBuild.exe
    MSVC:                        1900

  CPU/HW features:
    Baseline:                    SSE SSE2 SSE3
      requested:                 SSE3

  C/C++:
    Built as dynamic libs?:      YES
    C++11:                       YES
    C++ Compiler:                C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe  (ver 19.0.24215.1)
    C++ flags (Release):         /DWIN32 /D_WINDOWS /W4 /GR  /EHa  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi      /wd4127 /wd4251 /wd4324 /wd4275 /wd4512 /wd4589 /MP8  /MD /O2 /Ob2 /DNDEBUG  /Zi
    C++ flags (Debug):           /DWIN32 /D_WINDOWS /W4 /GR  /EHa  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi      /wd4127 /wd4251 /wd4324 /wd4275 /wd4512 /wd4589 /MP8  /MDd /Zi /Ob0 /Od /RTC1
    C Compiler:                  C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
    C flags (Release):           /DWIN32 /D_WINDOWS /W3  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi        /MP8  /MD /O2 /Ob2 /DNDEBUG  /Zi
    C flags (Debug):             /DWIN32 /D_WINDOWS /W3  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi        /MP8  /MDd /Zi /Ob0 /Od /RTC1
    Linker flags (Release):      /machine:x64  /INCREMENTAL:NO  /debug
    Linker flags (Debug):        /machine:x64  /debug /INCREMENTAL
    ccache:                      NO
    Precompiled headers:         YES
    Extra dependencies:
    3rdparty dependencies:

  OpenCV modules:
    To be built:                 aruco bgsegm bioinspired calib3d ccalib core datasets dnn dpm face features2d flann fuzzy highgui img_hash imgcodecs imgproc line_descriptor ml objdetect optflow phase_unwrapping photo plot python2 python3 python_bindings_generator reg rgbd saliency shape stereo stitching structured_light superres surface_matching text tracking ts video videoio videostab xfeatures2d ximgproc xobjdetect xphoto
    Disabled:                    cnn_3dobj js world
    Disabled by dependency:      -
    Unavailable:                 cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev cvv dnn_modern freetype hdf java matlab ovis sfm viz
    Applications:                apps
    Documentation:               NO
    Non-free algorithms:         NO

  Windows RT support:            NO

  GUI:
    Win32 UI:                    YES
    VTK support:                 NO

  Media I/O:
    ZLib:                        build (ver 1.2.11)
    JPEG:                        build (ver 90)
    WEBP:                        build (ver encoder: 0x020e)
    PNG:                         build (ver 1.6.34)
    TIFF:                        build (ver 42 - 4.0.9)
    JPEG 2000:                   build (ver 1.900.1)
    OpenEXR:                     build (ver 1.7.1)

  Video I/O:
    Video for Windows:           YES
    DC1394:                      NO
    FFMPEG:                      YES (prebuilt binaries)
      avcodec:                   YES (ver 57.89.100)
      avformat:                  YES (ver 57.71.100)
      avutil:                    YES (ver 55.58.100)
      swscale:                   YES (ver 4.6.100)
      avresample:                YES (ver 3.5.0)
    GStreamer:                   NO
    DirectShow:                  YES

  Parallel framework:            Concurrency

  Trace:                         YES (with Intel ITT)

  Other third-party libraries:
    Intel IPP:                   2017.0.3 [2017.0.3]
           at:                   C:/lib/Build/3rdparty/ippicv/ippicv_win
    Intel IPP IW:                sources (2017.0.3)
              at:                C:/lib/Build/3rdparty/ippicv/ippiw_win
    Lapack:                      NO
    Eigen:                       NO
    Custom HAL:                  NO

  OpenCL:                        YES (no extra features)
    Include path:                C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/include/CL
    Link libraries:              C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/lib/x64/OpenCL.lib

  Python 2:
    Interpreter:                 C:/ProgramData/Anaconda2/python.exe (ver 2.7.13)
    Libraries:                   C:/ProgramData/Anaconda2/libs/python27.lib (ver 2.7.13)
    numpy:                       C:/ProgramData/Anaconda2/lib/site-packages/numpy/core/include (ver 1.13.3)
    packages path:               C:/ProgramData/Anaconda2/Lib/site-packages

  Python 3:
    Interpreter:                 C:/Users/yiran/Anaconda3/python.exe (ver 3.6.2)
    Libraries:                   C:/Users/yiran/Anaconda3/libs/python36.lib (ver 3.6.2)
    numpy:                       C:/Users/yiran/Anaconda3/lib/site-packages/numpy/core/include (ver 1.13.3)
    packages path:               C:/Users/yiran/Anaconda3/Lib/site-packages

  Python (for build):            C:/ProgramData/Anaconda2/python.exe

  Java:
    ant:                         NO
    JNI:                         NO
    Java wrappers:               NO
    Java tests:                  NO

  Install to:                    C:/lib/Build/install
-----------------------------------------------------------------

```

**Comment by yiran-THU** [comment] 2017-12-30 01:39
@dkurt I don't know how to get the other two summary, can you tell me how to get them?
My cpu is Intel(R)_Core(TM)_i7-6700HQ_CPU_@_2.60GHz

**Comment by alalek** [comment] 2017-12-30 02:22
> opencv_test_dnn

This is OpenCV test, just enable tests in CMake (BUILD_TESTS=ON), build target "opencv_test_dnn" and check for this binary in "bin" subdirectory.

BTW, "clinfo" output should be good too, but we need to know that GPU is selected by OpenCV (Intel iGPU or another CUDA device). Did you see lines like these (in sample terminal window):
```
[ INFO:0] Successfully initialized OpenCL cache directory: /build/.cache/opencv_opencl_cache_x64/
[ INFO:0] Preparing OpenCL cache configuration for context: Intel_R__Corporation--Intel_R__HD_Graphics--r5_0_63503
```

@dkurt 
> Driver version = r4.0.59481

Please update to the latest OpenCL runtime (r5.0 from July 2017)

**Comment by yiran-THU** [comment] 2017-12-30 09:42
@alalek 
This is my information in terminal window if I set `net.setPreferableTarget(DNN_TARGET_OPENCL);`   
```
[ INFO:0] Initialize OpenCL runtime...
OpenCV(ocl4dnn): consider to specify kernel configuration cache directory
                 via OPENCV_OCL4DNN_CONFIG_PATH parameter.
[ INFO:0] Successfully initialized OpenCL cache directory: C:\Users\yiran\AppData\Local\Temp\opencv\3.4.0\opencl_cache\
[ INFO:0] Preparing OpenCL cache configuration for context: Intel_R__Corporation--Intel_R__HD_Graphics_530--21_20_16_4542
```

**Comment by alalek** [comment] 2017-12-30 11:41
> 21_20_16_4542

OpenCV's build machines have this driver version: 23_20_16_4849
You can get updates here: https://downloadcenter.intel.com/product/80939/Graphics-Drivers

BTW, NVIDIA GPU would not work via OpenCL because current OpenCV DNN has optimizations with "Intel subgroups" extension requirement.

**Comment by dkurt** [comment] 2017-12-30 12:32
@alalek,
```
OpenCL Platforms: 
    Intel(R) OpenCL
        iGPU: Intel(R) HD Graphics (OpenCL 1.2 )
        CPU: Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (OpenCL 1.2 (Build 475))
Current OpenCL device: 
    Type = iGPU
    Name = Intel(R) HD Graphics
    Version = OpenCL 1.2 
    Driver version = r5.0.63503
...
```
```
[ INFO:0] Successfully initialized OpenCL cache directory: /home/dkurtaev/.cache/opencv/3.4.0-dev/opencl_cache/
[ INFO:0] Preparing OpenCL cache configuration for context: Intel_R__Corporation--Intel_R__HD_Graphics--r5_0_63503
unknown file: Failure
```
Tests are failed. May be problem is in OpenCL version 1.2 but not 2.0?

**Comment by yiran-THU** [comment] 2017-12-30 12:48
@dkurt 
No，I have tried both OpenCL  2.0 and 1.2 , none of them works.

**Comment by yiran-THU** [comment] 2017-12-30 13:42
@dkurt 
@alalek 
@atlury 

Good news! It's working!
I have upgraded the driver of my iGPU to the latest version, which is 23_20_16_4901 .
Then everything goes well.

The information in terminal window is:
```
[ INFO:0] Initialize OpenCL runtime...
OpenCV(ocl4dnn): consider to specify kernel configuration cache directory
                 via OPENCV_OCL4DNN_CONFIG_PATH parameter.
[ INFO:0] Successfully initialized OpenCL cache directory: C:\Users\yiran\AppData\Local\Temp\opencv\3.4.0\opencl_cache\
[ INFO:0] Preparing OpenCL cache configuration for context: Intel_R__Corporation--Intel_R__HD_Graphics_530--23_20_16_4901
```

**Comment by yiran-THU** [comment] 2017-12-30 13:44
@dkurt @atlury @alalek 
Thank you very much！

**Comment by atlury** [comment] 2017-12-30 13:46
Most welcome...

**Comment by alalek** [comment] 2017-12-30 14:17
@dkurt,
It is strange. It should look like [this](http://pullrequest.opencv.org/buildbot/builders/master-lin64/builds/10326/steps/test_core-ippicv-opencl/logs/stdio):
```
OpenCL Platforms: 
    Intel(R) OpenCL
        iGPU: Intel(R) HD Graphics (OpenCL 2.0 )
        CPU: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (OpenCL 2.0 (Build 475))
Current OpenCL device: 
    Type = iGPU
    Name = Intel(R) HD Graphics
    Version = OpenCL 2.0 
    Driver version = r5.0.63503
...
        cl_intel_subgroups
        cl_intel_subgroups_short
```

But it is for Skylake CPU. i5-4460 is Hasswell CPU with HD4600. Do you see "cl_intel_subgroups" extensions?

**Comment by dkurt** [comment] 2017-12-30 14:53
@alalek, yeah. Here it is.
```
OpenCV version: 3.4.0-dev
OpenCV VCS version: 3.2.0-2389-ga50a355
Build type: release
Parallel framework: pthreads
CPU features: mmx sse sse2 sse3
Intel(R) IPP optimization: enabled
Intel(R) IPP version: ippIP AVX2 (l9) 2017.0.3 (-) Jul 29 2017
[ INFO:0] Initialize OpenCL runtime...
OpenCL Platforms: 
    Intel(R) OpenCL
        iGPU: Intel(R) HD Graphics (OpenCL 1.2 )
        CPU: Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (OpenCL 1.2 (Build 475))
Current OpenCL device: 
    Type = iGPU
    Name = Intel(R) HD Graphics
    Version = OpenCL 1.2 
    Driver version = r5.0.63503
    Address bits = 64
    Compute units = 20
    Max work group size = 256
    Local memory size = 64 kB 
    Max memory allocation size = 815 MB 204 kB 819 B
    Double support = No
    Host unified memory = Yes
    Device extensions:
        cl_intel_accelerator
        cl_intel_advanced_motion_estimation
        cl_intel_driver_diagnostics
        cl_intel_motion_estimation
        cl_intel_planar_yuv
        cl_intel_packed_yuv
        cl_intel_required_subgroup_size
        cl_intel_subgroups
        cl_intel_va_api_media_sharing
        cl_khr_3d_image_writes
        cl_khr_byte_addressable_store
        cl_khr_depth_images
        cl_khr_global_int32_base_atomics
        cl_khr_global_int32_extended_atomics
        cl_khr_icd
        cl_khr_local_int32_base_atomics
        cl_khr_local_int32_extended_atomics
        cl_khr_spir
    Has AMD Blas = No
    Has AMD Fft = No
    Preferred vector width char = 16
    Preferred vector width short = 8
    Preferred vector width int = 4
    Preferred vector width long = 1
    Preferred vector width float = 1
    Preferred vector width double = 0
```

**Comment by kdouc** [comment] 2018-01-15 02:14
same problem in tensorflow mobile-ssd net, the result box is biger than cpu

**Comment by vpisarev** [comment] 2018-02-07 12:22
@pengli, could you or someone from your folks please check this issue?

**Comment by pengli** [comment] 2018-02-19 01:13
@vpisarev，ok，i will take a look at this issue

**Comment by pengli** [comment] 2018-02-22 12:43
it looks this issue has been fixed on latest，can someone give a try ？

**Comment by dkurt** [comment] 2018-02-22 19:18
@pengli,
```
[  FAILED  ] 29 tests, listed below:
[  FAILED  ] OCL_Reproducibility_MobileNet_SSD.Accuracy
[  FAILED  ] OCL_Reproducibility_ResNet50.Accuracy
[  FAILED  ] OCL_Reproducibility_SqueezeNet_v1_1.Accuracy
[  FAILED  ] OCL_Reproducibility_GoogLeNet.Accuracy
[  FAILED  ] OCL_SeveralCalls_GoogLeNet.Accuracy
[  FAILED  ] OCL_Layer_Test_DeConvolution.Accuracy
[  FAILED  ] OCL_Layer_Test_InnerProduct.Accuracy
[  FAILED  ] OCL_Test_TensorFlow.deconvolution
[  FAILED  ] OCL_Torch_Importer.run_deconv
[  FAILED  ] OCL_Torch_Importer.net_softmax
[  FAILED  ] OCL_Torch_Importer.net_logsoftmax
[  FAILED  ] OCL_Torch_Importer.net_normalize
[  FAILED  ] OCL_Torch_Importer.net_non_spatial
[  FAILED  ] OCL_Torch_Importer.OpenFace_accuracy
[  FAILED  ] OCL_Torch_Importer.ENet_accuracy
[  FAILED  ] OCL_Torch_Importer.FastNeuralStyle_accuracy
[  FAILED  ] DNNTestNetwork.AlexNet/0, where GetParam() = (DNN_BACKEND_DEFAULT, DNN_TARGET_OPENCL)
[  FAILED  ] DNNTestNetwork.ResNet_50/0, where GetParam() = (DNN_BACKEND_DEFAULT, DNN_TARGET_OPENCL)
[  FAILED  ] DNNTestNetwork.SqueezeNet_v1_1/0, where GetParam() = (DNN_BACKEND_DEFAULT, DNN_TARGET_OPENCL)
[  FAILED  ] DNNTestNetwork.GoogLeNet/0, where GetParam() = (DNN_BACKEND_DEFAULT, DNN_TARGET_OPENCL)
[  FAILED  ] DNNTestNetwork.Inception_5h/0, where GetParam() = (DNN_BACKEND_DEFAULT, DNN_TARGET_OPENCL)
[  FAILED  ] DNNTestNetwork.ENet/0, where GetParam() = (DNN_BACKEND_DEFAULT, DNN_TARGET_OPENCL)
[  FAILED  ] DNNTestNetwork.MobileNet_SSD_Caffe/0, where GetParam() = (DNN_BACKEND_DEFAULT, DNN_TARGET_OPENCL)
[  FAILED  ] DNNTestNetwork.OpenFace/0, where GetParam() = (DNN_BACKEND_DEFAULT, DNN_TARGET_OPENCL)
[  FAILED  ] DNNTestNetwork.opencv_face_detector/0, where GetParam() = (DNN_BACKEND_DEFAULT, DNN_TARGET_OPENCL)
[  FAILED  ] OCL_Test_Caffe/Reproducibility_OCL_AlexNet.Accuracy/0, where GetParam() = false
[  FAILED  ] OCL_Test_Caffe/Reproducibility_OCL_AlexNet.Accuracy/1, where GetParam() = true
[  FAILED  ] Test_Caffe/opencv_face_detector.Accuracy/1, where GetParam() = ("dnn/opencv_face_detector.caffemodel", DNN_TARGET_OPENCL)
[  FAILED  ] Test_Caffe/opencv_face_detector.Accuracy/3, where GetParam() = ("dnn/opencv_face_detector_fp16.caffemodel", DNN_TARGET_OPENCL)
```

```
OpenCV version: 3.4.0-dev
OpenCV VCS version: 3.2.0-2827-g5caf624
Build type: release
Parallel framework: pthreads
CPU features: mmx sse sse2 sse3
Intel(R) IPP optimization: enabled
Intel(R) IPP version: ippIP AVX2 (l9) 2017.0.3 (-) Jul 29 2017
[ INFO:0] Initialize OpenCL runtime...
OpenCL Platforms: 
    Intel(R) OpenCL
        iGPU: Intel(R) HD Graphics (OpenCL 1.2 )
        CPU: Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (OpenCL 1.2 (Build 475))
    Experimental OpenCL 2.1 CPU Only Platform
        CPU: Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (OpenCL 2.1 (Build 10))
Current OpenCL device: 
    Type = iGPU
    Name = Intel(R) HD Graphics
    Version = OpenCL 1.2 
    Driver version = r5.0.63503
    Address bits = 64
    Compute units = 20
    Max work group size = 256
    Local memory size = 64 KB
    Max memory allocation size = 815 MB 204 KB 819 B
    Double support = No
    Host unified memory = Yes
    Device extensions:
        cl_intel_accelerator
        cl_intel_advanced_motion_estimation
        cl_intel_driver_diagnostics
        cl_intel_motion_estimation
        cl_intel_planar_yuv
        cl_intel_packed_yuv
        cl_intel_required_subgroup_size
        cl_intel_subgroups
        cl_intel_va_api_media_sharing
        cl_khr_3d_image_writes
        cl_khr_byte_addressable_store
        cl_khr_depth_images
        cl_khr_global_int32_base_atomics
        cl_khr_global_int32_extended_atomics
        cl_khr_icd
        cl_khr_local_int32_base_atomics
        cl_khr_local_int32_extended_atomics
        cl_khr_spir
    Has AMD Blas = No
    Has AMD Fft = No
    Preferred vector width char = 16
    Preferred vector width short = 8
    Preferred vector width int = 4
    Preferred vector width long = 1
    Preferred vector width float = 1
    Preferred vector width double = 0
```

**Comment by pengli** [comment] 2018-02-24 10:31
@dkurt,  hi, please try below patch and see if it works for you. 

diff --git a/modules/dnn/src/layers/softmax_layer.cpp b/modules/dnn/src/layers/softmax_layer.cpp
index 49807cd..c33a241 100644
--- a/modules/dnn/src/layers/softmax_layer.cpp
+++ b/modules/dnn/src/layers/softmax_layer.cpp
@@ -118,7 +118,7 @@ public:
         UMat& src = inputs[0];
         UMat& dstMat = outputs[0];

-        if (softmaxOp->Forward(src, dstMat))
+        if (0 && softmaxOp->Forward(src, dstMat))
             return true;

         UMat& bufMat = internals[0];

**Comment by dkurt** [comment] 2018-02-24 11:18
@pengli, some of tests have been fixed this way:
```
[  FAILED  ] 18 tests, listed below:
[  FAILED  ] OCL_Reproducibility_ResNet50.Accuracy
[  FAILED  ] OCL_Layer_Test_DeConvolution.Accuracy
[  FAILED  ] OCL_Layer_Test_InnerProduct.Accuracy
[  FAILED  ] OCL_Test_TensorFlow.deconvolution
[  FAILED  ] OCL_Torch_Importer.run_deconv
[  FAILED  ] OCL_Torch_Importer.net_normalize
[  FAILED  ] OCL_Torch_Importer.net_non_spatial
[  FAILED  ] OCL_Torch_Importer.OpenFace_accuracy
[  FAILED  ] OCL_Torch_Importer.ENet_accuracy
[  FAILED  ] OCL_Torch_Importer.FastNeuralStyle_accuracy
[  FAILED  ] DNNTestNetwork.AlexNet/0, where GetParam() = (DNN_BACKEND_DEFAULT, DNN_TARGET_OPENCL)
[  FAILED  ] DNNTestNetwork.ResNet_50/0, where GetParam() = (DNN_BACKEND_DEFAULT, DNN_TARGET_OPENCL)
[  FAILED  ] DNNTestNetwork.GoogLeNet/0, where GetParam() = (DNN_BACKEND_DEFAULT, DNN_TARGET_OPENCL)
[  FAILED  ] DNNTestNetwork.Inception_5h/0, where GetParam() = (DNN_BACKEND_DEFAULT, DNN_TARGET_OPENCL)
[  FAILED  ] DNNTestNetwork.ENet/0, where GetParam() = (DNN_BACKEND_DEFAULT, DNN_TARGET_OPENCL)
[  FAILED  ] DNNTestNetwork.OpenFace/0, where GetParam() = (DNN_BACKEND_DEFAULT, DNN_TARGET_OPENCL)
[  FAILED  ] OCL_Test_Caffe/Reproducibility_OCL_AlexNet.Accuracy/0, where GetParam() = false
[  FAILED  ] OCL_Test_Caffe/Reproducibility_OCL_AlexNet.Accuracy/1, where GetParam() = true
```

**Comment by pengli** [comment] 2018-02-24 11:23
OK, Thanks for the quick reply. Intel(R) Core(TM) i5-4460 is haswell platform,  which is old.  I need to find one hardware and debug.

**Closed** 2020-12-13 06:55 UTC
Labels: bug, category: 3rdparty, category: dnn, category: ocl, priority: low, wontfix
