### ISSUE TITLE
OpenCV 3.2 + Python 3.6.1: imshow() not worked even with waitKey(0)

### ISSUE THREAD

**Issue by nyngwang** [opencv/opencv#8885] opened 2017-06-10 07:37 UTC
##### System information (version)
- OpenCV => 3.2
- Operating System / Platform => MacOS Sierra 10.12.5
- Compiler => Terminal

I followed the documentation with: 

```
import cv2
import numpy as np

img = cv2.imread('1.jpg')
print(img)
cv2.imshow('Image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()
```

But I got empty content window:

[Image](https://i.stack.imgur.com/DxsAq.png)

Is this related to OpenCV?

For readability I posted this question to stackoverflow: https://stackoverflow.com/q/44469973/7813604

**Comment by alalek** [comment] 2017-06-10 11:04
Validate output of these lines:
```
print(cv2.__file__)
print(cv2.getBuildInformation()) # OpenCV version / build timestamp / used python paths
```

Could you try to run this sample: [digits](https://github.com/opencv/opencv/blob/3.2.0/samples/python/digits.py) (shows "table" with numbers).
Could you try C++ [sample](https://github.com/opencv/opencv/blob/3.2.0/samples/cpp/drawing.cpp) (add CMake option `-DBUILD_EXAMPLES=ON`).


BTW, Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by felipecastrillon** [comment] 2017-06-11 15:43
I am having the same issue with the same macOS version and opencv version, but with Python 2.7.12

**Comment by eeking** [comment] 2017-06-11 17:24
the same issue with the same macOS ,and install opencv follow pyimage

**Comment by cstarknyc** [comment] 2017-06-12 01:43
Same problem, attacked in multiple ways, all failed.

- macOS 10.12.5
- trial#1, #2: built from source
   - using both py35 and py36
- trial#3 installed using:   conda install -c menpo opencv3 in virtual env for py35
- tested against several images 
  e.g., img = cv2.imread('tmp.png',0); cv2.imshow('test',img);cv2.waitKey(0)

In every case, once cv2.imshow() in invoked, I get the window title bar but an empty window

**Comment by cstarknyc** [comment] 2017-06-12 01:47
>>> print(cv2.__file__)
>>> /Users/<me>/OpenCV/lib/python3.5/site-packages/cv2.cpython-35m-darwin.so


>>> print(cv2.getBuildInformation())
>>> 
General configuration for OpenCV 3.2.0-dev =====================================
  Version control:               3.2.0-761-g772a8188c

  Extra modules:
    Location (extra):            /Users/<me>/Work/opencv_contrib/modules
    Version control (extra):     3.2.0-289-g09b73b2d-dirty

  Platform:
    Timestamp:                   2017-06-12T00:01:30Z
    Host:                        Darwin 16.6.0 x86_64
    CMake:                       3.8.1
    CMake generator:             Unix Makefiles
    CMake build tool:            /usr/bin/make
    Configuration:               RELEASE

  CPU/HW features:
    Baseline:                    SSE SSE2 SSE3 SSSE3
      requested:                 SSSE3
    Dispatched code generation:  SSE4_1 FP16 AVX AVX2
      requested:                 SSE4_1 AVX FP16 AVX2
      SSE4_1 (0 files):          + SSE4_1
      FP16 (1 files):            + SSE4_1 POPCNT SSE4_2 FP16 AVX
      AVX (1 files):             + SSE4_1 POPCNT SSE4_2 AVX
      AVX2 (1 files):            + SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2

  C/C++:
    Built as dynamic libs?:      YES
    C++ Compiler:                /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  (ver 8.1.0.8020042)
    C++ flags (Release):         -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -fno-omit-frame-pointer -ffunction-sections  -msse -msse2 -msse3 -mssse3 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG  -DNDEBUG
    C++ flags (Debug):           -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -fno-omit-frame-pointer -ffunction-sections  -msse -msse2 -msse3 -mssse3 -fvisibility=hidden -fvisibility-inlines-hidden -g  -O0 -DDEBUG -D_DEBUG
    C Compiler:                  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
    C flags (Release):           -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -fno-omit-frame-pointer -ffunction-sections  -msse -msse2 -msse3 -mssse3 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG  -DNDEBUG
    C flags (Debug):             -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -fno-omit-frame-pointer -ffunction-sections  -msse -msse2 -msse3 -mssse3 -fvisibility=hidden -fvisibility-inlines-hidden -g  -O0 -DDEBUG -D_DEBUG
    Linker flags (Release):
    Linker flags (Debug):
    ccache:                      NO
    Precompiled headers:         NO
    Extra dependencies:          -framework OpenCL /opt/local/lib/libwebp.dylib avcodec avformat avutil swscale avresample gphoto2 gphoto2_port m -framework VideoDecodeAcceleration bz2 -framework Accelerate -framework AVFoundation -framework CoreGraphics -framework CoreMedia -framework CoreVideo -framework QuartzCore vtkRenderingOpenGL2 vtkCommonCore vtksys vtkCommonDataModel vtkCommonMath vtkCommonMisc vtkCommonSystem vtkCommonTransforms vtkCommonExecutionModel vtkIOImage vtkDICOMParser vtkmetaio vtkzlib vtkjpeg vtkpng vtktiff vtkImagingCore vtkRenderingCore vtkCommonColor vtkCommonComputationalGeometry vtkFiltersCore vtkFiltersGeneral vtkFiltersGeometry vtkFiltersSources vtkglew vtkInteractionStyle vtkFiltersExtraction vtkFiltersStatistics vtkImagingFourier vtkalglib vtkRenderingLOD vtkFiltersModeling vtkIOPLY vtkIOCore vtkFiltersTexture vtkRenderingFreeType vtkfreetype vtkIOExport vtkRenderingGL2PSOpenGL2 vtkgl2ps vtkIOGeometry vtkIOLegacy -framework Cocoa /System/Library/Frameworks/Accelerate.framework /opt/local/lib/libhdf5.dylib /usr/lib/libz.dylib /usr/lib/libdl.dylib /usr/lib/libm.dylib /opt/local/lib/libglog.dylib gflags_shared
    3rdparty dependencies:

  OpenCV modules:
    To be built:                 core flann hdf imgproc ml objdetect phase_unwrapping photo plot reg surface_matching video viz xphoto bgsegm dnn face fuzzy imgcodecs shape videoio xobjdetect highgui superres ts bioinspired dpm features2d line_descriptor saliency text calib3d ccalib datasets rgbd stereo structured_light tracking videostab xfeatures2d ximgproc aruco optflow sfm stitching python3
    Disabled:                    python2 world contrib_world
    Disabled by dependency:      -
    Unavailable:                 cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev java cnn_3dobj cvv dnn_modern matlab

  GUI: 
    QT:                          NO
    Cocoa:                       YES
    OpenGL support:              NO
    VTK support:                 YES (ver 7.1.1)

  Media I/O: 
    ZLib:                        build (ver 1.2.8)
    JPEG:                        build (ver 90)
    WEBP:                        /opt/local/lib/libwebp.dylib (ver encoder: 0x020e)
    PNG:                         build (ver 1.6.24)
    TIFF:                        build (ver 42 - 4.0.2)
    JPEG 2000:                   build (ver 1.900.1)
    OpenEXR:                     build (ver 1.7.1)
    GDAL:                        NO
    GDCM:                        NO

  Video I/O:
    DC1394 1.x:                  NO
    DC1394 2.x:                  NO
    FFMPEG:                      YES
      avcodec:                   YES (ver 57.64.101)
      avformat:                  YES (ver 57.56.101)
      avutil:                    YES (ver 55.34.101)
      swscale:                   YES (ver 4.2.100)
      avresample:                YES (ver 3.1.0)
    GStreamer:                   NO
    OpenNI:                      NO
    OpenNI PrimeSensor Modules:  NO
    OpenNI2:                     NO
    PvAPI:                       NO
    GigEVisionSDK:               NO
    Aravis SDK:                  NO
    AVFoundation:                YES
    V4L/V4L2:                    NO/NO
    XIMEA:                       NO
    gPhoto2:                     YES

  Parallel framework:            GCD

  Other third-party libraries:
    Use Intel IPP:               2017.0.2 [2017.0.2]
               at:               /Users/<me>/Work/opencv/build/3rdparty/ippicv/ippicv_mac
    Use Intel IPP IW:            prebuilt binaries (2017.0.2)
    Use Intel IPP Async:         NO
    Use VA:                      NO
    Use Intel VA-API/OpenCL:     NO
    Use Lapack:                  YES (/System/Library/Frameworks/Accelerate.framework /System/Library/Frameworks/Accelerate.framework)
    Use Eigen:                   YES (ver 3.3.3)
    Use Cuda:                    NO
    Use OpenCL:                  YES
    Use OpenVX:                  NO
    Use custom HAL:              NO

  OpenCL:                        <Link with OpenCL library>
    Link libraries:              -framework OpenCL
    Use AMDFFT:                  NO
    Use AMDBLAS:                 NO

  Python 2:
    Interpreter:                 /opt/local/bin/python2.7 (ver 2.7.13)

  Python 3:
    Interpreter:                 /opt/local/bin/python3 (ver 3.5.3)
    Libraries:                   /opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib (ver 3.5.3)
    numpy:                       /opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/numpy/core/include (ver 1.12.1)
    packages path:               lib/python3.5/site-packages

  Python (for build):            /opt/local/bin/python2.7

  Java:
    ant:                         NO
    JNI:                         /System/Library/Frameworks/JavaVM.framework/Headers /System/Library/Frameworks/JavaVM.framework/Headers /System/Library/Frameworks/JavaVM.framework/Headers
    Java wrappers:               NO
    Java tests:                  NO

  Matlab:                        Matlab not found or implicitly disabled

  Documentation:
    Doxygen:                     NO

  Tests and samples:
    Tests:                       YES
    Performance tests:           YES
    C/C++ Examples:              YES

  Install path:                  /Users/<me>/OpenCV

  cvconfig.h is in:              /Users/<me>/Work/opencv/build
-----------------------------------------------------------------


>>> print(cv2.__file__)
>>> /Users/<me>/OpenCV/lib/python3.5/site-packages/cv2.cpython-35m-darwin.so

>>> print(cv2.getBuildInformation())
>>> 
General configuration for OpenCV 3.2.0-dev =====================================
  Version control:               3.2.0-761-g772a8188c

  Extra modules:
    Location (extra):            /Users/<me>/Work/opencv_contrib/modules
    Version control (extra):     3.2.0-289-g09b73b2d-dirty

  Platform:
    Timestamp:                   2017-06-12T00:01:30Z
    Host:                        Darwin 16.6.0 x86_64
    CMake:                       3.8.1
    CMake generator:             Unix Makefiles
    CMake build tool:            /usr/bin/make
    Configuration:               RELEASE

  CPU/HW features:
    Baseline:                    SSE SSE2 SSE3 SSSE3
      requested:                 SSSE3
    Dispatched code generation:  SSE4_1 FP16 AVX AVX2
      requested:                 SSE4_1 AVX FP16 AVX2
      SSE4_1 (0 files):          + SSE4_1
      FP16 (1 files):            + SSE4_1 POPCNT SSE4_2 FP16 AVX
      AVX (1 files):             + SSE4_1 POPCNT SSE4_2 AVX
      AVX2 (1 files):            + SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2

  C/C++:
    Built as dynamic libs?:      YES
    C++ Compiler:                /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  (ver 8.1.0.8020042)
    C++ flags (Release):         -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -fno-omit-frame-pointer -ffunction-sections  -msse -msse2 -msse3 -mssse3 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG  -DNDEBUG
    C++ flags (Debug):           -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -fno-omit-frame-pointer -ffunction-sections  -msse -msse2 -msse3 -mssse3 -fvisibility=hidden -fvisibility-inlines-hidden -g  -O0 -DDEBUG -D_DEBUG
    C Compiler:                  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
    C flags (Release):           -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -fno-omit-frame-pointer -ffunction-sections  -msse -msse2 -msse3 -mssse3 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG  -DNDEBUG
    C flags (Debug):             -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -fno-omit-frame-pointer -ffunction-sections  -msse -msse2 -msse3 -mssse3 -fvisibility=hidden -fvisibility-inlines-hidden -g  -O0 -DDEBUG -D_DEBUG
    Linker flags (Release):
    Linker flags (Debug):
    ccache:                      NO
    Precompiled headers:         NO
    Extra dependencies:          -framework OpenCL /opt/local/lib/libwebp.dylib avcodec avformat avutil swscale avresample gphoto2 gphoto2_port m -framework VideoDecodeAcceleration bz2 -framework Accelerate -framework AVFoundation -framework CoreGraphics -framework CoreMedia -framework CoreVideo -framework QuartzCore vtkRenderingOpenGL2 vtkCommonCore vtksys vtkCommonDataModel vtkCommonMath vtkCommonMisc vtkCommonSystem vtkCommonTransforms vtkCommonExecutionModel vtkIOImage vtkDICOMParser vtkmetaio vtkzlib vtkjpeg vtkpng vtktiff vtkImagingCore vtkRenderingCore vtkCommonColor vtkCommonComputationalGeometry vtkFiltersCore vtkFiltersGeneral vtkFiltersGeometry vtkFiltersSources vtkglew vtkInteractionStyle vtkFiltersExtraction vtkFiltersStatistics vtkImagingFourier vtkalglib vtkRenderingLOD vtkFiltersModeling vtkIOPLY vtkIOCore vtkFiltersTexture vtkRenderingFreeType vtkfreetype vtkIOExport vtkRenderingGL2PSOpenGL2 vtkgl2ps vtkIOGeometry vtkIOLegacy -framework Cocoa /System/Library/Frameworks/Accelerate.framework /opt/local/lib/libhdf5.dylib /usr/lib/libz.dylib /usr/lib/libdl.dylib /usr/lib/libm.dylib /opt/local/lib/libglog.dylib gflags_shared
    3rdparty dependencies:

  OpenCV modules:
    To be built:                 core flann hdf imgproc ml objdetect phase_unwrapping photo plot reg surface_matching video viz xphoto bgsegm dnn face fuzzy imgcodecs shape videoio xobjdetect highgui superres ts bioinspired dpm features2d line_descriptor saliency text calib3d ccalib datasets rgbd stereo structured_light tracking videostab xfeatures2d ximgproc aruco optflow sfm stitching python3
    Disabled:                    python2 world contrib_world
    Disabled by dependency:      -
    Unavailable:                 cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev java cnn_3dobj cvv dnn_modern matlab

  GUI: 
    QT:                          NO
    Cocoa:                       YES
    OpenGL support:              NO
    VTK support:                 YES (ver 7.1.1)

  Media I/O: 
    ZLib:                        build (ver 1.2.8)
    JPEG:                        build (ver 90)
    WEBP:                        /opt/local/lib/libwebp.dylib (ver encoder: 0x020e)
    PNG:                         build (ver 1.6.24)
    TIFF:                        build (ver 42 - 4.0.2)
    JPEG 2000:                   build (ver 1.900.1)
    OpenEXR:                     build (ver 1.7.1)
    GDAL:                        NO
    GDCM:                        NO

  Video I/O:
    DC1394 1.x:                  NO
    DC1394 2.x:                  NO
    FFMPEG:                      YES
      avcodec:                   YES (ver 57.64.101)
      avformat:                  YES (ver 57.56.101)
      avutil:                    YES (ver 55.34.101)
      swscale:                   YES (ver 4.2.100)
      avresample:                YES (ver 3.1.0)
    GStreamer:                   NO
    OpenNI:                      NO
    OpenNI PrimeSensor Modules:  NO
    OpenNI2:                     NO
    PvAPI:                       NO
    GigEVisionSDK:               NO
    Aravis SDK:                  NO
    AVFoundation:                YES
    V4L/V4L2:                    NO/NO
    XIMEA:                       NO
    gPhoto2:                     YES

  Parallel framework:            GCD

  Other third-party libraries:
    Use Intel IPP:               2017.0.2 [2017.0.2]
               at:               /Users/<me>/Work/opencv/build/3rdparty/ippicv/ippicv_mac
    Use Intel IPP IW:            prebuilt binaries (2017.0.2)
    Use Intel IPP Async:         NO
    Use VA:                      NO
    Use Intel VA-API/OpenCL:     NO
    Use Lapack:                  YES (/System/Library/Frameworks/Accelerate.framework /System/Library/Frameworks/Accelerate.framework)
    Use Eigen:                   YES (ver 3.3.3)
    Use Cuda:                    NO
    Use OpenCL:                  YES
    Use OpenVX:                  NO
    Use custom HAL:              NO

  OpenCL:                        <Link with OpenCL library>
    Link libraries:              -framework OpenCL
    Use AMDFFT:                  NO
    Use AMDBLAS:                 NO

  Python 2:
    Interpreter:                 /opt/local/bin/python2.7 (ver 2.7.13)

  Python 3:
    Interpreter:                 /opt/local/bin/python3 (ver 3.5.3)
    Libraries:                   /opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib (ver 3.5.3)
    numpy:                       /opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/numpy/core/include (ver 1.12.1)
    packages path:               lib/python3.5/site-packages

  Python (for build):            /opt/local/bin/python2.7

  Java:
    ant:                         NO
    JNI:                         /System/Library/Frameworks/JavaVM.framework/Headers /System/Library/Frameworks/JavaVM.framework/Headers /System/Library/Frameworks/JavaVM.framework/Headers
    Java wrappers:               NO
    Java tests:                  NO

  Matlab:                        Matlab not found or implicitly disabled

  Documentation:
    Doxygen:                     NO

  Tests and samples:
    Tests:                       YES
    Performance tests:           YES
    C/C++ Examples:              YES

  Install path:                  /Users/<me>/OpenCV

  cvconfig.h is in:              /Users/<me>/Work/opencv/build
-----------------------------------------------------------------

**Comment by Abiwax** [comment] 2017-06-12 14:53
Having same issue also, has anyone been able to solve it

**Comment by alalek** [comment] 2017-06-12 15:21
What is about C++ samples? Did C++ examples show normal windows?

**Comment by cstarknyc** [comment] 2017-06-14 01:11
Testing digits.py begets the following error:

``

python3.5 digits.py

SVM and KNearest digit recognition.
Sample loads a dataset of handwritten digits from '../data/digits.png'.
Then it trains a SVM and KNearest classifiers on it and evaluates
their accuracy.
Following preprocessing is applied to the dataset:
 - Moment-based image deskew (see deskew())
 - Digit images are split into 4 10x10 cells and 16-bin
   histogram of oriented gradients is computed for each
   cell
 - Transform histograms to space with Hellinger metric (see [1] (RootSIFT))
[1] R. Arandjelovic, A. Zisserman
    "Three things everyone should know to improve object retrieval"
    http://www.robots.ox.ac.uk/~vgg/publications/2012/Arandjelovic12/arandjelovic12.pdf
Usage:
   digits.py

loading "digits.png" ...
preprocessing...
training KNearest...
error: 3.40 %
Traceback (most recent call last):
  File "digits.py", line 170, in <module>
    vis = evaluate_model(model, digits_test, samples_test, labels_test)
  File "digits.py", line 107, in evaluate_model
    confusion[i, j] += 1
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
``

**Comment by cstarknyc** [comment] 2017-06-14 01:13
Python 3.5.3 (default, Apr 23 2017, 18:09:27) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> numpy.__version__
>>> '1.12.1'

**Comment by cstarknyc** [comment] 2017-06-14 01:39
Testing a sample cpp fails also. A window flashes black on the screen and disappears immediately.

>> testing% g++ -ggdb `pkg-config --cflags --libs opencv` -stdlib=libc++ drawing.cpp -o drawing
>> testing% ./drawing

**Comment by cstarknyc** [comment] 2017-06-14 07:07
Since we are seeing runtime errors, I thought this "ldd" check might be informative:

otool -L /Users/me/OpenCV/lib/python3.5/site-packages/cv2.cpython-35m-darwin.so 

/Users/me/OpenCV/lib/python3.5/site-packages/cv2.cpython-35m-darwin.so:
	@rpath/libopencv_hdf.3.2.dylib (compatibility version 3.2.0, current version 3.2.0)
	@rpath/libopencv_reg.3.2.dylib (compatibility version 3.2.0, current version 3.2.0)
	@rpath/libopencv_surface_matching.3.2.dylib (compatibility version 3.2.0, current version 3.2.0)
	@rpath/libopencv_xphoto.3.2.dylib (compatibility version 3.2.0, current version 3.2.0)
	@rpath/libopencv_bgsegm.3.2.dylib (compatibility version 3.2.0, current version 3.2.0)
	@rpath/libopencv_face.3.2.dylib (compatibility version 3.2.0, current version 3.2.0)
	@rpath/libopencv_fuzzy.3.2.dylib (compatibility version 3.2.0, current version 3.2.0)
	@rpath/libopencv_xobjdetect.3.2.dylib (compatibility version 3.2.0, current version 3.2.0)
	@rpath/libopencv_superres.3.2.dylib (compatibility version 3.2.0, current version 3.2.0)
	@rpath/libopencv_bioinspired.3.2.dylib (compatibility version 3.2.0, current version 3.2.0)
	@rpath/libopencv_dpm.3.2.dylib (compatibility version 3.2.0, current version 3.2.0)
	@rpath/libopencv_line_descriptor.3.2.dylib (compatibility version 3.2.0, current version 3.2.0)
	@rpath/libopencv_saliency.3.2.dylib (compatibility version 3.2.0, current version 3.2.0)
	@rpath/libopencv_ccalib.3.2.dylib (compatibility version 3.2.0, current version 3.2.0)
	@rpath/libopencv_rgbd.3.2.dylib (compatibility version 3.2.0, current version 3.2.0)
	@rpath/libopencv_structured_light.3.2.dylib (compatibility version 3.2.0, current version 3.2.0)
	@rpath/libopencv_tracking.3.2.dylib (compatibility version 3.2.0, current version 3.2.0)
	@rpath/libopencv_videostab.3.2.dylib (compatibility version 3.2.0, current version 3.2.0)
	@rpath/libopencv_aruco.3.2.dylib (compatibility version 3.2.0, current version 3.2.0)
	@rpath/libopencv_optflow.3.2.dylib (compatibility version 3.2.0, current version 3.2.0)
	@rpath/libopencv_sfm.3.2.dylib (compatibility version 3.2.0, current version 3.2.0)
	@rpath/libopencv_stitching.3.2.dylib (compatibility version 3.2.0, current version 3.2.0)
	@rpath/libopencv_objdetect.3.2.dylib (compatibility version 3.2.0, current version 3.2.0)
	@rpath/libopencv_phase_unwrapping.3.2.dylib (compatibility version 3.2.0, current version 3.2.0)
	@rpath/libopencv_viz.3.2.dylib (compatibility version 3.2.0, current version 3.2.0)
	@rpath/libopencv_plot.3.2.dylib (compatibility version 3.2.0, current version 3.2.0)
	@rpath/libopencv_dnn.3.2.dylib (compatibility version 3.2.0, current version 3.2.0)
	@rpath/libopencv_datasets.3.2.dylib (compatibility version 3.2.0, current version 3.2.0)
	@rpath/libopencv_text.3.2.dylib (compatibility version 3.2.0, current version 3.2.0)
	@rpath/libopencv_ml.3.2.dylib (compatibility version 3.2.0, current version 3.2.0)
	@rpath/libopencv_photo.3.2.dylib (compatibility version 3.2.0, current version 3.2.0)
	@rpath/libopencv_ximgproc.3.2.dylib (compatibility version 3.2.0, current version 3.2.0)
	@rpath/libopencv_xfeatures2d.3.2.dylib (compatibility version 3.2.0, current version 3.2.0)
	@rpath/libopencv_shape.3.2.dylib (compatibility version 3.2.0, current version 3.2.0)
	@rpath/libopencv_video.3.2.dylib (compatibility version 3.2.0, current version 3.2.0)
	@rpath/libopencv_calib3d.3.2.dylib (compatibility version 3.2.0, current version 3.2.0)
	@rpath/libopencv_features2d.3.2.dylib (compatibility version 3.2.0, current version 3.2.0)
	@rpath/libopencv_flann.3.2.dylib (compatibility version 3.2.0, current version 3.2.0)
	@rpath/libopencv_highgui.3.2.dylib (compatibility version 3.2.0, current version 3.2.0)
	@rpath/libopencv_videoio.3.2.dylib (compatibility version 3.2.0, current version 3.2.0)
	@rpath/libopencv_imgcodecs.3.2.dylib (compatibility version 3.2.0, current version 3.2.0)
	@rpath/libopencv_imgproc.3.2.dylib (compatibility version 3.2.0, current version 3.2.0)
	@rpath/libopencv_core.3.2.dylib (compatibility version 3.2.0, current version 3.2.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.5.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.60.2)

**Comment by cstarknyc** [comment] 2017-06-14 10:54
Just to make clear: despite the odd grammar in the title of this issue, and some problems with the info given about it, it is a perfectly legitimate OpenCV issue to raise.  Several of us are finding runtime window display errors with various versions of OpenCV running on recent incarnations of MacOS. Via Python and C++ examples. Compilations give no indication whatsoever of a problem.

**Comment by mattmyne** [comment] 2017-06-14 12:37
I can confirm all my previously working C++ code now only shows window title bars without contents. Running macOS 10.12.5.

The issue appears to be with the use of WINDOW_AUTOSIZE in namedWindow. If I use WINDOW_NORMAL and manually size using resizeWindow then I can see the content again. Note using resizeWindow if WINDOW_AUTOSIZE still specified does not work (though I don't know if this is expected behaviour).

Perhaps WINDOW_AUTOSIZE is being treated as WINDOW_NORMAL, or there is an issue with the autosize code (or that code is not being called).

Needless to say, I feel this is quite a significant bug!

**Comment by mattmyne** [comment] 2017-06-14 16:54
The above PR fixes the issue for me. I have not tested it in python but hope it will have resolved this too.

**Comment by cstarknyc** [comment] 2017-06-15 01:15
Reverting to 3.2.0-265-g5d03262b0 aka <git checkout 5d03262b00> aka #8307, Python problem same; C++ sample problem same. 

Tried reverting further to #7193 but began to have build problems so stopped.

**Comment by mattmyne** [comment] 2017-06-15 11:21
commit 5d03262 is not before #8307. That only reverts a minor addition after #8307. You'll need to revert window_cocoa.mm to commit acb626 to undo this. I used git checkout acb626 -- modules/highgui/src/window_cocoa.mm

**Comment by cstarknyc** [comment] 2017-06-15 23:52
Aha! Thanks for the tip. This fixes the window autosize bug on MacOS Sierra, BUT it does mean windows _don't_ autosize at all, and instead render at 1:1 pixel scale. Makes for some gigantic windows when imshow'ing large images.
Windows don't seem to die gracefully either, but that may simply be SOP for cv2 in Python.

Note to @alalek: I reran the tests you suggested: 
 - digits.py has a bug on line 107 in py3, since the zip returns an `int x` and a `float y`, leading `confusion[i,j]` to fail. When hacked to `confusion[i,int(j)]` the demo works and pretty window is generated.
 - drawing.cpp again compiles no prob, but runtime generates a flash of a window (black?) and abruptly exits. I haven't debugged.

**Comment by berak** [comment] 2017-06-16 13:49
@cstarknyc , the problem in digits.py was [fixed a month ago](https://github.com/opencv/opencv/commit/7b05d52f7b4f8b8eb80e5789c46c49203314727e)

**Comment by mattmyne** [comment] 2017-06-16 15:43
@cstarknyc I'm not sure how your autosize used to work before, but I believe it has always resized the window to match the size of the image/matrix passed to it. Yes, it has been a common issue that large images lead to large windows. You can always use the resize function on the image/matrix before passing it to the window. I do not believe this is a bug as a result of this issue.

**Comment by RobertGolosynsky** [comment] 2017-06-18 01:04
confirming the bug with empty window when doing cv2.imshow, can't contribute, too noob, totaly recreated what @cstarknyc claimed : "I get the window title bar but an empty window"

**Comment by cstarknyc** [comment] 2017-06-18 01:31
@RobertGolosynsky:  If you follow @mattmyne 's advice of doing ` git checkout acb626 -- modules/highgui/src/window_cocoa.mm`  and rebuild the problem will be fixed for you.

@berak:  I was "just following orders" with executing the `digits.py` test. Am a total noob at OpenCV so haven't been following updates. My fix matches the one you mention, so all good. Except that the fix you indicate apparently isn't in master yet? Cos it's not in the main git clone. Needs patching in.

**Comment by berak** [comment] 2017-06-18 06:26
@cstarknyc all good with you, you did anything perfectly as requested.
the updated sample **is** in the [master branch](https://github.com/opencv/opencv/blame/master/samples/python/digits.py#L112), (not in the 3.2 release).

again, thanks a lot for sharing your insights here, - everythings alright, dont worry ;)

**Comment by RobertGolosynsky** [comment] 2017-06-18 14:38
@cstarknyc  doing git checkout acb626 -- modules/highgui/src/window_cocoa.mm and rebuilding fixed the problem for me, thank you very much!

**Comment by revelfire** [comment] 2017-06-21 05:00
Resolved for me.

**Closed** 2017-06-28 10:58 UTC
Labels: bug, category: highgui-gui, category: ios/osx
