### ISSUE TITLE
Enabling Cmake option OPENCV_ENABLE_NONFREE generates a make error in opencv_cudaarithm

### ISSUE THREAD

**Issue by MGarvinNYC** [opencv/opencv#16382] opened 2020-01-19 03:13 UTC
Something within OpenCV's NONFREE library is triggering a fatal make error.  The error message does not provide many clues:

[ 51%] Linking CXX shared library ../../lib/libopencv_cudaarithm.so
[ 51%] Built target opencv_cudaarithm
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
m@DarkMatter:/DM_Util/_INSTALL_LINUX/OpenCV_4/OpenCV_4.2.0_2020jan16/opencv/build$ 

Line 162 in the Makefile is just the spec for make target, so no clues there either:
> The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start 
       ...
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start 

---------------------------------------------------------------------------------------------------
Additional notes:  Though I have not seen this consistently between build attempts,
there is sometimes a non-fatal error re openGL.  But this related indirectly to rgbd in the contrib lib. 

[ 50%] Built target example_shape_shape_example
[ 50%] Built target opencv_test_shape
../../lib/libopencv_rgbd.so.4.2.0: undefined reference to `glRenderbufferStorageEXT'
../../lib/libopencv_rgbd.so.4.2.0: undefined reference to `glGenFramebuffersEXT'
../../lib/libopencv_rgbd.so.4.2.0: undefined reference to `glBindRenderbufferEXT'
../../lib/libopencv_rgbd.so.4.2.0: undefined reference to `glGenRenderbuffersEXT'
../../lib/libopencv_rgbd.so.4.2.0: undefined reference to `glFramebufferRenderbufferEXT'
../../lib/libopencv_rgbd.so.4.2.0: undefined reference to `glBindFramebufferEXT'
collect2: error: ld returned 1 exit status
modules/rgbd/CMakeFiles/opencv_test_rgbd.dir/build.make:192: recipe for target 'bin/opencv_test_rgbd' failed
make[2]: *** [bin/opencv_test_rgbd] Error 1
CMakeFiles/Makefile2:12517: recipe for target 'modules/rgbd/CMakeFiles/opencv_test_rgbd.dir/all' failed
make[1]: *** [modules/rgbd/CMakeFiles/opencv_test_rgbd.dir/all] Error 2
[ 50%] Built target opencv_datasets

[end]

**Comment by alalek** [comment] 2020-01-19 08:13
Avoid using of make's parallel builds (`-j` option) for investigation of build problems. It provides mess on output. Force `-j1` to collect accurate logs.

---

opencv_contrib issues should go here: https://github.com/opencv/opencv_contrib/issues

---

Duplicate of:
- #16282
- https://github.com/opencv/opencv_contrib/issues/2307

---

Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Closed by alalek** 2020-01-19 08:13 UTC
Labels: category: contrib, incomplete, question (invalid tracker)

**Comment by MGarvinNYC** [comment] 2020-01-19 08:46
I didn't realize that multicore output messages were not synchronized.  It makes sense that this did not relate directly to opencv_cudaarithm.

In any case, I had seen the other threads, but did not think this was directly related.

It seems that the problem occurs only when OPENCV_ENABLE_NONFREE along with setting OpenGL_GL_PREFERENCE to GLVND.  If the latter is set to LEGACY, there is no error.

**Comment by excellentcx** [comment] 2020-02-07 02:31
I have a similar question, can you please help me to see why? @MGarvinNYC 
[Building project "opencv_rgbd" FAILED ](https://github.com/opencv/opencv_contrib/issues/2423)
