### ISSUE TITLE
Pycharm Cannot find reference 'VideoWriter' in '__init__.py | __init__.py' 

### ISSUE THREAD

**Issue by EsbernTK** [opencv/opencv#18728] opened 2020-11-04 15:43 UTC
##### System information (version)
- OpenCV => 4.4
- Operating System / Platform => Windows 10 64 Bit
- Compiler => Visual Studio 2019
- IDE => Pycharm Community edition 2019
- Python version => 3.6
##### Detailed description

PROBLEM:
I compiled OpenCV 4.4 to get cuda and nvencoding support for it, and i compiled it for Python 3.6 too. 
I checked that the python package had been installed correctly in the console by importing cv2 and printing cv2.__version__.
My issue is that when i opened my IDE, Pycharm, it highlighted all cv2 classes with yellow and gave the message
Cannot find reference 'xxx' in '__init__.py | __init__.py'
The Intellisense also didnt work, and only showed bootstrap() as an autocomplete option.
Pycharms package manager also does not recognize cv2 as a package.
My code still worked though, and i could read frames from a video file, resize them and write them to a new file without problem.

FIX:
I have fixed this issue by commenting out line 85 in the init.py file ; "del sys.modules['cv2']" 
and by adding "from .cv2 import *" at the bottom of the init.py file, after the bootstrap() call.
Pycharm now no longer highlights any of the code with yellow, and the Intellisense autocomplete works.
This approach was borrowed from the opencv-python pip package.
However, this has broken the cv2.__version__ which now returns an error, and im not sure if anything else is quietly failing in the background due to this change. Though my code works fine and i can now see cv2.cuda packages too in python.

Comment:
The reason i mark this as an issue is that the current __init__.py file in modules/python/package/cv2 is not designed to be used with an IDE, which makes developing code with it much more tedious and more difficult too. However i am not familiar enough with why line 85 exists, and why it is done in this way in general, to be able to make a pull request, so im hoping someone with more experience in that area can solve this issue.

**Comment by srivatsav1998** [comment] 2020-11-16 05:12
Hi, I see that the bug is still reproducible. If it is okay, I would like to work on this as my first bug. Can you also suggest some pointers to start with?

**Comment by alalek** [comment] 2020-11-16 05:33
Proposed "FIX" (workaround btw) is not acceptable "as is".

Is there somehow to detect working PyCharm's Intellisense autocompletion? (usually autocompletion tools doesn't run any external code)
If so, then proposed changes can be added under the guard with condition of PyCharm detection.

**Comment by srivatsav1998** [comment] 2020-11-16 06:26
Hi @alalek, I don't think it's the issue with PyCharm's autocompletion alone. I tried with VSCode and Spyder as well. It failed to work there also. I think all the autocompletion tools rely on the fact that function definitions will be visible in __init__.py. I think we have to comply with that in order to extend support to IDEs. Do share your thoughts on the same :)

**Comment by alalek** [comment] 2020-11-16 06:31
> function definitions will be visible in `__init__.py`

Please note that OpenCV Python module is a **binary extension**, so there are no functions/classes definitions in .py files.

**Comment by srivatsav1998** [comment] 2020-11-17 13:23
Hi @alalek, I have tried various methods to get that working, but in vain. I think that to support IDE's autocompletion, we need to import cv2 as mentioned in the suggested FIX along with the current approach. But this implementation is tricky as we have the *.pyd inside python-x.x folder of site_packages/cv2. Is there are specific reason to have such a folder structure internally? Kindly let me know your thoughts and suggest any alternatives if you find any.

**Comment by alalek** [comment] 2020-11-19 20:52
> specific reason to have such a folder structure internally

As mentioned above OpenCV provides **binary Python extension**

This structure is used to support from the single package:
- different Python versions, like 2.7 and 3.x (2.7 is EOL nowadays, but this feature is here for several years)
- different binary-incompatible Python implementations
- different version of dependencies, like `numpy` (which has own API/ABI)

---

Did you tried to specify cv2.pyd file directly for IDE auto-completion. Does it really work?

**Comment by AleksandrPanov** [comment] 2021-09-06 13:16
This will be fixed by #20370 PR
This problem has already been described in #14590 issue.

**Closed** 2021-09-06 16:13 UTC
Labels: duplicate, feature, category: python bindings, incomplete

**Comment by TheBricktop** [comment] 2021-11-15 21:18
Opencv-python 4.53 here same issue on pycharm.

**Comment by fperezgamonal** [comment] 2021-11-23 14:54
Just for everyone's information, the issue is also present in PyCharm Community Edition 2021.2.3 with the package `opencv-python` with version `4.5.4.58`

**Comment by kevinlinxc** [comment] 2022-10-01 05:54
This problem is still present and incredibly annoying.

**Comment by yt4766269** [comment] 2023-01-01 22:48
This problem is still there (with opencv-python-4.7.0.68 and pycharm 2022.3.1). Very annoying...

**Comment by elsoifey** [comment] 2023-04-29 08:09
so do I
I'm still facing the same issue with the version of opencv-python-4.7.0.72 in PyCharm 2022.3.3

**Comment by ikbalunal** [comment] 2024-02-07 16:42
try cv2.VideoWriter.fourcc(*'MP4V')
