### ISSUE TITLE
 Unspecified error (Unknown layer type FIFOQueueV2 in op batch_join/fifo_queue) 

### ISSUE THREAD

**Issue by shashi438** [opencv/opencv#14835] opened 2019-06-19 15:57 UTC
- OpenCV = >3.4.1```

- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio [2017]

##### Detailed description

I have used the Facenet code to train a model and get .ckpt and .meta files. (https://github.com/davidsandberg/facenet). I used freeze_graph.py from tensorflow to get a .pb file from this, and then used the steps here (https://medium.com/@dibyaranjan.sathua/how-to-use-tensorflow-graph-with-opencv-dnn-module-3bbeeb4920c5) to optimize the model. 
Now I've tried calling it in tf_inception.cpp from CV dnn samples, just to see if model would load.

My model throws error as 

```
batch_join/fifo_queue:FIFOQueueV2
shared_name:[ ]
shapes:[ ]
container:[ ]
component_types:[ ]
capacity:[ ]
OpenCV(3.4.1) Error: Unspecified error (Unknown layer type FIFOQueueV2 in op batch_join/fifo_queue) in cv::dnn::experimental_dnn_v4::`anonymous-namespace'::TFImporter::populateNet, file C:\build\master_winpack-build-win64-vc14\opencv\modules\dnn\src\tensorflow\tf_importer.cpp, line 1582

``````

How do I solve this? 

=> Is it because the training code has FIFOQueueV2  as part of input pipeline, and CV doesn't recognize it?
=> Am I using the wrong .cpp file to call model?
=> would there be something wrong with my .pb file? 

thanks!

**Comment by alalek** [comment] 2019-06-19 17:03
duplicate of #9137

**Closed by alalek** 2019-06-19 17:03 UTC
Labels: category: dnn, duplicate

**Comment by shashi438** [comment] 2019-06-19 17:08
> duplicate of #9137

Hey the issue was not solved there, hence posted again. thanks!
