### ISSUE TITLE
Opencv include in c++ error

### ISSUE THREAD

**Issue by Seven-7Up** [opencv/opencv#20181] opened 2021-05-30 08:34 UTC
**HEAD**: I rewrite my issue for people who search for c++ include error solution.

Opencv4 (version 4.x.x) (building from source for linux) move include files in /usr/local/include/**opencv4/opencv2**/...
The problem is lot of opencv modules are including **<opencv2/**...> which make error while compiling.
Yes, I know that is very difficult to change all includes in modules, but you can change it in the Makefile.

Of course, this is just a recommendation for your project, for me, I resolved the problem by executing this commands:

```bash
mv /usr/local/include/opencv4/opencv2 /usr/local/include/.
rm -rf /usr/local/include/opencv4
```

Thanks Developers :1st_place_medal: !

**EDIT**: I found a new problem while compiling a simple opencv project which read image and display it. And I found a resolution for this error:

```bash
# I make an opencv.pc file which it can be read by pkg-config in linux
cat > /usr/lib/pkgconfig/opencv.pc << EOF
# Package Information for pkg-config

prefix=/usr
exec_prefix=${prefix}/local
libdir=${prefix}/lib
includedir=${exec_prefix}/include/opencv2

Name: OpenCV
Description: Open Source Computer Vision Library
Version: 4.5.1
Libs: -L${libdir} -lopencv_stitching -lopencv_alphamat -lopencv_aruco -lopencv_bgsegm -lopencv_bioinspired -lopencv_ccalib -lopencv_dnn_objdetect -lopencv_dnn_superres -lopencv_dpm -lopencv_face -lopencv_freetype -lopencv_fuzzy -lopencv_hdf -lopencv_hfs -lopencv_img_hash -lopencv_intensity_transform -lopencv_line_descriptor -lopencv_mcc -lopencv_quality -lopencv_rapid -lopencv_reg -lopencv_rgbd -lopencv_saliency -lopencv_shape -lopencv_stereo -lopencv_structured_light -lopencv_phase_unwrapping -lopencv_superres -lopencv_optflow -lopencv_surface_matching -lopencv_tracking -lopencv_highgui -lopencv_datasets -lopencv_text -lopencv_plot -lopencv_ml -lopencv_videostab -lopencv_videoio -lopencv_viz -lopencv_ximgproc -lopencv_video -lopencv_dnn -lopencv_xobjdetect -lopencv_objdetect -lopencv_calib3d -lopencv_imgcodecs -lopencv_features2d -lopencv_flann -lopencv_xphoto -lopencv_photo -lopencv_imgproc -lopencv_core
Libs.private: -ldl -lm -lpthread -lrt
Cflags: -I${includedir}
EOF
```

I made a full automation script shell in my [repo](https://github.com/Seven-7Up/opencv-installerForLinux/). Check it later if you like.

**Comment by alalek** [comment] 2021-05-30 14:33
duplicate of #13154

**Closed by alalek** 2021-05-30 14:33 UTC
Labels: duplicate, invalid
