### ISSUE TITLE
executing cuda template match cause procedure hang on?how to solve it.

### ISSUE THREAD

**Issue by lugui2009** [opencv/opencv#14063] opened 2019-03-15 07:55 UTC
- OpenCV => 3.4.0
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015
- Graphic card =>Nvidia RTX 2080
- CUDA =>10.1

hello everyone.
when I execute the cuda template match fuction , something wrong happens.
here is my test code from another issue here:

```
#include "cuda_runtime.h"
#include "opencv2/opencv.hpp"
#include <stdio.h>

int main()
{
	cv::cuda::GpuMat image_h(1080, 1920, CV_8UC1);
	cv::cuda::GpuMat templ_h(64, 64, CV_8UC1);
	cv::cuda::GpuMat result(1080 - 64 + 1, 1920 - 64 + 1, CV_32FC1);

	cv::Ptr<cv::cuda::TemplateMatching> alg;
	printf("before create\n");
	alg = cv::cuda::createTemplateMatching(templ_h.type(), CV_TM_CCOEFF_NORMED);
	printf("before match\n");
	alg->match(image_h, templ_h, result);
	printf("finished\n");
	cudaDeviceSynchronize();
	return 0;
}

```
when it executes the alg->match() fuction, the procedure doesn't go further,as belows:
![pic](https://user-images.githubusercontent.com/20158014/54416018-19055a80-4739-11e9-93c2-8041db535cee.jpg)

this fuction works well when I using Nvidia GTX 1070 and the cuda version is 9.1. I don't know why update to RTX 2080 and cuda version updates to 10.1,this function doesn't work. I haven't test other cuda functions .I recompile the opencv ,but it still doesn't work.

so I want to know how to solve this problem.I am new to opencv and cuda.some issues has seem to explain something  about that.However I still don't know how to solve it.So someone can give me some direct methods .thank you very much.

**Comment by alalek** [comment] 2019-03-15 08:00
duplicate of #13477

**Closed by alalek** 2019-03-15 08:00 UTC
Labels: category: gpu/cuda (contrib), duplicate
