### ISSUE TITLE
Trojan downloaders inside !!

### ISSUE THREAD

**Issue by virushater** [opencv/opencv#12309] opened 2018-08-25 14:55 UTC
##### System information (version)

Why u is there a trojan downloader ?!  I do not appreciate it!

##### Detailed description

Avast: JS:Downloader-DZB [Trj] 
AVG : JS:Downloader-DZB [Trj]
cyren : ZIP/Trojan.JDGB-6
Qihoo360 :  Script/Trojan.Downloader.3f1

**Comment by berak** [comment] 2018-08-25 17:53
@virushater -- care to inform us, **what** you downloaded, and from **where** ?

it's probably just a duplicate of #8156

**Closed** 2018-08-25 20:37 UTC
Labels: invalid
