### ISSUE TITLE
expose 'cv::partition' function to Java

### ISSUE THREAD

**Issue by amiriahmad72** [opencv/opencv#14304] opened 2019-04-11 16:16 UTC
can expose 'cv::partition' function to Java?

I download OpenCV 4.1(Win pack) and install it on my Windows-10 64 Bit.
I want to use it in my Java program but 'partition' function is not in java wrapper.

**Comment by alalek** [comment] 2019-04-11 16:21
duplicate of #11842

**Closed by alalek** 2019-04-11 16:21 UTC
