### ISSUE TITLE
java.lang.UnsatisfiedLinkError: Cannot find dependent libraries

### ISSUE THREAD

**Issue by BullyWiiPlaza** [opencv/opencv#13012] opened 2018-11-01 14:07 UTC
How can this common `Windows 7` error be fixed? I'm using the Java bindings and I'm about to go nuts since I tried everything and nothing worked:

1. Running the system file checker `sfc /scannow` (no violations found)
2. Searching for each DLL in the Windows search (all DLLs are found)
3. Repairing the system image `Dism /Online /Cleanup-Image /RestoreHealth` (does not work on `Windows 7`)
4. [Downloading `OpenCV`](https://opencv.org/releases.html) and extract the `DLL`s to the Java application's root folder (does not fix the issue)
5. Installing the [`DirectX End-User Runtime Web Installer`](https://www.microsoft.com/en-us/download/details.aspx?id=35) (does not fix the issue)
6. Rebooting after all previous mentioned points (does not fix the issue)

[This](https://stackoverflow.com/questions/53100890) is a related `StackOverflow` question with additional information.

Thank you.

**Comment by alalek** [comment] 2018-11-01 14:52
Are you able to run `opencv_version_win32.exe` ?

**Comment by BullyWiiPlaza** [comment] 2018-11-01 17:44
Good call, now I'm one step further:
![image](https://user-images.githubusercontent.com/7620135/47869007-0df30300-de06-11e8-97b1-7c7c2c734158.png)

On my `Windows 10` machine `opencv_version_win32.exe` runs fine. How would I install that `DLL` the proper way without some shady `DLL` download websites?

**Comment by alalek** [comment] 2018-11-01 18:52
OpenCV binaries are built on Windows 10 system. So they may not run on some Windows 7 installations (there are successful stories launching in Win7 without manual file downloading, but exact original package is unknown)

duplicate of #12010

**Closed by alalek** 2018-11-01 18:52 UTC
Labels: category: build/install, category: videoio, platform: win32
