### ISSUE TITLE
Opencv fails to read TensorFlow Faster R-CNN frozen graph with dnn module

### ISSUE THREAD

**Issue by pengfeisu** [opencv/opencv#12033] opened 2018-07-21 02:55 UTC
##### System information (version)

- OpenCV => 3.4.1
- Operating System / Platform => Ubuntu 16.04 64Bit
- Compiler => gcc 5.4.0
- TensorFlow => 1.4.0
- Model => faster_rcnn_resnet50_coco http://download.tensorflow.org/models/object_detection/faster_rcnn_resnet50_coco_2018_01_28.tar.gz

##### Detailed description

I have trained the original model on myself image set with the form of VOC2007.
But when I try to load the frozen model  in Tensorflow into OpenCV, the following error persists.
##### Steps to reproduce

Loading the frozen graphs

`cvNet = cv.dnn.readNetFromTensorflow('./output_inference_graph/trans_graph.pb', './output_inference_graph/graph.pbtxt')`

I get the error

`OpenCV(3.4.1) Error: Unspecified error (Input layer not found: FirstStageFeatureExtractor/resnet_v1_50/resnet_v1_50/conv1/BatchNorm/FusedBatchNorm) in connect, file /io/opencv/modules/dnn/src/tensorflow/tf_importer.cpp, line 553
Traceback (most recent call last):
  File "detect_opencv_tensorflow_2.py", line 3, in <module>
    cvNet = cv.dnn.readNetFromTensorflow('./output_inference_graph/trans_graph.pb', './output_inference_graph/graph.pbtxt')
cv2.error: OpenCV(3.4.1) /io/opencv/modules/dnn/src/tensorflow/tf_importer.cpp:553: error: (-2) Input layer not found: FirstStageFeatureExtractor/resnet_v1_50/resnet_v1_50/conv1/BatchNorm/FusedBatchNorm in function connect`

**Comment by alalek** [comment] 2018-07-21 03:49
Probably duplicate of #10870 (supported after release of OpenCV 3.4.1).
Try OpenCV 3.4.2 or latest code from 3.4 branch.

**Comment by dkurt** [comment] 2018-08-23 10:27
@pengfeisu, please try to update OpenCV. There were no Faster-RCNN networks from TensorFlow Object Detection API in OpenCV 3.4.1. Only SSDs.

**Comment by bleedingfight** [comment] 2018-09-03 02:30
@dkurt Hi,thanks for for replay,My program were trained on faster_rcnn_inception_v2(tensorflow object detection),my opencv version is 4.3.2,Can I use opencv detection my models?

**Comment by dkurt** [comment] 2018-09-04 12:11
@pengfeisu, Test for mentioned model has been added. See https://github.com/opencv/opencv/pull/12211.

**Closed by dkurt** 2018-09-04 12:11 UTC
Labels: category: dnn
