### ISSUE TITLE
CMake Project Fails Under a Directory With Non-Alphanumeric Characters

### ISSUE THREAD

**Issue by TekuConcept** [opencv/opencv#8962] opened 2017-06-21 20:44 UTC
##### System information (version)

- OpenCV => Latest master branch (following latest commit 92c0709)
- Operating System / Platform => Debian Linux BeagleBone Black 4.4.9-ti-r25
- Compiler => GCC Version 4.9.2 (Debian 4.9.2-10)
- CMake => v3.5.2

##### Detailed description

CMake Build Error - Directory names used in OpenCVUtils regular expressions containing non-alphanumeric characters such as '+' in `../c++/` cause cmake to fail. Renaming the parent directory from "C++" to "Cxx" allows cmake to proceed. Note though that in the cmake output below, the directory `/usr/bin/c++` is also used.

```
-- The CXX compiler identification is GNU 4.9.2
-- The C compiler identification is GNU 4.9.2
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Detected version of GNU GCC: 49 (409)
RegularExpression::compile(): Nested *?+.
RegularExpression::compile(): Error in compile.
CMake Error at cmake/OpenCVUtils.cmake:120 (if):
  if given arguments:

    "/home/debian/Desktop/Sandbox/C++/opencv/Build" "MATCHES" "^/home/debian/Desktop/Sandbox/C++/opencv" "OR" "/home/debian/Desktop/Sandbox/C++/opencv/Build" "MATCHES" "^/home/debian/Desktop/Sandbox/C++/opencv/Build" "OR" "(" "OPENCV_EXTRA_MODULES_PATH" "AND" "/home/debian/Desktop/Sandbox/C++/opencv/Build" "MATCHES" "^" ")"

  Regular expression "^/home/debian/Desktop/Sandbox/C++/opencv" cannot
  compile
Call Stack (most recent call first):
  cmake/OpenCVUtils.cmake:135 (ocv_is_opencv_directory)
  CMakeLists.txt:488 (ocv_include_directories)


-- Configuring incomplete, errors occurred!
```

##### Steps to reproduce

```
cd ~; mkdir C++ && cd C++
git clone <opencv repo> opencv; cd opencv
mkdir Build && cd Build
cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D WITH_CUDA=OFF -D WITH_CUFFT=OFF -D WITH_CUBLAS=OFF -D WITH_NVCUVID=OFF -D WITH_OPENCL=OFF -D WITH_OPENCLAMDFFT=OFF -D WITH_OPENCLAMDBLAS=OFF -D BUILD_opencv_apps=OFF -D BUILD_DOCS=OFF -D BUILD_PERF_TESTS=OFF -D BUILD_TESTS=OFF -D ENABLE_NEON=on ..

**Comment by mshabunin** [comment] 2017-06-22 16:33
Duplicate of #6046

**Closed by mshabunin** 2017-06-22 16:33 UTC
Labels: category: build/install, duplicate, wontfix

**Comment by TekuConcept** [comment] 2017-06-22 17:20
My appologies for posting a duplicate issue! I looked up and down for possible duplicates but couldn't find any before posting. I guess my eyes missed that one...
