### ISSUE TITLE
ProxyLoopBody needs overload that accepts cv::Range

### ISSUE THREAD

**Issue by TechnikEmpire** [opencv/opencv#12197] opened 2018-08-11 17:13 UTC
##### System information (version)

- OpenCV => 4eb2966
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017

##### Detailed description

When compiling with MKL and OpenMP, `parallel.cpp` defines `ProxyLoopBody` in such a way that it is missing an overload that accepts `cv::Range`, yet is called elsewhere with a `cv::Range` argument.

##### Steps to reproduce

Current version:
```C++
#elif defined WINRT || defined HAVE_CONCURRENCY
    class ProxyLoopBody : public ParallelLoopBodyWrapper
    {
    public:
        ProxyLoopBody(ParallelLoopBodyWrapperContext& ctx)
        : ParallelLoopBodyWrapper(ctx)
        {}

        void operator ()(int i) const
        {
            this->ParallelLoopBodyWrapper::operator()(cv::Range(i, i + 1));
        }
    };
#else
    typedef ParallelLoopBodyWrapper ProxyLoopBody;
#endif
```

Fix:
```C++
#elif defined WINRT || defined HAVE_CONCURRENCY
    class ProxyLoopBody : public ParallelLoopBodyWrapper
    {
    public:
        ProxyLoopBody(ParallelLoopBodyWrapperContext& ctx)
        : ParallelLoopBodyWrapper(ctx)
        {}

        void operator ()(int i) const
        {
            this->ParallelLoopBodyWrapper::operator()(cv::Range(i, i + 1));
        }

	void operator ()(const cv::Range& range) const
	{
		this->ParallelLoopBodyWrapper::operator()(range);
	}
    };
#else
    typedef ParallelLoopBodyWrapper ProxyLoopBody;
#endif
```

**Comment by alalek** [comment] 2018-08-13 19:45
Duplicate of #11998

**Closed by alalek** 2018-08-13 19:45 UTC
Labels: duplicate
