### ISSUE TITLE
cv::cuda::CascadeClassifier OpenCV 3.2 using data trained in OpenCV 2.4.11

### ISSUE THREAD

**Issue by shincodex** [opencv/opencv#9141] opened 2017-07-11 13:47 UTC
I have run the cuda version of cascade classifier in OpenCV 2.4.11 on cpu and a 860M GPU. The results can be wildly different in terms of being accurate. To a point where a detected object that was found in CPU has the same rectangle size on GPU version, but in a location that is way off. I need to know if anyone has experienced this. If you have. Did you retrain the classifier on that GPU?

I have tested my trained data(2.4.11) in OpenCV 2.4.11 cpu. I then was like well let me update the code base to use 3.2. Same, thing. Wildly different. Sometimes its correct sometimes it isn't.

I'm using LPB and blasting full 1920x1080 images at it.

This is a bug and a question.

**Comment by alalek** [comment] 2017-07-11 13:51
Duplicate of #6693

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Closed by alalek** 2017-07-11 13:51 UTC
Labels: duplicate, question (invalid)
