### ISSUE TITLE
OpenCV video_stab caused error

### ISSUE THREAD

**Issue by ferdyandannes** [opencv/opencv#14695] opened 2019-06-02 05:52 UTC
##### System information (version)
- OpenCV => 3.4.2
- Operating System / Platform => Ubuntu 16.04
- Compiler => CMAKE

##### Detailed description

Hello I tried to reinstalling my opencv with TBB support, but when I tried to install it, there is error in the video_stab when I tried to run -make j8 in the command. The reason why I re install because I need TBB support in my code. Is there anyone has same problem with me and solved this problem? Thank you

##### Steps to reproduce

cmake -D CMAKE_BUILD_TYPE=RELEASE \
-D CMAKE_INSTALL_PREFIX=/usr/local \
-D INSTALL_PYTHON_EXAMPLES=ON \
-D INSTALL_C_EXAMPLES=OFF \
-D WITH_CUDA=ON \
-D ENABLE_FAST_MATH=1 \
-D CUDA_FAST_MATH=1 \
-D WITH_CUBLAS=1 \
-D OPENCV_EXTRA_MODULES_PATH="/home/ee401_2/opencv_install/opencv_contrib-3.4.2/modules" \
-D BUILD_EXAMPLES=ON \
-D WITH_TBB=ON \
-D BUILD_opencv_xfeatures2d=ON ..

make -j8

#### Error
[ 89%] Building CXX object samples/gpu/CMakeFiles/example_gpu_generalized_hough.dir/generalized_hough.cpp.o
[ 89%] Built target opencv_perf_superres
[ 89%] Linking CXX executable ../../bin/example_gpu_hog
Scanning dependencies of target example_gpu_cascadeclassifier
[ 89%] Built target example_gpu_stereo_match
[ 89%] Building CXX object samples/gpu/CMakeFiles/example_gpu_cascadeclassifier.dir/cascadeclassifier.cpp.o
Scanning dependencies of target example_gpu_super_resolution
[ 89%] Built target opencv_test_superres
[ 89%] Building CXX object samples/gpu/CMakeFiles/example_gpu_super_resolution.dir/super_resolution.cpp.o
Scanning dependencies of target example_gpu_multi
[ 89%] Building CXX object samples/gpu/CMakeFiles/example_gpu_multi.dir/multi.cpp.o
[ 89%] Linking CXX executable ../../bin/example_gpu_opticalflow_nvidia_api
[ 89%] Linking CXX executable ../../bin/example_gpu_generalized_hough
[ 89%] Built target example_gpu_hog
[ 89%] Linking CXX executable ../../bin/example_gpu_stereo_multi
Scanning dependencies of target example_gpu_video_writer
[ 89%] Building CXX object samples/gpu/CMakeFiles/example_gpu_video_writer.dir/video_writer.cpp.o
[ 89%] Built target example_gpu_opticalflow_nvidia_api
Scanning dependencies of target example_gpu_morphology
[ 89%] Linking CXX executable ../../bin/example_gpu_video_writer
[ 89%] Building CXX object samples/gpu/CMakeFiles/example_gpu_morphology.dir/morphology.cpp.o
[ 89%] Linking CXX executable ../../bin/example_gpu_super_resolution
[ 89%] Built target example_gpu_generalized_hough
Scanning dependencies of target example_gpu_bgfg_segm
[ 89%] Built target example_gpu_stereo_multi
[ 89%] Built target example_gpu_video_writer
[ 89%] Building CXX object samples/gpu/CMakeFiles/example_gpu_bgfg_segm.dir/bgfg_segm.cpp.o
Scanning dependencies of target example_gpu_pyrlk_optical_flow
[ 89%] Linking CXX executable ../../bin/example_gpu_multi
[ 89%] Building CXX object samples/gpu/CMakeFiles/example_gpu_pyrlk_optical_flow.dir/pyrlk_optical_flow.cpp.o
/usr/bin/ld: CMakeFiles/example_gpu_multi.dir/multi.cpp.o: undefined reference to symbol '_ZN3tbb18task_group_contextD1Ev'
//usr/lib/x86_64-linux-gnu/libtbb.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
samples/gpu/CMakeFiles/example_gpu_multi.dir/build.make:122: recipe for target 'bin/example_gpu_multi' failed
make[2]: *** [bin/example_gpu_multi] Error 1
CMakeFiles/Makefile2:48496: recipe for target 'samples/gpu/CMakeFiles/example_gpu_multi.dir/all' failed
make[1]: *** [samples/gpu/CMakeFiles/example_gpu_multi.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 89%] Linking CXX executable ../../bin/example_gpu_cascadeclassifier
[ 89%] Built target example_gpu_super_resolution
[ 89%] Linking CXX executable ../../bin/example_gpu_morphology
[ 89%] Built target example_gpu_cascadeclassifier
[ 89%] Linking CXX executable ../../bin/example_gpu_bgfg_segm
[ 89%] Built target example_gpu_morphology
[ 89%] Linking CXX executable ../../bin/example_gpu_pyrlk_optical_flow
[ 89%] Built target example_gpu_bgfg_segm
[ 89%] Built target example_gpu_pyrlk_optical_flow
Scanning dependencies of target opencv_videostab
[ 89%] Building CXX object modules/videostab/CMakeFiles/opencv_videostab.dir/src/deblurring.cpp.o
[ 89%] Building CXX object modules/videostab/CMakeFiles/opencv_videostab.dir/src/frame_source.cpp.o
[ 89%] Building CXX object modules/videostab/CMakeFiles/opencv_videostab.dir/src/fast_marching.cpp.o
[ 89%] Building CXX object modules/videostab/CMakeFiles/opencv_videostab.dir/src/global_motion.cpp.o
[ 89%] Building CXX object modules/videostab/CMakeFiles/opencv_videostab.dir/src/wobble_suppression.cpp.o
[ 89%] Building CXX object modules/videostab/CMakeFiles/opencv_videostab.dir/src/motion_stabilizing.cpp.o
[ 89%] Building CXX object modules/videostab/CMakeFiles/opencv_videostab.dir/src/outlier_rejection.cpp.o
[ 89%] Building CXX object modules/videostab/CMakeFiles/opencv_videostab.dir/src/optical_flow.cpp.o
cc1plus: warning: /home/ee401_2/opencv_install/opencv-3.4.2/build2/modules/videostab/precomp.hpp.gch/opencv_videostab_RELEASE.gch: not used because `OPENCV_TRAITS_ENABLE_DEPRECATED' is defined [-Winvalid-pch]
cc1plus: warning: /home/ee401_2/opencv_install/opencv-3.4.2/build2/modules/videostab/precomp.hpp.gch/opencv_videostab_RELEASE.gch: not used because `OPENCV_TRAITS_ENABLE_DEPRECATED' is defined [-Winvalid-pch]
cc1plus: warning: /home/ee401_2/opencv_install/opencv-3.4.2/build2/modules/videostab/precomp.hpp.gch/opencv_videostab_RELEASE.gch: not used because `OPENCV_TRAITS_ENABLE_DEPRECATED' is defined [-Winvalid-pch]
cc1plus: warning: /home/ee401_2/opencv_install/opencv-3.4.2/build2/modules/videostab/precomp.hpp.gch/opencv_videostab_RELEASE.gch: not used because `OPENCV_TRAITS_ENABLE_DEPRECATED' is defined [-Winvalid-pch]
cc1plus: warning: /home/ee401_2/opencv_install/opencv-3.4.2/build2/modules/videostab/precomp.hpp.gch/opencv_videostab_RELEASE.gch: not used because `OPENCV_TRAITS_ENABLE_DEPRECATED' is defined [-Winvalid-pch]
cc1plus: warning: /home/ee401_2/opencv_install/opencv-3.4.2/build2/modules/videostab/precomp.hpp.gch/opencv_videostab_RELEASE.gch: not used because `OPENCV_TRAITS_ENABLE_DEPRECATED' is defined [-Winvalid-pch]
cc1plus: warning: /home/ee401_2/opencv_install/opencv-3.4.2/build2/modules/videostab/precomp.hpp.gch/opencv_videostab_RELEASE.gch: not used because `OPENCV_TRAITS_ENABLE_DEPRECATED' is defined [-Winvalid-pch]
cc1plus: warning: /home/ee401_2/opencv_install/opencv-3.4.2/build2/modules/videostab/precomp.hpp.gch/opencv_videostab_RELEASE.gch: not used because `OPENCV_TRAITS_ENABLE_DEPRECATED' is defined [-Winvalid-pch]
[ 89%] Building CXX object modules/videostab/CMakeFiles/opencv_videostab.dir/src/stabilizer.cpp.o
cc1plus: warning: /home/ee401_2/opencv_install/opencv-3.4.2/build2/modules/videostab/precomp.hpp.gch/opencv_videostab_RELEASE.gch: not used because `OPENCV_TRAITS_ENABLE_DEPRECATED' is defined [-Winvalid-pch]
[ 89%] Building CXX object modules/videostab/CMakeFiles/opencv_videostab.dir/src/log.cpp.o
cc1plus: warning: /home/ee401_2/opencv_install/opencv-3.4.2/build2/modules/videostab/precomp.hpp.gch/opencv_videostab_RELEASE.gch: not used because `OPENCV_TRAITS_ENABLE_DEPRECATED' is defined [-Winvalid-pch]
[ 89%] Building CXX object modules/videostab/CMakeFiles/opencv_videostab.dir/src/inpainting.cpp.o
cc1plus: warning: /home/ee401_2/opencv_install/opencv-3.4.2/build2/modules/videostab/precomp.hpp.gch/opencv_videostab_RELEASE.gch: not used because `OPENCV_TRAITS_ENABLE_DEPRECATED' is defined [-Winvalid-pch]
[ 89%] Linking CXX shared library ../../lib/libopencv_videostab.so
[ 89%] Built target opencv_videostab
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by alalek** [comment] 2019-06-02 10:55
> video_stab caused error

Wrong.
Don't report with logs from parallel builds. Their mess is very hard to read.
Always use `make -j1` to debug build issues.

Failed part is here:
> //usr/lib/x86_64-linux-gnu/libtbb.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
samples/gpu/CMakeFiles/example_gpu_multi.dir/build.make:122: recipe for target 'bin/example_gpu_multi' failed
make[2]: *** [bin/example_gpu_multi] Error 1

Duplicate of #11759 and other issues with "example_gpu_multi".

Possible workarounds are:
- disabled CUDA (`WITH_CUDA=OFF`)
- disable TBB
- disable examples (`BUILD_EXAMPLES=OFF`)

Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

> 3.4.2

Too old release (>1 year).
Try to build to latest code from 3.4/master branch at first.

**Closed by alalek** 2019-06-02 10:55 UTC
Labels: category: gpu/cuda (contrib), duplicate, question (invalid tracker)
