### ISSUE TITLE
Any known issues with calling opencv code from multiple threads under OS X ?

### ISSUE THREAD

**Issue by malcolmgreaves** [opencv/opencv#6461] opened 2016-04-23 00:14 UTC
Hello!

I have run into a very difficult-to-comprehend problem. 

I am calling OpenCV code from the JVM (through the javacpp project https://github.com/bytedeco/javacpp ). In my program, I have a process which takes several images and runs some simple image processing commands on each (rgb2gray, some erosion & dilation). 

Crucially, everything is fine *so long as my program only calls opencv code in serial*. The second that I start processing each image in parallel, my program has deterministic behavior. Eventually, it always receives a SIGSEV. *This happens even when I set the number of threads in openCV to 0*.The Java signal handler catches this, prints out the following, and dies:

```
# C  [libopencv_imgproc.3.0.dylib+0x36490]  cv::CvtColorLoop_Invoker<cv::RGB2Gray<unsigned char> >::operator()(cv::Range const&) const+0x70
```

So, *on os x*, it is still trying to do the RGB2Gray conversion in parallel (that's what `CvtColorLoop_Invoker` does to the extent of my C++ knowledge and code reviews over the past few days).

However... here's where stuff gets interesting. If I execute the same code under linux, I have no problems when running in serial or in parallel.

This fact leads me to believe that there is something wrong with either (1) open cv not respecting serial processing on OS X or (2) something wrong with grand central dispatch in OS X itself.

I am not a C++ dev so I need a lot of help in tracking down this problem. I am very willing to put in time and effort to track down the root cause of this behavior, find a fix, and push it back upstream.

Thank you for any and all help in advance!

**Comment by alalek** [comment] 2016-04-23 07:44
Possibly related to `fork()` call problem: #5150

**Comment by malcolmgreaves** [comment] 2016-04-24 03:20
Interesting -- I read through that issue before. What I find most peculiar is that there is a significant difference, and similarity, to #5150.

The foremost difference between my use case and that of #5150 is that I'm calling opencv code from the same process. The Python program of #5150 uses multiprocessing to perform parallel image processing. The memory and task isolation present between processes would prevent any kind of race condition.

Perhaps more interesting (and maybe closer to the root of the problem) is the fact that both mine and #5150 problems were reported running under OSX. Under OSX, OpenCV's multithreading code is compiled using Grand Central Dispatch (GCD). GCD is OSX's thread scheduler. I have no idea how it works...

I find it interesting that my problem is only present under OSX. Could it be that the GCD-specific compiled code is buggy and doesn't obey the indended semantics of `cv::setNumThreads(0)`?

Could it be a bug in GCD itself? (I find this highly unlikely...) Could it be a bug in the Java Native Interface (JNI) implementation for the OSX specific JVM? Or a bug in multuithreading code for the JVM that only occurs on OSX when interacting with OSX-specific JNI code (Again, I find this unlikely...).

**Comment by malcolmgreaves** [comment] 2016-04-24 03:22
On another idea: Would it be feasible to strip-out all of the multi-threading code from OpenCV and produce a custom build of it? Or perhaps is there a reliable and straightforward way to disable all of the GCD code in opencv and have it fall back to using `pthreads`?

**Comment by alalek** [comment] 2016-04-24 08:44
Parallel backend is selected during compile time, so you need to rebuild OpenCV yourself to fallback to pthreads.
Looks like there is no CMake option in OpenCV to select parallel framework directly.
Try to put here 0 to fall-back on pthreads backend: https://github.com/Itseez/opencv/blob/master/cmake/OpenCVFindLibsPerf.cmake#L98

**Comment by mshabunin** [comment] 2016-04-25 14:35
By the way, if you take a look at [setNumThreads](https://github.com/Itseez/opencv/blob/af5bec70cd8803920e018a87a8a158cda3d7d568/modules/core/src/parallel.cpp#L380) you will see that GCD backend does not support setting custom number of threads.

**Comment by malcolmgreaves** [comment] 2016-04-25 18:42
@mshabunin Ah that is an incredibly interesting and important fact! Ok so this makes me believe that I really have to make sure that I'm using OpenCV with pthreads only. If I am not mistaken, that is the only way to guarantee that all concurrent execution happens in serial. (Please chime in if this understanding is wrong!)

I will take some time to look into compiling OpenCV on OSX with pthreads only... I have had some difficulty compiling already. But it must be achievable! :P

**Comment by mshabunin** [comment] 2016-07-12 14:16
I will close it for now. Feel free to reopen if you have more specific information and a small reproducing example.

**Closed by mshabunin** 2016-07-12 14:16 UTC
Labels: question (invalid)

**Comment by malcolmgreaves** [comment] 2016-07-13 21:01
Hi @mshabunin ! Unfortunately, I was not able to perform the necessary recompilation and (for my use case) get it working with JNI. For the project that I am working on, I moved over to use the [`boofcv`](https://github.com/lessthanoptimal/BoofCV) library. Thank you for your time and effort on this issue!
