### ISSUE TITLE
 error: (-2:Unspecified error) Can't initialize GTK backend in function 'cvInitSystem'

### ISSUE THREAD

**Issue by Dolphinzzx** [opencv/opencv#18666] opened 2020-10-27 04:15 UTC
##### System information (version)

- OpenCV = 4.5.0
- Operating System / Platform => Raspbian 32 Bit
- Compiler => Visual Studio 2017

##### Detailed description

This is my program:
import cv2
img = cv2.imread('test.png',1)
cv2.imshow('Camera Capture', img)

![image](https://user-images.githubusercontent.com/35594203/97256254-8b16ae80-184d-11eb-8914-62d7b1f0b4dc.png)
When i run this program, it will prompt "error: (-2:Unspecified error) Can't initialize GTK backend in function 'cvInitSystem'"
![image](https://user-images.githubusercontent.com/35594203/97256316-ada8c780-184d-11eb-8fa5-d7d527a3e6c3.png)

**Comment by wolfedale** [comment] 2020-10-29 08:24
I'm hitting the same issue when using Ubuntu.

**Comment by cassidylinhares** [comment] 2020-11-06 14:55
Im getting the same issue with debian on aarch64

**Comment by alalek** [comment] 2020-11-06 15:08
duplicate of #18461

**Closed by alalek** 2020-11-06 15:08 UTC
Labels: duplicate, question (invalid tracker)

**Comment by vijaysekark** [comment] 2022-05-22 14:46
it will run only if login as root user
