### ISSUE TITLE
contours, hierarchy = cv2.findContours(img_th, cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE) ValueError: too many values to unpack

### ISSUE THREAD

**Issue by nishchaytrivedi123** [opencv/opencv#9635] opened 2017-09-15 11:45 UTC
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

**Comment by berak** [comment] 2017-09-15 12:29
definitely not a bug.

most likely, you're trying to use above (opencv2.4) code with opencv3, where findContours returns an additional image (so you have 3 return values, but only 2 vars to hold them)

please check `help(cv2.findContours)` and `cv2.__version__`
would you be so kind, and close this issue ? further questions should go to http://answers.opencv.org/questions/

**Closed** 2017-09-15 13:18 UTC
Labels: question (invalid)

**Comment by nishchaytrivedi123** [comment] 2017-09-15 16:19
actually I am using opencv 3.3.0 
so what can be the solution?

**Comment by alalek** [comment] 2017-09-15 19:26
> please check `help(cv2.findContours)` and `cv2.__version__`

@nishchaytrivedi123 What do you have here?

**Comment by nishchaytrivedi123** [comment] 2017-09-17 07:26
@alalek using help(cv2.findContours) i got this
findContours(...)
    findContours(image, mode, method[, contours[, hierarchy[, offset]]]) -> image, contours, hierarchy
    .   @brief Finds contours in a binary image.
    .   
    .   The function retrieves contours from the binary image using the algorithm @cite Suzuki85 . The contours
    .   are a useful tool for shape analysis and object detection and recognition. See squares.cpp in the
    .   OpenCV sample directory.
    .   @note Since opencv 3.2 source image is not modified by this function.
    .   
    .   @param image Source, an 8-bit single-channel image. Non-zero pixels are treated as 1's. Zero
    .   pixels remain 0's, so the image is treated as binary . You can use cv::compare, cv::inRange, cv::threshold ,
    .   cv::adaptiveThreshold, cv::Canny, and others to create a binary image out of a grayscale or color one.
    .   If mode equals to cv::RETR_CCOMP or cv::RETR_FLOODFILL, the input can also be a 32-bit integer image of labels (CV_32SC1).
    .   @param contours Detected contours. Each contour is stored as a vector of points (e.g.
    .   std::vector<std::vector<cv::Point> >).
    .   @param hierarchy Optional output vector (e.g. std::vector<cv::Vec4i>), containing information about the image topology. It has
    .   as many elements as the number of contours. For each i-th contour contours[i], the elements
    .   hierarchy[i][0] , hierarchy[i][1] , hierarchy[i][2] , and hierarchy[i][3] are set to 0-based indices
    .   in contours of the next and previous contours at the same hierarchical level, the first child
    .   contour and the parent contour, respectively. If for the contour i there are no next, previous,
    .   parent, or nested contours, the corresponding elements of hierarchy[i] will be negative.
    .   @param mode Contour retrieval mode, see cv::RetrievalModes
    .   @param method Contour approximation method, see cv::ContourApproximationModes
    .   @param offset Optional offset by which every contour point is shifted. This is useful if the
    .   contours are extracted from the image ROI and then they should be analyzed in the whole image
    .   context.

and using  cv2.__version__ i got 3.3.0

**Comment by alalek** [comment] 2017-09-17 09:39
> contours, hierarchy = cv2.findContours

should be

> image, contours, hierarchy

in this version.
