### ISSUE TITLE
constant l_MAGIC_VAL already exists

### ISSUE THREAD

**Issue by manish199957** [opencv/opencv#16917] opened 2020-03-27 10:35 UTC
[ 82%] Built target opencv_python2
[ 82%] Generating pyopencv_generated_include.h, pyopencv_generated_funcs.h, pyopencv_generated_types.h, pyopencv_generated_type_reg.h, pyopencv_generated_ns_reg.h
Note: Class l has more than 1 base class (not supported by Python C extensions)
      Bases:  cv::a, cv::s, cv::s, cv::A, cv::l, cv::g, cv::o, cv::r, cv::i, cv::t, cv::h, cv::m
      Only the first base class will be used
Generator error: constant l_MAGIC_VAL (cname=cv::l::MAGIC_VAL) already exists
make[2]: *** [modules/python3/CMakeFiles/opencv_python3.dir/build.make:269: modules/python3/pyopencv_generated_include.h] Error 255
make[1]: *** [CMakeFiles/Makefile2:13602: modules/python3/CMakeFiles/opencv_python3.dir/all] Error 2
make: *** [Makefile:163: all] Error 2

I used python 3.7

cmake -D CMAKE_BUILD_TYPE=RELEASE \
    -D CMAKE_INSTALL_PREFIX=/usr/local \
    -D INSTALL_PYTHON_EXAMPLES=ON \
    -D INSTALL_C_EXAMPLES=OFF \
    -D ENABLE_PRECOMPILED_HEADERS=OFF \
    -D OPENCV_EXTRA_MODULES_PATH=~/opencv_contrib-3.1.0/modules \
    -D BUILD_EXAMPLES=ON ..

and followed these steps https://www.pyimagesearch.com/2016/04/18/install-guide-raspberry-pi-3-raspbian-jessie-opencv-3/

please help!!!!!

**Comment by alalek** [comment] 2020-03-27 12:17
duplicate of #16917

Use old Python 3.x from OpenCV 3.1.0 release date or Python 2.7.x

**Closed by alalek** 2020-03-27 12:17 UTC
Labels: duplicate
