### ISSUE TITLE
Still getting Using 'value' pointer is unsafe and deprecated. Use NULL as value pointer. To fetch trackbar value setup callback. 

### ISSUE THREAD

**Issue by sourdurian** [opencv/opencv#20694] opened 2021-09-12 08:14 UTC
##### System information (version)

- OpenCV => 4.5.3
- Operating System / Platform => Windows 64 Bit
- Compiler => VSC

##### Detailed description

I've been trying to create a trackbar. I've also tried the solutions provided in Github by Berak (https://www.gitmemory.com/issue/opencv/opencv/20408/880533612) but I am still getting the same errors. 

##### Steps to reproduce

```
import cv2
import numpy as np

lowH = 0
highH = 180

lowS = 0
highS = 255

lowV = 0
highV = 255

cap = cv2.VideoCapture(0)
cv2.createTrackbar("l-h", "frame", lowH, 180, lambda x:x)
cv2.createTrackbar("h-h", "frame", highH, 180, lambda x:x)
cv2.createTrackbar("l-s", "frame", lowS, 255, lambda x:x)
cv2.createTrackbar("h-s", "frame", highS, 255, lambda x:x)
cv2.createTrackbar("l-v", "frame", lowV, 255, lambda x:x)
cv2.createTrackbar("h-v", "frame", highV, 255, lambda x:x)
```

**Comment by alalek** [comment] 2021-09-12 11:02
You need to build from sources if you can't wait for release.

duplicate of #20408

---

Build / usage questions should go to Users OpenCV Q/A forum: https://forum.opencv.org/

**Closed by alalek** 2021-09-12 11:02 UTC
Labels: duplicate, invalid
