### ISSUE TITLE
longjmp causes uninitialized stack frame ***: ./bin/opencv_test_core terminated

### ISSUE THREAD

**Issue by wangzhankun** [opencv/opencv#15671] opened 2019-10-09 08:40 UTC
##### System information (version)

- OpenCV => 3.4.7
- Operating System / Platform => ubuntu18.04 x86_64

##### Detailed description
When I try to run my program which can be compiled without error,  it said:
```Bash
error while loading shared libraries: libopencv_world.so.3.4: cannot open shared object file: No such file or directory
```

When I have installed opencv (nothing error happened while compiling)， I try to exec opencv_test_core and errors happen.

```Bash
[ RUN      ] Core_InputOutput.filestorage_base64_basic_read_XML
/home/wang/Downloads/opencv-3.4.7/modules/core/test/test_io.cpp:774: Failure
Expected equality of these values:
  (int)rawdata[i].u1
    Which is: 0
  1
/home/wang/Downloads/opencv-3.4.7/modules/core/test/test_io.cpp:775: Failure
Expected equality of these values:
  (int)rawdata[i].u2
    Which is: 0
  2
/home/wang/Downloads/opencv-3.4.7/modules/core/test/test_io.cpp:776: Failure
Expected equality of these values:
  (int)rawdata[i].i1
    Which is: 0
  1
/home/wang/Downloads/opencv-3.4.7/modules/core/test/test_io.cpp:777: Failure
Expected equality of these values:
  (int)rawdata[i].i2
    Which is: 0
  2
/home/wang/Downloads/opencv-3.4.7/modules/core/test/test_io.cpp:778: Failure
Expected equality of these values:
  (int)rawdata[i].i3
    Which is: 0
  3
/home/wang/Downloads/opencv-3.4.7/modules/core/test/test_io.cpp:779: Failure
Expected equality of these values:
  rawdata[i].d1
    Which is: 0
  0.1
/home/wang/Downloads/opencv-3.4.7/modules/core/test/test_io.cpp:780: Failure
Expected equality of these values:
  rawdata[i].d2
    Which is: 0
  0.2
i = 0
/home/wang/Downloads/opencv-3.4.7/modules/core/test/test_io.cpp:774: Failure
Expected equality of these values:
  (int)rawdata[i].u1
    Which is: 0
  1
/home/wang/Downloads/opencv-3.4.7/modules/core/test/test_io.cpp:775: Failure
Expected equality of these values:
  (int)rawdata[i].u2
    Which is: 0
  2
/home/wang/Downloads/opencv-3.4.7/modules/core/test/test_io.cpp:776: Failure
Expected equality of these values:
  (int)rawdata[i].i1
    Which is: 0
  1
/home/wang/Downloads/opencv-3.4.7/modules/core/test/test_io.cpp:777: Failure
Expected equality of these values:
  (int)rawdata[i].i2
    Which is: 0
  2
/home/wang/Downloads/opencv-3.4.7/modules/core/test/test_io.cpp:778: Failure
Expected equality of these values:
  (int)rawdata[i].i3
    Which is: 0
  3
/home/wang/Downloads/opencv-3.4.7/modules/core/test/test_io.cpp:779: Failure
Expected equality of these values:
  rawdata[i].d1
    Which is: 0
  0.1
/home/wang/Downloads/opencv-3.4.7/modules/core/test/test_io.cpp:780: Failure
Expected equality of these values:
  rawdata[i].d2
    Which is: 0
  0.2
/home/wang/Downloads/opencv-3.4.7/modules/core/test/test_io.cpp:781: Failure
Expected equality of these values:
  (int)rawdata[i].i4
    Which is: 0
  i
    Which is: 1
i = 1
/home/wang/Downloads/opencv-3.4.7/modules/core/test/test_io.cpp:774: Failure
Expected equality of these values:
  (int)rawdata[i].u1
    Which is: 0
  1
/home/wang/Downloads/opencv-3.4.7/modules/core/test/test_io.cpp:775: Failure
Expected equality of these values:
  (int)rawdata[i].u2
    Which is: 0
  2
/home/wang/Downloads/opencv-3.4.7/modules/core/test/test_io.cpp:776: Failure
Expected equality of these values:
  (int)rawdata[i].i1
    Which is: 0
  1
/home/wang/Downloads/opencv-3.4.7/modules/core/test/test_io.cpp:777: Failure
Expected equality of these values:
  (int)rawdata[i].i2
    Which is: 0
  2
/home/wang/Downloads/opencv-3.4.7/modules/core/test/test_io.cpp:778: Failure
Expected equality of these values:
  (int)rawdata[i].i3
    Which is: 0
  3
/home/wang/Downloads/opencv-3.4.7/modules/core/test/test_io.cpp:779: Failure
Expected equality of these values:
  rawdata[i].d1
    Which is: 0
  0.1
/home/wang/Downloads/opencv-3.4.7/modules/core/test/test_io.cpp:780: Failure
Expected equality of these values:
  rawdata[i].d2
    Which is: 0
  0.2
/home/wang/Downloads/opencv-3.4.7/modules/core/test/test_io.cpp:781: Failure
Expected equality of these values:
  (int)rawdata[i].i4
    Which is: 0
  i
    Which is: 2
i = 2
/home/wang/Downloads/opencv-3.4.7/modules/core/test/test_io.cpp:798: Failure
Expected equality of these values:
  _2d_in.rows
    Which is: 0
  _2d_out.rows
    Which is: 10
/home/wang/Downloads/opencv-3.4.7/modules/core/test/test_io.cpp:799: Failure
Expected equality of these values:
  _2d_in.cols
    Which is: 0
  _2d_out.cols
    Which is: 20
/home/wang/Downloads/opencv-3.4.7/modules/core/test/test_io.cpp:800: Failure
Expected equality of these values:
  _2d_in.dims
    Which is: 0
  _2d_out.dims
    Which is: 2
*** longjmp causes uninitialized stack frame ***: ./bin/opencv_test_core terminated
*** longjmp causes uninitialized stack frame ***: ./bin/opencv_test_core terminated
*** longjmp causes uninitialized stack frame ***: ./bin/opencv_test_core terminated
*** longjmp causes uninitialized stack frame ***: ./bin/opencv_test_core terminated
*** longjmp causes uninitialized stack frame ***: ./bin/opencv_test_core terminated
*** longjmp causes uninitialized stack frame ***: ./bin/opencv_test_core terminated
*** longjmp causes uninitialized stack frame ***: ./bin/opencv_test_core terminated
*** longjmp causes uninitialized stack frame ***: ./bin/opencv_test_core terminated
*** longjmp causes uninitialized stack frame ***: ./bin/opencv_test_core terminated
*** longjmp causes uninitialized stack frame ***: ./bin/opencv_test_core terminated
*** longjmp causes uninitialized stack frame ***: ./bin/opencv_test_core terminated
*** longjmp causes uninitialized stack frame ***: ./bin/opencv_test_core terminated
*** longjmp causes uninitialized stack frame ***: ./bin/opencv_test_core terminated
*** longjmp causes uninitialized stack frame ***: ./bin/opencv_test_core terminated
*** longjmp causes uninitialized stack frame ***: ./bin/opencv_test_core terminated
*** longjmp causes uninitialized stack frame ***: ./bin/opencv_test_core terminated
*** longjmp causes uninitialized stack frame ***: ./bin/opencv_test_core terminated
*** longjmp causes uninitialized stack frame ***: ./bin/opencv_test_core terminated
*** longjmp causes uninitialized stack frame ***: ./bin/opencv_test_core terminated
*** longjmp causes uninitialized stack frame ***: ./bin/opencv_test_core terminated
*** longjmp causes uninitialized stack frame ***: ./bin/opencv_test_core terminated
*** longjmp causes uninitialized stack frame ***: ./bin/opencv_test_core terminated
[1]    25343 segmentation fault (core dumped)  ./bin/opencv_test_core

```

**Comment by alalek** [comment] 2019-10-09 10:13
There was a bug in test (which can't work properly without testdata, use `OPENCV_TEST_DATA_PATH=<opencv_extra>/testdata`). Should be fixed in latest code from 3.4 branch.

**Closed by alalek** 2019-10-09 10:13 UTC
Labels: test

**Comment by wangzhankun** [comment] 2019-10-09 10:22
Yes, I did. But nothing changes.
```Bash
set OPENCV_TEST_DATA_PATH=/home/wang/Downloads/opencv_extra-3.4.7/testdata
```

**Comment by alalek** [comment] 2019-10-10 16:21
[Can't reproduce](http://pullrequest.opencv.org/buildbot/grid?tag=scheduled-3.4&width=7).
