### ISSUE TITLE
Videoio tests segfaulting (impossible to open video)

### ISSUE THREAD

**Issue by alcinos** [opencv/opencv#7274] opened 2016-09-12 22:34 UTC
##### System information (version)

- OpenCV => latest master version (commit b632f95f8dd869258e50a3b8a2f3c4af9c26ad2d)
- Operating System / Platform => archlinux
- Compiler => 
  COLLECT_GCC=gcc
  COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/lto-wrapper
  Cible : x86_64-pc-linux-gnu
  Configuré avec: /build/gcc5/src/gcc-5.4.0/configure --prefix=/usr --build=x86_64-pc-linux-gnu --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --with-linker-hash-style=gnu --enable-gnu-indirect-function --disable-multilib --disable-werror --enable-checking=release --program-suffix=-5 --enable-version-specific-runtime-libs
  Modèle de thread: posix
  gcc version 5.4.0 (GCC) 
- FFMPEG =>
  ffmpeg version 3.1.3 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 6.1.1 (GCC) 20160802
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-avisynth --enable-avresample --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libass --enable-libbluray --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-netcdf --enable-shared --enable-version3 --enable-x11grab
   libavutil      55. 28.100 / 55. 28.100
   libavcodec     57. 48.101 / 57. 48.101
   libavformat    57. 41.100 / 57. 41.100
   libavdevice    57.  0.101 / 57.  0.101
   libavfilter     6. 47.100 /  6. 47.100
   libavresample   3.  0.  0 /  3.  0.  0
   libswscale      4.  1.100 /  4.  1.100
   libswresample   2.  1.100 /  2.  1.100
   libpostproc    54.  0.100 / 54.  0.100
##### Detailed description

I have two tests failing : 

```
 /home/nicolas/Documents/Developpement/Projets/GoPro_toolbox/opencv/modules/ts/src/ts.cpp:518: Failure
 Failed

failure reason: Arithmetic exception
test case #-1
seed: ffffffffffffffff
LOG:
General failure:
Arithmetic exception (-6)
[  FAILED  ] Videoio_Video.ffmpeg_writebig (3742 ms)
[ RUN      ] Videoio_Video.ffmpeg_image
[1]    20718 segmentation fault (core dumped)  ./opencv_test_videoio
```
##### Steps to reproduce

Build and run opencv_test_videoio
Actually any code trying to read a video is segfaulting.

**Comment by alalek** [comment] 2016-09-13 10:59
I'm not able to reproduce problem on Fedora with [custom](https://gist.github.com/alalek/03ccd2ec63041731aa1bcd57cfce3607) ffmpeg 3.1.3 build:
```
    FFMPEG:                      YES
      codec:                     YES (ver 57.48.101)
      format:                    YES (ver 57.40.101)
      util:                      YES (ver 55.27.100)
      swscale:                   YES (ver 4.1.100)
      resample:                  YES (ver 3.0.0)
      gentoo-style:              YES
```

Could you add gdb stacktrace?

**Comment by alcinos** [comment] 2016-09-13 11:20
Hi,

So I took a closer look, and it might actually be more involved than initially thought.
The backtrace for the test "Videoio_Video.write_read" is [here](https://gist.github.com/alcinos/622b7a0de529acbdd03e6bd90e0b66ac). It seems to have something to do with tbb. The version on my computer is 4.4_20160526-2

However, there might be more to it, since even a very simple program is failing. See [this gist](https://gist.github.com/alcinos/d3470f49223bc725e5e88d0faf44b81a) for minimal failing code and corresponding backtrace.

Tell me if you need anything else

**Comment by romanimm** [comment] 2017-04-16 15:13
Hi,
Same issue here. Downgraded these packages:
x265 (2.3-1 -> 2.2-1)
libdrm (2.4.79-1 -> 2.4.78-1)
libva (1.8.1-1 -> 1.7.3-2)
libass (0.13.6-1 -> 0.13.4-1)
libbluray (1.0.0-1 -> 0.9.3.r84.05c9fdec-1)
downgraded ffmpeg (1:3.3-1 -> 1:3.2.4-1)
downgraded ffmpeg2.8 (2.8.11-2 -> 2.8.11-1)
downgraded xine-lib (1.2.8-2 -> 1.2.8-1)
(maybe one too much)

The versions on the right work.

**Comment by romanimm** [comment] 2017-05-12 08:20
Hi @alcinos 

I think this was a problem from archlinux and got fixed in the meantime.

**Closed** 2017-05-24 23:32 UTC
Labels: incomplete
