### ISSUE TITLE
CAFFE USING OPEN CV :  ERROR  IN <module>  detections = net.forward() cv2.error: OpenCV(3.4.2) C:\projects\opencv-python\opencv\modules\dnn\src\dnn.cpp:431: error: (-215:Assertion failed) inputs.size() == requiredOutputs in function 'cv::dnn::experimental_dnn_v5::DataLayer::getMemoryShapes'

### ISSUE THREAD

**Issue by AnmaTech** [opencv/opencv#12177] opened 2018-08-08 05:14 UTC
dear friends;

I am running a pretrained Caffe Model using OPEN CV module named "cv2.dnn.readNetFromCaffe", but
I have these error}.

"Traceback (most recent call last):
  File "C:\Users\CIDRHI04\Documents\DISCO DURO\LAS\CV\Open_Cv_Caffe\Prueba\Caffe_2.py", line 36, in <module>
    detections = net.forward()
cv2.error: OpenCV(3.4.2) C:\projects\opencv-python\opencv\modules\dnn\src\dnn.cpp:431: error: (-215:Assertion failed) inputs.size() == requiredOutputs in function 'cv::dnn::experimental_dnn_v5::DataLayer::getMemoryShapes'

My PYTHON code:

```python
# import the necessary packages
from imutils.video import VideoStream
from imutils.video import FPS
import numpy as np
import argparse
import imutils
import time
import cv2


# load the input image from disk
image = cv2.imread("horse.jpg")

model = "model_iter_70000.caffemodel"
prototxt = "deploy.prototxt"


# initialize the list of class labels 
CLASSES = [' royal tennis', ' cricket', ' field hockey', ' water sport', ' croquet', ' Greco-Roman wrestling', ' fishing', ' stickball', ' overcast', ' spar', ' polo', ' fly-fishing', ' outdoor game', ' no-hit game', ' singles', ' ducking', ' outdoor sport', ' athletic game', ' auto racing', ' high jump', ' horse racing', ' roller skating', ' ice skating', ' fight', ' showjumping', ' court game', ' dip', ' badminton', ' sledding', ' professional basketball', ' cycling', ' golf', ' skiing', ' scuba diving', ' riding', ' doubles', ' soccer', ' funambulism', ' casting', ' round of golf', ' bathe', ' wrestling', ' floating', ' shuffleboard', ' dive', ' pony-trekking', ' boat racing', ' rollerblading', ' miniature golf', ' beagling', ' judo', ' professional football', ' skating', ' doubles', ' four-hitter', ' bullfighting', ' team sport', ' figure skating', ' professional baseball', ' coursing', ' hurling', ' American football', ' skin diving', ' greyhound racing', ' singles', ' camel racing', ' hydroplane racing', ' hunt', ' sculling', ' two-hitter', ' football', ' contact sport', ' cockfighting', ' surf casting', ' swimming', ' fox hunting', ' three-hitter', ' squash', ' track and field', ' netball', ' professional tennis', ' day game', ' water-skiing', ' ice hockey', ' skateboarding', ' boxing', ' cross-country riding', ' jai alai', ' luging', ' deer hunting', ' tetherball', ' quoits', ' ball', ' sumo', ' rugby', ' tennis', ' professional golf', ' water polo', ' ski jumping', ' racing', ' gymnastics', ' sport', ' cross-country skiing', ' piaffe', ' motorcycling', ' dressage', ' battledore', ' snorkeling', ' softball', ' match play', ' fly casting', ' volleyball', ' ball game', ' professional boxing', ' troll', ' basketball', ' angling', ' archery', ' broad jump', ' cliff diving', ' professional wrestling', ' rock climbing', ' equestrian sport', ' baseball', ' shinny', ' track', ' speed skating', ' rowing', ' tobogganing', ' bobsledding', ' perfect game', ' medal play', ' touch football', ' acrobatics', ' three-day event', ' field game', ' lacrosse', ' handball', ' racquetball', ' flip', ' pallone', ' bicycling', ' surfing', ' real tennis', ' hockey', ' aquatics', ' sportfishing', ' stickball game', ' sparring', ' no-hitter', ' duck hunting', ' field sport', ' car racing', ' stadium jumping', ' plunge', ' golf game', ' horseback riding', ' association football', ' tightrope walking', ' cast', ' round', ' rassling', ' natation', ' shovelboard', ' diving', ' 4-hitter', ' tauromachy', ' American football game', ' skin-dive', ' hunting', ' 2-hitter', ' football game', ' surf fishing', ' swim', ' foxhunt', ' 3-hitter', ' squash racquets', ' hockey', ' pugilism', ' cross-country jumping', ' pelota', ' deer hunt', ' horseshoes', ' rugby football', ' lawn tennis', ' gymnastic exercise', ' athletics', ' battledore and shuttlecock', ' snorkel diving', ' softball game', ' volleyball game', ' ballgame', ' trolling', ' basketball game', ' long jump', ' baseball game', ' shinney', ' running', ' row', ' stroke play', ' tumbling', ' surfboarding', ' real tennis', ' hockey', ' aquatics', ' sportfishing', ' stickball game', ' sparring', ' no-hitter', ' duck hunting', ' field sport', ' car racing', ' stadium jumping', ' plunge', ' golf game', ' horseback riding', ' association football', ' tightrope walking', ' cast', ' round', ' rassling', ' natation', ' shovelboard', ' diving', ' 4-hitter', ' tauromachy', ' American football game', ' skin-dive', ' hunting', ' 2-hitter', ' football game', ' surf fishing', ' swim', ' foxhunt', ' 3-hitter', ' squash racquets', ' hockey', ' pugilism', ' cross-country jumping', ' pelota', ' deer hunt', ' horseshoes', ' rugby football', ' lawn tennis', ' gymnastic exercise', ' athletics', ' battledore and shuttlecock', ' snorkel diving', ' softball game', ' volleyball game', ' ballgame', ' trolling', ' basketball game', ' long jump', ' baseball game', ' shinney', ' running', ' row', ' stroke play', ' tumbling', ' surfboarding', ' court tennis', ' equitation', ' grappling', ' squash rackets', ' hockey game', ' fisticuffs', ' rugger', ' hoops', ' surfriding']
COLORS = np.random.uniform(0, 255, size=(len(CLASSES), 3))


# load our serialized model from disk
##print("[INFO] loading model...")
net = cv2.dnn.readNetFromCaffe(prototxt, model)
(h, w) = image.shape[:2]
blob = cv2.dnn.blobFromImage(cv2.resize(image, (300, 300)), 0.007843,
        (300, 300), 127.5)
# pass the blob through the network and obtain the detections and
# predictions
#print("[INFO] computing object detections...")
net.setInput(blob)
detections = net.forward()

# loop over the detections
for i in np.arange(0, detections.shape[2]):
        # extract the confidence (i.e., probability) associated with the
        # prediction
        confidence = detections[0, 0, i, 2]         
        # filter out weak detections by ensuring the `confidence` is
        # greater than the minimum confidence
        if confidence > 0.1:                        
                # extract the index of the class label from the `detections`,
                # then compute the (x, y)-coordinates of the bounding box for
                # the object
                idx = int(detections[0, 0, i, 1])
                box = detections[0, 0, i, 3:7] * np.array([w, h, w, h])
                (startX, startY, endX, endY) = box.astype("int")
                # display the prediction                        
                label = "{}: {:.2f}%".format(CLASSES[idx], confidence * 100)
                #print("[INFO] {}".format(label))
                cv2.rectangle(image, (startX, startY), (endX, endY),
                        COLORS[idx], 1)
                y = startY - 15 if startY - 15 > 15 else startY + 15
                cv2.putText(image, label, (startX, y),
                       cv2.FONT_HERSHEY_SIMPLEX, 0.4, COLORS[idx], 1)                                   


        ### show the output image
        cv2.namedWindow("image", cv2.WINDOW_NORMAL)
        cv2.imshow("image", image)
        if cv2.waitKey(1) >= 0:  # Break with ESC 
                break
```

My files:

Python code:
https://drive.google.com/file/d/1zGc-ECW9VJ65xodSioYlpIDqmKkBGJwl/view?usp=sharing

model_iter_70000.caffemodel
https://drive.google.com/file/d/1ii4gmDcxCAvYfIc1ZbkLFT_nRMdMRV5h/view?usp=sharing

image
https://drive.google.com/open?id=1Bx055wj_34U_62TxoYJprJdomf-B4GD2

classes:
https://drive.google.com/open?id=1lgm2PNGhMDorbGbi6NijpAF8J9-NSwPF

deployproto.txt 
https://drive.google.com/file/d/1f2GARJqCepe_MgsiBHixowasmSWNY68A/view?usp=sharing

Thanks

**Comment by dkurt** [comment] 2018-08-08 06:41
@AnmaTech, Do you know that mentioned model is not object detection model?

**Comment by AnmaTech** [comment] 2018-08-09 15:42
Sorry  Dmitry,  you right. First , I want to thanks your soon response and your big help for me. I appreciate that so much.

I am trying load a pretrainned model using cv2.dnn.readNetFromCaffe(prototxtFile, modelFile), and have difficulties finetuning the models.

My goal is to use Caffe pretrained models for the analysis of sports videos. 

I can not find an easy procedure to train models using (Opencv-Python-Caffe), to obtain my own (prototxt and caffemodel)

These pre trainned model was downloaded from https://www.deepdetect.com/applications/model/
Each  detection package have the next files:
	corresp.txt
	deploy.prototxt
	final.json
	googlenet.prototxt
	googlenet_solver.prototxt
	mean.binaryproto
	model.json
	model_iter_70000.caffemodel
	model_iter_70000.solverstate

**Comment by dkurt** [comment] 2018-08-09 16:08
@AnmaTech, please use http://answers.opencv.org to get help with OpenCV usage. This is a tracker for bug reports and feature requests.

You may also check [OpenCV's deep learning module tutorials](https://docs.opencv.org/master/d2/d58/tutorial_table_of_content_dnn.html) and [samples](https://github.com/opencv/opencv/tree/master/samples/dnn).

**Comment by dkurt** [comment] 2018-08-23 16:07
@AnmaTech, you may make work this model in OpenCV by replacing
```yaml
layer {
  name: "googlenet"
  type: "MemoryData"
  top: "data"
  top: "label"
  memory_data_param {
    batch_size: 32
    channels: 3
    height: 224
    width: 224
  }
}
```
to
```yaml
input: "data"
input_dim: 1
input_dim: 3
input_dim: 224
input_dim: 224
```
Can we close this issue?

**Comment by AnmaTech** [comment] 2018-08-23 20:33
Sure, Sorry for the delay, I will try to make those changes in the files

Thank you so much..

Dr. Esp. Ing. Luis Sánchez R.

Doctor en Ciencias Técnicas (Ing. Hidráulica).
Jefe del Centro de Investigaciones de Recursos Hídricos CIDRHI



Web oficial : http://drluisalejandrosanchez.blogspot.com/
Portal Cursos pregrado:
https://sites.google.com/site/hidroingcilvil/clases/obras-hidraulicas/dr-phd-ing-luis-sanchez
 

    El jueves, 23 de agosto de 2018 12:09:12 p. m. GMT-4, Dmitry Kurtaev <notifications@github.com> escribió:  
 
 
@AnmaTech, you may make work this model in OpenCV by replacing
layer {
  name: "googlenet"
  type: "MemoryData"
  top: "data"
  top: "label"
  memory_data_param {
    batch_size: 32
    channels: 3
    height: 224
    width: 224
  }
}
to
input: "data"
input_dim: 1
input_dim: 3
input_dim: 224
input_dim: 224
Can we close this issue?

**Closed** 2018-08-24 06:02 UTC
Labels: category: dnn

**Comment by RBNadekar** [comment] 2018-11-24 07:11
@dkurt 
    detections = net.forward()

error: OpenCV(3.4.3) C:\projects\opencv-python\opencv\modules\dnn\src\dnn.cpp:565: error: (-215:Assertion failed) inputs.size() == requiredOutputs in function 'cv::dnn::experimental_dnn_34_v7::DataLayer::getMemoryShapes'

i got this error 
i am creating my own model i am create it successfully but when i use that model in python to detect the object it give above error here i am attaching my file


[real-time-object-detection.zip](https://github.com/opencv/opencv/files/2612054/real-time-object-detection.zip)

**Comment by soufianesabiri** [comment] 2019-03-11 10:37
I have same error: ` inputs.size() == requiredOutputs in function 'cv::dnn::experimental_dnn_34_v7::DataLayer::getMemoryShapes'`

Please help if you found a solution... Thanks!

**Comment by danyfang** [comment] 2019-03-15 09:22
For tensorflow the problem is likely caused by the wrong '.pbtxt' file and there is a solution answered by me [here](https://stackoverflow.com/questions/55158339/tensorflow-pb-and-pbtxt-files-dont-work-with-opencv-after-retraining-mobilenet/55168444#55168444). For tensorflow model there are two different methods of reusing the pretrained model and there is an official tutorial[ here](https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API). 

As for Caffe model, I suppose the problem is also because the unmatch between '.caffemodel' and '.prototxt' but I cannot confirm this.

**Comment by vikramreddy0307** [comment] 2019-10-16 05:35
I am getting the error if I am trying to convert the below-mentioned code.
layer {
  name: "data"
  #type: "OnDiskData"
  top: "data"
  input_param { shape: { dim: 1 dim: 1 dim: 32 dim: 32 } }
  #data_param { source: "/home/busta/data/SynthText/train_icdar.txt" }
  top: "gt_boxes"
  top: "gt_labels"
  top: "line_boxes"
  top: "line_labels"
}


to
input: "data"
input_dim: 1
input_dim: 1
input_dim: 32
input_dim: 32
 Help me out with this.

Thanks

**Comment by databaaz** [comment] 2019-12-29 09:54
I am getting the same error
`OpenCV(4.1.2) /build/master_pack-android/opencv/modules/dnn/src/dnn.cpp:693: error: (-215:Assertion failed) inputs.size() == requiredOutputs in function 'getMemoryShapes'`
when I try to load an ONNX model and run `forward()` on it.

The problem is it's working well on desktop CPP but is failing when run in Android through JNI for CPP
The same exact code is giving 2 distinct behaviour on desktop and mobile.

**Comment by databaaz** [comment] 2019-12-29 10:54
> I am getting the same error
> `OpenCV(4.1.2) /build/master_pack-android/opencv/modules/dnn/src/dnn.cpp:693: error: (-215:Assertion failed) inputs.size() == requiredOutputs in function 'getMemoryShapes'`
> when I try to load an ONNX model and run `forward()` on it.
> 
> The problem is it's working well on desktop CPP but is failing when run in Android through JNI for CPP
> The same exact code is giving 2 distinct behaviour on desktop and mobile.

I figured out, there was an issue with my C++ code, there's no problem in OpenCV DNN forward() method

**Comment by subzeromot** [comment] 2020-04-04 05:37
> > I am getting the same error
> > `OpenCV(4.1.2) /build/master_pack-android/opencv/modules/dnn/src/dnn.cpp:693: error: (-215:Assertion failed) inputs.size() == requiredOutputs in function 'getMemoryShapes'`
> > when I try to load an ONNX model and run `forward()` on it.
> > The problem is it's working well on desktop CPP but is failing when run in Android through JNI for CPP
> > The same exact code is giving 2 distinct behaviour on desktop and mobile.
> 
> I figured out, there was an issue with my C++ code, there's no problem in OpenCV DNN forward() method

how you fix this, pls?
