### ISSUE TITLE
 In the opencv installation process on Ubuntu 16.04,  Error occurs after "make" command is typed in.

### ISSUE THREAD

**Issue by zengletian1491** [opencv/opencv#15818] opened 2019-10-31 10:45 UTC
In the opencv installation process on Ubuntu 16.04,  Error occurs after "make" command is typed in. The report is in the following:

/home/kangyun/Software/opencv/opencv_contrib-master/modules/xfeatures2d/test/test_features2d.cpp:51:10: fatal error: features2d/test/test_detectors_regression.impl.hpp: No such file or directory
 **#include "features2d/test/test_detectors_regression.impl.hpp"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.**
modules/xfeatures2d/CMakeFiles/opencv_test_xfeatures2d.dir/build.make:75: recipe for target 'modules/xfeatures2d/CMakeFiles/opencv_test_xfeatures2d.dir/test/test_features2d.cpp.o' failed
make[2]: *** [modules/xfeatures2d/CMakeFiles/opencv_test_xfeatures2d.dir/test/test_features2d.cpp.o] Error 1
CMakeFiles/Makefile2:5806: recipe for target 'modules/xfeatures2d/CMakeFiles/opencv_test_xfeatures2d.dir/all' failed
make[1]: *** [modules/xfeatures2d/CMakeFiles/opencv_test_xfeatures2d.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

Would you please give me a hand? Thanks very much!

**Comment by alalek** [comment] 2019-10-31 10:52
duplicate of https://github.com/opencv/opencv_contrib/issues/1950
(Feel free to provide additional information for issue investigation)

**Closed by alalek** 2019-10-31 10:52 UTC
Labels: duplicate
