### ISSUE TITLE
OpenCV 3.1 - Upper body detection not working in any example

### ISSUE THREAD

**Issue by ontheronix** [opencv/opencv#6695] opened 2016-06-17 13:42 UTC
My problem: no upper bodies are being detected when using **haarcascade_profileface.xml** or **haarcascade_mcs_profileface.xml**.

Software used: 
- print cv2._ _version__  yields 3.0.0 although the x86 version (cv2.pyd) of OpenCV 3.1 is used
  I also tried with OpenCV 3.0 buth the problem persists.. Anybody?
- Python 2.7 x86
- Numpy 11.1.0 x86
- Eclipse x86
- Windows 7 x64

(I tried with all x64 version but the problem persists)

The following code is used:

```
    import numpy as np
    import cv2

    img = cv2.imread('723.jpg',0)

    upperBody_cascade = cv2.CascadeClassifier('haarcascade_upperbody.xml')    

    arrUpperBody = upperBody_cascade.detectMultiScale(img)
    if arrUpperBody != ():
            for (x,y,w,h) in arrUpperBody:
                cv2.rectangle(img,(x,y),(x+w,y+h),(255,0,0),2)
            print 'body found'

    cv2.imshow('image',img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
```

Result: no upper bodies detected:
![Result: no upper bodies detected](http://pic80.picturetrail.com/VOL952/7205667/23849157/412575810.jpg)

Using haarcascade _mcs_upperbody.xml also yields NO detection. 

When other haarcascades (eye, nose, mouth, face_default) are used, detection works fine. (And similar code using a webcam stream shows the same behaviour)
![Result with HAAR facecascade](http://pic80.picturetrail.com/VOL952/7205667/23849157/412575809.jpg)

Does anyone have an idea what can be the issue here? 

cv2.getBuildInformation:

```
 videoio: Removing WinRT API headers by default

General configuration for OpenCV 3.0.0 =====================================
  Version control:               3.0.0

  Platform:
    Host:                        Windows 6.1 AMD64
    CMake:                       2.8.11.2
    CMake generator:             Visual Studio 12 Win64
    CMake build tool:            C:/PROGRA~2/MSBuild/12.0/Bin/MSBuild.exe
    MSVC:                        1800

  C/C++:
    Built as dynamic libs?:      NO
    C++ Compiler:                C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/x86_amd64/cl.exe  (ver 18.0.21005.1)
    C++ flags (Release):         /DWIN32 /D_WINDOWS /W4 /GR /EHa  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /wd4251 /wd4324 /MP4  /MT /O2 /Ob2 /D NDEBUG  /Zi
    C++ flags (Debug):           /DWIN32 /D_WINDOWS /W4 /GR /EHa  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /wd4251 /wd4324 /MP4  /D_DEBUG /MTd /Zi /Ob0 /Od /RTC1 
    C Compiler:                  C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/x86_amd64/cl.exe
    C flags (Release):           /DWIN32 /D_WINDOWS /W3  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi    /MP4  /MT /O2 /Ob2 /D NDEBUG  /Zi
    C flags (Debug):             /DWIN32 /D_WINDOWS /W3  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi    /MP4  /D_DEBUG /MTd /Zi /Ob0 /Od /RTC1 
    Linker flags (Release):      /machine:x64   /NODEFAULTLIB:atlthunk.lib /NODEFAULTLIB:msvcrt.lib /NODEFAULTLIB:msvcrtd.lib /INCREMENTAL:NO  /debug /NODEFAULTLIB:libcmtd.lib
    Linker flags (Debug):        /machine:x64   /NODEFAULTLIB:atlthunk.lib /NODEFAULTLIB:msvcrt.lib /NODEFAULTLIB:msvcrtd.lib /debug /INCREMENTAL  /NODEFAULTLIB:libcmt.lib
    Precompiled headers:         YES
    Extra dependencies:
    3rdparty dependencies:       ippicv

  OpenCV modules:
    To be built:                 hal core flann imgproc ml photo video imgcodecs shape videoio highgui objdetect superres ts features2d calib3d java stitching videostab python2
    Disabled:                    world
    Disabled by dependency:      -
    Unavailable:                 cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev python3 viz

  Windows RT support:            NO

  GUI: 
    QT:                          NO
    Win32 UI:                    YES
    OpenGL support:              NO
    VTK support:                 NO

  Media I/O: 
    ZLib:                        build (ver 1.2.8)
    JPEG:                        build (ver 90)
    WEBP:                        build (ver 0.3.1)
    PNG:                         build (ver 1.5.12)
    TIFF:                        build (ver 42 - 4.0.2)
    JPEG 2000:                   build (ver 1.900.1)
    OpenEXR:                     build (ver 1.7.1)
    GDAL:                        NO

  Video I/O:
    Video for Windows:           YES
    DC1394 1.x:                  NO
    DC1394 2.x:                  NO
    FFMPEG:                      YES (prebuilt binaries)
      codec:                     YES (ver 55.18.102)
      format:                    YES (ver 55.12.100)
      util:                      YES (ver 52.38.100)
      swscale:                   YES (ver 2.3.100)
      resample:                  NO
      gentoo-style:              YES
    OpenNI:                      NO
    OpenNI PrimeSensor Modules:  NO
    OpenNI2:                     NO
    PvAPI:                       NO
    GigEVisionSDK:               NO
    DirectShow:                  YES
    Media Foundation:            NO
    XIMEA:                       NO
    Intel PerC:                  NO

  Other third-party libraries:
    Use IPP:                     8.2.1 [8.2.1]
         at:                     C:/builds/master_PackSlaveAddon-win64-vc12-static/opencv/3rdparty/ippicv/unpack/ippicv_win
    Use IPP Async:               NO
    Use Eigen:                   NO
    Use TBB:                     NO
    Use OpenMP:                  NO
    Use GCD                      NO
    Use Concurrency              YES
    Use C=:                      NO
    Use pthreads for parallel for:
                                 NO
    Use Cuda:                    NO
    Use OpenCL:                  YES

  OpenCL:
    Version:                     dynamic
    Include path:                C:/builds/master_PackSlaveAddon-win64-vc12-static/opencv/3rdparty/include/opencl/1.2 C:/Program Files (x86)/AMD/clAmdFft/include C:/Program Files (x86)/AMD/clAmdBlas/include
    Use AMDFFT:                  YES
    Use AMDBLAS:                 YES

  Python 2:
    Interpreter:                 c:/python27-x64/python.exe (ver 2.7.5)
    Libraries:                   C:/Python27-x64/Libs/python27.lib (ver 2.7.5)
    numpy:                       c:/python27-x64/lib/site-packages/numpy-1.8.0-py2.7-win-amd64.egg/numpy/core/include (ver 1.8.0)
    packages path:               c:/python27-x64/Lib/site-packages

  Python 3:
    Interpreter:                 NO

  Python (for build):            c:/python27-x64/python.exe

  Java:
    ant:                         C:/Program Files (x86)/apache-ant/bin/ant.bat (ver 1.9.2)
    JNI:                         C:/Program Files/Java/jdk1.6.0_45/include C:/Program Files/Java/jdk1.6.0_45/include/win32 C:/Program Files/Java/jdk1.6.0_45/include
    Java wrappers:               YES
    Java tests:                  NO

  Matlab:
    mex:                         NO

  Documentation:
    Doxygen:                     c:/utils/doxygen/doxygen.exe (ver 1.8.9.1)
    PlantUML:                    NO

  Tests and samples:
    Tests:                       NO
    Performance tests:           NO
    C/C++ Examples:              NO

  Install path:                  C:/builds/master_PackSlaveAddon-win64-vc12-static/build/install

  cvconfig.h is in:              C:/builds/master_PackSlaveAddon-win64-vc12-static/build/opencv_build
-----------------------------------------------------------------
```

**Comment by StevenPuttemans** [comment] 2016-06-28 07:17
Be sure to use the latest 2.4 or master branch! There have been tons of reported errors on those models that have been solved by now, due to wrong internal parameters.

**Comment by sovrasov** [comment] 2016-11-01 13:52
I suppose that the problem is related to 3.0 version.
At the latest master `haarcascade_upperbody` gives detection:
![image](https://cloud.githubusercontent.com/assets/5373517/19891891/3588a78c-a053-11e6-9f07-8adf4504cde5.png)
![image](https://cloud.githubusercontent.com/assets/5373517/19891898/3b6cc9c6-a053-11e6-88ff-f916232703a0.png)

**Comment by StevenPuttemans** [comment] 2016-11-03 09:39
Can we close this down ... all models had issues and the latest 2.4 and 3.x branch are working just fine. We cannot guarantee that old branches still do the same.

**Closed** 2016-11-03 18:03 UTC
Labels: bug, category: objdetect
