### ISSUE TITLE
Issues with cv::imencode (.jpg) on OpenCV 3.3.0 and Tegra TX2

### ISSUE THREAD

**Issue by 4sfaloth** [opencv/opencv#17344] opened 2020-05-21 15:57 UTC
Hi all,

First of all I'd like to state that I realize this issue will seem somewhat ill-defined, as unfortunately I've been unable to reproduce it with a simple code snippet. I just hope that my description might ring a bell on someone's mind that can help with finding/fixing this, as it is really driving me crazy.

Basically when running a complex application I am getting errors in libjpg when calling cv::imencode with ".jpg" extension. Basically it's a function doing
```
std::vector<uchar> compressed;
cv::imencode(".jpg", input, compressed);
```

where `input` is an input image passed by const reference to the method. It also crashes if I try to do an `cv::imread` or `cv::imwrite` (with ".jpg" extension) inside that method. Using other extensions works without any issues. The strangest thing is, I made a unit test for that method and it worked without any issue. Following that up I found that if I called that method or performed any `imread`/`imwrite` for .jpg right at the beginning of main() it would work without any issues, both for that first call and for all others. So basically my program runs as long as I do a `imread`/`imwrite`/`imencode` for .jpg right at the beginning.

The error message varies a bit but it seems consistently related to some access violation in libnvjpg (see attachment).

![error_message](https://user-images.githubusercontent.com/8202087/82577643-2ca12200-9b83-11ea-8f6a-46f990fba3a6.PNG)

I haven't tested this in most recent OpenCV versions because this is running in a very particular software image and it wouldn't be easy at all to update OpenCV.

Any help would be greatly appreciated. Please let me know if any further data would be helpful in diagnosing this

Thanks in advance.

My setup:
- OpenCV => 3.3.0
- Operating System / Platform => Ubuntu 16.04.3 LTS (on a Jetson TX2)
- Compiler =>gcc 5.4.0 20160609

**Comment by mshabunin** [comment] 2020-05-21 17:05
Try to build debug version of your application and run it with valgrind to check for memory corruptions. For now it does not look like an issue in OpenCV.

**Comment by 4sfaloth** [comment] 2020-05-26 10:50
> Try to build debug version of your application and run it with valgrind to check for memory corruptions. For now it does not look like an issue in OpenCV.

Hi @mshabunin, thanks for taking the time to step in. I am sorry for taking so long to respond but I was trying to gather more information on this issue

I've build the debug version and run it with valgrind and it found no issues.  I've made many tests but overall the symptoms remain the same:
1.   If I use imencode (with .jpg extension) during normal execution, with crashes with an access violation like the above
2.   If I use imread (with .jpg extension) during normal execution, if fails and returns an empty image
3.  Both imencode and imread function correctly during normal execution with .bmp extension
4.  Making a imread or imencode, with .jpg extension, at the beginning of the program works. Not only that, it seems to fix the issue since the program then executes normally (performing imencode with .jpg extension)

**Comment by mshabunin** [comment] 2020-05-26 12:07
Are you using OpenCV from the NVIDIA JetPack? I'd suggest reporting the issue to the official forum.

There is a chance we can help only if you:
* provide short reproducer application
* provide full gdb stack trace
* test whether the issue can be reproduced with recent OpenCV version from _3.4_ or _master_ branch

Currently it looks like a crash in one of system libraries (libnvjpeg.so), so I'm closing this issue. Feel free to reopen if you have an evidence that the problem originates in OpenCV.

**Closed by mshabunin** 2020-05-26 12:07 UTC
Labels: incomplete
