### ISSUE TITLE
Portrait mode issue with javacameraview

### ISSUE THREAD

**Issue by sureshkona** [opencv/opencv#8281] opened 2017-02-27 09:52 UTC
I am able to see the landscape mode properly but portrait mode also showing preview as 
landscape mode.

I am doing camera frames processing dynamically.

##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

**Comment by alalek** [comment] 2017-02-27 10:58
Duplicate of #4704

**Closed by alalek** 2017-02-27 10:58 UTC
Labels: duplicate

**Comment by sureshkona** [comment] 2017-03-02 06:32
Hi alalek,

I am able to see the preview as portrait but it was saved as landscape only.
Please see the below code...

 protected Size calculateCameraFrameSize(List<?> supportedSizes, ListItemAccessor accessor, int surfaceWidth, int surfaceHeight) {
        int calcWidth = 0;
        int calcHeight = 0;

// I added additionally the following code for portrait

        **if(surfaceHeight > surfaceWidth){
            int temp = surfaceHeight;
            surfaceHeight = surfaceWidth;
            surfaceWidth = temp;
        }**
.......    ......

}

and 
 protected void deliverAndDrawFrame(CvCameraViewFrame frame) {

-----------
 if (mScale != 0) {

 if(canvas.getWidth() > canvas.getHeight()) {
// full screen for Landscape mode....
canvas.drawBitmap(mCacheBitmap, new Rect(0,0,mCacheBitmap.getWidth(), mCacheBitmap.getHeight()),
                                new Rect((int)(0),(int)(0),(int)(canvas.getWidth()),(int)(canvas.getHeight())), null);

  } else {
canvas.drawBitmap(mCacheBitmap, rotateMe(width_Canvas,height_Canvas,width,height), null);
}

 private Matrix rotateMe(int width_canvas,int height_canvas ,int bm_width,int bm_height) {
        // TODO Auto-generated method stub
        Matrix mtx=new Matrix();
        float scale = (float) width_canvas / (float) bm_height;
        mtx.preTranslate((width_canvas - bm_width)/2, (height_canvas - bm_height)/2);
        mtx.postRotate(90,width_canvas/2, height_canvas/2);
        mtx.postScale(scale, scale, width_canvas/2 , height_canvas/2 );
        return mtx;
    }
 
The above code showing the preview as portrait but it is saved in the device as landscape. that means if set into the imageview as bitmap then it display as landscape.

I think we are not rotating the camera based on orientation. like native camera.

please help me. how to change the actual preview based on orientation.
