### ISSUE TITLE
Python: Pyramids not working for calcOpticalFlowPyrLK	

### ISSUE THREAD

**Issue by jahdiel** [opencv/opencv#7236] opened 2016-09-05 15:44 UTC
##### System information (version)
- OpenCV => 3.1-dev
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015
##### Detailed description

When trying to run pyramids as the input for the cv2.calcOpticalFlowPyrLK    function the program gives out an error. when I run the cv2.buildOpticalFlowPyramid method it returns a pyramid, without any errors but as soon as I use it as input it doesn't run. 
##### Steps to reproduce

```
lk_params = dict(winSize=(21, 21),  # Parameters used for cv2.calcOpticalFlowPyrLK (KLT tracker)
             maxLevel=3,
             criteria=(cv2.TERM_CRITERIA_EPS | cv2.TERM_CRITERIA_COUNT, 30, 0.01))

def KLT_featureTracking(image_ref, image_cur, px_ref):

    image_ref = cv2.buildOpticalFlowPyramid(image_ref, (512, 512), 2)
    image_cur = cv2.buildOpticalFlowPyramid(image_cur, (512, 512), 2)

    kp2, st, err = cv2.calcOpticalFlowPyrLK(image_ref, image_cur, px_ref, None, **lk_params)
    kp1, st, err = cv2.calcOpticalFlowPyrLK(image_cur, image_ref, kp2, None, **lk_params)
```

Error:

```
kp2, st, err = cv2.calcOpticalFlowPyrLK(image_ref, image_cur, px_ref, None, **lk_params)
TypeError: prevImg is not a numerical tuple
```

**Comment by mshabunin** [comment] 2016-09-08 14:47
`cv2.buildOpticalFlowPyramid` returns tuple with two elements: `(number_of_levels, pyramid)`
Try to pass second tuple element to _calcopticalFlowPyrLK_.

**Comment by mshabunin** [comment] 2016-09-08 14:57
Here is the result of `help(cv2.buildOpticalFlowPyramid)`:
```
buildOpticalFlowPyramid(img, winSize, maxLevel[, pyramid[, withDerivatives[, pyrBorder[, derivBorder[, tryReuseInputImage]]]]]) -> retval, pyramid
```

**Comment by jahdiel** [comment] 2016-09-28 23:12
Thanks for the correction but it still it doesn't work. Now it produces an error with the format of the pyramid. I verified the **type(image_ref)** and prints our **type list**. I have tried to change it to a np.array but it still produces errors. I would greatly appreciate comments. 

# Code 

    ret, image_ref = cv2.buildOpticalFlowPyramid(image_ref, (512, 512), 2)
    ret, image_cur = cv2.buildOpticalFlowPyramid(image_cur, (512, 512), 2)

    # Feature Correspondence with Backtracking Check
    kp2, st, err = cv2.calcOpticalFlowPyrLK(image_ref, image_cur, px_ref, None, **lk_params)
    kp1, st, err = cv2.calcOpticalFlowPyrLK(image_cur, image_ref, kp2, None, **lk_params)

# Error

    kp2, st, err = cv2.calcOpticalFlowPyrLK(image_ref, image_cur, px_ref, None, **lk_params)
    TypeError: prevImg is not a numpy array, neither a scalar

**Comment by headdab** [comment] 2018-03-21 17:16
Any progress on this?  When processing video, e.g., the same pyramid has to be computed twice.
Would be great no to have to do this.

**Comment by glenn-jocher** [comment] 2018-04-01 16:51
I currently see the same issue when passing a cv2.buildOpticalFlowPyramid pyramid into cv2.calcOpticalFlowPyrLK. Forward-backward tracking is thus computationally wasteful, forcing a computating of the image pyramids twice.

**Comment by alalek** [comment] 2018-04-25 16:11
Duplicate of #4777

**Closed by alalek** 2018-04-25 16:11 UTC
Labels: category: python bindings, category: video, duplicate

**Comment by hiteyoshi** [comment] 2018-07-31 02:18
same thing happened to me
