### ISSUE TITLE
Training cascade is too slow if all negative files are small pictures. 

### ISSUE THREAD

**Issue by qinjian623** [opencv/opencv#5999] opened 2016-01-20 16:00 UTC
Before training cascade, all positive files are transformed into a single vec file, but negative files are still spread on disk.

If there are many small negative files(millions), training will be very slow. The program can't sample many negative samples from one negative file, so it keep reading all small files from disk. But the disk and file system can't afford the cost of reading many small files. IO becomes the bottleneck of training speed.

Is it possible to transform or concat all negative files into one big file before training (just like positives)?

**Comment by teng88** [comment] 2016-01-20 16:13
For a 20 stages classifier with 1e4 negatives and FA=0.5 for each stage, winSize = 20x20,
we need 1e4 * 1e6 * 400 Byte = 4000 GB storage

**Comment by qinjian623** [comment] 2016-01-20 16:21
hi, @teng88 
If we have 1e4 negatives, then we only need 1e4 * 400Byte ( if every sample is 400Byte) storage.

I think the storage is nothing with the FA or stage number (maybe I'm wrong).

**Comment by teng88** [comment] 2016-01-20 16:28
To fill 1 negative in the 20th stage, since the FA has reached 0.5^20, 1e6 samples will be traversed.

**Comment by qinjian623** [comment] 2016-01-20 16:35
Yes, but all negative is still 1e4. 
In fact, I have trained a model with 2 million negatives. 
To avoid the bottleneck, I moved all negatives into a 7 GB ramfs on linux.

But if I want to increase the negatives to 20 million, 70 GB ram is not a easy option.

**Comment by teng88** [comment] 2016-01-20 16:43
1. The final filled negatives for each stage is 1e4, that's true.
2. Could you please provide some data about how ramfs helps the training time, this sounds reasonable, thanks!

**Comment by qinjian623** [comment] 2016-01-20 16:58
When a new training stage starts, the program need to sample some negatives( default value is 1000) from all negatives (that is the traversing you mentioned).
And the bottleneck happens here. That needs to read a lot of small files from disk which is really a nightmare.

I didn't do a very strict experiment. 
But iotop shows speed of reading from disk is less than 300KB/s. 
Ramfs's IO speed is the same as reading/writing memory (so may be more than 500MB/s).

And I'm sure that traversing negative samples from ramfs is much faster than from disk.  But I don't have a 70GB memory. 

If all negatives are packed into one big file, I think the disk IO of reading would be 50~70MB/s(depends on disk) or even more than 150MB/s for SSD.

**Comment by teng88** [comment] 2016-01-20 17:19
So, your plan is to pack all negative files to a single file, while, I am telling to pack all traversed negative samples into a signle file. These are quite different.
According to current implementation of fill negative samples, I think your plan may help little in saving time. Because after a negative file is read, lots of samples are sampled from different scales of this image, and then processing the next negative file.
If all files are read into memory in advance (e.g. ramfs), there may be some improvement in training time.

**Comment by qinjian623** [comment] 2016-01-20 17:34
Maybe I should change the word sample to file. It's easy to misunderstand what I want to explain. And my negative files are all small size pictures. So can't sample many samples from one file, but read a new file from disk.

**Comment by teng88** [comment] 2016-01-21 00:28
In case negative file is as small as sample size, a negative file equals to a negative sample. Then you will need 1e10 files for a 20 stage classifier as I had analyzed. 1e4 is the number need to fill for each stage in my assumption, not the total number of negative files. In order to fill 1e4 negative samples, a total of 1e10 negative samples will be traversed.

**Comment by qinjian623** [comment] 2016-01-21 01:13
That's why I need more negatives, but disk is too slow and memory is too small. All negatives in one big file is the only choice to do a faster training.

**Comment by qinjian623** [comment] 2016-01-21 01:34
Hi, @alalek

Maybe I didn't express myself very clearly. So I modified the issue title and description.

I have a lot of small negative files. The trainer can get only one sample per negative file.
So it need to keep reading all files from disk. But disk is too slow to load small files. For example, to fill 1000 negative samples at 10th or 11th stages, it need more than one hour. 

I think if all negative files can be packed into one file (like positive files to one vec file), reading from disk will be much faster.

**Comment by alalek** [comment] 2016-01-21 04:35
1) Looks like traincascade uses "sliding window" approach to extract negative samples: https://github.com/Itseez/opencv/blob/3.1.0/apps/traincascade/imagestorage.cpp#L94-L118
Current preferred way to specify negatives via full-sized frames without objects of interest.

2) To follow approach with packing negatives from small files into set of large packed files you can try to adjust sliding window [parameters](https://github.com/Itseez/opencv/blob/3.1.0/apps/traincascade/imagestorage.cpp#L23-L26) and may be algorithm.

I can add "feature" label in mean of "support packed files with negatives". Also we don't have similar prepared databases to provide/integrate patch for this at this moment.

cc @vpisarev @StevenPuttemans Any ideas?

**Comment by StevenPuttemans** [comment] 2016-01-21 08:39
`to fill 1000 negative samples at 10th or 11th stages, it needs more than one hour.`

Okay I think that you are misunderstanding why the reading of negative files goes slow. It has nothing to do with the limited reading speed of all the small samples, but everything to do with the structure of a cascade classifier and the boosting process behind it.

What is happening here is that once you reach the 11th stage, the negative sample grabber tries to find 1000 unique negative samples that have NOT yet been classified as negatives by the 10 previous stages. As this chance of finding such an example decreases exponentially (this is the large benefit of cascade classifiers and the early rejection principle), it might be perfectly possible that the 11th stage needs to evaluate more than 100.000 random sliding window based negative samples to get those new 1000 samples, depending on how you set the FA parameter for each stage, just like @teng88 says.

The exact reason why all open source frameworks for cascade classifiers are using large images to sample negatives from is to avoid the IO bottleneck, but I have done the comparison and extracting all negative windows beforehand and training a model equally large like from large images takes about the same time. It was a difference of only 25 minutes on 17 hours of training...

As to creating a negative vec file, it is actually possible. I remember a discussion with a forum member about a year ago who used the positive vec file creation interface to replace the negative grabbing part. The ONLY reason why he and some others were doing that, is to be able to control beforehand WHICH samples are fed to the training, a bit identical to what I am doing, which is pushing hard negatives as single windows to the front of the file to bootstrap the detection model.

**Comment by StevenPuttemans** [comment] 2016-01-21 08:54
By the way, the time needed to create that vec file of millions of images or more, might take longer than the IO bottleneck. IO bottlenecks are mainly a concern when reading large files, not when reading small files.

**Comment by qinjian623** [comment] 2016-01-21 09:45
Hi @StevenPuttemans ,

When using large images to sample negatives, I think the speed will be ok. Reading one large image means thousands samples (all happens in memory).
But now I have only small negative files, because I don't have full-sized frames without objects of interest (that is impossible to have pure background for my task). Reading one image means only one candidate sample which is very possible classified as negative by previous stages. 

The training sped up after I moved the dataset into ramfs on Linux (main part of the speed up was negative sampling). So reading from disk has an influence on training speed when negative files are small pictures.

And the time creating a vec file is long, but when I try to train another model with the same dataset. The reading time of this second training is saved.

I think my concern comes from the fact that I only have small negative files. 
Maybe this is a very special case.

**Comment by StevenPuttemans** [comment] 2016-01-21 10:00
@qinjian623 

`When using large images to sample negatives, I think the speed will be ok. Reading one large image means thousands samples (all happens in memory).`

That is like I said only a VERY small part of the actual processing. The loading is nothing compared to the time consument of the stage comparison for new negative samples.

`The training sped up after I moved the dataset into ramfs on Linux (main part of the speed up was negative sampling). So reading from disk has an influence on training speed when negative files are small pictures.`

How much, could you present numbers, because as I said, on my hardware, a 32GB 8 core CPU, the difference is kind of expandable.

`And the time creating a vec file is long, but when I try to train another model with the same dataset. The reading time of this second training is saved.`

Again this depends. If for a single training you win 10 minutes of training time, but for creating the vec you need an hour, you can train 6 models without doing the extra work. Could you come up with absolute data?

`I think my concern comes from the fact that I only have small negative files.`

We all understand that, but I am still convinced that based on my measurements this is ignorable and not reproducable for 99.9% of the cases... could you give more insight in the used setup?

**Comment by qinjian623** [comment] 2016-01-21 11:03
@StevenPuttemans 
I did a small and not very strict experiment. Here is the setup and result:

===============
### Hardware and OS:
CPU: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
MEMORY: 16GB
OS: Ubuntu 15.04 (GNU/Linux 3.19.0-15-generic x86_64) 

===============
### Training parameters:
Copy the raw command from terminal.
+ OpenCV 3.1 with TBB
+ Using the same positive vec file (on disk )
+ To save time, number of stages is set to 15, and use LBP feature
+ 2000 pos vs 1000 neg per stage(same as default value) 
+ mode ALL is for HAAR, so I think this has no influence on training
+ These two ```neg.info``` both contain 1645852 lines 
+ /tmp/ramdisk0 is the ramfs

#### With ramfs
```
time bin/opencv_traincascade  -mode ALL -numPos 2000 -numNeg 1000 -data cascade_haar -vec pos.vec -bg /tmp/ramdisk0/negative/neg.info  -featureType LBP -w 30 -h 30 -numStages 15
```

#### With disk
```
time bin/opencv_traincascade  -mode ALL -numPos 2000 -numNeg 1000 -data cascade_haar -vec pos.vec -bg ~/xxxxxx_dataset/negative/neg.info  -featureType LBP -w 30 -h 30 -numStages 15
```
Sorry, I can't let you know the name of dataset. So replaced that with xxxxxx
 
===============
### Time

#### With ramfs
Finished all 15 stages. Last stage's acceptance ratio is 0.000566741(I think it almost consumed all my negative files).
```
real    2m52.163s
user    4m14.796s
sys     0m54.384s
```

#### With disk
Too slow, I had to kill the training when it finished the 5th stage. 
Last stage's acceptance ratio is 0.0910332 (only a very small part of negatives).
```
===== TRAINING 5-stage =====
<BEGIN
POS count : consumed   2000 : 2046
NEG cKilled samples: 127

real    9m24.758s
user    0m52.308s
sys     0m8.812s
```

#### Training time without negative sampling
Both are very fast. I can't tell you the exact time. 
But I'm pretty sure both are less than 1 min per stage.(In fact, you can see it took 52s to train 5 stages with disk, so avg should be 10s, more or less)

**Comment by StevenPuttemans** [comment] 2016-01-21 11:44
What do you mean with, training without negative sampling? If I get it correctly

With ramfs --> small images all pushed into some virtual memory from which they are read one by one
With disk --> small images all residing on the disk itself

But what is the last one then?

**Comment by StevenPuttemans** [comment] 2016-01-21 11:45
Also I do not have experience using ramfs so I am wondering what that does exactly...

**Comment by qinjian623** [comment] 2016-01-21 12:34
>  What do you mean with, training without negative sampling?

That's just to say, a big part of time is spent on negative sampling. Training cascade itself is very fast (because there are only 2000 pos and 1000 neg).

>  Also I do not have experience using ramfs so I am wondering what that does exactly...

It's a virtual file system. But actually all data is in memory. So reading and writing files in ramfs is as fast as reading and writing in memory, and if reboot, all data in ramfs will be lost.

The experiment above is very special:  
+ Must have many small negative files (in my case, 1.6million, 30x30 ~ 35x35 size pictures)
+ Can't sample many negatives from one file( in my case, almost only one sample per file)

**Comment by StevenPuttemans** [comment] 2016-10-13 13:34
I am wondering if we cannot close this down or add a feature request label? Basically this is a very specific case, one where I guess the only solution is that @qinjian623 creates a modified OpenCV source specifically for this issue. This is not generalizable for the larger community and thus not an addition I would make.

@alalek Can you close it down for now, we can always reopen if @qinjian623 resumes the discussion.

**Closed** 2016-10-13 13:47 UTC
Labels: question (invalid)

**Comment by zanazakaryaie** [comment] 2019-03-07 14:29
@qinjian623 
Could you please guide me how to put the negative images to ramfs?
