### ISSUE TITLE
Sporadic failure in the Linux x64 Debug builder with dnn tests

### ISSUE THREAD

**Issue by cv3d** [opencv/opencv#12734] opened 2018-10-03 14:27 UTC
##### Detailed description
Several builds (e.g. [this](http://pullrequest.opencv.org/buildbot/builders/precommit_linux64_no_opt/builds/17355) and [this](http://pullrequest.opencv.org/buildbot/builders/precommit_linux64_no_opt/builds/17347)) are failing, due to bad parsing of the test results..

##### Actual results
Failure with the following status:
```
test_dnn test_dnn ; cases (tests): 0 (0) ; passed: 695 ; failed 
```

##### Expected results
Success with the following status:
```
test_dnn test_dnn ; cases (tests): 60 (887) ; passed: 887 ; 
```

**Comment by alalek** [comment] 2018-10-03 15:01
Duplicate of #12710

**Closed by alalek** 2018-10-03 15:01 UTC
Labels: duplicate
