### ISSUE TITLE
Setting CAP_PROP_EXPOSURE on VideoCapture does not change anything

### ISSUE THREAD

**Issue by Arrowana** [opencv/opencv#9738] opened 2017-09-28 05:52 UTC
##### System information (version)
- OpenCV => 3.3.0
- Operating System / Platform => Windows 10 Enterprise 64 Bit
- Compiler => using opencv-python

##### Detailed description
Setting exposure is not working with the python wrapper for opencv, I don't know if this is related to the wrapper.

I tried to set CAP_PROP_AUTO_EXPOSURE as well to disable any auto exposure.

The camera is a HD USB Camera USB8MP02G
http://www.elpcctv.com/8mp-highdefinition-usb-camera-module-usb20-sony-imx179-color-cmos-sensor-75degree-lens-p-223.html

##### Steps to reproduce

I use this snippet to try to set the exposure to different values
```
import cv2

cap = cv2.VideoCapture(0)
cap.set(cv2.CAP_PROP_AUTO_EXPOSURE, 0)
cap.set(cv2.CAP_PROP_EXPOSURE, -7.0)
print(cap.get(cv2.CAP_PROP_EXPOSURE))
while True:
	ret, frame = cap.read()
	cv2.imshow('test', frame)
	cv2.waitKey(1)
```

I can't see any difference when changing exposure

**Comment by jj364** [comment] 2017-11-23 10:42
I've been having almost exactly the same problem using an ELP camera. I solved it by doing

`cap.set(cv2.CAP_PROP_AUTO_EXPOSURE, 0.25`

Then setting the exposure to what I needed. I believe that 0.25 is the value that CAP_PROP_AUTO_EXPOSURE needs to be to give you manual control.

I hope this helps!

**Comment by AriaPahlavan** [comment] 2018-03-23 04:27
Hi @Arrowana,

Were you able to resolve your issue? I am having the same problem when trying to set EXPOSURE, BRIGHTNESS or CONTRAST; None of these three properties seems to be changing on my [ ELP camera](https://www.amazon.com/ELP-Megapixel-Camera-Biometric-dual/dp/B00VG32EC2).

**Comment by ChenMyjob** [comment] 2018-09-12 03:04
@jj364 thanks，it works

**Comment by mayursadawana** [comment] 2018-12-03 17:00
Hi. I could make the camera work on manual mode now with auto exposure set on 0.25. But I can't put the Camera back on auto mode. I have tried setting 0 and 1 as the auto_exposure value, but no help. Can you please guide?

**Comment by hoerin** [comment] 2018-12-14 16:18
In my case, it works on Windows, but doesn't work on Mac.
Is there anyone who could set CAP_PROP_EXPOSURE and CAP_PROP_AUTO_EXPOSURE properties on Mac?

**Comment by mayursadawana** [comment] 2018-12-14 17:07
Hi hoerin,
The auto_exposure property should expect two values 0.75 as auto exposure On and 0.25 as auto exposure OFF. Once you set auto exposure Off with 0.25 then set exposure to any value that you desire. This is tested on Mac and Raspberry both.

**Comment by alalek** [comment] 2019-05-07 08:34
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
This tracker is for issues and bugs that needs fix in OpenCV.

---

> cap.set(...)

Always check returned values.

---

Properties availability/implementation/etc are backend-specific. So it is bad idea to use them without backend check.
To use V4L2 properties you should force backend via `CAP_V4L2` parameter.

---

> opencv-python

Check `cv.getBuildInformation()` at first for V4L2 availability:
```
python -c 'import cv2 as cv; print(cv.getBuildInformation())'
```

> 3.3.0

I believe it should be fixed in fresh OpenCV packages.

**Closed by alalek** 2019-05-07 08:34 UTC
Labels: category: videoio(camera), question (invalid tracker)

**Comment by ethanseow** [comment] 2020-02-17 04:39
I have encountered an issue with cap prop exposure for my specific camera, the logitech c270 webcam

So the problem is that when you set cap prop exposure the first time the camera is placed in, the exposure is not changed

To fix this issue call ret, frame = cap.read() before the cap exposure call

    cap = cv2.VideoCapture(0)
    # we capture the first frame for the camera to adjust itself to the exposure
    ret_val , cap_for_exposure = cap.read()

    cap.set(cv2.CAP_PROP_AUTO_EXPOSURE, 0.25)
    cap.set(cv2.CAP_PROP_EXPOSURE , -1)

I believe the reason for calling read before setting the exposure for it to work is because the camera needs to adjust and understand what it is seeing before adjusting the exposure, sort of like dipping your toes in a cold pool.

I may be completely wrong with my explanation, but I hope this helps anyone :)

**Comment by merlzbert** [comment] 2020-05-10 16:31
Has anyone got this running on Mac? I am not able switch of the autoexposure (tried both 0.25 and 0) and set exposure (neither range -13 - -1 or 0-1) it always returns 0.0. It seems that AVFoundation is not supporting exposure but only resolution and fps. With a linux machine and V4L it worked. Has anyone found a work around for iOS? Would highly appreciate!

**Comment by esitarski** [comment] 2020-06-15 18:37
I am willing to help out here.
I discovered that if you set Width/Height to large values, the camera will be reliably set to its largest resolution.  With this knowledge, I added a MAXxMAX feature to the resolution option.  That's as far as I got.

Controlling the other options is more difficult due to a lack of documentation of the opencv options.  I am not the only one [struggling](https://stackoverflow.com/questions/54365170/exposure-mode-opencv-4-0-1) with this.

Can someone point me to a page with the values for all the properties?  The full list is [here](https://vovkos.github.io/doxyrest-showcase/opencv/sphinx_rtd_theme/enum_cv_VideoCaptureProperties.html#details-d4-d15-group-videoio-flags-base-1gaeb8dd9c89c10a5c63c139bf7c4f5704d).
Help is much appreciated.

With regard to the examples,  if CAP_PROP_AUTO_EXPOSURE is 0.25 this means manual, 0.75 sets it to automatic.  Other values are ignored (I think).
CAP_PROP_EXPOSURE, takes a power of 2 seconds (I think).  So, in the first example, -7 means 2^-7 = 1/(2^7) = 1/128 sec.
In the second example, the value of -1 = 2^(-1) = 1/(2^1) = 1/2 sec.  That would be a very., very long exposure time and very blurry.  It would be consistent with 2 frames per second which is very choppy video.
It wouldn't surprise me that the camera reverted to some automatic default if it gets an unrealistic value.  Also not sure if values other than integers are accepted.

**Comment by seyoung-solteq** [comment] 2020-08-06 10:38
> I've been having almost exactly the same problem using an ELP camera. I solved it by doing
> 
> `cap.set(cv2.CAP_PROP_AUTO_EXPOSURE, 0.25)`
> 
> Then setting the exposure to what I needed. I believe that 0.25 is the value that CAP_PROP_AUTO_EXPOSURE needs to be to give you manual control.
> 
> I needed to set my exposure as an absolute value, 0.01 in my case, rather than using negative values. But that may be different for your camera.
> 
> I hope this helps!

@jj364 Could you elaborate how you found your solution? This would be useful information people facing issues with different cameras.

**Comment by jonasfrey** [comment] 2021-10-07 06:48
i think finally i found a solution, at least for my problem, 

```python
capture = cv2.VideoCapture(id)
capture.set(cv2.CAP_PROP_AUTO_EXPOSURE, 3) # auto mode
capture.set(cv2.CAP_PROP_AUTO_EXPOSURE, 1) # manual mode
capture.set(cv2.CAP_PROP_EXPOSURE, desired_exposure_value)

```
i have to first set the auto_exposure to 3 (auto mode) <br>
then i have to set it to 1 (manual mode) <br>
and then i can set the manual exposure

<br>

you can set the settings with shell too 
<br> 
list available options
```bash
video_id=1
v4l2-ctl --device /dev/video$video_id -l
```
<br> 
set them with python
<br>

```python
def set_manual_exposure(dev_video_id, exposure_time):
    commands = [
        ("v4l2-ctl --device /dev/video"+str(id)+" -c exposure_auto=3"),
        ("v4l2-ctl --device /dev/video"+str(id)+" -c exposure_auto=1"),
        ("v4l2-ctl --device /dev/video"+str(id)+" -c exposure_absolute="+str(exposure_time))
    ]
    for c in commands: 
        os.system(c)
# usage 
set_manual_exposure(1, 18)
```

**Comment by teddy-lu** [comment] 2021-12-06 02:31
> i think finally i found a solution, at least for my problem,
> 
> ```python
> capture = cv2.VideoCapture(id)
> capture.set(cv2.CAP_PROP_AUTO_EXPOSURE, 3) # auto mode
> capture.set(cv2.CAP_PROP_AUTO_EXPOSURE, 1) # manual mode
> capture.set(cv2.CAP_PROP_EXPOSURE, desired_exposure_value)
> ```
> 
> i have to first set the auto_exposure to 3 (auto mode) then i have to set it to 1 (manual mode) and then i can set the manual exposure
> 
> 
> you can set the settings with shell too list available options
> 
> ```shell
> video_id=1
> v4l2-ctl --device /dev/video$video_id --all
> ```
> 
> 
> set them with python
> ```python
> def set_manual_exposure(dev_video_id, exposure_time):
>     commands = [
>         ("v4l2-ctl --device /dev/video"+str(dev_video_id)+" -c exposure_auto=3"),
>         ("v4l2-ctl --device /dev/video"+str(dev_video_id)+" -c exposure_auto=1"),
>         ("v4l2-ctl --device /dev/video"+str(dev_video_id)+" -c exposure_absolute="+str(exposure_time))
>     ]
>     for c in commands: 
>         os.system(c)
> # usage 
> set_manual_exposure(1, 18)
> ```

Bravo！！！  this really work for me

**Comment by Taiinguyenn139** [comment] 2022-01-11 03:32
> I have encountered an issue with cap prop exposure for my specific camera, the logitech c270 webcam
> 
> So the problem is that when you set cap prop exposure the first time the camera is placed in, the exposure is not changed, but if you close the python code and rerun it, it works. Whenever you take the camera out and put it in again and run the code again, the exposure not being set property arises again.
> 
> To fix this issue call ret, frame = cap.read() before the cap exposure call
> 
> ```
> cap = cv2.VideoCapture(0)
> # we capture the first frame for the camera to adjust itself to the exposure
> ret_val , cap_for_exposure = cap.read()
> 
> cap.set(cv2.CAP_PROP_AUTO_EXPOSURE, 0.25)
> cap.set(cv2.CAP_PROP_EXPOSURE , -1)
> ```
> 
> I believe the reason for calling read before setting the exposure for it to work is because the camera needs to adjust and understand what it is seeing before adjusting the exposure, sort of like dipping your toes in a cold pool.
> 
> I may be completely wrong with my explanation, but I hope this helps anyone :)

This really work for my problem when I try to set focus value manually. Tks u so much!!!

**Comment by TalesDias** [comment] 2022-01-15 16:52
> i think finally i found a solution, at least for my problem,
> 
> ```python
> capture = cv2.VideoCapture(id)
> capture.set(cv2.CAP_PROP_AUTO_EXPOSURE, 3) # auto mode
> capture.set(cv2.CAP_PROP_AUTO_EXPOSURE, 1) # manual mode
> capture.set(cv2.CAP_PROP_EXPOSURE, desired_exposure_value)
> ```
> 
> i have to first set the auto_exposure to 3 (auto mode) then i have to set it to 1 (manual mode) and then i can set the manual exposure
> 
> you can set the settings with shell too list available options
> 
> ```shell
> video_id=1
> v4l2-ctl --device /dev/video$video_id --all
> ```
> 
> 
> set them with python
> 
> ```python
> def set_manual_exposure(dev_video_id, exposure_time):
>     commands = [
>         ("v4l2-ctl --device /dev/video"+str(dev_video_id)+" -c exposure_auto=3"),
>         ("v4l2-ctl --device /dev/video"+str(dev_video_id)+" -c exposure_auto=1"),
>         ("v4l2-ctl --device /dev/video"+str(dev_video_id)+" -c exposure_absolute="+str(exposure_time))
>     ]
>     for c in commands: 
>         os.system(c)
> # usage 
> set_manual_exposure(1, 18)
> ```

Worked for me too
Thanks a lot 💕

**Comment by rkinnett** [comment] 2022-04-01 08:30
I couldn't get manual exposure to work with any of the above python-only solutions (didn't try v4l2 method), in conjunction with the VideoCapture read() method.  Replacing read() with grab() and retrieve() worked for me.  I believe this has to do with having 2 webcams on my system (one built into the laptop and the other a ZWO ASI USB camera), even though I'm only actively working with the USB camera (device 5, not 0 as shown in the simplified snippet below).

`
import math, cv2
exposure_sec = 0.5
cap = cv2.VideoCapture(0)
cap.set(cv2.CAP_PROP_EXPOSURE, math.log2(exposure_sec))
while True:
  frame_ready = False
  while not frame_ready:
    frame_ready = cap.grab()
  ret, img = cap.retrieve(0)
  cv2.imshow('image',img)
  if cv2.waitKey(1) & 0xFF == ord('q'):
    break
`

**Comment by myboyhood** [comment] 2023-01-08 14:51
I find the reason!! 
At first, I use OpenCV 3.4.10.
I follows the code 
```py
#!/usr/bin/env python3
import cv2
print(cv2.__version__)
cap = cv2.VideoCapture(0)
cap.set(cv2.CAP_PROP_AUTO_EXPOSURE, 3) # auto mode
cap.set(cv2.CAP_PROP_AUTO_EXPOSURE, 1) # manual mode
cap.set(cv2.CAP_PROP_EXPOSURE, 10)
while cap.isOpened():
    ret, frame = cap.read()
    cv2.imshow("DetectionResults", frame)
    cv2.waitKey(1)
```
output
```sh
3.4.10
[ WARN:0] OpenCV | GStreamer warning: Cannot query video position: status=0, value=-1, duration=-1
[ WARN:0] OpenCV | GStreamer warning: GStreamer: unhandled property
[ WARN:0] OpenCV | GStreamer warning: GStreamer: unhandled property
[ WARN:0] OpenCV | GStreamer warning: GStreamer: unhandled property
```
I can not set the `CV_CAP_PROP_EXPOSURE` or `CV_CAP_PROP_AUTO_EXPOSURE`. 

However, when I change the python version to 4.2.0 at the first line
```py
#!/usr/bin/env python
import cv2
print(cv2.__version__)
cap = cv2.VideoCapture(0)
cap.set(cv2.CAP_PROP_AUTO_EXPOSURE, 3) # auto mode
cap.set(cv2.CAP_PROP_AUTO_EXPOSURE, 1) # manual mode
cap.set(cv2.CAP_PROP_EXPOSURE, 10)
while cap.isOpened():
    ret, frame = cap.read()
    cv2.imshow("DetectionResults", frame)
    cv2.waitKey(1)
```
output is
```sh
4.2.0
```
Yes ! !  I can set the `CV_CAP_PROP_EXPOSURE`. I try form `1` to `30`, the EXPOSURE will increase.

**Comment by leimao** [comment] 2023-06-01 04:49
This method helped to increase FPS some extent, but not to the highest possible. I got a Logitech Brio 4K which could reach 90 FPS at 1280 x 720 in the day time and only 15 FPS in the night without using this trick. When this trick was applied, the FPS got increased to 60 FPS, but could not go any higher.

**Comment by leimao** [comment] 2023-06-01 04:52
> 

Got the same problem.

**Comment by leimao** [comment] 2023-06-01 04:53
> Hi. I could make the camera work on manual mode now with auto exposure set on 0.25. But I can't put the Camera back on auto mode. I have tried setting 0 and 1 as the auto_exposure value, but no help. Can you please guide?

Got the same problem.

**Comment by leimao** [comment] 2023-06-01 04:56
> Hi hoerin, The auto_exposure property should expect two values 0.75 as auto exposure On and 0.25 as auto exposure OFF. Once you set auto exposure Off with 0.25 then set exposure to any value that you desire. This is tested on Mac and Raspberry both.

OK, the solution is to set to manual mode before video capture release.
```python
            video_capture.set(cv2.CAP_PROP_AUTO_EXPOSURE, 3) # auto mode
            video_capture.release()
```

**Comment by hansipete** [comment] 2023-07-11 11:56
Solution for me was to `read()` a frame before setting `CAP_PROP_AUTO_EXPOSURE` to 1.
`CAP_PROP_EXPOSURE` as absolute positive integer from 1 to 5000.

```
# v4l2-ctl -l output for USB camera ELP-USBFHD01H
...
                  auto_exposure 0x009a0901 (menu)   : min=0 max=3 default=3 value=3
         exposure_time_absolute 0x009a0902 (int)    : min=1 max=5000 step=1 default=157 value=157 flags=inactive
     exposure_dynamic_framerate 0x009a0903 (bool)   : default=0 value=1
     ```

**Comment by lightwise15** [comment] 2024-03-27 09:49
I am using an ELP camera 8MP and was trying all of the above with little success.
Results of settings below were very unreliable until I added the delay after setting exposure.  Then it all calmed down and image exposures were quite stable and consistent.
(I am looking at bright LED sources - thus the super short exposures. )

thanks for all the posting above...  very helpful indeed. (unlike the support info from ELP)

cap = cv2.VideoCapture(0)
    ret, frame = cap.read()
    cap.set(cv2.CAP_PROP_AUTO_EXPOSURE,3)
    cap.set(cv2.CAP_PROP_AUTO_EXPOSURE,1)
    cap.set(cv2.CAP_PROP_EXPOSURE,-11)

    time.sleep(1)

    print (cap.get(cv2.CAP_PROP_EXPOSURE))

    ret, frame = cap.read()

**Comment by mohankaushik97** [comment] 2024-03-28 20:53
> I needed to set my exposure as an absolute value, 0.01 in my case, rather than using negative values. But that may be different for your camera.

What is the unit of the absolute value of the exposure?
